# Matches details

In [1]:
import requests
import pandas as pd

url = "https://cricbuzz-cricket.p.rapidapi.com/matches/v1/live"

headers = {
	"x-rapidapi-key": "095038d962msh9068af945c80bc9p1ad37cjsna03b2a42de54",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

data = response.json()

In [3]:
data

{'typeMatches': [{'matchType': 'International',
   'seriesMatches': [{'seriesAdWrapper': {'seriesId': 11570,
      'seriesName': "ICC Men's T20 2028 World Cup Americas Sub Regional Qualifier B, 2026",
      'matches': [{'matchInfo': {'matchId': 147563,
         'seriesId': 11570,
         'seriesName': "ICC Men's T20 2028 World Cup Americas Sub Regional Qualifier B, 2026",
         'matchDesc': '8th Match',
         'matchFormat': 'T20',
         'startDate': '1773343800000',
         'endDate': '1773356400000',
         'state': 'Complete',
         'status': 'Argentina won by 7 wkts',
         'team1': {'teamId': 2285,
          'teamName': 'Suriname',
          'teamSName': 'SN',
          'imageId': 582333},
         'team2': {'teamId': 549,
          'teamName': 'Argentina',
          'teamSName': 'ARG',
          'imageId': 172601},
         'venueInfo': {'id': 892,
          'ground': 'Jimmy Powell Oval',
          'city': 'George Town',
          'timezone': '-05:00',
          'latitude': '19.286932',
          'longitude': '-81.367439'},
         'currBatTeamId': 549,
         'seriesStartDt': '1772928000000',
         'seriesEndDt': '1773792000000',
         'isTimeAnnounced': True,
         'stateTitle': 'Complete'},
        'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
           'runs': 107,
           'wickets': 7,
           'overs': 19.6}},
         'team2Score': {'inngs1': {'inningsId': 2,
           'runs': 109,
           'wickets': 3,
           'overs': 16.6}}}}]}}]},
  {'matchType': 'Domestic',
   'seriesMatches': [{'seriesAdWrapper': {'seriesId': 11553,
      'seriesName': 'CSA Provincial One-Day Challenge Division One 2026',
      'matches': [{'matchInfo': {'matchId': 147299,
         'seriesId': 11553,
         'seriesName': 'CSA Provincial One-Day Challenge Division One 2026',
         'matchDesc': '16th Match',
         'matchFormat': 'ODI',
         'startDate': '1773313200000',
         'endDate': '1773342000000',
         'state': 'Complete',
         'status': 'Titans won by 6 wkts  -  20 overs game gue to rain',
         'team1': {'teamId': 1766,
          'teamName': 'KwaZulu-Natal Inland - Tuskers',
          'teamSName': 'KZNIN',
          'imageId': 349611},
         'team2': {'teamId': 89,
          'teamName': 'Titans',
          'teamSName': 'TIT',
          'imageId': 172182},
         'venueInfo': {'id': 75,
          'ground': 'SuperSport Park',
          'city': 'Centurion',
          'timezone': '+02:00',
          'latitude': '-25.859938',
          'longitude': '28.195531'},
         'currBatTeamId': 89,
         'seriesStartDt': '1772150400000',
         'seriesEndDt': '1774915200000',
         'isTimeAnnounced': True,
         'stateTitle': 'Complete'},
        'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
           'runs': 180,
           'wickets': 7,
           'overs': 20.0}},
         'team2Score': {'inngs1': {'inningsId': 2,
           'runs': 181,
           'wickets': 4,
           'overs': 19.0}}}}]}},
    {'seriesAdWrapper': {'seriesId': 11559,
      'seriesName': 'CSA Provincial One-Day Challenge Division Two 2026',
      'matches': [{'matchInfo': {'matchId': 147596,
         'seriesId': 11559,
         'seriesName': 'CSA Provincial One-Day Challenge Division Two 2026',
         'matchDesc': '24th Match',
         'matchFormat': 'ODI',
         'startDate': '1773302400000',
         'endDate': '1773331200000',
         'state': 'Complete',
         'status': 'Border won by 4 wkts',
         'team1': {'teamId': 912,
          'teamName': 'Limpopo',
          'teamSName': 'LIMPO',
          'imageId': 248430},
         'team2': {'teamId': 1775,
          'teamName': 'Border',
          'teamSName': 'BOR',
          'imageId': 349602},
         'venueInfo': {'id': 99,
          'ground': 'Buffalo Park',
          'city': 'East London',
          'timezone': '+02:00',
          'latitude': '-33.006727',
          'longitude': '27.919465'},
         'currBatTeamId': 1775,
         'seriesStartDt': '1771632000000',
         'seriesEndDt': '1774310400000',
         'isTimeAnnounced': True,
         'stateTitle': 'Complete'},
        'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
           'runs': 218,
           'wickets': 9,
           'overs': 50.0}},
         'team2Score': {'inngs1': {'inningsId': 2,
           'runs': 219,
           'wickets': 6,
           'overs': 39.5}}}}]}},
    {'ad': {'name': 'native_matches',
      'layout': 'native_large',
      'position': 3}}]}],
 'filters': {'matchType': ['International', 'League', 'Domestic', 'Women']},
 'appIndex': {'seoTitle': 'Live Cricket Score - Scorecard and Match Results',
  'webURL': 'www.cricbuzz.com/live-cricket-scores/'},
 'responseLastUpdated': '1773384219'}

In [69]:
print(data.keys())

dict_keys(['typeMatches', 'filters', 'appIndex', 'responseLastUpdated'])

In [70]:
data['filters']

{'matchType': ['International', 'League', 'Domestic', 'Women']}

In [71]:
data['responseLastUpdated']

'1772626835'

In [72]:
data['appIndex']

{'seoTitle': 'Live Cricket Score - Scorecard and Match Results',
 'webURL': 'www.cricbuzz.com/live-cricket-scores/'}

In [73]:
data['typeMatches']

[{'matchType': 'Domestic',
  'seriesMatches': [{'seriesAdWrapper': {'seriesId': 11553,
     'seriesName': 'CSA Provincial One-Day Challenge Division One 2026',
     'matches': [{'matchInfo': {'matchId': 147104,
        'seriesId': 11553,
        'seriesName': 'CSA Provincial One-Day Challenge Division One 2026',
        'matchDesc': '6th Match',
        'matchFormat': 'ODI',
        'startDate': '1772622000000',
        'endDate': '1772650800000',
        'state': 'Toss',
        'status': 'Boland opt to bat',
        'team1': {'teamId': 1759,
         'teamName': 'Boland',
         'teamSName': 'BOL',
         'imageId': 349610},
        'team2': {'teamId': 1766,
         'teamName': 'KwaZulu-Natal Inland - Tuskers',
         'teamSName': 'KZNIN',
         'imageId': 349611},
        'venueInfo': {'id': 207,
         'ground': 'Boland Park',
         'city': 'Paarl',
         'timezone': '+02:00',
         'latitude': '-33.730900',
         'longitude': '18.970760'},
        'seriesStartDt': '1772150400000',
        'seriesEndDt': '1774915200000',
        'isTimeAnnounced': True,
        'stateTitle': 'Toss'}},
      {'matchInfo': {'matchId': 147112,
        'seriesId': 11553,
        'seriesName': 'CSA Provincial One-Day Challenge Division One 2026',
        'matchDesc': '7th Match',
        'matchFormat': 'ODI',
        'startDate': '1772622000000',
        'endDate': '1772650800000',
        'state': 'Toss',
        'status': 'North West - Eastvaal Renault Dragons opt to bowl',
        'team1': {'teamId': 157,
         'teamName': 'Lions',
         'teamSName': 'LIONS',
         'imageId': 172224},
        'team2': {'teamId': 922,
         'teamName': 'North West - Eastvaal Renault Dragons',
         'teamSName': 'NWEST',
         'imageId': 248439},
        'venueInfo': {'id': 102,
         'ground': 'Senwes Park',
         'city': 'Potchefstroom',
         'timezone': '+02:00',
         'latitude': '-26.695565',
         'longitude': '27.100691'},
        'seriesStartDt': '1772150400000',
        'seriesEndDt': '1774915200000',
        'isTimeAnnounced': True,
        'stateTitle': 'Toss'}}]}},
   {'seriesAdWrapper': {'seriesId': 11559,
     'seriesName': 'CSA Provincial One-Day Challenge Division Two 2026',
     'matches': [{'matchInfo': {'matchId': 147378,
        'seriesId': 11559,
        'seriesName': 'CSA Provincial One-Day Challenge Division Two 2026',
        'matchDesc': '15th Match',
        'matchFormat': 'ODI',
        'startDate': '1772611200000',
        'endDate': '1772640000000',
        'state': 'Complete',
        'status': 'Match abandoned without a ball bowled',
        'team1': {'teamId': 1782,
         'teamName': 'South Africa Emerging Players',
         'teamSName': 'SAEP',
         'imageId': 776290},
        'team2': {'teamId': 923,
         'teamName': 'Northern Cape',
         'teamSName': 'NCAPE',
         'imageId': 248438},
        'venueInfo': {'id': 367,
         'ground': 'LC de Villiers Oval',
         'city': 'Pretoria',
         'timezone': '+02:00',
         'latitude': '-25.771079',
         'longitude': '28.221849'},
        'seriesStartDt': '1771632000000',
        'seriesEndDt': '1774310400000',
        'isTimeAnnounced': True,
        'stateTitle': 'Abandon'}},
      {'matchInfo': {'matchId': 147310,
        'seriesId': 11559,
        'seriesName': 'CSA Provincial One-Day Challenge Division Two 2026',
        'matchDesc': '13th Match',
        'matchFormat': 'ODI',
        'startDate': '1772611200000',
        'endDate': '1772640000000',
        'state': 'Innings Break',
        'status': 'Innings Break',
        'team1': {'teamId': 1775,
         'teamName': 'Border',
         'teamSName': 'BOR',
         'imageId': 349602},
        'team2': {'teamId': 933,
         'teamName': 'Eastern Storm',
         'teamSName': 'ESTORM',
         'imageId': 248407},
        'venueInfo': {'id': 99,
         'ground': 'Buffalo Park',
         'city': 'East London',
         'timezone': '+02:00',
         'latitude': '-33.006727',
         'longitude': '27.919465'},
        'currBatTeamId': 1775,
        'seriesStartDt': '1771632000000',
        'seriesEndDt': '1774310400000',
        'isTimeAnnounced': True,
        'stateTitle': 'Ings Break'},
       'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
          'runs': 306,
          'wickets': 5,
          'overs': 49.6}}}},
      {'matchInfo': {'matchId': 147359,
        'seriesId': 11559,
        'seriesName': 'CSA Provincial One-Day Challenge Division Two 2026',
        'matchDesc': '14th Match',
        'matchFormat': 'ODI',
        'startDate': '1772611200000',
        'endDate': '1772640000000',
        'state': 'In Progress',
        'status': '38 Overs game due to rain',
        'team1': {'teamId': 903,
         'teamName': 'Mpumalanga Rhinos',
         'teamSName': 'MPR',
         'imageId': 248434},
        'team2': {'teamId': 912,
         'teamName': 'Limpopo',
         'teamSName': 'LIMPO',
         'imageId': 248430},
        'venueInfo': {'id': 772,
         'ground': 'Polokwane Cricket Club',
         'city': 'Polokwane',
         'timezone': '+02:00',
         'latitude': '-23.912260',
         'longitude': '29.453550'},
        'currBatTeamId': 903,
        'seriesStartDt': '1771632000000',
        'seriesEndDt': '1774310400000',
        'isTimeAnnounced': True,
        'stateTitle': 'In Progress'},
       'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
          'runs': 152,
          'wickets': 5,
          'overs': 31.6}}}}]}}]}]

In [4]:
type_match=data['typeMatches']
print(type_match[0])

{'matchType': 'International', 'seriesMatches': [{'seriesAdWrapper': {'seriesId': 11570, 'seriesName': "ICC Men's T20 2028 World Cup Americas Sub Regional Qualifier B, 2026", 'matches': [{'matchInfo': {'matchId': 147563, 'seriesId': 11570, 'seriesName': "ICC Men's T20 2028 World Cup Americas Sub Regional Qualifier B, 2026", 'matchDesc': '8th Match', 'matchFormat': 'T20', 'startDate': '1773343800000', 'endDate': '1773356400000', 'state': 'Complete', 'status': 'Argentina won by 7 wkts', 'team1': {'teamId': 2285, 'teamName': 'Suriname', 'teamSName': 'SN', 'imageId': 582333}, 'team2': {'teamId': 549, 'teamName': 'Argentina', 'teamSName': 'ARG', 'imageId': 172601}, 'venueInfo': {'id': 892, 'ground': 'Jimmy Powell Oval', 'city': 'George Town', 'timezone': '-05:00', 'latitude': '19.286932', 'longitude': '-81.367439'}, 'currBatTeamId': 549, 'seriesStartDt': '1772928000000', 'seriesEndDt': '1773792000000', 'isTimeAnnounced': True, 'stateTitle': 'Complete'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 107, 'wickets': 7, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 109, 'wickets': 3, 'overs': 16.6}}}}]}}]}

In [5]:
series_matches = type_match[0]['seriesMatches']
print(series_matches[0])

{'seriesAdWrapper': {'seriesId': 11570, 'seriesName': "ICC Men's T20 2028 World Cup Americas Sub Regional Qualifier B, 2026", 'matches': [{'matchInfo': {'matchId': 147563, 'seriesId': 11570, 'seriesName': "ICC Men's T20 2028 World Cup Americas Sub Regional Qualifier B, 2026", 'matchDesc': '8th Match', 'matchFormat': 'T20', 'startDate': '1773343800000', 'endDate': '1773356400000', 'state': 'Complete', 'status': 'Argentina won by 7 wkts', 'team1': {'teamId': 2285, 'teamName': 'Suriname', 'teamSName': 'SN', 'imageId': 582333}, 'team2': {'teamId': 549, 'teamName': 'Argentina', 'teamSName': 'ARG', 'imageId': 172601}, 'venueInfo': {'id': 892, 'ground': 'Jimmy Powell Oval', 'city': 'George Town', 'timezone': '-05:00', 'latitude': '19.286932', 'longitude': '-81.367439'}, 'currBatTeamId': 549, 'seriesStartDt': '1772928000000', 'seriesEndDt': '1773792000000', 'isTimeAnnounced': True, 'stateTitle': 'Complete'}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 107, 'wickets': 7, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 109, 'wickets': 3, 'overs': 16.6}}}}]}}

In [6]:
# Access series ad wrapper inside
series_wrapper = series_matches[0]['seriesAdWrapper']
print(series_wrapper.keys())

dict_keys(['seriesId', 'seriesName', 'matches'])

In [7]:
# Access matches of series wrapper
match_list = series_wrapper['matches']
first_match = match_list[0]
print(first_match['matchInfo'])

{'matchId': 147563, 'seriesId': 11570, 'seriesName': "ICC Men's T20 2028 World Cup Americas Sub Regional Qualifier B, 2026", 'matchDesc': '8th Match', 'matchFormat': 'T20', 'startDate': '1773343800000', 'endDate': '1773356400000', 'state': 'Complete', 'status': 'Argentina won by 7 wkts', 'team1': {'teamId': 2285, 'teamName': 'Suriname', 'teamSName': 'SN', 'imageId': 582333}, 'team2': {'teamId': 549, 'teamName': 'Argentina', 'teamSName': 'ARG', 'imageId': 172601}, 'venueInfo': {'id': 892, 'ground': 'Jimmy Powell Oval', 'city': 'George Town', 'timezone': '-05:00', 'latitude': '19.286932', 'longitude': '-81.367439'}, 'currBatTeamId': 549, 'seriesStartDt': '1772928000000', 'seriesEndDt': '1773792000000', 'isTimeAnnounced': True, 'stateTitle': 'Complete'}

# First match info

In [6]:
#Access match info
match_info = first_match['matchInfo']

#Access fields 
print('Match Id',match_info['matchId'])
print('Series Id',match_info['seriesId'])
print('Series Name',match_info['seriesName'])
print('Match Desc',match_info['matchDesc'])
print('Match Format',match_info['matchFormat'])
print('Start date',match_info['startDate'])

#team details
print('Team1',match_info['team1']['teamName'])
print('Team2',match_info['team2']['teamName'])

# Match venue
print('Venue',match_info['venueInfo']['ground'])

Match Id 148742
Series Id 11689
Series Name Bahrain tour of Malaysia, 2026
Match Desc 3rd T20I
Match Format T20
Start date 1773126000000
Team1 Malaysia
Team2 Bahrain
Venue Bayuemas Oval

In [8]:
#Actual extraction logic
matches = []

for type_match in data.get("typeMatches",[]):
    for series_matches in type_match.get('seriesMatches',[]):
        series_data = series_matches.get('seriesAdWrapper',{})
        series_id = series_data.get('seriesId')
        series_name = series_data.get('seriesName')

        for match in series_data.get('matches',[]):
            info = match.get('matchInfo',{})
            matchId = info.get('matchId')
            match_desc = info.get('matchDesc')
            match_format = info.get('matchFormat')
            start_date = info.get('startDate')
            status = info.get('status')
            team1 = info.get('team1',{}).get('teamName')
            team2 = info.get('team2',{}).get('teamName')
            venue = info.get('venueInfo',{}).get('ground')
            
            matches.append({
                "series_id" : series_id,
                "series_name" : series_name,
                "matchId" : matchId,
                "match_desc" : match_desc,
                "match_format" : match_format,
                "start_date" : start_date,
                "status" : status,
                "team1" : team1,
                "team2" : team2,
                "venue" : venue,
               })

In [92]:
df_matches = pd.DataFrame(matches)
df_matches

,series_id,series_name,matchId,match_desc,match_format,start_date,status,team1,team2,venue
0,11553,CSA Provincial One-Day Challenge Division One ...,147104,6th Match,ODI,1772622000000,Boland opt to bat,Boland,KwaZulu-Natal Inland - Tuskers,Boland Park
1,11553,CSA Provincial One-Day Challenge Division One ...,147112,7th Match,ODI,1772622000000,North West - Eastvaal Renault Dragons opt to bowl,Lions,North West - Eastvaal Renault Dragons,Senwes Park
2,11559,CSA Provincial One-Day Challenge Division Two ...,147378,15th Match,ODI,1772611200000,Match abandoned without a ball bowled,South Africa Emerging Players,Northern Cape,LC de Villiers Oval
3,11559,CSA Provincial One-Day Challenge Division Two ...,147310,13th Match,ODI,1772611200000,Innings Break,Border,Eastern Storm,Buffalo Park
4,11559,CSA Provincial One-Day Challenge Division Two ...,147359,14th Match,ODI,1772611200000,38 Overs game due to rain,Mpumalanga Rhinos,Limpopo,Polokwane Cricket Club

# My Cricbuzz team details

In [ ]:
import pandas as pd

In [ ]:
!pip install request

'pip' is not recognized as an internal or external command,
operable program or batch file.

In [184]:
import requests
import pandas as pd

url = "https://cricbuzz-cricket.p.rapidapi.com/teams/v1/2/players"

headers = {
	"x-rapidapi-key": "e6021fb984msh201af5139a6e2e9p149939jsn32edaa5716a4",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

data1 = response.json()

In [18]:
data1

{'player': [{'name': 'BATSMEN', 'imageId': 174146},
  {'id': '11808',
   'name': 'Shubman Gill',
   'imageId': 616515,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm offbreak'},
  {'id': '13940',
   'name': 'Yashasvi Jaiswal',
   'imageId': 591942,
   'battingStyle': 'Left-hand bat',
   'bowlingStyle': 'Right-arm legbreak'},
  {'id': '13866',
   'name': 'Sai Sudharsan',
   'imageId': 717782,
   'battingStyle': 'Left-hand bat',
   'bowlingStyle': 'Right-arm legbreak'},
  {'id': '576',
   'name': 'Rohit Sharma',
   'imageId': 616514,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm offbreak'},
  {'id': '1413',
   'name': 'Virat Kohli',
   'imageId': 616517,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm medium'},
  {'id': '7915',
   'name': 'Suryakumar Yadav',
   'imageId': 846028,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm offbreak'},
  {'id': '9428',
   'name': 'Shreyas Iyer',
   'imageId': 616518,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm legbreak'},
  {'id': '10896',
   'name': 'Rinku Singh',
   'imageId': 846030,
   'battingStyle': 'Left-hand bat',
   'bowlingStyle': 'Right-arm offbreak'},
  {'id': '14504',
   'name': 'Tilak Varma',
   'imageId': 846029,
   'battingStyle': 'Left-hand bat',
   'bowlingStyle': 'Right-arm offbreak'},
  {'id': '11813',
   'name': 'Ruturaj Gaikwad',
   'imageId': 781069,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm offbreak'},
  {'id': '10636',
   'name': 'Rajat Patidar',
   'imageId': 760758,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm offbreak'},
  {'id': '9429',
   'name': 'Sarfaraz Khan',
   'imageId': 591955,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm legbreak'},
  {'id': '9716',
   'name': 'Abhimanyu Easwaran',
   'imageId': 591956,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm legbreak'},
  {'id': '8257',
   'name': 'Karun Nair',
   'imageId': 717781,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm offbreak'},
  {'name': 'ALL ROUNDER', 'imageId': 174146},
  {'id': '14701',
   'name': 'Nitish Kumar Reddy',
   'imageId': 591947,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm fast-medium'},
  {'id': '9647',
   'name': 'Hardik Pandya',
   'imageId': 846032,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm fast-medium'},
  {'id': '11195',
   'name': 'Shivam Dube',
   'imageId': 846034,
   'battingStyle': 'Left-hand bat',
   'bowlingStyle': 'Right-arm medium'},
  {'id': '12086',
   'name': 'Abhishek Sharma',
   'imageId': 846031,
   'battingStyle': 'Left-hand bat',
   'bowlingStyle': 'Left-arm orthodox'},
  {'id': '587',
   'name': 'Ravindra Jadeja',
   'imageId': 616520,
   'battingStyle': 'Left-hand bat',
   'bowlingStyle': 'Left-arm orthodox'},
  {'id': '8683',
   'name': 'Shardul Thakur',
   'imageId': 352487,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm fast-medium'},
  {'id': '10945',
   'name': 'Washington Sundar',
   'imageId': 616522,
   'battingStyle': 'Left-hand bat',
   'bowlingStyle': 'Right-arm offbreak'},
  {'id': '8808',
   'name': 'Axar Patel',
   'imageId': 846033,
   'battingStyle': 'Left-hand bat',
   'bowlingStyle': 'Left-arm orthodox'},
  {'name': 'WICKET KEEPER', 'imageId': 174146},
  {'id': '10744',
   'name': 'Rishabh Pant',
   'imageId': 616524,
   'battingStyle': 'Left-hand bat'},
  {'id': '8733',
   'name': 'KL Rahul',
   'imageId': 616523,
   'battingStyle': 'Right-hand bat'},
  {'id': '14691',
   'name': 'Dhruv Jurel',
   'imageId': 591954,
   'battingStyle': 'Right-hand bat'},
  {'id': '8271',
   'name': 'Sanju Samson',
   'imageId': 846035,
   'battingStyle': 'Right-hand bat'},
  {'id': '10276',
   'name': 'Ishan Kishan',
   'imageId': 846036,
   'battingStyle': 'Left-hand bat'},
  {'name': 'BOWLER', 'imageId': 174146},
  {'id': '10808',
   'name': 'Mohammed Siraj',
   'imageId': 591952,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm fast'},
  {'id': '9311',
   'name': 'Jasprit Bumrah',
   'imageId': 846037,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm fast'},
  {'id': '10551',
   'name': 'Prasidh Krishna',
   'imageId': 591958,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm fast'},
  {'id': '14726',
   'name': 'Akash Deep',
   'imageId': 591951,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm fast-medium'},
  {'id': '8292',
   'name': 'Kuldeep Yadav',
   'imageId': 846039,
   'battingStyle': 'Left-hand bat',
   'bowlingStyle': 'Left-arm wrist-spin'},
  {'id': '13217',
   'name': 'Arshdeep Singh',
   'imageId': 846038,
   'battingStyle': 'Left-hand bat',
   'bowlingStyle': 'Left-arm fast-medium'},
  {'id': '24729',
   'name': 'Harshit Rana',
   'imageId': 616529,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm fast-medium'},
  {'id': '14659',
   'name': 'Ravi Bishnoi',
   'imageId': 226280,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm legbreak'},
  {'id': '10754',
   'name': 'Mukesh Kumar',
   'imageId': 333872,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm fast-medium'},
  {'id': '12926',
   'name': 'Varun Chakaravarthy',
   'imageId': 846040,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm legbreak'}]}

In [19]:
data1.keys()

dict_keys(['player'])

# Here we assign the player list to the data1

In [20]:
data1["player"]

[{'name': 'BATSMEN', 'imageId': 174146},
 {'id': '11808',
  'name': 'Shubman Gill',
  'imageId': 616515,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm offbreak'},
 {'id': '13940',
  'name': 'Yashasvi Jaiswal',
  'imageId': 591942,
  'battingStyle': 'Left-hand bat',
  'bowlingStyle': 'Right-arm legbreak'},
 {'id': '13866',
  'name': 'Sai Sudharsan',
  'imageId': 717782,
  'battingStyle': 'Left-hand bat',
  'bowlingStyle': 'Right-arm legbreak'},
 {'id': '576',
  'name': 'Rohit Sharma',
  'imageId': 616514,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm offbreak'},
 {'id': '1413',
  'name': 'Virat Kohli',
  'imageId': 616517,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm medium'},
 {'id': '7915',
  'name': 'Suryakumar Yadav',
  'imageId': 846028,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm offbreak'},
 {'id': '9428',
  'name': 'Shreyas Iyer',
  'imageId': 616518,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm legbreak'},
 {'id': '10896',
  'name': 'Rinku Singh',
  'imageId': 846030,
  'battingStyle': 'Left-hand bat',
  'bowlingStyle': 'Right-arm offbreak'},
 {'id': '14504',
  'name': 'Tilak Varma',
  'imageId': 846029,
  'battingStyle': 'Left-hand bat',
  'bowlingStyle': 'Right-arm offbreak'},
 {'id': '11813',
  'name': 'Ruturaj Gaikwad',
  'imageId': 781069,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm offbreak'},
 {'id': '10636',
  'name': 'Rajat Patidar',
  'imageId': 760758,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm offbreak'},
 {'id': '9429',
  'name': 'Sarfaraz Khan',
  'imageId': 591955,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm legbreak'},
 {'id': '9716',
  'name': 'Abhimanyu Easwaran',
  'imageId': 591956,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm legbreak'},
 {'id': '8257',
  'name': 'Karun Nair',
  'imageId': 717781,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm offbreak'},
 {'name': 'ALL ROUNDER', 'imageId': 174146},
 {'id': '14701',
  'name': 'Nitish Kumar Reddy',
  'imageId': 591947,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm fast-medium'},
 {'id': '9647',
  'name': 'Hardik Pandya',
  'imageId': 846032,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm fast-medium'},
 {'id': '11195',
  'name': 'Shivam Dube',
  'imageId': 846034,
  'battingStyle': 'Left-hand bat',
  'bowlingStyle': 'Right-arm medium'},
 {'id': '12086',
  'name': 'Abhishek Sharma',
  'imageId': 846031,
  'battingStyle': 'Left-hand bat',
  'bowlingStyle': 'Left-arm orthodox'},
 {'id': '587',
  'name': 'Ravindra Jadeja',
  'imageId': 616520,
  'battingStyle': 'Left-hand bat',
  'bowlingStyle': 'Left-arm orthodox'},
 {'id': '8683',
  'name': 'Shardul Thakur',
  'imageId': 352487,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm fast-medium'},
 {'id': '10945',
  'name': 'Washington Sundar',
  'imageId': 616522,
  'battingStyle': 'Left-hand bat',
  'bowlingStyle': 'Right-arm offbreak'},
 {'id': '8808',
  'name': 'Axar Patel',
  'imageId': 846033,
  'battingStyle': 'Left-hand bat',
  'bowlingStyle': 'Left-arm orthodox'},
 {'name': 'WICKET KEEPER', 'imageId': 174146},
 {'id': '10744',
  'name': 'Rishabh Pant',
  'imageId': 616524,
  'battingStyle': 'Left-hand bat'},
 {'id': '8733',
  'name': 'KL Rahul',
  'imageId': 616523,
  'battingStyle': 'Right-hand bat'},
 {'id': '14691',
  'name': 'Dhruv Jurel',
  'imageId': 591954,
  'battingStyle': 'Right-hand bat'},
 {'id': '8271',
  'name': 'Sanju Samson',
  'imageId': 846035,
  'battingStyle': 'Right-hand bat'},
 {'id': '10276',
  'name': 'Ishan Kishan',
  'imageId': 846036,
  'battingStyle': 'Left-hand bat'},
 {'name': 'BOWLER', 'imageId': 174146},
 {'id': '10808',
  'name': 'Mohammed Siraj',
  'imageId': 591952,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm fast'},
 {'id': '9311',
  'name': 'Jasprit Bumrah',
  'imageId': 846037,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm fast'},
 {'id': '10551',
  'name': 'Prasidh Krishna',
  'imageId': 591958,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm fast'},
 {'id': '14726',
  'name': 'Akash Deep',
  'imageId': 591951,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm fast-medium'},
 {'id': '8292',
  'name': 'Kuldeep Yadav',
  'imageId': 846039,
  'battingStyle': 'Left-hand bat',
  'bowlingStyle': 'Left-arm wrist-spin'},
 {'id': '13217',
  'name': 'Arshdeep Singh',
  'imageId': 846038,
  'battingStyle': 'Left-hand bat',
  'bowlingStyle': 'Left-arm fast-medium'},
 {'id': '24729',
  'name': 'Harshit Rana',
  'imageId': 616529,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm fast-medium'},
 {'id': '14659',
  'name': 'Ravi Bishnoi',
  'imageId': 226280,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm legbreak'},
 {'id': '10754',
  'name': 'Mukesh Kumar',
  'imageId': 333872,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm fast-medium'},
 {'id': '12926',
  'name': 'Varun Chakaravarthy',
  'imageId': 846040,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm legbreak'}]

# filtering the indian player name
Question 1 Find all players who represent India. Display their full name, playing role, batting style, and bowling style.

In [21]:
# Create an empty list to store our filtered data
indianplayers = []

#access the list of players from the teams/players
for player in data1.get('player',[]):
    details = {
        "player_id" : player.get("id"),
        "full_name" : player.get("name"),
        "batting_style" : player.get("battingStyle"),
        "bowling_style" : player.get("bowlingStyle")
    }
    indianplayers.append(details)

In [22]:
indianplayers

[{'player_id': None,
  'full_name': 'BATSMEN',
  'batting_style': None,
  'bowling_style': None},
 {'player_id': '11808',
  'full_name': 'Shubman Gill',
  'batting_style': 'Right-hand bat',
  'bowling_style': 'Right-arm offbreak'},
 {'player_id': '13940',
  'full_name': 'Yashasvi Jaiswal',
  'batting_style': 'Left-hand bat',
  'bowling_style': 'Right-arm legbreak'},
 {'player_id': '13866',
  'full_name': 'Sai Sudharsan',
  'batting_style': 'Left-hand bat',
  'bowling_style': 'Right-arm legbreak'},
 {'player_id': '576',
  'full_name': 'Rohit Sharma',
  'batting_style': 'Right-hand bat',
  'bowling_style': 'Right-arm offbreak'},
 {'player_id': '1413',
  'full_name': 'Virat Kohli',
  'batting_style': 'Right-hand bat',
  'bowling_style': 'Right-arm medium'},
 {'player_id': '7915',
  'full_name': 'Suryakumar Yadav',
  'batting_style': 'Right-hand bat',
  'bowling_style': 'Right-arm offbreak'},
 {'player_id': '9428',
  'full_name': 'Shreyas Iyer',
  'batting_style': 'Right-hand bat',
  'bowling_style': 'Right-arm legbreak'},
 {'player_id': '10896',
  'full_name': 'Rinku Singh',
  'batting_style': 'Left-hand bat',
  'bowling_style': 'Right-arm offbreak'},
 {'player_id': '14504',
  'full_name': 'Tilak Varma',
  'batting_style': 'Left-hand bat',
  'bowling_style': 'Right-arm offbreak'},
 {'player_id': '11813',
  'full_name': 'Ruturaj Gaikwad',
  'batting_style': 'Right-hand bat',
  'bowling_style': 'Right-arm offbreak'},
 {'player_id': '10636',
  'full_name': 'Rajat Patidar',
  'batting_style': 'Right-hand bat',
  'bowling_style': 'Right-arm offbreak'},
 {'player_id': '9429',
  'full_name': 'Sarfaraz Khan',
  'batting_style': 'Right-hand bat',
  'bowling_style': 'Right-arm legbreak'},
 {'player_id': '9716',
  'full_name': 'Abhimanyu Easwaran',
  'batting_style': 'Right-hand bat',
  'bowling_style': 'Right-arm legbreak'},
 {'player_id': '8257',
  'full_name': 'Karun Nair',
  'batting_style': 'Right-hand bat',
  'bowling_style': 'Right-arm offbreak'},
 {'player_id': None,
  'full_name': 'ALL ROUNDER',
  'batting_style': None,
  'bowling_style': None},
 {'player_id': '14701',
  'full_name': 'Nitish Kumar Reddy',
  'batting_style': 'Right-hand bat',
  'bowling_style': 'Right-arm fast-medium'},
 {'player_id': '9647',
  'full_name': 'Hardik Pandya',
  'batting_style': 'Right-hand bat',
  'bowling_style': 'Right-arm fast-medium'},
 {'player_id': '11195',
  'full_name': 'Shivam Dube',
  'batting_style': 'Left-hand bat',
  'bowling_style': 'Right-arm medium'},
 {'player_id': '12086',
  'full_name': 'Abhishek Sharma',
  'batting_style': 'Left-hand bat',
  'bowling_style': 'Left-arm orthodox'},
 {'player_id': '587',
  'full_name': 'Ravindra Jadeja',
  'batting_style': 'Left-hand bat',
  'bowling_style': 'Left-arm orthodox'},
 {'player_id': '8683',
  'full_name': 'Shardul Thakur',
  'batting_style': 'Right-hand bat',
  'bowling_style': 'Right-arm fast-medium'},
 {'player_id': '10945',
  'full_name': 'Washington Sundar',
  'batting_style': 'Left-hand bat',
  'bowling_style': 'Right-arm offbreak'},
 {'player_id': '8808',
  'full_name': 'Axar Patel',
  'batting_style': 'Left-hand bat',
  'bowling_style': 'Left-arm orthodox'},
 {'player_id': None,
  'full_name': 'WICKET KEEPER',
  'batting_style': None,
  'bowling_style': None},
 {'player_id': '10744',
  'full_name': 'Rishabh Pant',
  'batting_style': 'Left-hand bat',
  'bowling_style': None},
 {'player_id': '8733',
  'full_name': 'KL Rahul',
  'batting_style': 'Right-hand bat',
  'bowling_style': None},
 {'player_id': '14691',
  'full_name': 'Dhruv Jurel',
  'batting_style': 'Right-hand bat',
  'bowling_style': None},
 {'player_id': '8271',
  'full_name': 'Sanju Samson',
  'batting_style': 'Right-hand bat',
  'bowling_style': None},
 {'player_id': '10276',
  'full_name': 'Ishan Kishan',
  'batting_style': 'Left-hand bat',
  'bowling_style': None},
 {'player_id': None,
  'full_name': 'BOWLER',
  'batting_style': None,
  'bowling_style': None},
 {'player_id': '10808',
  'full_name': 'Mohammed Siraj',
  'batting_style': 'Right-hand bat',
  'bowling_style': 'Right-arm fast'},
 {'player_id': '9311',
  'full_name': 'Jasprit Bumrah',
  'batting_style': 'Right-hand bat',
  'bowling_style': 'Right-arm fast'},
 {'player_id': '10551',
  'full_name': 'Prasidh Krishna',
  'batting_style': 'Right-hand bat',
  'bowling_style': 'Right-arm fast'},
 {'player_id': '14726',
  'full_name': 'Akash Deep',
  'batting_style': 'Right-hand bat',
  'bowling_style': 'Right-arm fast-medium'},
 {'player_id': '8292',
  'full_name': 'Kuldeep Yadav',
  'batting_style': 'Left-hand bat',
  'bowling_style': 'Left-arm wrist-spin'},
 {'player_id': '13217',
  'full_name': 'Arshdeep Singh',
  'batting_style': 'Left-hand bat',
  'bowling_style': 'Left-arm fast-medium'},
 {'player_id': '24729',
  'full_name': 'Harshit Rana',
  'batting_style': 'Right-hand bat',
  'bowling_style': 'Right-arm fast-medium'},
 {'player_id': '14659',
  'full_name': 'Ravi Bishnoi',
  'batting_style': 'Right-hand bat',
  'bowling_style': 'Right-arm legbreak'},
 {'player_id': '10754',
  'full_name': 'Mukesh Kumar',
  'batting_style': 'Right-hand bat',
  'bowling_style': 'Right-arm fast-medium'},
 {'player_id': '12926',
  'full_name': 'Varun Chakaravarthy',
  'batting_style': 'Right-hand bat',
  'bowling_style': 'Right-arm legbreak'}]

In [23]:
df = pd.DataFrame(indianplayers)

In [24]:
df

   player_id            full_name   batting_style          bowling_style
0        NaN              BATSMEN             NaN                    NaN
1      11808         Shubman Gill  Right-hand bat     Right-arm offbreak
2      13940     Yashasvi Jaiswal   Left-hand bat     Right-arm legbreak
3      13866        Sai Sudharsan   Left-hand bat     Right-arm legbreak
4        576         Rohit Sharma  Right-hand bat     Right-arm offbreak
5       1413          Virat Kohli  Right-hand bat       Right-arm medium
6       7915     Suryakumar Yadav  Right-hand bat     Right-arm offbreak
7       9428         Shreyas Iyer  Right-hand bat     Right-arm legbreak
8      10896          Rinku Singh   Left-hand bat     Right-arm offbreak
9      14504          Tilak Varma   Left-hand bat     Right-arm offbreak
10     11813      Ruturaj Gaikwad  Right-hand bat     Right-arm offbreak
11     10636        Rajat Patidar  Right-hand bat     Right-arm offbreak
12      9429        Sarfaraz Khan  Right-hand bat     Right-arm legbreak
13      9716   Abhimanyu Easwaran  Right-hand bat     Right-arm legbreak
14      8257           Karun Nair  Right-hand bat     Right-arm offbreak
15       NaN          ALL ROUNDER             NaN                    NaN
16     14701   Nitish Kumar Reddy  Right-hand bat  Right-arm fast-medium
17      9647        Hardik Pandya  Right-hand bat  Right-arm fast-medium
18     11195          Shivam Dube   Left-hand bat       Right-arm medium
19     12086      Abhishek Sharma   Left-hand bat      Left-arm orthodox
20       587      Ravindra Jadeja   Left-hand bat      Left-arm orthodox
21      8683       Shardul Thakur  Right-hand bat  Right-arm fast-medium
22     10945    Washington Sundar   Left-hand bat     Right-arm offbreak
23      8808           Axar Patel   Left-hand bat      Left-arm orthodox
24       NaN        WICKET KEEPER             NaN                    NaN
25     10744         Rishabh Pant   Left-hand bat                    NaN
26      8733             KL Rahul  Right-hand bat                    NaN
27     14691          Dhruv Jurel  Right-hand bat                    NaN
28      8271         Sanju Samson  Right-hand bat                    NaN
29     10276         Ishan Kishan   Left-hand bat                    NaN
30       NaN               BOWLER             NaN                    NaN
31     10808       Mohammed Siraj  Right-hand bat         Right-arm fast
32      9311       Jasprit Bumrah  Right-hand bat         Right-arm fast
33     10551      Prasidh Krishna  Right-hand bat         Right-arm fast
34     14726           Akash Deep  Right-hand bat  Right-arm fast-medium
35      8292        Kuldeep Yadav   Left-hand bat    Left-arm wrist-spin
36     13217       Arshdeep Singh   Left-hand bat   Left-arm fast-medium
37     24729         Harshit Rana  Right-hand bat  Right-arm fast-medium
38     14659         Ravi Bishnoi  Right-hand bat     Right-arm legbreak
39     10754         Mukesh Kumar  Right-hand bat  Right-arm fast-medium
40     12926  Varun Chakaravarthy  Right-hand bat     Right-arm legbreak

In [25]:
df["playingrole"] = None

In [26]:
df

,player_id,full_name,batting_style,bowling_style,playingrole
0,NaN,BATSMEN,NaN,NaN,None
1,11808,Shubman Gill,Right-hand bat,Right-arm offbreak,None
2,13940,Yashasvi Jaiswal,Left-hand bat,Right-arm legbreak,None
3,13866,Sai Sudharsan,Left-hand bat,Right-arm legbreak,None
4,576,Rohit Sharma,Right-hand bat,Right-arm offbreak,None
5,1413,Virat Kohli,Right-hand bat,Right-arm medium,None
6,7915,Suryakumar Yadav,Right-hand bat,Right-arm offbreak,None
7,9428,Shreyas Iyer,Right-hand bat,Right-arm legbreak,None
8,10896,Rinku Singh,Left-hand bat,Right-arm offbreak,None
9,14504,Tilak Varma,Left-hand bat,Right-arm offbreak,None
10,11813,Ruturaj Gaikwad,Right-hand bat,Right-arm offbreak,None
11,10636,Rajat Patidar,Right-hand bat,Right-arm offbreak,None
12,9429,Sarfaraz Khan,Right-hand bat,Right-arm legbreak,None
13,9716,Abhimanyu Easwaran,Right-hand bat,Right-arm legbreak,None
14,8257,Karun Nair,Right-hand bat,Right-arm offbreak,None
15,NaN,ALL ROUNDER,NaN,NaN,None
16,14701,Nitish Kumar Reddy,Right-hand bat,Right-arm fast-medium,None
17,9647,Hardik Pandya,Right-hand bat,Right-arm fast-medium,None
18,11195,Shivam Dube,Left-hand bat,Right-arm medium,None
19,12086,Abhishek Sharma,Left-hand bat,Left-arm orthodox,None
20,587,Ravindra Jadeja,Left-hand bat,Left-arm orthodox,None
21,8683,Shardul Thakur,Right-hand bat,Right-arm fast-medium,None
22,10945,Washington Sundar,Left-hand bat,Right-arm offbreak,None
23,8808,Axar Patel,Left-hand bat,Left-arm orthodox,None
24,NaN,WICKET KEEPER,NaN,NaN,None
25,10744,Rishabh Pant,Left-hand bat,NaN,None
26,8733,KL Rahul,Right-hand bat,NaN,None
27,14691,Dhruv Jurel,Right-hand bat,NaN,None
28,8271,Sanju Samson,Right-hand bat,NaN,None
29,10276,Ishan Kishan,Left-hand bat,NaN,None
30,NaN,BOWLER,NaN,NaN,None
31,10808,Mohammed Siraj,Right-hand bat,Right-arm fast,None
32,9311,Jasprit Bumrah,Right-hand bat,Right-arm fast,None
33,10551,Prasidh Krishna,Right-hand bat,Right-arm fast,None
34,14726,Akash Deep,Right-hand bat,Right-arm fast-medium,None
35,8292,Kuldeep Yadav,Left-hand bat,Left-arm wrist-spin,None
36,13217,Arshdeep Singh,Left-hand bat,Left-arm fast-medium,None
37,24729,Harshit Rana,Right-hand bat,Right-arm fast-medium,None
38,14659,Ravi Bishnoi,Right-hand bat,Right-arm legbreak,None
39,10754,Mukesh Kumar,Right-hand bat,Right-arm fast-medium,None
40,12926,Varun Chakaravarthy,Right-hand bat,Right-arm legbreak,None

In [27]:
df.loc[0:14, "playingrole"] = "Batsman"

In [28]:
df

,player_id,full_name,batting_style,bowling_style,playingrole
0,NaN,BATSMEN,NaN,NaN,Batsman
1,11808,Shubman Gill,Right-hand bat,Right-arm offbreak,Batsman
2,13940,Yashasvi Jaiswal,Left-hand bat,Right-arm legbreak,Batsman
3,13866,Sai Sudharsan,Left-hand bat,Right-arm legbreak,Batsman
4,576,Rohit Sharma,Right-hand bat,Right-arm offbreak,Batsman
5,1413,Virat Kohli,Right-hand bat,Right-arm medium,Batsman
6,7915,Suryakumar Yadav,Right-hand bat,Right-arm offbreak,Batsman
7,9428,Shreyas Iyer,Right-hand bat,Right-arm legbreak,Batsman
8,10896,Rinku Singh,Left-hand bat,Right-arm offbreak,Batsman
9,14504,Tilak Varma,Left-hand bat,Right-arm offbreak,Batsman
10,11813,Ruturaj Gaikwad,Right-hand bat,Right-arm offbreak,Batsman
11,10636,Rajat Patidar,Right-hand bat,Right-arm offbreak,Batsman
12,9429,Sarfaraz Khan,Right-hand bat,Right-arm legbreak,Batsman
13,9716,Abhimanyu Easwaran,Right-hand bat,Right-arm legbreak,Batsman
14,8257,Karun Nair,Right-hand bat,Right-arm offbreak,Batsman
15,NaN,ALL ROUNDER,NaN,NaN,None
16,14701,Nitish Kumar Reddy,Right-hand bat,Right-arm fast-medium,None
17,9647,Hardik Pandya,Right-hand bat,Right-arm fast-medium,None
18,11195,Shivam Dube,Left-hand bat,Right-arm medium,None
19,12086,Abhishek Sharma,Left-hand bat,Left-arm orthodox,None
20,587,Ravindra Jadeja,Left-hand bat,Left-arm orthodox,None
21,8683,Shardul Thakur,Right-hand bat,Right-arm fast-medium,None
22,10945,Washington Sundar,Left-hand bat,Right-arm offbreak,None
23,8808,Axar Patel,Left-hand bat,Left-arm orthodox,None
24,NaN,WICKET KEEPER,NaN,NaN,None
25,10744,Rishabh Pant,Left-hand bat,NaN,None
26,8733,KL Rahul,Right-hand bat,NaN,None
27,14691,Dhruv Jurel,Right-hand bat,NaN,None
28,8271,Sanju Samson,Right-hand bat,NaN,None
29,10276,Ishan Kishan,Left-hand bat,NaN,None
30,NaN,BOWLER,NaN,NaN,None
31,10808,Mohammed Siraj,Right-hand bat,Right-arm fast,None
32,9311,Jasprit Bumrah,Right-hand bat,Right-arm fast,None
33,10551,Prasidh Krishna,Right-hand bat,Right-arm fast,None
34,14726,Akash Deep,Right-hand bat,Right-arm fast-medium,None
35,8292,Kuldeep Yadav,Left-hand bat,Left-arm wrist-spin,None
36,13217,Arshdeep Singh,Left-hand bat,Left-arm fast-medium,None
37,24729,Harshit Rana,Right-hand bat,Right-arm fast-medium,None
38,14659,Ravi Bishnoi,Right-hand bat,Right-arm legbreak,None
39,10754,Mukesh Kumar,Right-hand bat,Right-arm fast-medium,None
40,12926,Varun Chakaravarthy,Right-hand bat,Right-arm legbreak,None

In [29]:
df.loc[31:40, "playingrole"] = "Bowler"

In [30]:
df

,player_id,full_name,batting_style,bowling_style,playingrole
0,NaN,BATSMEN,NaN,NaN,Batsman
1,11808,Shubman Gill,Right-hand bat,Right-arm offbreak,Batsman
2,13940,Yashasvi Jaiswal,Left-hand bat,Right-arm legbreak,Batsman
3,13866,Sai Sudharsan,Left-hand bat,Right-arm legbreak,Batsman
4,576,Rohit Sharma,Right-hand bat,Right-arm offbreak,Batsman
5,1413,Virat Kohli,Right-hand bat,Right-arm medium,Batsman
6,7915,Suryakumar Yadav,Right-hand bat,Right-arm offbreak,Batsman
7,9428,Shreyas Iyer,Right-hand bat,Right-arm legbreak,Batsman
8,10896,Rinku Singh,Left-hand bat,Right-arm offbreak,Batsman
9,14504,Tilak Varma,Left-hand bat,Right-arm offbreak,Batsman
10,11813,Ruturaj Gaikwad,Right-hand bat,Right-arm offbreak,Batsman
11,10636,Rajat Patidar,Right-hand bat,Right-arm offbreak,Batsman
12,9429,Sarfaraz Khan,Right-hand bat,Right-arm legbreak,Batsman
13,9716,Abhimanyu Easwaran,Right-hand bat,Right-arm legbreak,Batsman
14,8257,Karun Nair,Right-hand bat,Right-arm offbreak,Batsman
15,NaN,ALL ROUNDER,NaN,NaN,None
16,14701,Nitish Kumar Reddy,Right-hand bat,Right-arm fast-medium,None
17,9647,Hardik Pandya,Right-hand bat,Right-arm fast-medium,None
18,11195,Shivam Dube,Left-hand bat,Right-arm medium,None
19,12086,Abhishek Sharma,Left-hand bat,Left-arm orthodox,None
20,587,Ravindra Jadeja,Left-hand bat,Left-arm orthodox,None
21,8683,Shardul Thakur,Right-hand bat,Right-arm fast-medium,None
22,10945,Washington Sundar,Left-hand bat,Right-arm offbreak,None
23,8808,Axar Patel,Left-hand bat,Left-arm orthodox,None
24,NaN,WICKET KEEPER,NaN,NaN,None
25,10744,Rishabh Pant,Left-hand bat,NaN,None
26,8733,KL Rahul,Right-hand bat,NaN,None
27,14691,Dhruv Jurel,Right-hand bat,NaN,None
28,8271,Sanju Samson,Right-hand bat,NaN,None
29,10276,Ishan Kishan,Left-hand bat,NaN,None
30,NaN,BOWLER,NaN,NaN,None
31,10808,Mohammed Siraj,Right-hand bat,Right-arm fast,Bowler
32,9311,Jasprit Bumrah,Right-hand bat,Right-arm fast,Bowler
33,10551,Prasidh Krishna,Right-hand bat,Right-arm fast,Bowler
34,14726,Akash Deep,Right-hand bat,Right-arm fast-medium,Bowler
35,8292,Kuldeep Yadav,Left-hand bat,Left-arm wrist-spin,Bowler
36,13217,Arshdeep Singh,Left-hand bat,Left-arm fast-medium,Bowler
37,24729,Harshit Rana,Right-hand bat,Right-arm fast-medium,Bowler
38,14659,Ravi Bishnoi,Right-hand bat,Right-arm legbreak,Bowler
39,10754,Mukesh Kumar,Right-hand bat,Right-arm fast-medium,Bowler
40,12926,Varun Chakaravarthy,Right-hand bat,Right-arm legbreak,Bowler

# Q1 Final Indian player list 
Question 1 Find all players who represent India. Display their full name, playing role, batting style, and bowling style.

In [31]:
df.drop(index=[0, 15, 24, 30], inplace=True)
df

,player_id,full_name,batting_style,bowling_style,playingrole
1,11808,Shubman Gill,Right-hand bat,Right-arm offbreak,Batsman
2,13940,Yashasvi Jaiswal,Left-hand bat,Right-arm legbreak,Batsman
3,13866,Sai Sudharsan,Left-hand bat,Right-arm legbreak,Batsman
4,576,Rohit Sharma,Right-hand bat,Right-arm offbreak,Batsman
5,1413,Virat Kohli,Right-hand bat,Right-arm medium,Batsman
6,7915,Suryakumar Yadav,Right-hand bat,Right-arm offbreak,Batsman
7,9428,Shreyas Iyer,Right-hand bat,Right-arm legbreak,Batsman
8,10896,Rinku Singh,Left-hand bat,Right-arm offbreak,Batsman
9,14504,Tilak Varma,Left-hand bat,Right-arm offbreak,Batsman
10,11813,Ruturaj Gaikwad,Right-hand bat,Right-arm offbreak,Batsman
11,10636,Rajat Patidar,Right-hand bat,Right-arm offbreak,Batsman
12,9429,Sarfaraz Khan,Right-hand bat,Right-arm legbreak,Batsman
13,9716,Abhimanyu Easwaran,Right-hand bat,Right-arm legbreak,Batsman
14,8257,Karun Nair,Right-hand bat,Right-arm offbreak,Batsman
16,14701,Nitish Kumar Reddy,Right-hand bat,Right-arm fast-medium,None
17,9647,Hardik Pandya,Right-hand bat,Right-arm fast-medium,None
18,11195,Shivam Dube,Left-hand bat,Right-arm medium,None
19,12086,Abhishek Sharma,Left-hand bat,Left-arm orthodox,None
20,587,Ravindra Jadeja,Left-hand bat,Left-arm orthodox,None
21,8683,Shardul Thakur,Right-hand bat,Right-arm fast-medium,None
22,10945,Washington Sundar,Left-hand bat,Right-arm offbreak,None
23,8808,Axar Patel,Left-hand bat,Left-arm orthodox,None
25,10744,Rishabh Pant,Left-hand bat,NaN,None
26,8733,KL Rahul,Right-hand bat,NaN,None
27,14691,Dhruv Jurel,Right-hand bat,NaN,None
28,8271,Sanju Samson,Right-hand bat,NaN,None
29,10276,Ishan Kishan,Left-hand bat,NaN,None
31,10808,Mohammed Siraj,Right-hand bat,Right-arm fast,Bowler
32,9311,Jasprit Bumrah,Right-hand bat,Right-arm fast,Bowler
33,10551,Prasidh Krishna,Right-hand bat,Right-arm fast,Bowler
34,14726,Akash Deep,Right-hand bat,Right-arm fast-medium,Bowler
35,8292,Kuldeep Yadav,Left-hand bat,Left-arm wrist-spin,Bowler
36,13217,Arshdeep Singh,Left-hand bat,Left-arm fast-medium,Bowler
37,24729,Harshit Rana,Right-hand bat,Right-arm fast-medium,Bowler
38,14659,Ravi Bishnoi,Right-hand bat,Right-arm legbreak,Bowler
39,10754,Mukesh Kumar,Right-hand bat,Right-arm fast-medium,Bowler
40,12926,Varun Chakaravarthy,Right-hand bat,Right-arm legbreak,Bowler

In [32]:
import psycopg2

# 1. Establish the connection
conn = psycopg2.connect(
    host='localhost',
    database='cricbuzz',
    user='postgres',
    password='deepika@88',
    port=5432
)

# 2. Create a cursor object (this executes your SQL)
cur = conn.cursor()

In [33]:
cur.execute("""
    CREATE TABLE IF NOT EXISTS indian_Players (
        player_id VARCHAR(50),
        full_name VARCHAR(100),
        playing_role VARCHAR(50),
        batting_style VARCHAR(50),
        bowling_style VARCHAR(50)
    );
""")

In [34]:
conn.commit()

In [35]:
cur.execute("""
    CREATE TABLE IF NOT EXISTS indianPlayers (
        player_id VARCHAR(50),
        full_name VARCHAR(100),
        playing_role VARCHAR(50),
        batting_style VARCHAR(50),
        bowling_style VARCHAR(50)
    );
""")

# 4. Insert data from your 'indianplayers' list
for player in indianplayers:
    # Skip the 'BATSMEN' header row if it exists in your list
    if player.get('player_id') is None:
        continue
        
    cur.execute("""
        INSERT INTO indianPlayers (player_id, full_name, playing_role, batting_style, bowling_style)
        VALUES (%s, %s, %s, %s, %s)
    """, (
        player.get('player_id'),
        player.get('full_name'),
        player.get('playing_role'),
        player.get('batting_style'),
        player.get('bowling_style')
        
    ))

# 5. Commit the changes and close
conn.commit()
cur.close()
conn.close()

print("Data successfully pushed to PostgreSQL using psycopg2!")

Data successfully pushed to PostgreSQL using psycopg2!

In [36]:
import urllib.parse
from sqlalchemy import create_engine

# 1. Encode the special character in password
password = urllib.parse.quote_plus("deepika@88")

# 2. Use the encoded password in your connection string
# Also, ensure 'username' is replaced with your actual DB user (usually 'postgres')
engine = create_engine(f'postgresql+psycopg2://postgres:{password}@localhost:5432/cricbuzz')

# 3. Test the connection and push the data
df.to_sql('players_india', engine, if_exists='replace', index=False)

print("✅ Connection successful and table 'players_india' created!")

✅ Connection successful and table 'players_india' created!

# Q2
Show all cricket matches that were played in the last Few days. Include the match description, both team names, venue name with city, and the match date. Sort by most recent matches first.

In [39]:
import requests
import pandas as pd

url = "https://cricbuzz-cricket.p.rapidapi.com/matches/v1/recent"

headers = {
	"x-rapidapi-key": "87cb73cb75msh7a5d872ecde1a59p1feac0jsne6c94486f484",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

match_data = response.json()

In [38]:
print(match_data.keys())

dict_keys(['typeMatches', 'filters', 'appIndex', 'responseLastUpdated'])

In [39]:
match_data['filters']
match_data['typeMatches']

[{'matchType': 'International',
  'seriesMatches': [{'seriesAdWrapper': {'seriesId': 11253,
     'seriesName': "ICC Men's T20 World Cup 2026",
     'matches': [{'matchInfo': {'matchId': 139461,
        'seriesId': 11253,
        'seriesName': "ICC Men's T20 World Cup 2026",
        'matchDesc': '52nd Match, Super 8 Group 1 (X1 v X3)',
        'matchFormat': 'T20',
        'startDate': '1772371800000',
        'endDate': '1772384400000',
        'state': 'Complete',
        'status': 'India won by 5 wkts',
        'team1': {'teamId': 10,
         'teamName': 'West Indies',
         'teamSName': 'WI',
         'imageId': 776191},
        'team2': {'teamId': 2,
         'teamName': 'India',
         'teamSName': 'IND',
         'imageId': 776162},
        'venueInfo': {'id': 31,
         'ground': 'Eden Gardens',
         'city': 'Kolkata',
         'timezone': '+05:30',
         'latitude': '22.564527',
         'longitude': '88.343247'},
        'currBatTeamId': 2,
        'seriesStartDt': '1770422400000',
        'seriesEndDt': '1773100800000',
        'isTimeAnnounced': True,
        'stateTitle': 'IND Won',
        'isFantasyEnabled': True},
       'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
          'runs': 195,
          'wickets': 4,
          'overs': 19.6}},
        'team2Score': {'inngs1': {'inningsId': 2,
          'runs': 199,
          'wickets': 5,
          'overs': 19.2}}}},
      {'matchInfo': {'matchId': 139450,
        'seriesId': 11253,
        'seriesName': "ICC Men's T20 World Cup 2026",
        'matchDesc': '51st Match, Super 8 Group 1 (X2 v X4)',
        'matchFormat': 'T20',
        'startDate': '1772357400000',
        'endDate': '1772370000000',
        'state': 'Complete',
        'status': 'South Africa won by 5 wkts',
        'team1': {'teamId': 12,
         'teamName': 'Zimbabwe',
         'teamSName': 'ZIM',
         'imageId': 776198},
        'team2': {'teamId': 11,
         'teamName': 'South Africa',
         'teamSName': 'RSA',
         'imageId': 776287},
        'venueInfo': {'id': 51,
         'ground': 'Arun Jaitley Stadium',
         'city': 'Delhi',
         'timezone': '+05:30',
         'latitude': '28.637891',
         'longitude': '77.243073'},
        'currBatTeamId': 11,
        'seriesStartDt': '1770422400000',
        'seriesEndDt': '1773100800000',
        'isTimeAnnounced': True,
        'stateTitle': 'RSA Won',
        'isFantasyEnabled': True},
       'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
          'runs': 153,
          'wickets': 7,
          'overs': 19.6}},
        'team2Score': {'inngs1': {'inningsId': 2,
          'runs': 154,
          'wickets': 5,
          'overs': 17.5}}}},
      {'matchInfo': {'matchId': 139448,
        'seriesId': 11253,
        'seriesName': "ICC Men's T20 World Cup 2026",
        'matchDesc': '50th Match, Super 8 Group 2 (Y3 v Y4)',
        'matchFormat': 'T20',
        'startDate': '1772285400000',
        'endDate': '1772298000000',
        'state': 'Complete',
        'status': 'Pakistan won by 5 runs',
        'team1': {'teamId': 3,
         'teamName': 'Pakistan',
         'teamSName': 'PAK',
         'imageId': 776308},
        'team2': {'teamId': 5,
         'teamName': 'Sri Lanka',
         'teamSName': 'SL',
         'imageId': 776254},
        'venueInfo': {'id': 254,
         'ground': 'Pallekele International Cricket Stadium',
         'city': 'Pallekele',
         'timezone': '+05:30',
         'latitude': '7.280691',
         'longitude': '80.722493'},
        'currBatTeamId': 3,
        'seriesStartDt': '1770422400000',
        'seriesEndDt': '1773100800000',
        'isTimeAnnounced': True,
        'stateTitle': 'PAK Won',
        'isFantasyEnabled': True},
       'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
          'runs': 212,
          'wickets': 8,
          'overs': 19.6}},
        'team2Score': {'inngs1': {'inningsId': 2,
          'runs': 207,
          'wickets': 6,
          'overs': 19.6}}}},
      {'matchInfo': {'matchId': 139437,
        'seriesId': 11253,
        'seriesName': "ICC Men's T20 World Cup 2026",
        'matchDesc': '49th Match, Super 8 Group 2 (Y1 v Y2)',
        'matchFormat': 'T20',
        'startDate': '1772199000000',
        'endDate': '1772211600000',
        'state': 'Complete',
        'status': 'England won by 4 wkts',
        'team1': {'teamId': 13,
         'teamName': 'New Zealand',
         'teamSName': 'NZ',
         'imageId': 776333},
        'team2': {'teamId': 9,
         'teamName': 'England',
         'teamSName': 'ENG',
         'imageId': 776237},
        'venueInfo': {'id': 15,
         'ground': 'R.Premadasa Stadium',
         'city': 'Colombo',
         'timezone': '+05:30',
         'latitude': '6.939966',
         'longitude': '79.872222'},
        'currBatTeamId': 9,
        'seriesStartDt': '1770422400000',
        'seriesEndDt': '1773100800000',
        'isTimeAnnounced': True,
        'stateTitle': 'ENG Won',
        'isFantasyEnabled': True},
       'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
          'runs': 159,
          'wickets': 7,
          'overs': 19.6}},
        'team2Score': {'inngs1': {'inningsId': 2,
          'runs': 161,
          'wickets': 6,
          'overs': 19.3}}}},
      {'matchInfo': {'matchId': 139426,
        'seriesId': 11253,
        'seriesName': "ICC Men's T20 World Cup 2026",
        'matchDesc': '48th Match, Super 8 Group 1 (X1 v X2)',
        'matchFormat': 'T20',
        'startDate': '1772112600000',
        'endDate': '1772125200000',
        'state': 'Complete',
        'status': 'India won by 72 runs',
        'team1': {'teamId': 2,
         'teamName': 'India',
         'teamSName': 'IND',
         'imageId': 776162},
        'team2': {'teamId': 12,
         'teamName': 'Zimbabwe',
         'teamSName': 'ZIM',
         'imageId': 776198},
        'venueInfo': {'id': 11,
         'ground': 'MA Chidambaram Stadium',
         'city': 'Chennai',
         'timezone': '+05:30',
         'latitude': '13.06282',
         'longitude': '80.279274'},
        'currBatTeamId': 2,
        'seriesStartDt': '1770422400000',
        'seriesEndDt': '1773100800000',
        'isTimeAnnounced': True,
        'stateTitle': 'IND Won',
        'isFantasyEnabled': True},
       'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
          'runs': 256,
          'wickets': 4,
          'overs': 19.6}},
        'team2Score': {'inngs1': {'inningsId': 2,
          'runs': 184,
          'wickets': 6,
          'overs': 19.6}}}},
      {'matchInfo': {'matchId': 139415,
        'seriesId': 11253,
        'seriesName': "ICC Men's T20 World Cup 2026",
        'matchDesc': '47th Match, Super 8 Group 1 (X3 v X4)',
        'matchFormat': 'T20',
        'startDate': '1772098200000',
        'endDate': '1772110800000',
        'state': 'Complete',
        'status': 'South Africa won by 9 wkts',
        'team1': {'teamId': 10,
         'teamName': 'West Indies',
         'teamSName': 'WI',
         'imageId': 776191},
        'team2': {'teamId': 11,
         'teamName': 'South Africa',
         'teamSName': 'RSA',
         'imageId': 776287},
        'venueInfo': {'id': 50,
         'ground': 'Narendra Modi Stadium',
         'city': 'Ahmedabad',
         'timezone': '+05:30',
         'latitude': '23.091785',
         'longitude': '72.597465'},
        'currBatTeamId': 11,
        'seriesStartDt': '1770422400000',
        'seriesEndDt': '1773100800000',
        'isTimeAnnounced': True,
        'stateTitle': 'RSA Won',
        'isFantasyEnabled': True},
       'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
          'runs': 176,
          'wickets': 8,
          'overs': 19.6}},
        'team2Score': {'inngs1': {'inningsId': 2,
          'runs': 177,
          'wickets': 1,
          'overs': 16.1}}}},
      {'matchInfo': {'matchId': 139404,
        'seriesId': 11253,
        'seriesName': "ICC Men's T20 World Cup 2026",
        'matchDesc': '46th Match, Super 8 Group 2 (Y2 v Y4)',
        'matchFormat': 'T20',
        'startDate': '1772026200000',
        'endDate': '1772038800000',
        'state': 'Complete',
        'status': 'New Zealand won by 61 runs',
        'team1': {'teamId': 13,
         'teamName': 'New Zealand',
         'teamSName': 'NZ',
         'imageId': 776333},
        'team2': {'teamId': 5,
         'teamName': 'Sri Lanka',
         'teamSName': 'SL',
         'imageId': 776254},
        'venueInfo': {'id': 15,
         'ground': 'R.Premadasa Stadium',
         'city': 'Colombo',
         'timezone': '+05:30',
         'latitude': '6.939966',
         'longitude': '79.872222'},
        'currBatTeamId': 13,
        'seriesStartDt': '1770422400000',
        'seriesEndDt': '1773100800000',
        'isTimeAnnounced': True,
        'stateTitle': 'NZ Won',
        'isFantasyEnabled': True},
       'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
          'runs': 168,
          'wickets': 7,
          'overs': 19.6}},
        'team2Score': {'inngs1': {'inningsId': 2,
          'runs': 107,
          'wickets': 8,
          'overs': 19.6}}}},
      {'matchInfo': {'matchId': 139393,
        'seriesId': 11253,
        'seriesName': "ICC Men's T20 World Cup 2026",
        'matchDesc': '45th Match, Super 8 Group 2 (Y1 v Y3)',
        'matchFormat': 'T20',
        'startDate': '1771939800000',
        'endDate': '1771952400000',
        'state': 'Complete',
        'status': 'England won by 2 wkts',
        'team1': {'teamId': 3,
         'teamName': 'Pakistan',
         'teamSName': 'PAK',
         'imageId': 776308},
        'team2': {'teamId': 9,
         'teamName': 'England',
         'teamSName': 'ENG',
         'imageId': 776237},
        'venueInfo': {'id': 254,
         'ground': 'Pallekele International Cricket Stadium',
         'city': 'Pallekele',
         'timezone': '+05:30',
         'latitude': '7.280691',
         'longitude': '80.722493'},
        'currBatTeamId': 9,
        'seriesStartDt': '1770422400000',
        'seriesEndDt': '1773100800000',
        'isTimeAnnounced': True,
        'stateTitle': 'ENG Won',
        'isFantasyEnabled': True},
       'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
          'runs': 164,
          'wickets': 9,
          'overs': 19.6}},
        'team2Score': {'inngs1': {'inningsId': 2,
          'runs': 166,
          'wickets': 8,
          'overs': 19.1}}}},
      {'matchInfo': {'matchId': 139382,
        'seriesId': 11253,
        'seriesName': "ICC Men's T20 World Cup 2026",
        'matchDesc': '44th Match, Super 8 Group 1 (X2 v X3)',
        'matchFormat': 'T20',
        'startDate': '1771853400000',
        'endDate': '1771866000000',
        'state': 'Complete',
        'status': 'West Indies won by 107 runs',
        'team1': {'teamId': 10,
         'teamName': 'West Indies',
         'teamSName': 'WI',
         'imageId': 776191},
        'team2': {'teamId': 12,
         'teamName': 'Zimbabwe',
         'teamSName': 'ZIM',
         'imageId': 776198},
        'venueInfo': {'id': 81,
         'ground': 'Wankhede Stadium',
         'city': 'Mumbai',
         'timezone': '+05:30',
         'latitude': '18.938956',
         'longitude': '72.825719'},
        'currBatTeamId': 10,
        'seriesStartDt': '1770422400000',
        'seriesEndDt': '1773100800000',
        'isTimeAnnounced': True,
        'stateTitle': 'WI Won',
        'isFantasyEnabled': True},
       'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
          'runs': 254,
          'wickets': 6,
          'overs': 19.6}},
        'team2Score': {'inngs1': {'inningsId': 2,
          'runs': 147,
          'wickets': 10,
          'overs': 17.4}}}}]}},
   {'seriesAdWrapper': {'seriesId': 11542,
     'seriesName': 'Quadrangular T20I Series in Thailand 2026 ',
     'matches': [{'matchInfo': {'matchId': 147016,
        'seriesId': 11542,
        'seriesName': 'Quadrangular T20I Series in Thailand 2026 ',
        'matchDesc': 'Final',
        'matchFormat': 'T20',
        'startDate': '1772260200000',
        'endDate': '1772272800000',
        'state': 'Complete',
        'status': 'Match tied (Bahrain won the super over)',
        'team1': {'teamId': 547,
         'teamName': 'Japan',
         'teamSName': 'JPN',
         'imageId': 248418},
        'team2': {'teamId': 543,
         'teamName': 'Bahrain',
         'teamSName': 'BHR',
         'imageId': 172594},
        'venueInfo': {'id': 474,
         'ground': 'Terdthai Cricket Ground',
         'city': 'Bangkok',
         'timezone': '+07:00',
         'latitude': '13.756331',
         'longitude': '100.501765'},
        'seriesStartDt': '1771977600000',
        'seriesEndDt': '1772409600000',
        'isTimeAnnounced': True,
        'stateTitle': 'Complete'},
       'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
          'runs': 108,
          'wickets': 9,
          'overs': 19.6}},
        'team2Score': {'inngs1': {'inningsId': 2,
          'runs': 108,
          'wickets': 9,
          'overs': 19.6}}}},
      {'matchInfo': {'matchId': 147005,
        'seriesId': 11542,
        'seriesName': 'Quadrangular T20I Series in Thailand 2026 ',
        'matchDesc': '3rd place play-off',
        'matchFormat': 'T20',
        'startDate': '1772244000000',
        'endDate': '1772256600000',
        'state': 'Complete',
        'status': 'Bhutan won by 7 runs',
        'team1': {'teamId': 555,
         'teamName': 'Bhutan',
         'teamSName': 'BTN',
         'imageId': 172607},
        'team2': {'teamId': 384,
         'teamName': 'Thailand',
         'teamSName': 'THAI',
         'imageId': 172437},
        'venueInfo': {'id': 474,
         'ground': 'Terdthai Cricket Ground',
         'city': 'Bangkok',
         'timezone': '+07:00',
         'latitude': '13.756331',
         'longitude': '100.501765'},
        'currBatTeamId': 555,
        'seriesStartDt': '1771977600000',
        'seriesEndDt': '1772409600000',
        'isTimeAnnounced': True,
        'stateTitle': 'BTN Won'},
       'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
          'runs': 86,
          'wickets': 8,
          'overs': 12.6}},
        'team2Score': {'inngs1': {'inningsId': 2,
          'runs': 79,
          'wickets': 9,
          'overs': 12.6}}}},
      {'matchInfo': {'matchId': 146994,
        'seriesId': 11542,
        'seriesName': 'Quadrangular T20I Series in Thailand 2026 ',
        'matchDesc': '6th Match',
        'matchFormat': 'T20',
        'startDate': '1772173800000',
        'endDate': '1772186400000',
        'state': 'Complete',
        'status': 'Bahrain won by 12 runs',
        'team1': {'teamId': 543,
         'teamName': 'Bahrain',
         'teamSName': 'BHR',
         'imageId': 172594},
        'team2': {'teamId': 384,
         'teamName': 'Thailand',
         'teamSName': 'THAI',
         'imageId': 172437},
        'venueInfo': {'id': 474,
         'ground': 'Terdthai Cricket Ground',
         'city': 'Bangkok',
         'timezone': '+07:00',
         'latitude': '13.756331',
         'longitude': '100.501765'},
        'currBatTeamId': 543,
        'seriesStartDt': '1771977600000',
        'seriesEndDt': '1772409600000',
        'isTimeAnnounced': True,
        'stateTitle': 'BHR Won'},
       'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
          'runs': 126,
          'wickets': 7,
          'overs': 19.6}},
        'team2Score': {'inngs1': {'inningsId': 2,
          'runs': 114,
          'wickets': 10,
          'overs': 19.3}}}},
      {'matchInfo': {'matchId': 146983,
        'seriesId': 11542,
        'seriesName': 'Quadrangular T20I Series in Thailand 2026 ',
        'matchDesc': '5th Match',
        'matchFormat': 'T20',
        'startDate': '1772157600000',
        'endDate': '1772170200000',
        'state': 'Complete',
        'status': 'Japan won by 77 runs',
        'team1': {'teamId': 547,
         'teamName': 'Japan',
         'teamSName': 'JPN',
         'imageId': 248418},
        'team2': {'teamId': 555,
         'teamName': 'Bhutan',
         'teamSName': 'BTN',
         'imageId': 172607},
        'venueInfo': {'id': 474,
         'ground': 'Terdthai Cricket Ground',
         'city': 'Bangkok',
         'timezone': '+07:00',
         'latitude': '13.756331',
         'longitude': '100.501765'},
        'currBatTeamId': 547,
        'seriesStartDt': '1771977600000',
        'seriesEndDt': '1772409600000',
        'isTimeAnnounced': True,
        'stateTitle': 'JPN Won'},
       'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
          'runs': 170,
          'wickets': 5,
          'overs': 19.6}},
        'team2Score': {'inngs1': {'inningsId': 2,
          'runs': 93,
          'wickets': 10,
          'overs': 18.2}}}},
      {'matchInfo': {'matchId': 146972,
        'seriesId': 11542,
        'seriesName': 'Quadrangular T20I Series in Thailand 2026 ',
        'matchDesc': '4th Match',
        'matchFormat': 'T20',
        'startDate': '1772087400000',
        'endDate': '1772100000000',
        'state': 'Complete',
        'status': 'Japan won by 8 wkts',
        'team1': {'teamId': 543,
         'teamName': 'Bahrain',
         'teamSName': 'BHR',
         'imageId': 172594},
        'team2': {'teamId': 547,
         'teamName': 'Japan',
         'teamSName': 'JPN',
         'imageId': 248418},
        'venueInfo': {'id': 474,
         'ground': 'Terdthai Cricket Ground',
         'city': 'Bangkok',
         'timezone': '+07:00',
         'latitude': '13.756331',
         'longitude': '100.501765'},
        'currBatTeamId': 547,
        'seriesStartDt': '1771977600000',
        'seriesEndDt': '1772409600000',
        'isTimeAnnounced': True,
        'stateTitle': 'JPN Won'},
       'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
          'runs': 87,
          'wickets': 10,
          'overs': 19.2}},
        'team2Score': {'inngs1': {'inningsId': 2,
          'runs': 88,
          'wickets': 2,
          'overs': 6.6}}}},
      {'matchInfo': {'matchId': 146961,
        'seriesId': 11542,
        'seriesName': 'Quadrangular T20I Series in Thailand 2026 ',
        'matchDesc': '3rd Match',
        'matchFormat': 'T20',
        'startDate': '1772071200000',
        'endDate': '1772083800000',
        'state': 'Complete',
        'status': 'Thailand won by 60 runs',
        'team1': {'teamId': 384,
         'teamName': 'Thailand',
         'teamSName': 'THAI',
         'imageId': 172437},
        'team2': {'teamId': 555,
         'teamName': 'Bhutan',
         'teamSName': 'BTN',
         'imageId': 172607},
        'venueInfo': {'id': 474,
         'ground': 'Terdthai Cricket Ground',
         'city': 'Bangkok',
         'timezone': '+07:00',
         'latitude': '13.756331',
         'longitude': '100.501765'},
        'currBatTeamId': 384,
        'seriesStartDt': '1771977600000',
        'seriesEndDt': '1772409600000',
        'isTimeAnnounced': True,
        'stateTitle': 'THAI Won'},
       'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
          'runs': 140,
          'wickets': 6,
          'overs': 19.6}},
        'team2Score': {'inngs1': {'inningsId': 2,
          'runs': 80,
          'wickets': 10,
          'overs': 17.1}}}},
      {'matchInfo': {'matchId': 146950,
        'seriesId': 11542,
        'seriesName': 'Quadrangular T20I Series in Thailand 2026 ',
        'matchDesc': '2nd Match',
        'matchFormat': 'T20',
        'startDate': '1772001000000',
        'endDate': '1772013600000',
        'state': 'Complete',
        'status': 'Bahrain won by 4 wkts',
        'team1': {'teamId': 555,
         'teamName': 'Bhutan',
         'teamSName': 'BTN',
         'imageId': 172607},
        'team2': {'teamId': 543,
         'teamName': 'Bahrain',
         'teamSName': 'BHR',
         'imageId': 172594},
        'venueInfo': {'id': 474,
         'ground': 'Terdthai Cricket Ground',

In [40]:
from datetime import datetime

matches1 = []

for type_match in match_data.get("typeMatches", []):
    for series_matches in type_match.get("seriesMatches", []):
        series_data = series_matches.get("seriesAdWrapper", {})

        for match in series_data.get("matches", []):
            match_info = match.get("matchInfo", {})

            match_desc = match_info.get("matchDesc")
            team1 = match_info.get("team1", {}).get("teamName")
            team2 = match_info.get("team2", {}).get("teamName")

            venue = f"{match_info.get('venueInfo', {}).get('ground')}, {match_info.get('venueInfo', {}).get('city')}"

            start_date = match_info.get("startDate")  # timestamp in ms

            # Convert timestamp → datetime
            if start_date:
                match_date = datetime.fromtimestamp(int(start_date)/1000)
            else:
                match_date = None

            matches1.append({
                "match_desc": match_desc,
                "team1": team1,
                "team2": team2,
                "venue": venue,
                "date": match_date
            })

In [41]:
matches_sorted = sorted(matches1, key=lambda x: x["date"], reverse=True)

In [42]:
df = pd.DataFrame(matches_sorted)
print(df.head(10))

                              match_desc  \
0                               2nd T20I
1  52nd Match, Super 8 Group 1 (X1 v X3)
2  51st Match, Super 8 Group 1 (X2 v X4)
3                              4th Match
4                              3rd Match
5                             10th Match
6                             11th Match
7                                3rd ODI
8                             12th Match
9                     2nd Unofficial ODI

                                   team1                           team2  \
0                      West Indies Women                 Sri Lanka Women
1                            West Indies                           India
2                               Zimbabwe                    South Africa
3                                 Titans                          Boland
4  North West - Eastvaal Renault Dragons  KwaZulu-Natal Inland - Tuskers
5          South Africa Emerging Players                         Knights
6                                Limpopo                   Northern Cape
7                         Pakistan Women              South Africa Women
8                                 Border               Mpumalanga Rhinos
9                             Pakistan A                   England Lions

                                           venue                date
0  National Cricket Stadium, St Georges, Grenada 2026-03-01 22:30:00
1                          Eden Gardens, Kolkata 2026-03-01 19:00:00
2                    Arun Jaitley Stadium, Delhi 2026-03-01 15:00:00
3                     SuperSport Park, Centurion 2026-03-01 13:30:00
4                    City Oval, Pietermaritzburg 2026-03-01 13:30:00
5                    Mangaung Oval, Bloemfontein 2026-03-01 13:30:00
6                        Diamond Oval, Kimberley 2026-03-01 13:30:00
7                              Kingsmead, Durban 2026-03-01 13:30:00
8       Uplands College, White River, Mpumalanga 2026-03-01 13:00:00
9                Sheikh Zayed Stadium, Abu Dhabi 2026-03-01 11:30:00

In [43]:
for m in matches_sorted[:10]:   # show latest 10 matches
    print("Match:", m["match_desc"])
    print("Teams:", m["team1"], "vs", m["team2"])
    print("Venue:", m["venue"])
    print("Date:", m["date"].strftime("%Y-%m-%d %H:%M:%S") if m["date"] else "N/A")
    print("-" * 60)

Match: 2nd T20I
Teams: West Indies Women vs Sri Lanka Women
Venue: National Cricket Stadium, St Georges, Grenada
Date: 2026-03-01 22:30:00
------------------------------------------------------------
Match: 52nd Match, Super 8 Group 1 (X1 v X3)
Teams: West Indies vs India
Venue: Eden Gardens, Kolkata
Date: 2026-03-01 19:00:00
------------------------------------------------------------
Match: 51st Match, Super 8 Group 1 (X2 v X4)
Teams: Zimbabwe vs South Africa
Venue: Arun Jaitley Stadium, Delhi
Date: 2026-03-01 15:00:00
------------------------------------------------------------
Match: 4th Match
Teams: Titans vs Boland
Venue: SuperSport Park, Centurion
Date: 2026-03-01 13:30:00
------------------------------------------------------------
Match: 3rd Match
Teams: North West - Eastvaal Renault Dragons vs KwaZulu-Natal Inland - Tuskers
Venue: City Oval, Pietermaritzburg
Date: 2026-03-01 13:30:00
------------------------------------------------------------
Match: 10th Match
Teams: South Africa Emerging Players vs Knights
Venue: Mangaung Oval, Bloemfontein
Date: 2026-03-01 13:30:00
------------------------------------------------------------
Match: 11th Match
Teams: Limpopo vs Northern Cape
Venue: Diamond Oval, Kimberley
Date: 2026-03-01 13:30:00
------------------------------------------------------------
Match: 3rd ODI
Teams: Pakistan Women vs South Africa Women
Venue: Kingsmead, Durban
Date: 2026-03-01 13:30:00
------------------------------------------------------------
Match: 12th Match
Teams: Border vs Mpumalanga Rhinos
Venue: Uplands College, White River, Mpumalanga
Date: 2026-03-01 13:00:00
------------------------------------------------------------
Match: 2nd Unofficial ODI
Teams: Pakistan A vs England Lions
Venue: Sheikh Zayed Stadium, Abu Dhabi
Date: 2026-03-01 11:30:00
------------------------------------------------------------

In [44]:
import psycopg2

conn = psycopg2.connect(
    host='localhost',
    database='cricbuzz',
    user='postgres',
    password='deepika@88',
    port=5432
)

cur = conn.cursor()

print("✅ PostgreSQL connected successfully")

✅ PostgreSQL connected successfully

In [45]:
insert_query = """
INSERT INTO recent_matches 
(match_desc, team1, team2, venue, match_date)
VALUES (%s, %s, %s, %s, %s)
"""

for m in matches_sorted:
    cur.execute(insert_query, (
        m.get("match_desc"),
        m.get("team1"),
        m.get("team2"),
        m.get("venue"),
        m.get("date")
    ))

conn.commit()
print("✅ Data inserted into PostgreSQL successfully")

✅ Data inserted into PostgreSQL successfully

#Q2 view

In [46]:
import pandas as pd

cur.execute("""
SELECT * 
FROM recent_matches 
ORDER BY match_date DESC 
LIMIT 10
""")

rows = cur.fetchall()

colnames = [desc[0] for desc in cur.description]

df = pd.DataFrame(rows, columns=colnames)
df

,id,match_desc,team1,team2,venue,match_date
0,86,2nd T20I,West Indies Women,Sri Lanka Women,"National Cricket Stadium, St Georges, Grenada",2026-03-01 22:30:00
1,87,"52nd Match, Super 8 Group 1 (X1 v X3)",West Indies,India,"Eden Gardens, Kolkata",2026-03-01 19:00:00
2,43,"51st Match, Super 8 Group 1 (X2 v X4)",Zimbabwe,South Africa,"Arun Jaitley Stadium, Delhi",2026-03-01 15:00:00
3,88,"51st Match, Super 8 Group 1 (X2 v X4)",Zimbabwe,South Africa,"Arun Jaitley Stadium, Delhi",2026-03-01 15:00:00
4,91,10th Match,South Africa Emerging Players,Knights,"Mangaung Oval, Bloemfontein",2026-03-01 13:30:00
5,90,3rd Match,North West - Eastvaal Renault Dragons,KwaZulu-Natal Inland - Tuskers,"City Oval, Pietermaritzburg",2026-03-01 13:30:00
6,44,3rd ODI,Pakistan Women,South Africa Women,"Kingsmead, Durban",2026-03-01 13:30:00
7,89,4th Match,Titans,Boland,"SuperSport Park, Centurion",2026-03-01 13:30:00
8,92,11th Match,Limpopo,Northern Cape,"Diamond Oval, Kimberley",2026-03-01 13:30:00
9,93,3rd ODI,Pakistan Women,South Africa Women,"Kingsmead, Durban",2026-03-01 13:30:00

# Batsmen details Top10

In [178]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/rankings/batsmen"

querystring = {"formatType":"test"}

headers = {
	"x-rapidapi-key": "87cb73cb75msh7a5d872ecde1a59p1feac0jsne6c94486f484",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

batsmen = response.json()

In [179]:
batsmen

{'message': 'You have exceeded the MONTHLY quota for Requests on your current plan, BASIC. Upgrade your plan at https://rapidapi.com/cricketapilive/api/cricbuzz-cricket'}

In [49]:
print(batsmen.keys())

dict_keys(['rank', 'appIndex'])

In [50]:
batsmen['appIndex']

{'seoTitle': 'ICC Cricket Rankings - Top 100 Batter | Cricbuzz.com',
 'webURL': 'www.cricbuzz.com/cricket-stats/icc-rankings'}

In [51]:
batsmen['rank']

[{'id': '8019',
  'rank': '1',
  'name': 'Joe Root',
  'country': 'England',
  'rating': '880',
  'points': '880',
  'lastUpdatedOn': '2026-03-02',
  'trend': 'Flat',
  'faceImageId': '717792',
  'countryId': '9'},
 {'id': '12201',
  'rank': '2',
  'name': 'Harry Brook',
  'country': 'England',
  'rating': '857',
  'points': '857',
  'lastUpdatedOn': '2026-03-02',
  'trend': 'Flat',
  'faceImageId': '848570',
  'countryId': '9'},
 {'id': '8497',
  'rank': '3',
  'name': 'Travis Head',
  'country': 'Australia',
  'rating': '853',
  'points': '853',
  'lastUpdatedOn': '2026-03-02',
  'trend': 'Flat',
  'faceImageId': '845768',
  'countryId': '4'},
 {'id': '2250',
  'rank': '4',
  'name': 'Steven Smith',
  'country': 'Australia',
  'rating': '831',
  'points': '831',
  'lastUpdatedOn': '2026-03-02',
  'trend': 'Flat',
  'faceImageId': '619873',
  'countryId': '4'},
 {'id': '6326',
  'rank': '5',
  'name': 'Kane Williamson',
  'country': 'New Zealand',
  'rating': '822',
  'points': '822',
  'lastUpdatedOn': '2026-03-02',
  'trend': 'Flat',
  'faceImageId': '616418',
  'countryId': '13'},
 {'id': '10940',
  'rank': '6',
  'name': 'Kamindu Mendis',
  'country': 'Sri Lanka',
  'rating': '781',
  'points': '781',
  'lastUpdatedOn': '2026-03-02',
  'trend': 'Flat',
  'faceImageId': '847173',
  'countryId': '5'},
 {'id': '8583',
  'rank': '7',
  'name': 'Temba Bavuma',
  'country': 'South Africa',
  'rating': '775',
  'points': '775',
  'lastUpdatedOn': '2026-03-02',
  'trend': 'Flat',
  'faceImageId': '619857',
  'countryId': '11'},
 {'id': '13940',
  'rank': '8',
  'name': 'Yashasvi Jaiswal',
  'country': 'India',
  'rating': '750',
  'points': '750',
  'lastUpdatedOn': '2026-03-02',
  'trend': 'Flat',
  'faceImageId': '591942',
  'countryId': '2'},
 {'id': '9812',
  'rank': '9',
  'name': 'Saud Shakeel',
  'country': 'Pakistan',
  'rating': '734',
  'points': '734',
  'lastUpdatedOn': '2026-03-02',
  'trend': 'Flat',
  'faceImageId': '616442',
  'countryId': '3'},
 {'id': '11808',
  'rank': '10',
  'name': 'Shubman Gill',
  'country': 'India',
  'rating': '730',
  'points': '730',
  'lastUpdatedOn': '2026-03-02',
  'trend': 'Flat',
  'faceImageId': '616515',
  'countryId': '2'},
 {'id': '6245',
  'rank': '11',
  'name': 'Dinesh Chandimal',
  'country': 'Sri Lanka',
  'rating': '717',
  'points': '717',
  'lastUpdatedOn': '2026-03-02',
  'trend': 'Flat',
  'faceImageId': '582334',
  'countryId': '5'},
 {'id': '11177',
  'rank': '12',
  'name': 'Rachin Ravindra',
  'country': 'New Zealand',
  'rating': '716',
  'points': '716',
  'lastUpdatedOn': '2026-03-02',
  'trend': 'Flat',
  'faceImageId': '845519',
  'countryId': '13'},
 {'id': '10713',
  'rank': '13',
  'name': 'Daryl Mitchell',
  'country': 'New Zealand',
  'rating': '711',
  'points': '711',
  'lastUpdatedOn': '2026-03-02',
  'trend': 'Flat',
  'faceImageId': '845511',
  'countryId': '13'},
 {'id': '9200',
  'rank': '14',
  'name': 'Alex Carey',
  'country': 'Australia',
  'rating': '706',
  'points': '706',
  'lastUpdatedOn': '2026-03-02',
  'trend': 'Flat',
  'faceImageId': '619880',
  'countryId': '4'},
 {'id': '10744',
  'rank': '15',
  'name': 'Rishabh Pant',
  'country': 'India',
  'rating': '704',
  'points': '704',
  'lastUpdatedOn': '2026-03-02',
  'trend': 'Flat',
  'faceImageId': '616524',
  'countryId': '2'}]

In [52]:
# Get keys from the first player in the list
keys = batsmen['rank'][0].keys()
print(list(keys))

['id', 'rank', 'name', 'country', 'rating', 'points', 'lastUpdatedOn', 'trend', 'faceImageId', 'countryId']

In [53]:
# Create an empty list to store our filtered data
playerinfo = []

#access the list of players from the rankings/batsmen
for r in batsmen.get('rank',[]):
    details = {
        "id" : r.get("id"),
        "rank" : r.get("rank"),
        "name" : r.get("name"),
        "country" : r.get("country"),
        "rating" : r.get("rating"),
        "points" : r.get("points"),
        "lastUpdatedOn" : r.get("lastUpdatedOn"),
        "trend" : r.get("trend"),
        "countryid" : r.get("countryid"),
        "faceimageid" : r.get("faceimageid")
    }
    playerinfo.append(details)

In [177]:
import pandas as pd

# 1. Create the list (Your existing logic)
playerinfo = []

for r in batsmen.get('rank', []):
    details = {
        "id" : r.get("id"),
        "rank" : r.get("rank"),
        "name" : r.get("name"),
        "country" : r.get("country"),
        "rating" : r.get("rating"),
        "points" : r.get("points"),
        "lastUpdatedOn" : r.get("lastUpdatedOn"), # Ensure the case matches the API key
        "trend" : r.get("trend"),
        "countryid" : r.get("countryid"),
        "faceimageid" : r.get("faceimageid")
    }
    playerinfo.append(details)

# 2. Convert to DataFrame
df_players = pd.DataFrame(playerinfo)

# 3. View the result
print(df_players.head(10))

NameError: name 'batsmen' is not defined

In [55]:
import urllib.parse
from sqlalchemy import create_engine

# 1. Encode the special character in password
password = urllib.parse.quote_plus("deepika@88")

# 2. Use the encoded password in your connection string
# Also, ensure 'username' is replaced with your actual DB user (usually 'postgres')
engine = create_engine(f'postgresql+psycopg2://postgres:{password}@localhost:5432/cricbuzz')

# 3. Test the connection and push the data
df_players.to_sql('top_batsmen', engine, if_exists='replace', index=False)

print("✅ Connection successful and table 'matches_get team' created!")

✅ Connection successful and table 'matches_get team' created!

In [56]:
import pandas as pd

# 1. Create df3 from the 'rank' list inside the 'batsmen' dictionary
df3 = pd.DataFrame(batsmen['rank'])

# 2. Reorder or select only the columns you want to see
# This uses the keys we identified: id, rank, name, country, etc.
df3 = df3[['rank', 'name', 'id', 'country', 'rating', 'points']]

# 3. Display the top 10 as per your Question 3 requirement
df3 = df3.head(10)

print(df3)

  rank              name     id       country rating points
0    1          Joe Root   8019       England    880    880
1    2       Harry Brook  12201       England    857    857
2    3       Travis Head   8497     Australia    853    853
3    4      Steven Smith   2250     Australia    831    831
4    5   Kane Williamson   6326   New Zealand    822    822
5    6    Kamindu Mendis  10940     Sri Lanka    781    781
6    7      Temba Bavuma   8583  South Africa    775    775
7    8  Yashasvi Jaiswal  13940         India    750    750
8    9      Saud Shakeel   9812      Pakistan    734    734
9   10      Shubman Gill  11808         India    730    730

In [57]:
import pandas as pd
import requests
import time

headers = {
    "x-rapidapi-key": "87cb73cb75msh7a5d872ecde1a59p1feac0jsne6c94486f484",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

player_stats = []

for p_id in df3['id']:
    url = f"https://cricbuzz-cricket.p.rapidapi.com/players/get-info?playerId={p_id}"
    response = requests.get(url, headers=headers).json()
        
    stats_data = response.get('battingStats', {}).get('ODI', {})
       
    if not stats_data:
        stats_data = response.get('values', {}).get('ODI', {})

    player_stats.append({
        "id": p_id,
        "total_runs": stats_data.get('runs', 0),
        "batting_average": stats_data.get('avg', 0),
        "centuries": stats_data.get('100s', 0)
    })
    
    time.sleep(0.5)

stats_df = pd.DataFrame(player_stats)

df3 = df3.merge(stats_df, on='id', how='left')

print(df3)

  rank              name     id       country rating points  total_runs  \
0    1          Joe Root   8019       England    880    880           0
1    2       Harry Brook  12201       England    857    857           0
2    3       Travis Head   8497     Australia    853    853           0
3    4      Steven Smith   2250     Australia    831    831           0
4    5   Kane Williamson   6326   New Zealand    822    822           0
5    6    Kamindu Mendis  10940     Sri Lanka    781    781           0
6    7      Temba Bavuma   8583  South Africa    775    775           0
7    8  Yashasvi Jaiswal  13940         India    750    750           0
8    9      Saud Shakeel   9812      Pakistan    734    734           0
9   10      Shubman Gill  11808         India    730    730           0

   batting_average  centuries
0                0          0
1                0          0
2                0          0
3                0          0
4                0          0
5                0          0
6                0          0
7                0          0
8                0          0
9                0          0

# Get team full details from matches

In [58]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/35878/team/9"

headers = {
	"x-rapidapi-key": "87cb73cb75msh7a5d872ecde1a59p1feac0jsne6c94486f484",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

teamdet = response.json()

In [59]:
print(teamdet.keys())

dict_keys(['player'])

In [60]:
teamdet['player']

[{'player': [{'id': '8345',
    'name': 'Alex Lees',
    'captain': False,
    'role': 'Batsman',
    'keeper': False,
    'teamname': 'England',
    'isheader': False,
    'imageId': 0,
    'battingStyle': '',
    'bowlingStyle': '',
    'faceimageid': 239485,
    'countryimageid': 0,
    'playingxichange': '',
    'inmatchchange': '',
    'isoverseas': False},
   {'id': '12770',
    'name': 'Zak Crawley',
    'captain': False,
    'role': 'Batsman',
    'keeper': False,
    'teamname': 'England',
    'isheader': False,
    'imageId': 0,
    'battingStyle': '',
    'bowlingStyle': '',
    'faceimageid': 180932,
    'countryimageid': 0,
    'playingxichange': '',
    'inmatchchange': '',
    'isoverseas': False},
   {'id': '8019',
    'name': 'Joe Root',
    'captain': True,
    'role': 'Batsman',
    'keeper': False,
    'teamname': 'England',
    'isheader': False,
    'imageId': 0,
    'battingStyle': '',
    'bowlingStyle': '',
    'faceimageid': 170942,
    'countryimageid': 0,
    'playingxichange': '',
    'inmatchchange': '',
    'isoverseas': False},
   {'id': '10385',
    'name': 'Daniel Lawrence',
    'captain': False,
    'role': 'Batsman',
    'keeper': False,
    'teamname': 'England',
    'isheader': False,
    'imageId': 0,
    'battingStyle': '',
    'bowlingStyle': '',
    'faceimageid': 158065,
    'countryimageid': 0,
    'playingxichange': '',
    'inmatchchange': '',
    'isoverseas': False},
   {'id': '6557',
    'name': 'Ben Stokes',
    'captain': False,
    'role': 'Batting Allrounder',
    'keeper': False,
    'teamname': 'England',
    'isheader': False,
    'imageId': 0,
    'battingStyle': '',
    'bowlingStyle': '',
    'faceimageid': 170950,
    'countryimageid': 0,
    'playingxichange': '',
    'inmatchchange': '',
    'isoverseas': False},
   {'id': '6507',
    'name': 'Jonny Bairstow',
    'captain': False,
    'role': 'WK-Batsman',
    'keeper': False,
    'teamname': 'England',
    'isheader': False,
    'imageId': 0,
    'battingStyle': '',
    'bowlingStyle': '',
    'faceimageid': 170976,
    'countryimageid': 0,
    'playingxichange': '',
    'inmatchchange': '',
    'isoverseas': False},
   {'id': '7859',
    'name': 'Ben Foakes',
    'captain': False,
    'role': 'WK-Batsman',
    'keeper': True,
    'teamname': 'England',
    'isheader': False,
    'imageId': 0,
    'battingStyle': '',
    'bowlingStyle': '',
    'faceimageid': 239479,
    'countryimageid': 0,
    'playingxichange': '',
    'inmatchchange': '',
    'isoverseas': False},
   {'id': '6670',
    'name': 'Chris Woakes',
    'captain': False,
    'role': 'Bowling Allrounder',
    'keeper': False,
    'teamname': 'England',
    'isheader': False,
    'imageId': 0,
    'battingStyle': '',
    'bowlingStyle': '',
    'faceimageid': 170964,
    'countryimageid': 0,
    'playingxichange': '',
    'inmatchchange': '',
    'isoverseas': False},
   {'id': '9392',
    'name': 'Matthew Fisher',
    'captain': False,
    'role': 'Bowler',
    'keeper': False,
    'teamname': 'England',
    'isheader': False,
    'imageId': 0,
    'battingStyle': '',
    'bowlingStyle': '',
    'faceimageid': 182026,
    'countryimageid': 0,
    'playingxichange': '',
    'inmatchchange': '',
    'isoverseas': False},
   {'id': '8578',
    'name': 'Jack Leach',
    'captain': False,
    'role': 'Bowler',
    'keeper': False,
    'teamname': 'England',
    'isheader': False,
    'imageId': 0,
    'battingStyle': '',
    'bowlingStyle': '',
    'faceimageid': 178391,
    'countryimageid': 0,
    'playingxichange': '',
    'inmatchchange': '',
    'isoverseas': False},
   {'id': '10394',
    'name': 'Saqib Mahmood',
    'captain': False,
    'role': 'Bowler',
    'keeper': False,
    'teamname': 'England',
    'isheader': False,
    'imageId': 0,
    'battingStyle': '',
    'bowlingStyle': '',
    'faceimageid': 156545,
    'countryimageid': 0,
    'playingxichange': '',
    'inmatchchange': '',
    'isoverseas': False}],
  'category': 'playing XI'},
 {'player': [{'id': '11691',
    'name': 'Ollie Pope',
    'captain': False,
    'role': 'WK-Batsman',
    'keeper': False,
    'teamname': 'England',
    'isheader': False,
    'imageId': 0,
    'battingStyle': '',
    'bowlingStyle': '',
    'faceimageid': 180934,
    'countryimageid': 0,
    'playingxichange': '',
    'inmatchchange': '',
    'isoverseas': False},
   {'id': '9531',
    'name': 'Ollie Robinson',
    'captain': False,
    'role': 'Bowler',
    'keeper': False,
    'teamname': 'England',
    'isheader': False,
    'imageId': 0,
    'battingStyle': '',
    'bowlingStyle': '',
    'faceimageid': 240049,
    'countryimageid': 0,
    'playingxichange': '',
    'inmatchchange': '',
    'isoverseas': False},
   {'id': '10395',
    'name': 'Matthew Parkinson',
    'captain': False,
    'role': 'Bowler',
    'keeper': False,
    'teamname': 'England',
    'isheader': False,
    'imageId': 0,
    'battingStyle': '',
    'bowlingStyle': '',
    'faceimageid': 180930,
    'countryimageid': 0,
    'playingxichange': '',
    'inmatchchange': '',
    'isoverseas': False},
   {'id': '8511',
    'name': 'Craig Overton',
    'captain': False,
    'role': 'Bowling Allrounder',
    'keeper': False,
    'teamname': 'England',
    'isheader': False,
    'imageId': 0,
    'battingStyle': '',
    'bowlingStyle': '',
    'faceimageid': 156179,
    'countryimageid': 0,
    'playingxichange': '',
    'inmatchchange': '',
    'isoverseas': False}],
  'category': 'bench'}]

In [61]:
# Get keys from the first player in the list
keys = teamdet['player'][0].keys()
print(list(keys))

['player', 'category']

In [62]:
# Convert the nested list into a clean DataFrame
players_list = []
for item in teamdet['player']:
       for p in item['player']:
        players_list.append(p)

df_details = pd.DataFrame(players_list)
print(df_details)

       id               name  captain                role  keeper teamname  \
0    8345          Alex Lees    False             Batsman   False  England
1   12770        Zak Crawley    False             Batsman   False  England
2    8019           Joe Root     True             Batsman   False  England
3   10385    Daniel Lawrence    False             Batsman   False  England
4    6557         Ben Stokes    False  Batting Allrounder   False  England
5    6507     Jonny Bairstow    False          WK-Batsman   False  England
6    7859         Ben Foakes    False          WK-Batsman    True  England
7    6670       Chris Woakes    False  Bowling Allrounder   False  England
8    9392     Matthew Fisher    False              Bowler   False  England
9    8578         Jack Leach    False              Bowler   False  England
10  10394      Saqib Mahmood    False              Bowler   False  England
11  11691         Ollie Pope    False          WK-Batsman   False  England
12   9531     Ollie Robinson    False              Bowler   False  England
13  10395  Matthew Parkinson    False              Bowler   False  England
14   8511      Craig Overton    False  Bowling Allrounder   False  England

    isheader  imageId battingStyle bowlingStyle  faceimageid  countryimageid  \
0      False        0                                 239485               0
1      False        0                                 180932               0
2      False        0                                 170942               0
3      False        0                                 158065               0
4      False        0                                 170950               0
5      False        0                                 170976               0
6      False        0                                 239479               0
7      False        0                                 170964               0
8      False        0                                 182026               0
9      False        0                                 178391               0
10     False        0                                 156545               0
11     False        0                                 180934               0
12     False        0                                 240049               0
13     False        0                                 180930               0
14     False        0                                 156179               0

   playingxichange inmatchchange  isoverseas
0                                      False
1                                      False
2                                      False
3                                      False
4                                      False
5                                      False
6                                      False
7                                      False
8                                      False
9                                      False
10                                     False
11                                     False
12                                     False
13                                     False
14                                     False

In [63]:
import urllib.parse
from sqlalchemy import create_engine

# 1. Encode the special character in password
password = urllib.parse.quote_plus("deepika@88")

# 2. Use the encoded password in your connection string
# Also, ensure 'username' is replaced with your actual DB user (usually 'postgres')
engine = create_engine(f'postgresql+psycopg2://postgres:{password}@localhost:5432/cricbuzz')

# 3. Test the connection and push the data
df_details.to_sql('matches_get_team', engine, if_exists='replace', index=False)

print("✅ Connection successful and table 'matches_get team' created!")

✅ Connection successful and table 'matches_get team' created!

# Match/get-info api

In [ ]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/148720"

headers = {
	"x-rapidapi-key": "87cb73cb75msh7a5d872ecde1a59p1feac0jsne6c94486f484",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

match_get_info = response.json()

In [65]:
match_get_info

{'matchid': 41881,
 'seriesid': 3926,
 'seriesname': 'ACC U19 Asia Cup 2021',
 'matchdesc': 'Group A',
 'matchformat': 'ODI',
 'startdate': 1640410200000,
 'enddate': 1640439000000,
 'state': 'Complete',
 'status': 'Afghanistan U19 won by 140 runs',
 'team1': {'teamid': 223,
  'teamname': 'Afghanistan U19',
  'teamsname': 'AFGU19',
  'isfullmember': False,
  'isassociated': False,
  'isleagueteam': False,
  'iswomenteam': False,
  'isheader': False,
  'isactive': False,
  'teampriority': '',
  'isvideopresent': False,
  'imageid': 0,
  'countryname': '',
  'belongsto': '',
  'teamcolor': ''},
 'team2': {'teamid': 283,
  'teamname': 'United Arab Emirates U19',
  'teamsname': 'UAEU19',
  'isfullmember': False,
  'isassociated': False,
  'isleagueteam': False,
  'iswomenteam': False,
  'isheader': False,
  'isactive': False,
  'teampriority': '',
  'isvideopresent': False,
  'imageid': 0,
  'countryname': '',
  'belongsto': '',
  'teamcolor': ''},
 'umpire1': {'id': 7540, 'name': 'Naresh Shah', 'country': 'KEN'},
 'umpire2': {'id': 7244, 'name': 'Sarika Prasad', 'country': 'SIN'},
 'umpire3': {'id': 8871, 'name': 'KN Anantha Padmanabhan', 'country': 'IND'},
 'referee': {'id': 9070, 'name': 'Akhtar Ahmad', 'country': 'BAN'},
 'venueinfo': {'id': 289,
  'ground': 'ICC Academy Ground',
  'city': 'Dubai',
  'country': 'United Arab Emirates',
  'timezone': '',
  'established': 2009,
  'capacity': '',
  'knownas': '',
  'ends': 'City End, Reem Raam End',
  'hometeam': 'United Arab Emirates',
  'floodlights': False,
  'curator': '',
  'profile': '',
  'imageurl': '',
  'groundlength': 0.0,
  'groundwidth': 0.0,
  'othersports': '',
  'imageid': 0,
  'latitude': '',
  'longitude': ''},
 'currbatteamid': 0,
 'ismatchnotcovered': False,
 'appindex': {'seotitle': 'Cricket match facts AFGU19 vs UAEU19 Group A,ACC U19 Asia Cup 2021 | Cricbuzz.com',
  'weburl': 'http://www.cricbuzz.com/cricket-match-facts/41881/afgu19-vs-uaeu19-group-a-acc-u19-asia-cup-2021'},
 'istournament': True,
 'tossstatus': '',
 'seriesstartdt': 1640410200000,
 'seriesenddt': 1640439000000,
 'istimeannounced': False,
 'statetitle': '',
 'replacematchid': 0,
 'livestreamenabled': False,
 'isfantasyenabled': False,
 'broadcastinfo': [],
 'daynight': False,
 'matchtype': 'domestic',
 'seriestype': '',
 'shortstatus': 'AFGU19 won',
 'boundarytrackervalues': {'boundarytrackervalue': []},
 'matchimageid': 379130,
 'islivestreamenabled': False,
 'isfantasyhandbookenabled': False,
 'isforecastenabled': False,
 'ispollenabled': False}

In [66]:
match_get_info['team1']

{'teamid': 223,
 'teamname': 'Afghanistan U19',
 'teamsname': 'AFGU19',
 'isfullmember': False,
 'isassociated': False,
 'isleagueteam': False,
 'iswomenteam': False,
 'isheader': False,
 'isactive': False,
 'teampriority': '',
 'isvideopresent': False,
 'imageid': 0,
 'countryname': '',
 'belongsto': '',
 'teamcolor': ''}

In [67]:
match_get_info['team2']

{'teamid': 283,
 'teamname': 'United Arab Emirates U19',
 'teamsname': 'UAEU19',
 'isfullmember': False,
 'isassociated': False,
 'isleagueteam': False,
 'iswomenteam': False,
 'isheader': False,
 'isactive': False,
 'teampriority': '',
 'isvideopresent': False,
 'imageid': 0,
 'countryname': '',
 'belongsto': '',
 'teamcolor': ''}

In [68]:
match_get_info['umpire3']

{'id': 8871, 'name': 'KN Anantha Padmanabhan', 'country': 'IND'}

In [69]:
match_get_info['referee']

{'id': 9070, 'name': 'Akhtar Ahmad', 'country': 'BAN'}

In [ ]:
import pandas as pd
# Convert the nested list into a clean DataFrame
getmatchinfo = []
det =  {
    "matchid": match_get_info.get('matchid'),
    'seriesid': match_get_info.get('seriesid'),
    'seriesname' : match_get_info.get('seriesname'),
    'matchdesc' : match_get_info.get('matchdesc'),
    'matchformat' : match_get_info.get('matchformat'),
    'state' : match_get_info.get('state'),
    'status' : match_get_info.get('status'),

    #getting team1 details
    'teamid': match_get_info.get('team1',{}).get('teamid'),
    'teamname' : match_get_info.get('team1',{}).get('teamname'),
    'teamsname' : match_get_info.get('team1',{}).get('teamsname'),

    #getting team2 details
     'teamid': match_get_info.get('team2',{}).get('teamid'),
    'teamname' : match_get_info.get('team2',{}).get('teamname'),
    'teamsname' : match_get_info.get('team2',{}).get('teamsname'),

    # Flattening Umpires
    "umpire1_id": match_get_info.get('umpire1', {}).get('id'),
    "umpire1_country": match_get_info.get('umpire1', {}).get('country'),
    "umpire1_name": match_get_info.get('umpire1', {}).get('name'),

    "umpire2_id": match_get_info.get('umpire2', {}).get('id'),
    "umpire2_country": match_get_info.get('umpire2', {}).get('country'),
    "umpire2_name": match_get_info.get('umpire2', {}).get('name'),

    "umpire3_id": match_get_info.get('umpire3', {}).get('id'),
    "umpire3_country": match_get_info.get('umpire3', {}).get('country'),
    "umpire3_name": match_get_info.get('umpire3', {}).get('name'),

    #Refree details
    "referee_id": match_get_info.get('referee', {}).get('id'),
    "referee_name" : match_get_info.get('referee',{}).get('name'),
    "referee_country": match_get_info.get('referee', {}).get('country'),

    # Flattening Venue
    "venue_id": match_get_info.get('venueinfo', {}).get('id'),
    "venue_ground": match_get_info.get('venueinfo', {}).get('ground'),
    "venue_city": match_get_info.get('venueinfo', {}).get('city'),
    "venue_country": match_get_info.get('venueinfo', {}).get('country'),
    "venue_established": match_get_info.get('venueinfo', {}).get('established'),
    "matchimageid": match_get_info.get('matchimageid'),
    'istournament' : match_get_info.get('istournament'),
    'daynight' : match_get_info.get('daynight'),
    'matchtype' : match_get_info.get('matchtype'),
    'shortstatus' : match_get_info.get('shortstatus'),
}

getmatchinfo.append(det)
# 2. Convert to DataFrame
df_getmatch_info = pd.DataFrame(getmatchinfo)

# 3. Fix the NameError: use 'match_get_info' instead of 'getmatch_info'
df_getmatch_info['startdate'] = pd.to_datetime(match_get_info.get('startdate'), unit='ms')
df_getmatch_info['enddate'] = pd.to_datetime(match_get_info.get('enddate'), unit='ms')

print(df_getmatch_info)

   matchid  seriesid             seriesname matchdesc matchformat     state  \
0    41881      3926  ACC U19 Asia Cup 2021   Group A         ODI  Complete

                            status  teamid                  teamname  \
0  Afghanistan U19 won by 140 runs     283  United Arab Emirates U19

  teamsname  ...  venue_city         venue_country venue_established  \
0    UAEU19  ...       Dubai  United Arab Emirates              2009

   matchimageid istournament daynight  matchtype shortstatus  \
0        379130         True    False   domestic  AFGU19 won

            startdate             enddate
0 2021-12-25 05:30:00 2021-12-25 13:30:00

[1 rows x 34 columns]

In [71]:
import urllib.parse
from sqlalchemy import create_engine

# 1. Encode the special character in password
password = urllib.parse.quote_plus("deepika@88")

# 2. Use the encoded password in your connection string
# Also, ensure 'username' is replaced with your actual DB user (usually 'postgres')
engine = create_engine(f'postgresql+psycopg2://postgres:{password}@localhost:5432/cricbuzz')

# 3. Test the connection and push the data
df_getmatch_info.to_sql('matches_get_info', engine, if_exists='replace', index=False)

print("✅ Connection successful and table 'matches_get info' created!")

✅ Connection successful and table 'matches_get info' created!

# Match/List api

In [5]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/matches/v1/recent"

headers = {
	"x-rapidapi-key": "edcc615a98msh9b529038adf520fp13b7cfjsnba97517d5849",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

match_list1 = response.json()

In [6]:
print(match_list1.keys())

dict_keys(['message'])

In [7]:
match_list1

{'message': 'You have exceeded the MONTHLY quota for Requests on your current plan, BASIC. Upgrade your plan at https://rapidapi.com/cricketapilive/api/cricbuzz-cricket'}

In [8]:
type_match=match_list1['typeMatches']
print(type_match[0])

KeyError: 'typeMatches'

In [ ]:
series_matches = type_match[0]['seriesMatches']
print(series_matches[0])

{'seriesAdWrapper': {'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matches': [{'matchInfo': {'matchId': 139461, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '52nd Match, Super 8 Group 1 (X1 v X3)', 'matchFormat': 'T20', 'startDate': '1772371800000', 'endDate': '1772384400000', 'state': 'Complete', 'status': 'India won by 5 wkts', 'team1': {'teamId': 10, 'teamName': 'West Indies', 'teamSName': 'WI', 'imageId': 776191}, 'team2': {'teamId': 2, 'teamName': 'India', 'teamSName': 'IND', 'imageId': 776162}, 'venueInfo': {'id': 31, 'ground': 'Eden Gardens', 'city': 'Kolkata', 'timezone': '+05:30', 'latitude': '22.564527', 'longitude': '88.343247'}, 'currBatTeamId': 2, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'IND Won', 'isFantasyEnabled': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 195, 'wickets': 4, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 199, 'wickets': 5, 'overs': 19.2}}}}, {'matchInfo': {'matchId': 139450, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '51st Match, Super 8 Group 1 (X2 v X4)', 'matchFormat': 'T20', 'startDate': '1772357400000', 'endDate': '1772370000000', 'state': 'Complete', 'status': 'South Africa won by 5 wkts', 'team1': {'teamId': 12, 'teamName': 'Zimbabwe', 'teamSName': 'ZIM', 'imageId': 776198}, 'team2': {'teamId': 11, 'teamName': 'South Africa', 'teamSName': 'RSA', 'imageId': 776287}, 'venueInfo': {'id': 51, 'ground': 'Arun Jaitley Stadium', 'city': 'Delhi', 'timezone': '+05:30', 'latitude': '28.637891', 'longitude': '77.243073'}, 'currBatTeamId': 11, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'RSA Won', 'isFantasyEnabled': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 153, 'wickets': 7, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 154, 'wickets': 5, 'overs': 17.5}}}}, {'matchInfo': {'matchId': 139448, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '50th Match, Super 8 Group 2 (Y3 v Y4)', 'matchFormat': 'T20', 'startDate': '1772285400000', 'endDate': '1772298000000', 'state': 'Complete', 'status': 'Pakistan won by 5 runs', 'team1': {'teamId': 3, 'teamName': 'Pakistan', 'teamSName': 'PAK', 'imageId': 776308}, 'team2': {'teamId': 5, 'teamName': 'Sri Lanka', 'teamSName': 'SL', 'imageId': 776254}, 'venueInfo': {'id': 254, 'ground': 'Pallekele International Cricket Stadium', 'city': 'Pallekele', 'timezone': '+05:30', 'latitude': '7.280691', 'longitude': '80.722493'}, 'currBatTeamId': 3, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'PAK Won', 'isFantasyEnabled': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 212, 'wickets': 8, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 207, 'wickets': 6, 'overs': 19.6}}}}, {'matchInfo': {'matchId': 139437, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '49th Match, Super 8 Group 2 (Y1 v Y2)', 'matchFormat': 'T20', 'startDate': '1772199000000', 'endDate': '1772211600000', 'state': 'Complete', 'status': 'England won by 4 wkts', 'team1': {'teamId': 13, 'teamName': 'New Zealand', 'teamSName': 'NZ', 'imageId': 776333}, 'team2': {'teamId': 9, 'teamName': 'England', 'teamSName': 'ENG', 'imageId': 776237}, 'venueInfo': {'id': 15, 'ground': 'R.Premadasa Stadium', 'city': 'Colombo', 'timezone': '+05:30', 'latitude': '6.939966', 'longitude': '79.872222'}, 'currBatTeamId': 9, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'ENG Won', 'isFantasyEnabled': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 159, 'wickets': 7, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 161, 'wickets': 6, 'overs': 19.3}}}}, {'matchInfo': {'matchId': 139426, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '48th Match, Super 8 Group 1 (X1 v X2)', 'matchFormat': 'T20', 'startDate': '1772112600000', 'endDate': '1772125200000', 'state': 'Complete', 'status': 'India won by 72 runs', 'team1': {'teamId': 2, 'teamName': 'India', 'teamSName': 'IND', 'imageId': 776162}, 'team2': {'teamId': 12, 'teamName': 'Zimbabwe', 'teamSName': 'ZIM', 'imageId': 776198}, 'venueInfo': {'id': 11, 'ground': 'MA Chidambaram Stadium', 'city': 'Chennai', 'timezone': '+05:30', 'latitude': '13.06282', 'longitude': '80.279274'}, 'currBatTeamId': 2, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'IND Won', 'isFantasyEnabled': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 256, 'wickets': 4, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 184, 'wickets': 6, 'overs': 19.6}}}}, {'matchInfo': {'matchId': 139415, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '47th Match, Super 8 Group 1 (X3 v X4)', 'matchFormat': 'T20', 'startDate': '1772098200000', 'endDate': '1772110800000', 'state': 'Complete', 'status': 'South Africa won by 9 wkts', 'team1': {'teamId': 10, 'teamName': 'West Indies', 'teamSName': 'WI', 'imageId': 776191}, 'team2': {'teamId': 11, 'teamName': 'South Africa', 'teamSName': 'RSA', 'imageId': 776287}, 'venueInfo': {'id': 50, 'ground': 'Narendra Modi Stadium', 'city': 'Ahmedabad', 'timezone': '+05:30', 'latitude': '23.091785', 'longitude': '72.597465'}, 'currBatTeamId': 11, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'RSA Won', 'isFantasyEnabled': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 176, 'wickets': 8, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 177, 'wickets': 1, 'overs': 16.1}}}}, {'matchInfo': {'matchId': 139404, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '46th Match, Super 8 Group 2 (Y2 v Y4)', 'matchFormat': 'T20', 'startDate': '1772026200000', 'endDate': '1772038800000', 'state': 'Complete', 'status': 'New Zealand won by 61 runs', 'team1': {'teamId': 13, 'teamName': 'New Zealand', 'teamSName': 'NZ', 'imageId': 776333}, 'team2': {'teamId': 5, 'teamName': 'Sri Lanka', 'teamSName': 'SL', 'imageId': 776254}, 'venueInfo': {'id': 15, 'ground': 'R.Premadasa Stadium', 'city': 'Colombo', 'timezone': '+05:30', 'latitude': '6.939966', 'longitude': '79.872222'}, 'currBatTeamId': 13, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'NZ Won', 'isFantasyEnabled': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 168, 'wickets': 7, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 107, 'wickets': 8, 'overs': 19.6}}}}, {'matchInfo': {'matchId': 139393, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '45th Match, Super 8 Group 2 (Y1 v Y3)', 'matchFormat': 'T20', 'startDate': '1771939800000', 'endDate': '1771952400000', 'state': 'Complete', 'status': 'England won by 2 wkts', 'team1': {'teamId': 3, 'teamName': 'Pakistan', 'teamSName': 'PAK', 'imageId': 776308}, 'team2': {'teamId': 9, 'teamName': 'England', 'teamSName': 'ENG', 'imageId': 776237}, 'venueInfo': {'id': 254, 'ground': 'Pallekele International Cricket Stadium', 'city': 'Pallekele', 'timezone': '+05:30', 'latitude': '7.280691', 'longitude': '80.722493'}, 'currBatTeamId': 9, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'ENG Won', 'isFantasyEnabled': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 164, 'wickets': 9, 'overs': 19.6}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 166, 'wickets': 8, 'overs': 19.1}}}}]}}

In [ ]:
series_wrapper = series_matches[0]['seriesAdWrapper']
print(series_wrapper.keys())

dict_keys(['seriesId', 'seriesName', 'matches'])

In [ ]:
# Access matches of series wrapper
m_list = series_wrapper['matches']
f_match = m_list[0]
print(f_match['matchInfo'])

{'matchId': 139461, 'seriesId': 11253, 'seriesName': "ICC Men's T20 World Cup 2026", 'matchDesc': '52nd Match, Super 8 Group 1 (X1 v X3)', 'matchFormat': 'T20', 'startDate': '1772371800000', 'endDate': '1772384400000', 'state': 'Complete', 'status': 'India won by 5 wkts', 'team1': {'teamId': 10, 'teamName': 'West Indies', 'teamSName': 'WI', 'imageId': 776191}, 'team2': {'teamId': 2, 'teamName': 'India', 'teamSName': 'IND', 'imageId': 776162}, 'venueInfo': {'id': 31, 'ground': 'Eden Gardens', 'city': 'Kolkata', 'timezone': '+05:30', 'latitude': '22.564527', 'longitude': '88.343247'}, 'currBatTeamId': 2, 'seriesStartDt': '1770422400000', 'seriesEndDt': '1773100800000', 'isTimeAnnounced': True, 'stateTitle': 'IND Won', 'isFantasyEnabled': True}

In [ ]:
venue_ids = [m.get('matchInfo', {}).get('venueInfo', {}).get('id') for tm in match_list1.get('typeMatches', []) for sm in tm.get('seriesMatches', []) for m in sm.get('seriesAdWrapper', {}).get('matches', []) if m.get('matchInfo', {}).get('venueInfo', {}).get('id')]

print(venue_ids)

[31, 51, 254, 15, 11, 50, 15, 254, 474, 474, 474, 474, 474, 474, 474, 474, 454, 454, 454, 454, 329, 206, 75, 88, 73, 148, 72, 1193, 135, 367, 72, 148, 1193, 371, 418, 44, 94, 94, 94, 39, 39, 300, 101, 101, 101, 74, 75, 100, 100, 100]

In [ ]:
# Extract seriesId from the seriesAdWrapper level
m_series_ids = [
    sm.get('seriesAdWrapper', {}).get('seriesId') 
    for tm in match_list1.get('typeMatches', []) 
    for sm in tm.get('seriesMatches', []) 
    if sm.get('seriesAdWrapper', {}).get('seriesId')
]

print(series_ids)

[11253, 11542, 11581, 10317, 11553, 11559, 10730, 11518, 9611, 11487, 10146, 10245]

In [ ]:
import pandas as pd

all_matches = []

# 1. Access the list of type matches
for type_match in match_list1.get('typeMatches', []):
    m_type = type_match.get('matchType')
    
    for series in type_match.get('seriesMatches', []):
        series_wrapper = series.get('seriesAdWrapper', {})
        
        # Pull Series ID from the wrapper level
        s_id = series_wrapper.get('seriesId')
        
        if series_wrapper and 'matches' in series_wrapper:
            for match in series_wrapper['matches']:
                info = match.get('matchInfo', {})
                score = match.get('matchScore', {})
                venue = info.get('venueInfo', {}) # Nested venue info
                
                match_data = {
                    'match_id': info.get('matchId'),
                    'series_id': s_id,
                    'series_name': info.get('seriesName'),
                    'type': m_type,
                    'match_desc': info.get('matchDesc'),
                    'status': info.get('status'),
                    'team1': info.get('team1', {}).get('teamName'),
                    'team2': info.get('team2', {}).get('teamName'),
                    'venue': venue.get('ground'),
                    'city': venue.get('city'),
                    'country': venue.get('country'),
                    'start_ts': info.get('startDate'), 
                    'end_ts': info.get('endDate'),
                    't1_runs': score.get('team1Score', {}).get('inngs1', {}).get('runs'),
                    't2_runs': score.get('team2Score', {}).get('inngs1', {}).get('runs'),
                }
                all_matches.append(match_data)

# 2. Create the DataFrame
df_all = pd.DataFrame(all_matches)

# 3. Convert timestamps and clean up
df_all['startdate'] = pd.to_datetime(pd.to_numeric(df_all['start_ts'], errors='coerce'), unit='ms')
df_all['enddate'] = pd.to_datetime(pd.to_numeric(df_all['end_ts'], errors='coerce'), unit='ms')
df_all = df_all.drop(columns=['start_ts', 'end_ts'])

# 4. View the final enriched DataFrame
print(df_all[['match_id', 'series_id', 'series_name', 'city', 'country']].head())

   match_id  series_id                   series_name       city country
0    139461      11253  ICC Men's T20 World Cup 2026    Kolkata    None
1    139450      11253  ICC Men's T20 World Cup 2026      Delhi    None
2    139448      11253  ICC Men's T20 World Cup 2026  Pallekele    None
3    139437      11253  ICC Men's T20 World Cup 2026    Colombo    None
4    139426      11253  ICC Men's T20 World Cup 2026    Chennai    None

In [ ]:
import pandas as pd

# 1. Extract data into list
all_matches = []

for type_match in match_list1.get('typeMatches', []):
    m_type = type_match.get('matchType')
    for series in type_match.get('seriesMatches', []):
        series_wrapper = series.get('seriesAdWrapper')
        if series_wrapper and 'matches' in series_wrapper:
            for match in series_wrapper['matches']:
                info = match.get('matchInfo', {})
                score = match.get('matchScore', {})
                
                match_data = {
                    'match_id': info.get('matchId'),
                    'type': m_type,
                    'series_name': info.get('seriesName'),
                    'match_desc': info.get('matchDesc'),
                    'status': info.get('status'),
                    'team1': info.get('team1', {}).get('teamName'),
                    'team2': info.get('team2', {}).get('teamName'),
                    'venue': info.get('venueInfo', {}).get('ground'),
                    'city': info.get('venueInfo', {}).get('city'),
                    # Extract raw timestamps here
                    'start_ts': info.get('startDate'), 
                    'end_ts': info.get('endDate'),
                    't1_runs': score.get('team1Score', {}).get('inngs1', {}).get('runs'),
                    't2_runs': score.get('team2Score', {}).get('inngs1', {}).get('runs'),
                    
                }
                all_matches.append(match_data)

# 2. Create the DataFrame
df_all = pd.DataFrame(all_matches)

# 3. Convert timestamps to Readable Dates
# Note: Use errors='coerce' just in case a timestamp is missing
df_all['startdate'] = pd.to_datetime(pd.to_numeric(df_all['start_ts']), unit='ms')
df_all['enddate'] = pd.to_datetime(pd.to_numeric(df_all['end_ts']), unit='ms')

# 4. Optional: Clean up by dropping the raw timestamp columns
df_all = df_all.drop(columns=['start_ts', 'end_ts'])

print(df_all[['match_id', 'team1', 'team2', 'startdate']].head())

   match_id        team1         team2           startdate
0    139461  West Indies         India 2026-03-01 13:30:00
1    139450     Zimbabwe  South Africa 2026-03-01 09:30:00
2    139448     Pakistan     Sri Lanka 2026-02-28 13:30:00
3    139437  New Zealand       England 2026-02-27 13:30:00
4    139426        India      Zimbabwe 2026-02-26 13:30:00

In [ ]:
df_all

,match_id,type,series_name,match_desc,status,team1,team2,venue,city,t1_runs,t2_runs,startdate,enddate
0,139461,International,ICC Men's T20 World Cup 2026,"52nd Match, Super 8 Group 1 (X1 v X3)",India won by 5 wkts,West Indies,India,Eden Gardens,Kolkata,195.0,199.0,2026-03-01 13:30:00,2026-03-01 17:00:00
1,139450,International,ICC Men's T20 World Cup 2026,"51st Match, Super 8 Group 1 (X2 v X4)",South Africa won by 5 wkts,Zimbabwe,South Africa,Arun Jaitley Stadium,Delhi,153.0,154.0,2026-03-01 09:30:00,2026-03-01 13:00:00
2,139448,International,ICC Men's T20 World Cup 2026,"50th Match, Super 8 Group 2 (Y3 v Y4)",Pakistan won by 5 runs,Pakistan,Sri Lanka,Pallekele International Cricket Stadium,Pallekele,212.0,207.0,2026-02-28 13:30:00,2026-02-28 17:00:00
3,139437,International,ICC Men's T20 World Cup 2026,"49th Match, Super 8 Group 2 (Y1 v Y2)",England won by 4 wkts,New Zealand,England,R.Premadasa Stadium,Colombo,159.0,161.0,2026-02-27 13:30:00,2026-02-27 17:00:00
4,139426,International,ICC Men's T20 World Cup 2026,"48th Match, Super 8 Group 1 (X1 v X2)",India won by 72 runs,India,Zimbabwe,MA Chidambaram Stadium,Chennai,256.0,184.0,2026-02-26 13:30:00,2026-02-26 17:00:00
5,139415,International,ICC Men's T20 World Cup 2026,"47th Match, Super 8 Group 1 (X3 v X4)",South Africa won by 9 wkts,West Indies,South Africa,Narendra Modi Stadium,Ahmedabad,176.0,177.0,2026-02-26 09:30:00,2026-02-26 13:00:00
6,139404,International,ICC Men's T20 World Cup 2026,"46th Match, Super 8 Group 2 (Y2 v Y4)",New Zealand won by 61 runs,New Zealand,Sri Lanka,R.Premadasa Stadium,Colombo,168.0,107.0,2026-02-25 13:30:00,2026-02-25 17:00:00
7,139393,International,ICC Men's T20 World Cup 2026,"45th Match, Super 8 Group 2 (Y1 v Y3)",England won by 2 wkts,Pakistan,England,Pallekele International Cricket Stadium,Pallekele,164.0,166.0,2026-02-24 13:30:00,2026-02-24 17:00:00
8,147016,International,Quadrangular T20I Series in Thailand 2026,Final,Match tied (Bahrain won the super over),Japan,Bahrain,Terdthai Cricket Ground,Bangkok,108.0,108.0,2026-02-28 06:30:00,2026-02-28 10:00:00
9,147005,International,Quadrangular T20I Series in Thailand 2026,3rd place play-off,Bhutan won by 7 runs,Bhutan,Thailand,Terdthai Cricket Ground,Bangkok,86.0,79.0,2026-02-28 02:00:00,2026-02-28 05:30:00
10,146994,International,Quadrangular T20I Series in Thailand 2026,6th Match,Bahrain won by 12 runs,Bahrain,Thailand,Terdthai Cricket Ground,Bangkok,126.0,114.0,2026-02-27 06:30:00,2026-02-27 10:00:00
11,146983,International,Quadrangular T20I Series in Thailand 2026,5th Match,Japan won by 77 runs,Japan,Bhutan,Terdthai Cricket Ground,Bangkok,170.0,93.0,2026-02-27 02:00:00,2026-02-27 05:30:00
12,146972,International,Quadrangular T20I Series in Thailand 2026,4th Match,Japan won by 8 wkts,Bahrain,Japan,Terdthai Cricket Ground,Bangkok,87.0,88.0,2026-02-26 06:30:00,2026-02-26 10:00:00
13,146961,International,Quadrangular T20I Series in Thailand 2026,3rd Match,Thailand won by 60 runs,Thailand,Bhutan,Terdthai Cricket Ground,Bangkok,140.0,80.0,2026-02-26 02:00:00,2026-02-26 05:30:00
14,146950,International,Quadrangular T20I Series in Thailand 2026,2nd Match,Bahrain won by 4 wkts,Bhutan,Bahrain,Terdthai Cricket Ground,Bangkok,91.0,95.0,2026-02-25 06:30:00,2026-02-25 10:00:00
15,146939,International,Quadrangular T20I Series in Thailand 2026,1st Match,Japan won by 37 runs,Japan,Thailand,Terdthai Cricket Ground,Bangkok,157.0,120.0,2026-02-25 02:00:00,2026-02-25 05:30:00
16,147733,International,"Kuwait tour of Hong Kong, China, 2026",4th T20I,Kuwait won by 3 wkts,"Hong Kong, China",Kuwait,Mission Road Ground,Mong Kok,125.0,127.0,2026-03-01 05:15:00,2026-03-01 08:45:00
17,147722,International,"Kuwait tour of Hong Kong, China, 2026",3rd T20I,Match abandoned without a ball bowled (No toss),"Hong Kong, China",Kuwait,Mission Road Ground,Mong Kok,NaN,NaN,2026-02-28 05:15:00,2026-02-28 08:45:00
18,147711,International,"Kuwait tour of Hong Kong, China, 2026",2nd T20I,"Hong Kong, China won by 24 runs","Hong Kong, China",Kuwait,Mission Road Ground,Mong Kok,171.0,147.0,2026-02-26 05:30:00,2026-02-26 09:00:00
19,147700,International,"Kuwait tour of Hong Kong, China, 2026",1st T20I,"Hong Kong, China won by 3 wkts",Kuwait,"Hong Kong, China",Mission Road Ground,Mong Kok,182.0,186.0,2026-02-25 05:30:00,2026-02-25 09:00:00
20,125085,Domestic,Ranji Trophy Elite 2025-26,Final,Match drawn,Jammu and Kashmir,Karnataka,KSCA Hubli Cricket Ground,Hubli,584.0,293.0,2026-02-24 04:00:00,2026-02-28 11:00:00
21,147046,Domestic,CSA Provincial One-Day Challenge Division One ...,3rd Match,North West - Eastvaal Renault Dragons won by...,North West - Eastvaal Renault Dragons,KwaZulu-Natal Inland - Tuskers,City Oval,Pietermaritzburg,291.0,219.0,2026-03-01 08:00:00,2026-03-01 16:00:00
22,147071,Domestic,CSA Provincial One-Day Challenge Division One ...,4th Match,Titans won by 13 runs (DLS method) - Revised d...,Titans,Boland,SuperSport Park,Centurion,235.0,213.0,2026-03-01 08:00:00,2026-03-01 16:00:00
23,147035,Domestic,CSA Provincial One-Day Challenge Division One ...,2nd Match,Lions won by 15 runs (DLS Method) - Revised du...,Western Province,Lions,The Wanderers Stadium,Johannesburg,259.0,245.0,2026-02-28 11:00:00,2026-02-28 19:00:00
24,147024,Domestic,CSA Provincial One-Day Challenge Division One ...,1st Match,Warriors won by 6 wkts,Dolphins,Warriors,St George's Park,Gqeberha,279.0,283.0,2026-02-27 11:00:00,2026-02-27 19:00:00
25,147249,Domestic,CSA Provincial One-Day Challenge Division Two ...,11th Match,Limpopo won by 13 runs,Limpopo,Northern Cape,Diamond Oval,Kimberley,303.0,290.0,2026-03-01 08:00:00,2026-03-01 16:00:00
26,147238,Domestic,CSA Provincial One-Day Challenge Division Two ...,10th Match,Knights won by 1 wkt,South Africa Emerging Players,Knights,Mangaung Oval,Bloemfontein,148.0,152.0,2026-03-01 08:00:00,2026-03-01 16:00:00
27,147271,Domestic,CSA Provincial One-Day Challenge Division Two ...,12th Match,Border won by 98 runs (DLS method) - Revised d...,Border,Mpumalanga Rhinos,"Uplands College, White River",Mpumalanga,273.0,145.0,2026-03-01 07:30:00,2026-03-01 15:30:00
28,147227,Domestic,CSA Provincial One-Day Challenge Division Two ...,9th Match,Eastern Storm won by 4 runs (DLS method) - DLS...,Eastern Storm,South Western Districts,Willowmoore Park,Benoni,298.0,154.0,2026-02-28 08:00:00,2026-02-28 16:00:00
29,147216,Domestic,CSA Provincial One-Day Challenge Division Two ...,8th Match,Limpopo won by 7 wkts,South Africa Emerging Players,Limpopo,LC de Villiers Oval,Pretoria,273.0,276.0,2026-02-26 08:00:00,2026-02-26 16:00:00
30,147203,Domestic,CSA Provincial One-Day Challenge Division Two ...,7th Match,Knights won by 47 runs,Knights,Border,Mangaung Oval,Bloemfontein,229.0,182.0,2026-02-26 08:00:00,2026-02-26 16:00:00
31,147159,Domestic,CSA Provincial One-Day Challenge Division Two ...,5th Match,Eastern Storm won by 6 wkts,Northern Cape,Eastern Storm,Diamond Oval,Kimberley,114.0,115.0,2026-02-25 08:00:00,2026-02-25 16:00:00
32,147170,Domestic,CSA Provincial One-Day Challenge Division Two ...,6th Match,Mpumalanga Rhinos won by 5 wkts,South Western Districts,Mpumalanga Rhinos,"Uplands College, White River",Mpumalanga,214.0,215.0,2026-02-25 07:30:00,2026-02-25 15:30:00
33,132296,Domestic,Plunket Shield 2025-26,15th Match,Match drawn,Otago,Canterbury,Hagley Oval,Christchurch,296.0,227.0,2026-02-27 21:30:00,2026-03-03 04:30:00
34,132274,Domestic,Plunket Shield 2025-26,13th Match,Northern Districts won by 6 wkts,Auckland,Northern Districts,Eden Park Outer Oval,Auckland,283.0,288.0,2026-02-27 21:30:00,2026-03-03 04:30:00
35,132285,Domestic,Plunket Shield 2025-26,14th Match,Match drawn,Wellington,Central Districts,McLean Park,Napier,401.0,296.0,2026-02-27 21:30:00,2026-03-03 04:30:00
36,145871,Domestic,"Pakistan A v England Lions in UAE, 2026",2nd Unofficial ODI,Match Cancelled,Pakistan A,England Lions,Sheikh Zayed Stadium,Abu Dhabi,NaN,NaN,2026-03-01 06:00:00,2026-03-01 14:00:00
37,145849,Domestic,"Pakistan A v England Lions in UAE, 2026",1st Unofficial ODI,England Lions won by 9 wkts,Pakistan A,England Lions,Sheikh Zayed Stadium,Abu Dhabi,152.0,154.0,2026-02-27 06:00:00,2026-02-27 14:00:00
38,145784,Domestic,"Pakistan A v England Lions in UAE, 2026",3rd T20,England Lions won by 2 wkts,Pakistan A,England Lions,Sheikh Zayed Stadium,Abu Dhabi,162.0,163.0,2026-02-24 15:30:00,2026-02-24 19:00:00
39,117065,Women,"India Women tour of Australia, 2026",3rd ODI,Australia Women won by 185 runs,Australia Women,India Women,Bellerive Oval,Hobart,409.0,224.0,2026-03-01 03:50:00,2026-03-01 11:50:00
40,117056,Women,"India Women tour of Australia, 2026",2nd ODI,Australia Women won by 5 wkts,India Women,Australia Women,Bellerive Oval,Hobart,251.0,252.0,2026-02-27 03:50:00,2026-02-27 11:50:00
41,117047,Women,"India Women tour of Australia, 2026",1st ODI,Australia Women won by 6 wkts,India Women,Australia Women,Allan Border Field,Brisbane,214.0,217.0,2026-02-24 03:50:00,2026-02-24 11:50:00
42,144651,Women,Sri Lanka Women tour of West Indies 2026,2nd T20I,Sri Lanka Women won by 4 wkts,West Indies Women,Sri Lanka Women,National Cricket Stadium,"St Georges, Grenada",101.0,102.0,2026-03-01 17:00:00,2026-03-01 20:30:00
43,144640,Women,Sri Lanka Women tour of West Indies 2026,1st T20I,No result due to rain,West Indies Women,Sri Lanka Women,National Cricket Stadium,"St Georges, Grenada",49.0,7.0,2026-02-28 17:00:00,2026-02-28 20:30:00
44,144631,Women,Sri Lanka Women tour of West Indies 2026,3rd ODI,West Indies Women won by 6 wkts,Sri Lanka Women,West Indies Women,National Cricket Stadium,"St Georges, Grenada",217.0,218.0,2026-02-25 13:30:00,2026-02-25 21:30:00
45,122198,Women,"Pakistan Women tour of South Africa, 2026",3rd ODI,Pakistan Women won by 119 runs,Pakistan Women,South Africa Women,Kingsmead,Durban,306.0,187.0,2026-03-01 08:00:00,2026-03-01 16:00:00
46,122187,Women,"Pakistan Women tour of South Africa, 2026",2nd ODI,South Africa Women won by 16 runs,South Africa Women,Pakistan Women,SuperSport Park,Centurion,361.0,345.0,2026-02-25 12:00:00,2026-02-25 20:00:00
47,122748,Women,"Zimbabwe Women tour of New Zealand, 2026",3rd T20I,New Zealand Women won by 10 wkts,Zimbabwe Women,New Zealand Women,Seddon Park,Hamilton,64.0,65.0,2026-03-01 00:15:00,2026-03-01 03:45:00
48,122742,Women,"Zimbabwe Women tour of New Zealand, 2026",2nd T20I,New Zealand Women won by 110 runs,New Zealand Women,Zimbabwe Women,Seddon Park,Hamilton,196.0,86.0,2026-02-27 06:15:00,2026-02-27 09:45:00
49,122737,Women,"Zimbabwe Women tour of New Zealand, 2026",1st T20I,New Zealand Women won by 92 runs,New Zealand Women,Zimbabwe Women,Seddon Park,Hamilton,202.0,110.0,2026-02-25 06:15:00,2026-02-25 09:45:00

# Q10 
Get details of the last 20 completed matches. Show match description, both team names, winning team, victory margin, victory type (runs/wickets), and venue name. Display the most recent matches first.

In [53]:
import pandas as pd
import re

all_matches = []

for type_match in match_list1.get('typeMatches', []):
    m_type = type_match.get('matchType')
    for series in type_match.get('seriesMatches', []):
        series_wrapper = series.get('seriesAdWrapper')
        if series_wrapper and 'matches' in series_wrapper:
            for match in series_wrapper['matches']:
                info = match.get('matchInfo', {})
                score = match.get('matchScore', {})
                status = info.get('status', "")
                
                # --- EXPERT EXTRACTION LOGIC ---
                # 1. Winning Team
                winning_team = status.split(" won")[0].strip() if " won" in status else "N/A"
                
                # 2. Victory Margin (Extract digits using Regex)
                margin_match = re.search(r'by (\d+)', status)
                victory_margin = margin_match.group(1) if margin_match else "N/A"
                
                # 3. Victory Type (Runs or Wickets)
                victory_type = "N/A"
                if "runs" in status.lower(): victory_type = "Runs"
                elif "wkts" in status.lower() or "wickets" in status.lower(): victory_type = "Wickets"

                match_data = {
                    'match_id': info.get('matchId'),
                    'type': m_type,
                    'series_name': info.get('seriesName'),
                    'match_desc': info.get('matchDesc'),
                    'status': status,
                    'winning_team': winning_team,
                    'victory_margin': victory_margin,
                    'victory_type': victory_type,
                    'team1': info.get('team1', {}).get('teamName'),
                    'team2': info.get('team2', {}).get('teamName'),
                    'venue': info.get('venueInfo', {}).get('ground'),
                    'city': info.get('venueInfo', {}).get('city'),
                    'start_ts': info.get('startDate'), 
                    'end_ts': info.get('endDate'),
                    't1_runs': score.get('team1Score', {}).get('inngs1', {}).get('runs'),
                    't2_runs': score.get('team2Score', {}).get('inngs1', {}).get('runs')
                }
                all_matches.append(match_data)

df_all = pd.DataFrame(all_matches)

# Convert dates
df_all['startdate'] = pd.to_datetime(pd.to_numeric(df_all['start_ts'], errors='coerce'), unit='ms')
df_all = df_all.drop(columns=['start_ts', 'end_ts'])

# Final Output for Question 10 (Last 20 Completed Matches)
completed_matches = df_all[df_all['status'].str.contains("won", na=False)].head(20)
print(completed_matches[['match_desc', 'team1', 'team2', 'winning_team', 'victory_margin', 'victory_type', 'venue']])

                               match_desc  \
0   52nd Match, Super 8 Group 1 (X1 v X3)
1   51st Match, Super 8 Group 1 (X2 v X4)
2   50th Match, Super 8 Group 2 (Y3 v Y4)
3   49th Match, Super 8 Group 2 (Y1 v Y2)
4   48th Match, Super 8 Group 1 (X1 v X2)
5   47th Match, Super 8 Group 1 (X3 v X4)
6   46th Match, Super 8 Group 2 (Y2 v Y4)
7   45th Match, Super 8 Group 2 (Y1 v Y3)
8                                   Final
9                      3rd place play-off
10                              6th Match
11                              5th Match
12                              4th Match
13                              3rd Match
14                              2nd Match
15                              1st Match
16                               4th T20I
18                               2nd T20I
19                               1st T20I
21                              3rd Match

                                    team1                           team2  \
0                             West Indies                           India
1                                Zimbabwe                    South Africa
2                                Pakistan                       Sri Lanka
3                             New Zealand                         England
4                                   India                        Zimbabwe
5                             West Indies                    South Africa
6                             New Zealand                       Sri Lanka
7                                Pakistan                         England
8                                   Japan                         Bahrain
9                                  Bhutan                        Thailand
10                                Bahrain                        Thailand
11                                  Japan                          Bhutan
12                                Bahrain                           Japan
13                               Thailand                          Bhutan
14                                 Bhutan                         Bahrain
15                                  Japan                        Thailand
16                       Hong Kong, China                          Kuwait
18                       Hong Kong, China                          Kuwait
19                                 Kuwait                Hong Kong, China
21  North West - Eastvaal Renault Dragons  KwaZulu-Natal Inland - Tuskers

                               winning_team victory_margin victory_type  \
0                                     India              5      Wickets
1                              South Africa              5      Wickets
2                                  Pakistan              5         Runs
3                                   England              4      Wickets
4                                     India             72         Runs
5                              South Africa              9      Wickets
6                               New Zealand             61         Runs
7                                   England              2      Wickets
8                       Match tied (Bahrain            N/A          N/A
9                                    Bhutan              7         Runs
10                                  Bahrain             12         Runs
11                                    Japan             77         Runs
12                                    Japan              8      Wickets
13                                 Thailand             60         Runs
14                                  Bahrain              4      Wickets
15                                    Japan             37         Runs
16                                   Kuwait              3      Wickets
18                         Hong Kong, China             24         Runs
19                         Hong Kong, China              3      Wickets
21  North West  -  Eastvaal Renault Dragons             72         Runs

                                      venue
0                              Eden Gardens
1                      Arun Jaitley Stadium
2   Pallekele International Cricket Stadium
3                       R.Premadasa Stadium
4                    MA Chidambaram Stadium
5                     Narendra Modi Stadium
6                       R.Premadasa Stadium
7   Pallekele International Cricket Stadium
8                   Terdthai Cricket Ground
9                   Terdthai Cricket Ground
10                  Terdthai Cricket Ground
11                  Terdthai Cricket Ground
12                  Terdthai Cricket Ground
13                  Terdthai Cricket Ground
14                  Terdthai Cricket Ground
15                  Terdthai Cricket Ground
16                      Mission Road Ground
18                      Mission Road Ground
19                      Mission Road Ground
21                                City Oval

In [9]:
df_all

NameError: name 'df_all' is not defined

Q10 Answer

In [54]:
import urllib.parse
from sqlalchemy import create_engine

# 1. Database Configuration
password = urllib.parse.quote_plus("deepika@88")


# 2. Establish Connection
engine = create_engine(f'postgresql+psycopg2://postgres:{password}@localhost:5432/cricbuzz')

# 3. Filter for exactly what Question 10 asks (Top 20 Completed Matches)
# We ensure we only take the columns required by the question
q10_data = df_all[df_all['status'].str.contains("won", na=False)].head(20)[
    ['match_desc', 'team1', 'team2', 'winning_team', 'victory_margin', 'victory_type', 'venue']
]

# 4. Push to SQL
try:
    # Creating the specific table: q10_last20matches
    q10_data.to_sql('q10_last20matches', engine, if_exists='replace', index=False)
    print("✅ Table 'q10_last20matches' successfully created in PostgreSQL!")
except Exception as e:
    print(f"❌ Database Error: {e}")

# Verify by printing the head of the migrated data
print(q10_data.head())

✅ Table 'q10_last20matches' successfully created in PostgreSQL!
                              match_desc        team1         team2  \
0  52nd Match, Super 8 Group 1 (X1 v X3)  West Indies         India
1  51st Match, Super 8 Group 1 (X2 v X4)     Zimbabwe  South Africa
2  50th Match, Super 8 Group 2 (Y3 v Y4)     Pakistan     Sri Lanka
3  49th Match, Super 8 Group 2 (Y1 v Y2)  New Zealand       England
4  48th Match, Super 8 Group 1 (X1 v X2)        India      Zimbabwe

   winning_team victory_margin victory_type  \
0         India              5      Wickets
1  South Africa              5      Wickets
2      Pakistan              5         Runs
3       England              4      Wickets
4         India             72         Runs

                                     venue
0                             Eden Gardens
1                     Arun Jaitley Stadium
2  Pallekele International Cricket Stadium
3                      R.Premadasa Stadium
4                   MA Chidambaram Stadium

Q5 data's

In [12]:
# 1. Create the win count table (Q5)
q5 = df_all[df_all['winner'] != 'Tie/NR']['winner'].value_counts().reset_index()
q5.columns = ['Team Name', 'Total Wins']

# 2. Sort to show most wins first
q5 = q5.sort_values(by='Total Wins', ascending=False)

# 3. Display the final allocated table
print(q5)

                                Team Name  Total Wins
0                                   Japan           3
1                         Australia Women           3
2                       New Zealand Women           3
3                            South Africa           2
4                                 England           2
5                        Hong Kong, China           2
6                           Eastern Storm           2
7                       West Indies Women           2
8                           England Lions           2
9                                 Limpopo           2
10                                Knights           2
11                                Bahrain           2
12                                  India           2
13                                 Titans           1
14                      Jammu and Kashmir           1
15                                 Kuwait           1
16                               Thailand           1
17                                 Bhutan           1
18                            New Zealand           1
19                               Pakistan           1
20  North West - Eastvaal Renault Dragons           1
21                      Mpumalanga Rhinos           1
22                                 Border           1
23                       Western Province           1
24                               Warriors           1
25                        Sri Lanka Women           1
26                     Northern Districts           1
27                         Pakistan Women           1
28                     South Africa Women           1

# Q5 moved to sql

In [13]:
import urllib.parse
from sqlalchemy import create_engine

# 1. Encode the special character in password
password = urllib.parse.quote_plus("deepika@88")

# 2. Use the encoded password in your connection string
# Also, ensure 'username' is replaced with your actual DB user (usually 'postgres')
engine = create_engine(f'postgresql+psycopg2://postgres:{password}@localhost:5432/cricbuzz')

# 3. Test the connection and push the data
q5.to_sql('q5_most_wins', engine, if_exists='replace', index=False)

print("✅ Connection successful and table 'most wins ' created!")

✅ Connection successful and table 'most wins ' created!

#  top 10 highest run scorers in ODI cricket

In [1]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/topstats/0"

querystring = {"statsType":"mostRuns"}

headers = {
	"x-rapidapi-key": "87cb73cb75msh7a5d872ecde1a59p1feac0jsne6c94486f484",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

odi_bat=response.json()

In [2]:
print(odi_bat.keys())

dict_keys(['filter', 'headers', 'values', 'appIndex'])

In [64]:
odi_bat['filter']

{'matchtype': [{'matchTypeId': '1', 'matchTypeDesc': 'test'},
  {'matchTypeId': '2', 'matchTypeDesc': 'odi'},
  {'matchTypeId': '3', 'matchTypeDesc': 't20i'}],
 'team': [{'id': '2', 'teamShortName': 'IND'},
  {'id': '27', 'teamShortName': 'IRE'},
  {'id': '3', 'teamShortName': 'PAK'},
  {'id': '4', 'teamShortName': 'AUS'},
  {'id': '5', 'teamShortName': 'SL'},
  {'id': '6', 'teamShortName': 'BAN'},
  {'id': '9', 'teamShortName': 'ENG'},
  {'id': '10', 'teamShortName': 'WI'},
  {'id': '11', 'teamShortName': 'RSA'},
  {'id': '12', 'teamShortName': 'ZIM'},
  {'id': '13', 'teamShortName': 'NZ'},
  {'id': '96', 'teamShortName': 'AFG'}],
 'selectedMatchType': 'test'}

In [4]:
# 1. Access the filter dictionary
filter_dict = odi_bat['filter']

# 2. Get the keys and convert to a list for easy viewing
filter_keys = list(filter_dict.keys())

print(filter_keys)

['matchtype', 'team', 'selectedMatchType']

In [5]:
odi_bat['headers']

['Batter', 'M', 'I', 'R', 'Avg']

In [6]:
odi_bat['values']

[{'values': ['25', 'Tendulkar', '200', '329', '15921', '53.79']},
 {'values': ['8019', 'Root', '163', '298', '13943', '51.07']},
 {'values': ['38', 'R Ponting', '168', '287', '13378', '51.85']},
 {'values': ['213', 'Kallis', '166', '280', '13289', '55.37']},
 {'values': ['27', 'Dravid', '164', '286', '13288', '52.31']},
 {'values': ['488', 'Cook', '161', '291', '12472', '45.35']},
 {'values': ['104', 'Sangakkara', '134', '233', '12400', '57.14']},
 {'values': ['240', 'B Lara', '131', '232', '11953', '52.89']},
 {'values': ['244', 'Chanderpaul', '164', '280', '11867', '51.37']},
 {'values': ['101', 'Mahela', '149', '252', '11814', '49.85']},
 {'values': ['4672', 'A Border', '156', '265', '11174', '50.56']},
 {'values': ['4712', 'S Waugh', '168', '260', '10927', '51.06']},
 {'values': ['2250', 'Steven Smith', '123', '220', '10763', '56.06']},
 {'values': ['3817', 'S Gavaskar', '125', '214', '10122', '51.12']},
 {'values': ['130', 'Younis Khan', '118', '213', '10099', '52.06']},
 {'values': ['6326', 'Williamson', '108', '192', '9461', '54.69']},
 {'values': ['314', 'Amla', '124', '215', '9282', '46.64']},
 {'values': ['207', 'Graeme Smith', '117', '205', '9265', '48.26']},
 {'values': ['1413', 'Virat Kohli', '123', '210', '9230', '46.85']},
 {'values': ['5308', 'G Gooch', '118', '215', '8900', '42.58']}]

In [14]:
# 1. Access the filter dictionary
filters = odi_bat.get('filter', {})

# 2. Extract Match Types (Test, ODI, T20)
match_types = []
for mt in filters.get('matchtype', []):
    match_types.append({
        'matchtypeid': mt.get('matchTypeId'),
        'description': mt.get('matchTypeDesc')
    })

# 3. Extract Teams
teams = []
for t in filters.get('team', []):
    teams.append({
        'teamid': t.get('id'),
        'short_name': t.get('teamShortName')
    })

# 4. Get the current selection
current_selection = filters.get('selectedMatchType')

# Convert to DataFrames for easy use in Streamlit
df_match_types = pd.DataFrame(match_types)
print(df_match_types)

df_teams = pd.DataFrame(teams)
print(df_teams)
#print("Available Teams:", teams)

  matchtypeid description
0           1        test
1           2         odi
2           3        t20i
   teamid short_name
0       2        IND
1      27        IRE
2       3        PAK
3       4        AUS
4       5         SL
5       6        BAN
6       9        ENG
7      10         WI
8      11        RSA
9      12        ZIM
10     13         NZ
11     96        AFG

In [ ]:
import pandas as pd

# Extract the list of values
odivalues = odi_bat['values'] 

# Match the 6 columns actually present in your data
columns = ['playerID', 'Player', 'Matches', 'Innings', 'Runs', 'Avg']

# 1. Rename the DataFrame variable to df_val
df_val = pd.DataFrame([item['values'] for item in odivalues], columns=columns)

# 2. Convert 'Runs' to numeric so sorting works correctly
df_val['Runs'] = pd.to_numeric(df_val['Runs'])

# 3. Get the Top 10 using the new variable name
top_10_odi = df_val.sort_values(by='Runs', ascending=False)

#head(10)
print(top_10_odi)

   playerID        Player Matches Innings   Runs    Avg
0        25     Tendulkar     200     329  15921  53.79
1      8019          Root     163     298  13943  51.07
2        38     R Ponting     168     287  13378  51.85
3       213        Kallis     166     280  13289  55.37
4        27        Dravid     164     286  13288  52.31
5       488          Cook     161     291  12472  45.35
6       104    Sangakkara     134     233  12400  57.14
7       240        B Lara     131     232  11953  52.89
8       244   Chanderpaul     164     280  11867  51.37
9       101        Mahela     149     252  11814  49.85
10     4672      A Border     156     265  11174  50.56
11     4712       S Waugh     168     260  10927  51.06
12     2250  Steven Smith     123     220  10763  56.06
13     3817    S Gavaskar     125     214  10122  51.12
14      130   Younis Khan     118     213  10099  52.06
15     6326    Williamson     108     192   9461  54.69
16      314          Amla     124     215   9282  46.64
17      207  Graeme Smith     117     205   9265  48.26
18     1413   Virat Kohli     123     210   9230  46.85
19     5308       G Gooch     118     215   8900  42.58

# All the state player data

In [72]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/team/2"

# here the matchtype =2 its indicates 'odi'
querystring = {"statsType":"mostRuns","matchType":"2"}

headers = {
	"x-rapidapi-key": "2454e52ef7msha9ad8a68de89ea1p1b4c51jsn18b293bbd472",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

allplayers = response.json()

In [159]:
print(allplayers.keys())

dict_keys(['filter', 'headers', 'values', 'appIndex'])

In [79]:
allplayers['values']

[{'values': ['25', 'Tendulkar', '463', '452', '18426', '44.83']},
 {'values': ['1413', 'Virat Kohli', '311', '299', '14797', '58.72']},
 {'values': ['576', 'Rohit Sharma', '282', '274', '11577', '48.85']},
 {'values': ['29', 'S Ganguly', '308', '297', '11221', '40.95']},
 {'values': ['27', 'Dravid', '340', '314', '10768', '39.16']},
 {'values': ['265', 'Dhoni', '347', '294', '10599', '50.23']},
 {'values': ['3864', 'M Azharuddin', '334', '308', '9378', '36.92']},
 {'values': ['69', 'Yuvraj', '301', '275', '8609', '36.48']},
 {'values': ['26', 'Sehwag', '241', '235', '7995', '35.38']},
 {'values': ['1446', 'Dhawan', '167', '164', '6793', '44.11']},
 {'values': ['413', 'Raina', '226', '194', '5615', '35.31']},
 {'values': ['3898', 'A Jadeja', '196', '179', '5359', '37.48']},
 {'values': ['308', 'Gambhir', '147', '143', '5238', '39.68']},
 {'values': ['3874', 'N Sidhu', '136', '127', '4413', '37.08']},
 {'values': ['3850', 'K Srikkanth', '146', '145', '4091', '29.01']},
 {'values': ['3838', 'K Dev', '225', '198', '3783', '23.79']},
 {'values': ['3832', 'D Vengsarkar', '129', '120', '3508', '34.73']},
 {'values': ['8733', 'Rahul', '94', '86', '3360', '50.91']},
 {'values': ['3849', 'R Shastri', '150', '128', '3108', '29.05']},
 {'values': ['3817', 'S Gavaskar', '108', '102', '3092', '35.14']}]

In [160]:
allplayers['filter']

{'matchtype': [{'matchTypeId': '1', 'matchTypeDesc': 'test'},
  {'matchTypeId': '2', 'matchTypeDesc': 'odi'},
  {'matchTypeId': '3', 'matchTypeDesc': 't20i'}],
 'team': [{'id': '58', 'teamShortName': 'CSK'},
  {'id': '97', 'teamShortName': 'INDW'},
  {'id': '61', 'teamShortName': 'DC'},
  {'id': '65', 'teamShortName': 'PBKS'},
  {'id': '63', 'teamShortName': 'KKR'},
  {'id': '62', 'teamShortName': 'MI'},
  {'id': '59', 'teamShortName': 'RCB'},
  {'id': '64', 'teamShortName': 'RR'},
  {'id': '255', 'teamShortName': 'SRH'},
  {'id': '971', 'teamShortName': 'GT'},
  {'id': '966', 'teamShortName': 'LSG'},
  {'id': '510', 'teamShortName': 'BTS'},
  {'id': '506', 'teamShortName': 'VANW'},
  {'id': '507', 'teamShortName': 'SKRW'},
  {'id': '496', 'teamShortName': 'BELW'},
  {'id': '508', 'teamShortName': 'DENW'},
  {'id': '509', 'teamShortName': 'SINW'},
  {'id': '518', 'teamShortName': 'AFGU23'},
  {'id': '517', 'teamShortName': 'SIND'},
  {'id': '516', 'teamShortName': 'RJP'},
  {'id': '515', 'teamShortName': 'PL'},
  {'id': '514', 'teamShortName': 'PAKHT'},
  {'id': '513', 'teamShortName': 'NW'},
  {'id': '512', 'teamShortName': 'MA'},
  {'id': '511', 'teamShortName': 'KKS'},
  {'id': '505', 'teamShortName': 'OMANW'},
  {'id': '504', 'teamShortName': 'GERW'},
  {'id': '503', 'teamShortName': 'NAMW'},
  {'id': '490', 'teamShortName': 'SLEW'},
  {'id': '489', 'teamShortName': 'ARGW'},
  {'id': '488', 'teamShortName': 'BWAW'},
  {'id': '487', 'teamShortName': 'JPNW'},
  {'id': '486', 'teamShortName': 'CHNW'},
  {'id': '485', 'teamShortName': 'QATW'},
  {'id': '484', 'teamShortName': 'IDNW'},
  {'id': '483', 'teamShortName': 'TANW'},
  {'id': '491', 'teamShortName': 'BRAW'},
  {'id': '492', 'teamShortName': 'FRAW'},
  {'id': '493', 'teamShortName': 'MOZW'},
  {'id': '502', 'teamShortName': 'HKC W'},
  {'id': '501', 'teamShortName': 'KENW'},
  {'id': '500', 'teamShortName': 'SWZW'},
  {'id': '499', 'teamShortName': 'LSOW'},
  {'id': '498', 'teamShortName': 'PERW'},
  {'id': '497', 'teamShortName': 'CHLW'},
  {'id': '495', 'teamShortName': 'MWIW'},
  {'id': '494', 'teamShortName': 'ZMBW'},
  {'id': '482', 'teamShortName': 'WSMW'},
  {'id': '519', 'teamShortName': 'INDU19A'},
  {'id': '520', 'teamShortName': 'INDU19B'},
  {'id': '540', 'teamShortName': 'BLZ'},
  {'id': '541', 'teamShortName': 'BEL'},
  {'id': '542', 'teamShortName': 'PER'},
  {'id': '543', 'teamShortName': 'BHR'},
  {'id': '544', 'teamShortName': 'MEX'},
  {'id': '545', 'teamShortName': 'WSM'},
  {'id': '546', 'teamShortName': 'PAN'},
  {'id': '547', 'teamShortName': 'JPN'},
  {'id': '548', 'teamShortName': 'CRI'},
  {'id': '549', 'teamShortName': 'ARG'},
  {'id': '550', 'teamShortName': 'HUN'},
  {'id': '551', 'teamShortName': 'MOZ'},
  {'id': '552', 'teamShortName': 'CHL'},
  {'id': '553', 'teamShortName': 'MWI'},
  {'id': '554', 'teamShortName': 'ISR'},
  {'id': '555', 'teamShortName': 'BTN'},
  {'id': '556', 'teamShortName': 'FIN'},
  {'id': '539', 'teamShortName': 'FRA'},
  {'id': '538', 'teamShortName': 'PHI'},
  {'id': '521', 'teamShortName': 'ESTXI'},
  {'id': '522', 'teamShortName': 'Malta'},
  {'id': '523', 'teamShortName': 'ESP'},
  {'id': '524', 'teamShortName': 'CHN'},
  {'id': '525', 'teamShortName': 'QAT'},
  {'id': '526', 'teamShortName': 'EST'},
  {'id': '527', 'teamShortName': 'ITA'},
  {'id': '528', 'teamShortName': 'ZIMCXI'},
  {'id': '529', 'teamShortName': 'BW'},
  {'id': '530', 'teamShortName': 'VEL'},
  {'id': '531', 'teamShortName': 'GH'},
  {'id': '532', 'teamShortName': 'AUT'},
  {'id': '533', 'teamShortName': 'GGY'},
  {'id': '534', 'teamShortName': 'SWE'},
  {'id': '535', 'teamShortName': 'TAN'},
  {'id': '536', 'teamShortName': 'NGA'},
  {'id': '537', 'teamShortName': 'LUX'},
  {'id': '557', 'teamShortName': 'IOM'},
  {'id': '404', 'teamShortName': 'MCCWXI'},
  {'id': '425', 'teamShortName': 'WXI'},
  {'id': '426', 'teamShortName': 'BZ'},
  {'id': '427', 'teamShortName': 'BLCB'},
  {'id': '428', 'teamShortName': 'CTKR'},
  {'id': '429', 'teamShortName': 'DW'},
  {'id': '430', 'teamShortName': 'JG'},
  {'id': '431', 'teamShortName': 'NMBS'},
  {'id': '432', 'teamShortName': 'PM'},
  {'id': '433', 'teamShortName': 'SK'},
  {'id': '434', 'teamShortName': 'SYL'},
  {'id': '435', 'teamShortName': 'IREA'},
  {'id': '436', 'teamShortName': 'WAXI'},
  {'id': '437', 'teamShortName': 'MS'},
  {'id': '438', 'teamShortName': 'HKIU'},
  {'id': '439', 'teamShortName': 'SAEW'},
  {'id': '440', 'teamShortName': 'INDWA'},
  {'id': '441', 'teamShortName': 'COL'},
  {'id': '424', 'teamShortName': 'KENU19'},
  {'id': '423', 'teamShortName': 'BLB'},
  {'id': '405', 'teamShortName': 'INDU23'},
  {'id': '406', 'teamShortName': 'PAKU23'},
  {'id': '407', 'teamShortName': 'SLU23'},
  {'id': '408', 'teamShortName': 'BANU23'},
  {'id': '410', 'teamShortName': 'Trichy'},
  {'id': '411', 'teamShortName': 'SIKAR'},
  {'id': '412', 'teamShortName': 'UDE'},
  {'id': '413', 'teamShortName': 'JAIPUR'},
  {'id': '414', 'teamShortName': 'JL'},
  {'id': '415', 'teamShortName': 'BWS'},
  {'id': '416', 'teamShortName': 'APS'},
  {'id': '417', 'teamShortName': 'SV'},
  {'id': '418', 'teamShortName': 'WS'},
  {'id': '419', 'teamShortName': 'YD'},
  {'id': '420', 'teamShortName': 'LT'},
  {'id': '421', 'teamShortName': 'LBL'},
  {'id': '422', 'teamShortName': 'SST'},
  {'id': '442', 'teamShortName': 'KAN'},
  {'id': '443', 'teamShortName': 'GAL'},
  {'id': '444', 'teamShortName': 'DAM'},
  {'id': '464', 'teamShortName': 'NGL'},
  {'id': '465', 'teamShortName': 'PDC'},
  {'id': '466', 'teamShortName': 'SKM'},
  {'id': '467', 'teamShortName': 'UTK'},
  {'id': '468', 'teamShortName': 'ARNP'},
  {'id': '469', 'teamShortName': 'HKCU19'},
  {'id': '470', 'teamShortName': 'KZ'},
  {'id': '471', 'teamShortName': 'PP'},
  {'id': '472', 'teamShortName': 'KDK'},
  {'id': '473', 'teamShortName': 'NL'},
  {'id': '474', 'teamShortName': 'BL'},
  {'id': '475', 'teamShortName': 'CTB'},
  {'id': '476', 'teamShortName': 'DH'},
  {'id': '477', 'teamShortName': 'JS'},
  {'id': '478', 'teamShortName': 'NMBG'},
  {'id': '479', 'teamShortName': 'PLR'},
  {'id': '480', 'teamShortName': 'TSP'},
  {'id': '463', 'teamShortName': 'MIZ'},
  {'id': '462', 'teamShortName': 'MGLY'},
  {'id': '445', 'teamShortName': 'MLYW'},
  {'id': '446', 'teamShortName': 'TRL'},
  {'id': '447', 'teamShortName': 'SPN'},
  {'id': '448', 'teamShortName': 'UGAW'},
  {'id': '449', 'teamShortName': 'UAEW'},
  {'id': '450', 'teamShortName': 'TTN'},
  {'id': '451', 'teamShortName': 'MNT'},
  {'id': '452', 'teamShortName': 'EDR'},
  {'id': '453', 'teamShortName': 'VCK'},
  {'id': '454', 'teamShortName': 'WPH'},
  {'id': '455', 'teamShortName': 'VKV'},
  {'id': '456', 'teamShortName': 'CWIB'},
  {'id': '457', 'teamShortName': 'INDWR'},
  {'id': '458', 'teamShortName': 'INDWB'},
  {'id': '459', 'teamShortName': 'INDWG'},
  {'id': '460', 'teamShortName': 'BIH'},
  {'id': '461', 'teamShortName': 'MNP'},
  {'id': '481', 'teamShortName': 'INDC'},
  {'id': '558', 'teamShortName': 'BGR'},
  {'id': '657', 'teamShortName': 'PTXI'},
  {'id': '770', 'teamShortName': 'TV'},
  {'id': '775', 'teamShortName': 'AUTW'},
  {'id': '779', 'teamShortName': 'FINXI'},
  {'id': '784', 'teamShortName': 'CUMXI'},
  {'id': '789', 'teamShortName': 'CLK'},
  {'id': '794', 'teamShortName': 'DVK'},
  {'id': '799', 'teamShortName': 'GGD'},
  {'id': '800', 'teamShortName': 'JST'},
  {'id': '805', 'teamShortName': 'KDT'},
  {'id': '807', 'teamShortName': 'BRSAL'},
  {'id': '812', 'teamShortName': 'KHULN'},
  {'id': '817', 'teamShortName': 'RJSHI'},
  {'id': '822', 'teamShortName': 'CTGRM'},
  {'id': '827', 'teamShortName': 'DHAKA'},
  {'id': '832', 'teamShortName': 'Root'},
  {'id': '838', 'teamShortName': 'NZWXI'},
  {'id': '843', 'teamShortName': 'BANE'},
  {'id': '768', 'teamShortName': 'TC'},
  {'id': '763', 'teamShortName': 'TR'},
  {'id': '666', 'teamShortName': 'GCXI'},
  {'id': '675', 'teamShortName': 'IRN'},
  {'id': '682', 'teamShortName': 'INDL'},
  {'id': '691', 'teamShortName': 'WIL'},
  {'id': '700', 'teamShortName': 'AUSL'},
  {'id': '709', 'teamShortName': 'SLL'},
  {'id': '718', 'teamShortName': 'RSAL'},
  {'id': '720', 'teamShortName': 'RWAW'},
  {'id': '729', 'teamShortName': 'SLCXI'},
  {'id': '733', 'teamShortName': 'WIHOXI'},
  {'id': '738', 'teamShortName': 'WIBRXI'},
  {'id': '743', 'teamShortName': 'TS'},
  {'id': '748', 'teamShortName': 'TBR'},
  {'id': '749', 'teamShortName': 'PAKWT'},
  {'id': '754', 'teamShortName': 'PAKGR'},
  {'id': '758', 'teamShortName': 'TMG'},
  {'id': '759', 'teamShortName': 'TMO'},
  {'id': '848', 'teamShortName': 'BANL'},
  {'id': '853', 'teamShortName': 'ENGL'},
  {'id': '861', 'teamShortName': 'ITT'},
  {'id': '928', 'teamShortName': 'ROCKS'},
  {'id': '933', 'teamShortName': 'ESTORM'},
  {'id': '941', 'teamShortName': 'CBJ'},
  {'id': '943', 'teamShortName': 'CLS'},
  {'id': '946', 'teamShortName': 'DAS'},
  {'id': '948', 'teamShortName': 'JKS'},
  {'id': '953', 'teamShortName': 'KDW'},
  {'id': '956', 'teamShortName': 'UGAU19'},
  {'id': '961', 'teamShortName': 'INDWD'},
  {'id': '976', 'teamShortName': 'MGD'},
  {'id': '981', 'teamShortName': 'SYSR'},
  {'id': '986', 'teamShortName': 'IMR'},
  {'id': '991', 'teamShortName': 'ALN'},
  {'id': '996', 'teamShortName': 'WGS'},
  {'id': '1011', 'teamShortName': 'BAW'},
  {'id': '1018', 'teamShortName': 'BHM'},
  {'id': '1020', 'teamShortName': 'CAYM'},
  {'id': '927', 'teamShortName': 'ECAPE'},
  {'id': '923', 'teamShortName': 'NCAPE'},
  {'id': '866', 'teamShortName': 'NRK'},
  {'id': '867', 'teamShortName': 'SLST'},
  {'id': '872', 'teamShortName': 'TLAT'},
  {'id': '876', 'teamShortName': 'TWS'},
  {'id': '881', 'teamShortName': 'ZIMSXI'},
  {'id': '886', 'teamShortName': 'PCCSXI'},
  {'id': '1032', 'teamShortName': 'JERW'},
  {'id': '887', 'teamShortName': 'A1'},
  {'id': '892', 'teamShortName': 'A2'},
  {'id': '897', 'teamShortName': 'TKY'},
  {'id': '902', 'teamShortName': 'TRKW'},
  {'id': '903', 'teamShortName': 'MPR'},
  {'id': '908', 'teamShortName': 'TUSKS'},
  {'id': '912', 'teamShortName': 'LIMPO'},
  {'id': '917', 'teamShortName': 'WPR'},
  {'id': '918', 'teamShortName': 'GRB'},
  {'id': '922', 'teamShortName': 'NWEST'},
  {'id': '1027', 'teamShortName': 'NOR'},
  {'id': '559', 'teamShortName': 'SLE'},
  {'id': '579', 'teamShortName': 'TKMNE'},
  {'id': '580', 'teamShortName': 'ETS'},
  {'id': '581', 'teamShortName': 'NMP'},
  {'id': '582', 'teamShortName': 'SBS'},
  {'id': '583', 'teamShortName': 'SPL'},
  {'id': '584', 'teamShortName': 'NBB'},
  {'id': '585', 'teamShortName': 'AA'},
  {'id': '586', 'teamShortName': 'SOL'},
  {'id': '587', 'teamShortName': 'GGS'},
  {'id': '588', 'teamShortName': 'HHS'},
  {'id': '589', 'teamShortName': 'ZR'},
  {'id': '590', 'teamShortName': 'KUTW'},
  {'id': '591', 'teamShortName': 'BTW'},
  {'id': '592', 'teamShortName': 'USAW'},
  {'id': '593', 'teamShortName': 'KUWU19'},
  {'id': '594', 'teamShortName': 'INDWBPXI'},
  {'id': '595', 'teamShortName': 'CDG'},
  {'id': '578', 'teamShortName': 'ATMWS'},
  {'id': '577', 'teamShortName': 'BFT'},
  {'id': '560', 'teamShortName': 'BRAZIL'},
  {'id': '561', 'teamShortName': 'CZE'},
  {'id': '562', 'teamShortName': 'SHN'},
  {'id': '563', 'teamShortName': 'MDV'},
  {'id': '564', 'teamShortName': 'GIB'},
  {'id': '565', 'teamShortName': 'MMR'},
  {'id': '566', 'teamShortName': 'IDN'},
  {'id': '567', 'teamShortName': 'GM'},
  {'id': '568', 'teamShortName': 'SWZ'},
  {'id': '569', 'teamShortName': 'RWA'},
  {'id': '570', 'teamShortName': 'LSO'},
  {'id': '571', 'teamShortName': 'SAU'},
  {'id': '572', 'teamShortName': 'ADK'},
  {'id': '573', 'teamShortName': 'RDR'},
  {'id': '574', 'teamShortName': 'EBR'},
  {'id': '575', 'teamShortName': 'GGG'},
  {'id': '576', 'teamShortName': 'DBC'},
  {'id': '596', 'teamShortName': 'PORT'},
  {'id': '597', 'teamShortName': 'DEG'},
  {'id': '598', 'teamShortName': 'UBL'},
  {'id': '618', 'teamShortName': 'TREW'},
  {'id': '619', 'teamShortName': 'SULW'},
  {'id': '620', 'teamShortName': 'SOUW'},
  {'id': '621', 'teamShortName': 'SLT'},
  {'id': '622', 'teamShortName': 'CGC'},
  {'id': '623', 'teamShortName': 'CW'},
  {'id': '624', 'teamShortName': 'RPR'},
  {'id': '625', 'teamShortName': 'DP'},
  {'id': '626', 'teamShortName': 'RSR'},
  {'id': '627', 'teamShortName': 'KLT'},
  {'id': '628', 'teamShortName': 'FLH'},
  {'id': '629', 'teamShortName': 'FYO'},
  {'id': '630', 'teamShortName': 'DSR'},
  {'id': '631', 'teamShortName': 'PGR'},
  {'id': '632', 'teamShortName': 'HSR'},
  {'id': '633', 'teamShortName': 'SGP'},
  {'id': '639', 'teamShortName': 'INDWC'},
  {'id': '617', 'teamShortName': 'MSGW'},
  {'id': '616', 'teamShortName': 'LDNW'},
  {'id': '599', 'teamShortName': 'QLD'},
  {'id': '600', 'teamShortName': 'BGT'},
  {'id': '601', 'teamShortName': 'AD'},
  {'id': '602', 'teamShortName': 'PD'},
  {'id': '603', 'teamShortName': 'JPNU19'},
  {'id': '604', 'teamShortName': 'NGAU19'},
  {'id': '605', 'teamShortName': 'MIL'},
  {'id': '606', 'teamShortName': 'WEF'},
  {'id': '607', 'teamShortName': 'BRM'},
  {'id': '608', 'teamShortName': 'LDN'},
  {'id': '609', 'teamShortName': 'MSG'},
  {'id': '610', 'teamShortName': 'SUL'},
  {'id': '611', 'teamShortName': 'SOU'},
  {'id': '612', 'teamShortName': 'TRE'},
  {'id': '613', 'teamShortName': 'MILW'},
  {'id': '614', 'teamShortName': 'WELW'},
  {'id': '615', 'teamShortName': 'BRMW'},
  {'id': '648', 'teamShortName': 'INDIAWB'},
  {'id': '403', 'teamShortName': 'SOUTH'},
  {'id': '149', 'teamShortName': 'GLAM'},
  {'id': '170', 'teamShortName': 'BRD'},
  {'id': '171', 'teamShortName': 'RAJ'},
  {'id': '172', 'teamShortName': 'SLU19'},
  {'id': '173', 'teamShortName': 'ENGU19'},
  {'id': '183', 'teamShortName': 'PWI'},
  {'id': '184', 'teamShortName': 'KTK'},
  {'id': '185', 'teamShortName': 'DEN'},
  {'id': '186', 'teamShortName': 'AKL'},
  {'id': '187', 'teamShortName': 'RUH'},
  {'id': '188', 'teamShortName': 'NEDW'},
  {'id': '189', 'teamShortName': 'IREW'},
  {'id': '190', 'teamShortName': 'SIN'},
  {'id': '191', 'teamShortName': 'CACXI'},
  {'id': '192', 'teamShortName': 'SYT'},
  {'id': '193', 'teamShortName': 'BRH'},
  {'id': '194', 'teamShortName': 'HBH'},
  {'id': '195', 'teamShortName': 'MLR'},
  {'id': '168', 'teamShortName': 'NCC'},
  {'id': '167', 'teamShortName': 'MP'},
  {'id': '150', 'teamShortName': 'KENT'},
  {'id': '151', 'teamShortName': 'GLOUCS'},
  {'id': '152', 'teamShortName': 'ESS'},
  {'id': '153', 'teamShortName': 'HAM'},
  {'id': '154', 'teamShortName': 'SLCPXI'},
  {'id': '155', 'teamShortName': 'WAR'},
  {'id': '156', 'teamShortName': 'CEN'},
  {'id': '157', 'teamShortName': 'LIONS'},
  {'id': '158', 'teamShortName': 'SAUS'},
  {'id': '159', 'teamShortName': 'GAW'},
  {'id': '160', 'teamShortName': 'EA'},
  {'id': '161', 'teamShortName': 'NAM'},
  {'id': '162', 'teamShortName': 'ASM'},
  {'id': '163', 'teamShortName': 'GUJ'},
  {'id': '164', 'teamShortName': 'QL'},
  {'id': '165', 'teamShortName': 'ECBXI'},
  {'id': '166', 'teamShortName': 'TAS'},
  {'id': '196', 'teamShortName': 'MLS'},
  {'id': '197', 'teamShortName': 'PRS'},
  {'id': '198', 'teamShortName': 'SYS'},
  {'id': '223', 'teamShortName': 'AFGU19'},
  {'id': '224', 'teamShortName': 'BANU19'},
  {'id': '226', 'teamShortName': 'IREU19'},
  {'id': '228', 'teamShortName': 'SCOU19'},
  {'id': '229', 'teamShortName': 'NPLU19'},
  {'id': '230', 'teamShortName': 'NAMU19'},
  {'id': '231', 'teamShortName': 'INDB'},
  {'id': '232', 'teamShortName': 'BEN'},
  {'id': '233', 'teamShortName': 'NZONE'},
  {'id': '234', 'teamShortName': 'WZONE'},
  {'id': '235', 'teamShortName': 'EZONE'},
  {'id': '236', 'teamShortName': 'SZONE'},
  {'id': '237', 'teamShortName': 'CZONE'},
  {'id': '238', 'teamShortName': 'PASXI'},
  {'id': '239', 'teamShortName': 'IWXI'},
  {'id': '240', 'teamShortName': 'MUMA'},
  {'id': '241', 'teamShortName': 'AP'},
  {'id': '222', 'teamShortName': 'PNGU19'},
  {'id': '221', 'teamShortName': 'ZIMU19'},
  {'id': '199', 'teamShortName': 'ADS'},
  {'id': '200', 'teamShortName': 'HAR'},
  {'id': '201', 'teamShortName': 'BB'},
  {'id': '202', 'teamShortName': 'CK'},
  {'id': '203', 'teamShortName': 'DG'},
  {'id': '204', 'teamShortName': 'DR'},
  {'id': '205', 'teamShortName': 'KRB'},
  {'id': '206', 'teamShortName': 'SR'},
  {'id': '207', 'teamShortName': 'WIA'},
  {'id': '208', 'teamShortName': 'BCD'},
  {'id': '209', 'teamShortName': 'KW'},
  {'id': '210', 'teamShortName': 'NN'},
  {'id': '211', 'teamShortName': 'RUR'},
  {'id': '212', 'teamShortName': 'UR'},
  {'id': '213', 'teamShortName': 'WU'},
  {'id': '214', 'teamShortName': 'UN'},
  {'id': '220', 'teamShortName': 'WIU19'},
  {'id': '242', 'teamShortName': 'HYD'},
  {'id': '148', 'teamShortName': 'SUR'},
  {'id': '2', 'teamShortName': 'IND'},
  {'id': '26', 'teamShortName': 'CAN'},
  {'id': '27', 'teamShortName': 'IRE'},
  {'id': '36', 'teamShortName': 'INDBLUE'},
  {'id': '41', 'teamShortName': 'SUS'},
  {'id': '42', 'teamShortName': 'ENGA'},
  {'id': '43', 'teamShortName': 'SLA'},
  {'id': '44', 'teamShortName': 'UGA'},
  {'id': '52', 'teamShortName': 'VIC'},
  {'id': '53', 'teamShortName': 'ACTXI'},
  {'id': '54', 'teamShortName': 'INDU19'},
  {'id': '55', 'teamShortName': 'NZU19'},
  {'id': '56', 'teamShortName': 'PAKU19'},
  {'id': '57', 'teamShortName': 'RSAU19'},
  {'id': '71', 'teamShortName': 'MLY'},
  {'id': '72', 'teamShortName': 'NEP'},
  {'id': '74', 'teamShortName': 'MDX'},
  {'id': '77', 'teamShortName': 'GER'},
  {'id': '25', 'teamShortName': 'BER'},
  {'id': '24', 'teamShortName': 'NED'},
  {'id': '3', 'teamShortName': 'PAK'},
  {'id': '4', 'teamShortName': 'AUS'},
  {'id': '5', 'teamShortName': 'SL'},
  {'id': '6', 'teamShortName': 'BAN'},
  {'id': '7', 'teamShortName': 'UAE'},
  {'id': '8', 'teamShortName': 'HKC'},
  {'id': '9', 'teamShortName': 'ENG'},
  {'id': '10', 'teamShortName': 'WI'},
  {'id': '11', 'teamShortName': 'RSA'},
  {'id': '12', 'teamShortName': 'ZIM'},
  {'id': '13', 'teamShortName': 'NZ'},
  {'id': '14', 'teamShortName': 'KEN'},
  {'id': '15', 'teamShortName': 'USA'},
  {'id': '18', 'teamShortName': 'INDSR'},
  {'id': '20', 'teamShortName': 'INDGREEN'},
  {'id': '21', 'teamShortName': 'INDRED'},
  {'id': '23', 'teamShortName': 'SCO'},
  {'id': '78', 'teamShortName': 'INDA'},
  {'id': '79', 'teamShortName': 'AUSA'},
  {'id': '80', 'teamShortName': 'NZA'},
  {'id': '105', 'teamShortName': 'OTG'},
  {'id': '119', 'teamShortName': 'SOM'},
  {'id': '122', 'teamShortName': 'MD'},
  {'id': '123', 'teamShortName': 'BP'},
  {'id': '125', 'teamShortName': 'BIJ'},
  {'id': '128', 'teamShortName': 'KAR'},
  {'id': '129', 'teamShortName': 'AUSU19'},
  {'id': '130', 'teamShortName': 'WIS'},
  {'id': '134', 'teamShortName': 'RGR'},
  {'id': '139', 'teamShortName': 'NOTTS'},
  {'id': '140', 'teamShortName': 'WARKS'},
  {'id': '141', 'teamShortName': 'DUR'},
  {'id': '142', 'teamShortName': 'NHNTS'},
  {'id': '143', 'teamShortName': 'LANCS'},
  {'id': '144', 'teamShortName': 'DERBY'},
  {'id': '145', 'teamShortName': 'LEIC'},
  {'id': '146', 'teamShortName': 'YORKS'},
  {'id': '104', 'teamShortName': 'NSW'},
  {'id': '103', 'teamShortName': 'WAY'},
  {'id': '81', 'teamShortName': 'DEL'},
  {'id': '82', 'teamShortName': 'ROI'},
  {'id': '84', 'teamShortName': 'TT'},
  {'id': '86', 'teamShortName': 'BPXI'},
  {'id': '87', 'teamShortName': 'WA'},
  {'id': '88', 'teamShortName': 'SKST'},
  {'id': '89', 'teamShortName': 'TIT'},
  {'id': '90', 'teamShortName': 'DOL'},
  {'id': '92', 'teamShortName': 'TN'},
  {'id': '93', 'teamShortName': 'UP'},
  {'id': '94', 'teamShortName': 'SAUR'},
  {'id': '95', 'teamShortName': 'MUM'},
  {'id': '96', 'teamShortName': 'AFG'},
  {'id': '98', 'teamShortName': 'NZW'},
  {'id': '99', 'teamShortName': 'ENGW'},
  {'id': '100', 'teamShortName': 'AUSW'},
  {'id': '101', 'teamShortName': 'COB'},
  {'id': '147', 'teamShortName': 'WORCS'},
  {'id': '323', 'teamShortName': 'BCBXI'},
  {'id': '347', 'teamShortName': 'HPCAXI'},
  {'id': '348', 'teamShortName': 'TNCAU17'},

In [72]:
allplayers['values']

[{'values': ['25', 'Tendulkar', '463', '452', '18426', '44.83']},
 {'values': ['1413', 'Virat Kohli', '311', '299', '14797', '58.72']},
 {'values': ['576', 'Rohit Sharma', '282', '274', '11577', '48.85']},
 {'values': ['29', 'S Ganguly', '308', '297', '11221', '40.95']},
 {'values': ['27', 'Dravid', '340', '314', '10768', '39.16']},
 {'values': ['265', 'Dhoni', '347', '294', '10599', '50.23']},
 {'values': ['3864', 'M Azharuddin', '334', '308', '9378', '36.92']},
 {'values': ['69', 'Yuvraj', '301', '275', '8609', '36.48']},
 {'values': ['26', 'Sehwag', '241', '235', '7995', '35.38']},
 {'values': ['1446', 'Dhawan', '167', '164', '6793', '44.11']},
 {'values': ['413', 'Raina', '226', '194', '5615', '35.31']},
 {'values': ['3898', 'A Jadeja', '196', '179', '5359', '37.48']},
 {'values': ['308', 'Gambhir', '147', '143', '5238', '39.68']},
 {'values': ['3874', 'N Sidhu', '136', '127', '4413', '37.08']},
 {'values': ['3850', 'K Srikkanth', '146', '145', '4091', '29.01']},
 {'values': ['3838', 'K Dev', '225', '198', '3783', '23.79']},
 {'values': ['3832', 'D Vengsarkar', '129', '120', '3508', '34.73']},
 {'values': ['8733', 'Rahul', '94', '86', '3360', '50.91']},
 {'values': ['3849', 'R Shastri', '150', '128', '3108', '29.05']},
 {'values': ['3817', 'S Gavaskar', '108', '102', '3092', '35.14']}]

# Q3 Final answer

In [73]:
import pandas as pd

# Extract the list of values
odivalues = allplayers['values'] 

# Match the 6 columns actually present in your data
columns = ['playerID', 'Player', 'Matches', 'Innings', 'Runs', 'Avg']

# 1. Rename the DataFrame variable to df_val
df_val = pd.DataFrame([item['values'] for item in odivalues], columns=columns)

# 2. Convert 'Runs' to numeric so sorting works correctly
df_val['Runs'] = pd.to_numeric(df_val['Runs'])

# 3. Get the Top 10 using the new variable name
top_10_odi = df_val.sort_values(by='Runs', ascending=False)

#head(10)
print(top_10_odi)

   playerID        Player Matches Innings   Runs    Avg
0        25     Tendulkar     463     452  18426  44.83
1      1413   Virat Kohli     311     299  14797  58.72
2       576  Rohit Sharma     282     274  11577  48.85
3        29     S Ganguly     308     297  11221  40.95
4        27        Dravid     340     314  10768  39.16
5       265         Dhoni     347     294  10599  50.23
6      3864  M Azharuddin     334     308   9378  36.92
7        69        Yuvraj     301     275   8609  36.48
8        26        Sehwag     241     235   7995  35.38
9      1446        Dhawan     167     164   6793  44.11
10      413         Raina     226     194   5615  35.31
11     3898      A Jadeja     196     179   5359  37.48
12      308       Gambhir     147     143   5238  39.68
13     3874       N Sidhu     136     127   4413  37.08
14     3850   K Srikkanth     146     145   4091  29.01
15     3838         K Dev     225     198   3783  23.79
16     3832  D Vengsarkar     129     120   3508  34.73
17     8733         Rahul      94      86   3360  50.91
18     3849     R Shastri     150     128   3108  29.05
19     3817    S Gavaskar     108     102   3092  35.14

In [76]:
import urllib.parse
from sqlalchemy import create_engine

# 1. Encode the special character in password
password = urllib.parse.quote_plus("deepika@88")

# 2. Use the encoded password in your connection string
# Also, ensure 'username' is replaced with your actual DB user (usually 'postgres')
engine = create_engine(f'postgresql+psycopg2://postgres:{password}@localhost:5432/cricbuzz')

# 3. Test the connection and push the data
df_val.to_sql('top10_odi', engine, if_exists='replace', index=False)

print("✅ Connection successful and table 'top10_odi' created!")

✅ Connection successful and table 'top10_odi' created!

# Q3 century

In [81]:
import pandas as pd
import requests
import time

centuries_list = []

print("Extracting centuries from player career endpoints...")

for pid in top_10_odi['playerID']:
    # FIX 1: Removed the "url = " text from inside the string
    career_url = f"https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/{pid}/batting"
    
    try:
        res = requests.get(career_url, headers=headers)
        if res.status_code == 200:
            career_data = res.json()
            
            # Get headers to find which column is 'ODI'
            header_list = career_data.get('headers', [])
            try:
                # Find the index of 'ODI' in headers (e.g., index 2)
                odi_index = header_list.index('ODI')
            except ValueError:
                centuries_list.append(0)
                continue
            
            # FIX 2: Navigate the table-style JSON
            # We need to find the dictionary where the first value in 'values' is '100s'
            stats_rows = career_data.get('values', [])
            hundreds = 0
            
            for row in stats_rows:
                row_values = row.get('values', [])
                if row_values[0] == '100s':
                    # Grab the value at the same index where 'ODI' was found
                    hundreds = row_values[odi_index]
                    break
            
            centuries_list.append(hundreds)
            print(f"ID {pid}: {hundreds} Centuries found.")
            
        else:
            print(f"Failed to fetch ID {pid}: Status {res.status_code}")
            centuries_list.append(0)
            
    except Exception as e:
        print(f"Error processing ID {pid}: {e}")
        centuries_list.append(0)
    
    time.sleep(1)

# Add to your dataframe
top_10_odi['Centuries'] = centuries_list
print(top_10_odi[['playerID', 'Player', 'Centuries']])

Extracting centuries from player career endpoints...
ID 25: 49 Centuries found.
ID 1413: 54 Centuries found.
ID 576: 33 Centuries found.
ID 29: 22 Centuries found.
ID 27: 12 Centuries found.
ID 265: 10 Centuries found.
ID 3864: 7 Centuries found.
ID 69: 14 Centuries found.
ID 26: 15 Centuries found.
ID 1446: 17 Centuries found.
ID 413: 5 Centuries found.
ID 3898: 6 Centuries found.
ID 308: 11 Centuries found.
ID 3874: 6 Centuries found.
ID 3850: 4 Centuries found.
ID 3838: 1 Centuries found.
ID 3832: 1 Centuries found.
ID 8733: 8 Centuries found.
ID 3849: 4 Centuries found.
ID 3817: 1 Centuries found.
   playerID        Player Centuries
0        25     Tendulkar        49
1      1413   Virat Kohli        54
2       576  Rohit Sharma        33
3        29     S Ganguly        22
4        27        Dravid        12
5       265         Dhoni        10
6      3864  M Azharuddin         7
7        69        Yuvraj        14
8        26        Sehwag        15
9      1446        Dhawan        17
10      413         Raina         5
11     3898      A Jadeja         6
12      308       Gambhir        11
13     3874       N Sidhu         6
14     3850   K Srikkanth         4
15     3838         K Dev         1
16     3832  D Vengsarkar         1
17     8733         Rahul         8
18     3849     R Shastri         4
19     3817    S Gavaskar         1

In [82]:
top_10_odi['Centuries'] = centuries_list

# Display the final results
print("\n--- Top 10 ODI Scorers with Career Centuries ---")
print(top_10_odi[['playerID', 'Player', 'Runs', 'Avg', 'Centuries']].to_string(index=False))

--- Top 10 ODI Scorers with Career Centuries ---
playerID       Player  Runs   Avg Centuries
      25    Tendulkar 18426 44.83        49
    1413  Virat Kohli 14797 58.72        54
     576 Rohit Sharma 11577 48.85        33
      29    S Ganguly 11221 40.95        22
      27       Dravid 10768 39.16        12
     265        Dhoni 10599 50.23        10
    3864 M Azharuddin  9378 36.92         7
      69       Yuvraj  8609 36.48        14
      26       Sehwag  7995 35.38        15
    1446       Dhawan  6793 44.11        17
     413        Raina  5615 35.31         5
    3898     A Jadeja  5359 37.48         6
     308      Gambhir  5238 39.68        11
    3874      N Sidhu  4413 37.08         6
    3850  K Srikkanth  4091 29.01         4
    3838        K Dev  3783 23.79         1
    3832 D Vengsarkar  3508 34.73         1
    8733        Rahul  3360 50.91         8
    3849    R Shastri  3108 29.05         4
    3817   S Gavaskar  3092 35.14         1

In [83]:
import urllib.parse
from sqlalchemy import create_engine

# 1. Encode the special character in password
password = urllib.parse.quote_plus("deepika@88")

# 2. Use the encoded password in your connection string
# Also, ensure 'username' is replaced with your actual DB user (usually 'postgres')
engine = create_engine(f'postgresql+psycopg2://postgres:{password}@localhost:5432/cricbuzz')

# 3. Test the connection and push the data
top_10_odi.to_sql('testdata', engine, if_exists='replace', index=False)

print("✅ Connection successful and table 'top10_odi' created!")

✅ Connection successful and table 'top10_odi' created!

In [108]:
venue_ids = [m.get('matchInfo', {}).get('venueInfo', {}).get('id') for tm in match_list1.get('typeMatches', []) for sm in tm.get('seriesMatches', []) for m in sm.get('seriesAdWrapper', {}).get('matches', []) if m.get('matchInfo', {}).get('venueInfo', {}).get('id')]

print(venue_ids)

[31, 51, 254, 15, 11, 50, 15, 254, 474, 474, 474, 474, 474, 474, 474, 474, 454, 454, 454, 454, 329, 206, 75, 88, 73, 148, 72, 1193, 135, 367, 72, 148, 1193, 371, 418, 44, 94, 94, 94, 39, 39, 300, 101, 101, 101, 74, 75, 100, 100, 100]

In [ ]:
venue_ids = [m.get('matchInfo', {}).get('venueInfo', {}).get('id') for tm in match_list1.get('typeMatches', []) for sm in tm.get('seriesMatches', []) for m in sm.get('seriesAdWrapper', {}).get('matches', []) if m.get('matchInfo', {}).get('venueInfo', {}).get('id')]

print(venue_ids)

# Q4 venue details

In [142]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/venues/v1/454"

headers = {
	"x-rapidapi-key": "87cb73cb75msh7a5d872ecde1a59p1feac0jsne6c94486f484",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

ground = response.json()

In [143]:
ground

{'ground': 'Mission Road Ground',
 'city': 'Mong Kok',
 'country': 'Hong Kong',
 'timezone': '+08:00',
 'established': 1976,
 'capacity': '3500',
 'knownAs': 'Tin Kwong Road Recreation Ground',
 'homeTeam': 'Hong Kong',
 'imageUrl': 'http://i.cricketcb.com/i/stats/fth/540x303/venue/images/454.jpg',
 'imageId': '189174'}

In [144]:
import pandas as pd
# Convert the nested list into a clean DataFrame
venue1 = []
det_g =  {
    # Flattening Venue
"venue_ground": ground.get('ground'), # Removed .get('venueinfo')
    "city": ground.get('city'),
    "country": ground.get('country'),
    "capacity": ground.get('capacity'),
    #"stadium_name": ground.get('knownAs')
   
}

venue1.append(det_g)
# 2. Convert to DataFrame
df_ven_info = pd.DataFrame(venue1)

# 3. Fix the NameError: use 'match_get_info' instead of 'getmatch_info'
# df_ven['startdate'] = pd.to_datetime(ground.get('startdate'), unit='ms')
# df_ven['enddate'] = pd.to_datetime(ground.get('enddate'), unit='ms')

print(df_ven_info)

          venue_ground      city    country capacity
0  Mission Road Ground  Mong Kok  Hong Kong     3500

In [145]:
import urllib.parse
from sqlalchemy import create_engine

# 1. Encode the special character in password
password = urllib.parse.quote_plus("deepika@88")

# 2. Use the encoded password in your connection string
# Also, ensure 'username' is replaced with your actual DB user (usually 'postgres')
engine = create_engine(f'postgresql+psycopg2://postgres:{password}@localhost:5432/cricbuzz')

# 3. Test the connection and push the data
df_ven_info.to_sql('Q4_venu', engine, if_exists='append', index=False)

print("✅ Connection successful and table 'venu info' updated!")

✅ Connection successful and table 'venu info' updated!

# Q7 the highest individual batting score achieved in each cricket format

ODI scores

In [148]:
import pandas as pd

# 1. Extract the list of values
# Using .get() is safer to avoid KeyErrors
odivalues = allplayers.get('values', []) 

# 2. Define the match type
selected_match_type = "ODI"

# 3. Create the DataFrame using the 6 base columns
columns = ['playerID', 'Player', 'Matches', 'Innings', 'Runs', 'Avg']
df_val = pd.DataFrame([item['values'] for item in odivalues], columns=columns)

# 4. ADD THE NEW COLUMN TO THE DATAFRAME
# This ensures every row in the table has "ODI" attached to it
df_val['selectedMatchType'] = selected_match_type

# 5. Data Cleaning: Convert 'Runs' and 'Avg' to numeric
# errors='coerce' turns non-numeric values (like '-') into NaN (Not a Number)
df_val['Runs'] = pd.to_numeric(df_val['Runs'], errors='coerce')
df_val['Avg'] = pd.to_numeric(df_val['Avg'], errors='coerce')

# 6. Sort by Runs (All rows included)
all_odi_players = df_val.sort_values(by='Runs', ascending=False)

# 7. Print all data
print(all_odi_players)

   playerID        Player Matches Innings   Runs    Avg selectedMatchType
0        25     Tendulkar     463     452  18426  44.83               ODI
1      1413   Virat Kohli     311     299  14797  58.72               ODI
2       576  Rohit Sharma     282     274  11577  48.85               ODI
3        29     S Ganguly     308     297  11221  40.95               ODI
4        27        Dravid     340     314  10768  39.16               ODI
5       265         Dhoni     347     294  10599  50.23               ODI
6      3864  M Azharuddin     334     308   9378  36.92               ODI
7        69        Yuvraj     301     275   8609  36.48               ODI
8        26        Sehwag     241     235   7995  35.38               ODI
9      1446        Dhawan     167     164   6793  44.11               ODI
10      413         Raina     226     194   5615  35.31               ODI
11     3898      A Jadeja     196     179   5359  37.48               ODI
12      308       Gambhir     147     143   5238  39.68               ODI
13     3874       N Sidhu     136     127   4413  37.08               ODI
14     3850   K Srikkanth     146     145   4091  29.01               ODI
15     3838         K Dev     225     198   3783  23.79               ODI
16     3832  D Vengsarkar     129     120   3508  34.73               ODI
17     8733         Rahul      94      86   3360  50.91               ODI
18     3849     R Shastri     150     128   3108  29.05               ODI
19     3817    S Gavaskar     108     102   3092  35.14               ODI

Test data

In [161]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/team/2"

# here the matchtype =2 its indicates 'odi'
querystring = {"statsType":"mostRuns","matchType":"1"}

headers = {
	"x-rapidapi-key": "87cb73cb75msh7a5d872ecde1a59p1feac0jsne6c94486f484",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

testplayers = response.json()

In [162]:
print(testplayers.keys())

dict_keys(['filter', 'headers', 'values', 'appIndex'])

In [163]:
testplayers['filter']

{'matchtype': [{'matchTypeId': '1', 'matchTypeDesc': 'test'},
  {'matchTypeId': '2', 'matchTypeDesc': 'odi'},
  {'matchTypeId': '3', 'matchTypeDesc': 't20i'}],
 'team': [{'id': '58', 'teamShortName': 'CSK'},
  {'id': '97', 'teamShortName': 'INDW'},
  {'id': '61', 'teamShortName': 'DC'},
  {'id': '65', 'teamShortName': 'PBKS'},
  {'id': '63', 'teamShortName': 'KKR'},
  {'id': '62', 'teamShortName': 'MI'},
  {'id': '59', 'teamShortName': 'RCB'},
  {'id': '64', 'teamShortName': 'RR'},
  {'id': '255', 'teamShortName': 'SRH'},
  {'id': '971', 'teamShortName': 'GT'},
  {'id': '966', 'teamShortName': 'LSG'},
  {'id': '510', 'teamShortName': 'BTS'},
  {'id': '506', 'teamShortName': 'VANW'},
  {'id': '507', 'teamShortName': 'SKRW'},
  {'id': '496', 'teamShortName': 'BELW'},
  {'id': '508', 'teamShortName': 'DENW'},
  {'id': '509', 'teamShortName': 'SINW'},
  {'id': '518', 'teamShortName': 'AFGU23'},
  {'id': '517', 'teamShortName': 'SIND'},
  {'id': '516', 'teamShortName': 'RJP'},
  {'id': '515', 'teamShortName': 'PL'},
  {'id': '514', 'teamShortName': 'PAKHT'},
  {'id': '513', 'teamShortName': 'NW'},
  {'id': '512', 'teamShortName': 'MA'},
  {'id': '511', 'teamShortName': 'KKS'},
  {'id': '505', 'teamShortName': 'OMANW'},
  {'id': '504', 'teamShortName': 'GERW'},
  {'id': '503', 'teamShortName': 'NAMW'},
  {'id': '490', 'teamShortName': 'SLEW'},
  {'id': '489', 'teamShortName': 'ARGW'},
  {'id': '488', 'teamShortName': 'BWAW'},
  {'id': '487', 'teamShortName': 'JPNW'},
  {'id': '486', 'teamShortName': 'CHNW'},
  {'id': '485', 'teamShortName': 'QATW'},
  {'id': '484', 'teamShortName': 'IDNW'},
  {'id': '483', 'teamShortName': 'TANW'},
  {'id': '491', 'teamShortName': 'BRAW'},
  {'id': '492', 'teamShortName': 'FRAW'},
  {'id': '493', 'teamShortName': 'MOZW'},
  {'id': '502', 'teamShortName': 'HKC W'},
  {'id': '501', 'teamShortName': 'KENW'},
  {'id': '500', 'teamShortName': 'SWZW'},
  {'id': '499', 'teamShortName': 'LSOW'},
  {'id': '498', 'teamShortName': 'PERW'},
  {'id': '497', 'teamShortName': 'CHLW'},
  {'id': '495', 'teamShortName': 'MWIW'},
  {'id': '494', 'teamShortName': 'ZMBW'},
  {'id': '482', 'teamShortName': 'WSMW'},
  {'id': '519', 'teamShortName': 'INDU19A'},
  {'id': '520', 'teamShortName': 'INDU19B'},
  {'id': '540', 'teamShortName': 'BLZ'},
  {'id': '541', 'teamShortName': 'BEL'},
  {'id': '542', 'teamShortName': 'PER'},
  {'id': '543', 'teamShortName': 'BHR'},
  {'id': '544', 'teamShortName': 'MEX'},
  {'id': '545', 'teamShortName': 'WSM'},
  {'id': '546', 'teamShortName': 'PAN'},
  {'id': '547', 'teamShortName': 'JPN'},
  {'id': '548', 'teamShortName': 'CRI'},
  {'id': '549', 'teamShortName': 'ARG'},
  {'id': '550', 'teamShortName': 'HUN'},
  {'id': '551', 'teamShortName': 'MOZ'},
  {'id': '552', 'teamShortName': 'CHL'},
  {'id': '553', 'teamShortName': 'MWI'},
  {'id': '554', 'teamShortName': 'ISR'},
  {'id': '555', 'teamShortName': 'BTN'},
  {'id': '556', 'teamShortName': 'FIN'},
  {'id': '539', 'teamShortName': 'FRA'},
  {'id': '538', 'teamShortName': 'PHI'},
  {'id': '521', 'teamShortName': 'ESTXI'},
  {'id': '522', 'teamShortName': 'Malta'},
  {'id': '523', 'teamShortName': 'ESP'},
  {'id': '524', 'teamShortName': 'CHN'},
  {'id': '525', 'teamShortName': 'QAT'},
  {'id': '526', 'teamShortName': 'EST'},
  {'id': '527', 'teamShortName': 'ITA'},
  {'id': '528', 'teamShortName': 'ZIMCXI'},
  {'id': '529', 'teamShortName': 'BW'},
  {'id': '530', 'teamShortName': 'VEL'},
  {'id': '531', 'teamShortName': 'GH'},
  {'id': '532', 'teamShortName': 'AUT'},
  {'id': '533', 'teamShortName': 'GGY'},
  {'id': '534', 'teamShortName': 'SWE'},
  {'id': '535', 'teamShortName': 'TAN'},
  {'id': '536', 'teamShortName': 'NGA'},
  {'id': '537', 'teamShortName': 'LUX'},
  {'id': '557', 'teamShortName': 'IOM'},
  {'id': '404', 'teamShortName': 'MCCWXI'},
  {'id': '425', 'teamShortName': 'WXI'},
  {'id': '426', 'teamShortName': 'BZ'},
  {'id': '427', 'teamShortName': 'BLCB'},
  {'id': '428', 'teamShortName': 'CTKR'},
  {'id': '429', 'teamShortName': 'DW'},
  {'id': '430', 'teamShortName': 'JG'},
  {'id': '431', 'teamShortName': 'NMBS'},
  {'id': '432', 'teamShortName': 'PM'},
  {'id': '433', 'teamShortName': 'SK'},
  {'id': '434', 'teamShortName': 'SYL'},
  {'id': '435', 'teamShortName': 'IREA'},
  {'id': '436', 'teamShortName': 'WAXI'},
  {'id': '437', 'teamShortName': 'MS'},
  {'id': '438', 'teamShortName': 'HKIU'},
  {'id': '439', 'teamShortName': 'SAEW'},
  {'id': '440', 'teamShortName': 'INDWA'},
  {'id': '441', 'teamShortName': 'COL'},
  {'id': '424', 'teamShortName': 'KENU19'},
  {'id': '423', 'teamShortName': 'BLB'},
  {'id': '405', 'teamShortName': 'INDU23'},
  {'id': '406', 'teamShortName': 'PAKU23'},
  {'id': '407', 'teamShortName': 'SLU23'},
  {'id': '408', 'teamShortName': 'BANU23'},
  {'id': '410', 'teamShortName': 'Trichy'},
  {'id': '411', 'teamShortName': 'SIKAR'},
  {'id': '412', 'teamShortName': 'UDE'},
  {'id': '413', 'teamShortName': 'JAIPUR'},
  {'id': '414', 'teamShortName': 'JL'},
  {'id': '415', 'teamShortName': 'BWS'},
  {'id': '416', 'teamShortName': 'APS'},
  {'id': '417', 'teamShortName': 'SV'},
  {'id': '418', 'teamShortName': 'WS'},
  {'id': '419', 'teamShortName': 'YD'},
  {'id': '420', 'teamShortName': 'LT'},
  {'id': '421', 'teamShortName': 'LBL'},
  {'id': '422', 'teamShortName': 'SST'},
  {'id': '442', 'teamShortName': 'KAN'},
  {'id': '443', 'teamShortName': 'GAL'},
  {'id': '444', 'teamShortName': 'DAM'},
  {'id': '464', 'teamShortName': 'NGL'},
  {'id': '465', 'teamShortName': 'PDC'},
  {'id': '466', 'teamShortName': 'SKM'},
  {'id': '467', 'teamShortName': 'UTK'},
  {'id': '468', 'teamShortName': 'ARNP'},
  {'id': '469', 'teamShortName': 'HKCU19'},
  {'id': '470', 'teamShortName': 'KZ'},
  {'id': '471', 'teamShortName': 'PP'},
  {'id': '472', 'teamShortName': 'KDK'},
  {'id': '473', 'teamShortName': 'NL'},
  {'id': '474', 'teamShortName': 'BL'},
  {'id': '475', 'teamShortName': 'CTB'},
  {'id': '476', 'teamShortName': 'DH'},
  {'id': '477', 'teamShortName': 'JS'},
  {'id': '478', 'teamShortName': 'NMBG'},
  {'id': '479', 'teamShortName': 'PLR'},
  {'id': '480', 'teamShortName': 'TSP'},
  {'id': '463', 'teamShortName': 'MIZ'},
  {'id': '462', 'teamShortName': 'MGLY'},
  {'id': '445', 'teamShortName': 'MLYW'},
  {'id': '446', 'teamShortName': 'TRL'},
  {'id': '447', 'teamShortName': 'SPN'},
  {'id': '448', 'teamShortName': 'UGAW'},
  {'id': '449', 'teamShortName': 'UAEW'},
  {'id': '450', 'teamShortName': 'TTN'},
  {'id': '451', 'teamShortName': 'MNT'},
  {'id': '452', 'teamShortName': 'EDR'},
  {'id': '453', 'teamShortName': 'VCK'},
  {'id': '454', 'teamShortName': 'WPH'},
  {'id': '455', 'teamShortName': 'VKV'},
  {'id': '456', 'teamShortName': 'CWIB'},
  {'id': '457', 'teamShortName': 'INDWR'},
  {'id': '458', 'teamShortName': 'INDWB'},
  {'id': '459', 'teamShortName': 'INDWG'},
  {'id': '460', 'teamShortName': 'BIH'},
  {'id': '461', 'teamShortName': 'MNP'},
  {'id': '481', 'teamShortName': 'INDC'},
  {'id': '558', 'teamShortName': 'BGR'},
  {'id': '657', 'teamShortName': 'PTXI'},
  {'id': '770', 'teamShortName': 'TV'},
  {'id': '775', 'teamShortName': 'AUTW'},
  {'id': '779', 'teamShortName': 'FINXI'},
  {'id': '784', 'teamShortName': 'CUMXI'},
  {'id': '789', 'teamShortName': 'CLK'},
  {'id': '794', 'teamShortName': 'DVK'},
  {'id': '799', 'teamShortName': 'GGD'},
  {'id': '800', 'teamShortName': 'JST'},
  {'id': '805', 'teamShortName': 'KDT'},
  {'id': '807', 'teamShortName': 'BRSAL'},
  {'id': '812', 'teamShortName': 'KHULN'},
  {'id': '817', 'teamShortName': 'RJSHI'},
  {'id': '822', 'teamShortName': 'CTGRM'},
  {'id': '827', 'teamShortName': 'DHAKA'},
  {'id': '832', 'teamShortName': 'Root'},
  {'id': '838', 'teamShortName': 'NZWXI'},
  {'id': '843', 'teamShortName': 'BANE'},
  {'id': '768', 'teamShortName': 'TC'},
  {'id': '763', 'teamShortName': 'TR'},
  {'id': '666', 'teamShortName': 'GCXI'},
  {'id': '675', 'teamShortName': 'IRN'},
  {'id': '682', 'teamShortName': 'INDL'},
  {'id': '691', 'teamShortName': 'WIL'},
  {'id': '700', 'teamShortName': 'AUSL'},
  {'id': '709', 'teamShortName': 'SLL'},
  {'id': '718', 'teamShortName': 'RSAL'},
  {'id': '720', 'teamShortName': 'RWAW'},
  {'id': '729', 'teamShortName': 'SLCXI'},
  {'id': '733', 'teamShortName': 'WIHOXI'},
  {'id': '738', 'teamShortName': 'WIBRXI'},
  {'id': '743', 'teamShortName': 'TS'},
  {'id': '748', 'teamShortName': 'TBR'},
  {'id': '749', 'teamShortName': 'PAKWT'},
  {'id': '754', 'teamShortName': 'PAKGR'},
  {'id': '758', 'teamShortName': 'TMG'},
  {'id': '759', 'teamShortName': 'TMO'},
  {'id': '848', 'teamShortName': 'BANL'},
  {'id': '853', 'teamShortName': 'ENGL'},
  {'id': '861', 'teamShortName': 'ITT'},
  {'id': '928', 'teamShortName': 'ROCKS'},
  {'id': '933', 'teamShortName': 'ESTORM'},
  {'id': '941', 'teamShortName': 'CBJ'},
  {'id': '943', 'teamShortName': 'CLS'},
  {'id': '946', 'teamShortName': 'DAS'},
  {'id': '948', 'teamShortName': 'JKS'},
  {'id': '953', 'teamShortName': 'KDW'},
  {'id': '956', 'teamShortName': 'UGAU19'},
  {'id': '961', 'teamShortName': 'INDWD'},
  {'id': '976', 'teamShortName': 'MGD'},
  {'id': '981', 'teamShortName': 'SYSR'},
  {'id': '986', 'teamShortName': 'IMR'},
  {'id': '991', 'teamShortName': 'ALN'},
  {'id': '996', 'teamShortName': 'WGS'},
  {'id': '1011', 'teamShortName': 'BAW'},
  {'id': '1018', 'teamShortName': 'BHM'},
  {'id': '1020', 'teamShortName': 'CAYM'},
  {'id': '927', 'teamShortName': 'ECAPE'},
  {'id': '923', 'teamShortName': 'NCAPE'},
  {'id': '866', 'teamShortName': 'NRK'},
  {'id': '867', 'teamShortName': 'SLST'},
  {'id': '872', 'teamShortName': 'TLAT'},
  {'id': '876', 'teamShortName': 'TWS'},
  {'id': '881', 'teamShortName': 'ZIMSXI'},
  {'id': '886', 'teamShortName': 'PCCSXI'},
  {'id': '1032', 'teamShortName': 'JERW'},
  {'id': '887', 'teamShortName': 'A1'},
  {'id': '892', 'teamShortName': 'A2'},
  {'id': '897', 'teamShortName': 'TKY'},
  {'id': '902', 'teamShortName': 'TRKW'},
  {'id': '903', 'teamShortName': 'MPR'},
  {'id': '908', 'teamShortName': 'TUSKS'},
  {'id': '912', 'teamShortName': 'LIMPO'},
  {'id': '917', 'teamShortName': 'WPR'},
  {'id': '918', 'teamShortName': 'GRB'},
  {'id': '922', 'teamShortName': 'NWEST'},
  {'id': '1027', 'teamShortName': 'NOR'},
  {'id': '559', 'teamShortName': 'SLE'},
  {'id': '579', 'teamShortName': 'TKMNE'},
  {'id': '580', 'teamShortName': 'ETS'},
  {'id': '581', 'teamShortName': 'NMP'},
  {'id': '582', 'teamShortName': 'SBS'},
  {'id': '583', 'teamShortName': 'SPL'},
  {'id': '584', 'teamShortName': 'NBB'},
  {'id': '585', 'teamShortName': 'AA'},
  {'id': '586', 'teamShortName': 'SOL'},
  {'id': '587', 'teamShortName': 'GGS'},
  {'id': '588', 'teamShortName': 'HHS'},
  {'id': '589', 'teamShortName': 'ZR'},
  {'id': '590', 'teamShortName': 'KUTW'},
  {'id': '591', 'teamShortName': 'BTW'},
  {'id': '592', 'teamShortName': 'USAW'},
  {'id': '593', 'teamShortName': 'KUWU19'},
  {'id': '594', 'teamShortName': 'INDWBPXI'},
  {'id': '595', 'teamShortName': 'CDG'},
  {'id': '578', 'teamShortName': 'ATMWS'},
  {'id': '577', 'teamShortName': 'BFT'},
  {'id': '560', 'teamShortName': 'BRAZIL'},
  {'id': '561', 'teamShortName': 'CZE'},
  {'id': '562', 'teamShortName': 'SHN'},
  {'id': '563', 'teamShortName': 'MDV'},
  {'id': '564', 'teamShortName': 'GIB'},
  {'id': '565', 'teamShortName': 'MMR'},
  {'id': '566', 'teamShortName': 'IDN'},
  {'id': '567', 'teamShortName': 'GM'},
  {'id': '568', 'teamShortName': 'SWZ'},
  {'id': '569', 'teamShortName': 'RWA'},
  {'id': '570', 'teamShortName': 'LSO'},
  {'id': '571', 'teamShortName': 'SAU'},
  {'id': '572', 'teamShortName': 'ADK'},
  {'id': '573', 'teamShortName': 'RDR'},
  {'id': '574', 'teamShortName': 'EBR'},
  {'id': '575', 'teamShortName': 'GGG'},
  {'id': '576', 'teamShortName': 'DBC'},
  {'id': '596', 'teamShortName': 'PORT'},
  {'id': '597', 'teamShortName': 'DEG'},
  {'id': '598', 'teamShortName': 'UBL'},
  {'id': '618', 'teamShortName': 'TREW'},
  {'id': '619', 'teamShortName': 'SULW'},
  {'id': '620', 'teamShortName': 'SOUW'},
  {'id': '621', 'teamShortName': 'SLT'},
  {'id': '622', 'teamShortName': 'CGC'},
  {'id': '623', 'teamShortName': 'CW'},
  {'id': '624', 'teamShortName': 'RPR'},
  {'id': '625', 'teamShortName': 'DP'},
  {'id': '626', 'teamShortName': 'RSR'},
  {'id': '627', 'teamShortName': 'KLT'},
  {'id': '628', 'teamShortName': 'FLH'},
  {'id': '629', 'teamShortName': 'FYO'},
  {'id': '630', 'teamShortName': 'DSR'},
  {'id': '631', 'teamShortName': 'PGR'},
  {'id': '632', 'teamShortName': 'HSR'},
  {'id': '633', 'teamShortName': 'SGP'},
  {'id': '639', 'teamShortName': 'INDWC'},
  {'id': '617', 'teamShortName': 'MSGW'},
  {'id': '616', 'teamShortName': 'LDNW'},
  {'id': '599', 'teamShortName': 'QLD'},
  {'id': '600', 'teamShortName': 'BGT'},
  {'id': '601', 'teamShortName': 'AD'},
  {'id': '602', 'teamShortName': 'PD'},
  {'id': '603', 'teamShortName': 'JPNU19'},
  {'id': '604', 'teamShortName': 'NGAU19'},
  {'id': '605', 'teamShortName': 'MIL'},
  {'id': '606', 'teamShortName': 'WEF'},
  {'id': '607', 'teamShortName': 'BRM'},
  {'id': '608', 'teamShortName': 'LDN'},
  {'id': '609', 'teamShortName': 'MSG'},
  {'id': '610', 'teamShortName': 'SUL'},
  {'id': '611', 'teamShortName': 'SOU'},
  {'id': '612', 'teamShortName': 'TRE'},
  {'id': '613', 'teamShortName': 'MILW'},
  {'id': '614', 'teamShortName': 'WELW'},
  {'id': '615', 'teamShortName': 'BRMW'},
  {'id': '648', 'teamShortName': 'INDIAWB'},
  {'id': '403', 'teamShortName': 'SOUTH'},
  {'id': '149', 'teamShortName': 'GLAM'},
  {'id': '170', 'teamShortName': 'BRD'},
  {'id': '171', 'teamShortName': 'RAJ'},
  {'id': '172', 'teamShortName': 'SLU19'},
  {'id': '173', 'teamShortName': 'ENGU19'},
  {'id': '183', 'teamShortName': 'PWI'},
  {'id': '184', 'teamShortName': 'KTK'},
  {'id': '185', 'teamShortName': 'DEN'},
  {'id': '186', 'teamShortName': 'AKL'},
  {'id': '187', 'teamShortName': 'RUH'},
  {'id': '188', 'teamShortName': 'NEDW'},
  {'id': '189', 'teamShortName': 'IREW'},
  {'id': '190', 'teamShortName': 'SIN'},
  {'id': '191', 'teamShortName': 'CACXI'},
  {'id': '192', 'teamShortName': 'SYT'},
  {'id': '193', 'teamShortName': 'BRH'},
  {'id': '194', 'teamShortName': 'HBH'},
  {'id': '195', 'teamShortName': 'MLR'},
  {'id': '168', 'teamShortName': 'NCC'},
  {'id': '167', 'teamShortName': 'MP'},
  {'id': '150', 'teamShortName': 'KENT'},
  {'id': '151', 'teamShortName': 'GLOUCS'},
  {'id': '152', 'teamShortName': 'ESS'},
  {'id': '153', 'teamShortName': 'HAM'},
  {'id': '154', 'teamShortName': 'SLCPXI'},
  {'id': '155', 'teamShortName': 'WAR'},
  {'id': '156', 'teamShortName': 'CEN'},
  {'id': '157', 'teamShortName': 'LIONS'},
  {'id': '158', 'teamShortName': 'SAUS'},
  {'id': '159', 'teamShortName': 'GAW'},
  {'id': '160', 'teamShortName': 'EA'},
  {'id': '161', 'teamShortName': 'NAM'},
  {'id': '162', 'teamShortName': 'ASM'},
  {'id': '163', 'teamShortName': 'GUJ'},
  {'id': '164', 'teamShortName': 'QL'},
  {'id': '165', 'teamShortName': 'ECBXI'},
  {'id': '166', 'teamShortName': 'TAS'},
  {'id': '196', 'teamShortName': 'MLS'},
  {'id': '197', 'teamShortName': 'PRS'},
  {'id': '198', 'teamShortName': 'SYS'},
  {'id': '223', 'teamShortName': 'AFGU19'},
  {'id': '224', 'teamShortName': 'BANU19'},
  {'id': '226', 'teamShortName': 'IREU19'},
  {'id': '228', 'teamShortName': 'SCOU19'},
  {'id': '229', 'teamShortName': 'NPLU19'},
  {'id': '230', 'teamShortName': 'NAMU19'},
  {'id': '231', 'teamShortName': 'INDB'},
  {'id': '232', 'teamShortName': 'BEN'},
  {'id': '233', 'teamShortName': 'NZONE'},
  {'id': '234', 'teamShortName': 'WZONE'},
  {'id': '235', 'teamShortName': 'EZONE'},
  {'id': '236', 'teamShortName': 'SZONE'},
  {'id': '237', 'teamShortName': 'CZONE'},
  {'id': '238', 'teamShortName': 'PASXI'},
  {'id': '239', 'teamShortName': 'IWXI'},
  {'id': '240', 'teamShortName': 'MUMA'},
  {'id': '241', 'teamShortName': 'AP'},
  {'id': '222', 'teamShortName': 'PNGU19'},
  {'id': '221', 'teamShortName': 'ZIMU19'},
  {'id': '199', 'teamShortName': 'ADS'},
  {'id': '200', 'teamShortName': 'HAR'},
  {'id': '201', 'teamShortName': 'BB'},
  {'id': '202', 'teamShortName': 'CK'},
  {'id': '203', 'teamShortName': 'DG'},
  {'id': '204', 'teamShortName': 'DR'},
  {'id': '205', 'teamShortName': 'KRB'},
  {'id': '206', 'teamShortName': 'SR'},
  {'id': '207', 'teamShortName': 'WIA'},
  {'id': '208', 'teamShortName': 'BCD'},
  {'id': '209', 'teamShortName': 'KW'},
  {'id': '210', 'teamShortName': 'NN'},
  {'id': '211', 'teamShortName': 'RUR'},
  {'id': '212', 'teamShortName': 'UR'},
  {'id': '213', 'teamShortName': 'WU'},
  {'id': '214', 'teamShortName': 'UN'},
  {'id': '220', 'teamShortName': 'WIU19'},
  {'id': '242', 'teamShortName': 'HYD'},
  {'id': '148', 'teamShortName': 'SUR'},
  {'id': '2', 'teamShortName': 'IND'},
  {'id': '26', 'teamShortName': 'CAN'},
  {'id': '27', 'teamShortName': 'IRE'},
  {'id': '36', 'teamShortName': 'INDBLUE'},
  {'id': '41', 'teamShortName': 'SUS'},
  {'id': '42', 'teamShortName': 'ENGA'},
  {'id': '43', 'teamShortName': 'SLA'},
  {'id': '44', 'teamShortName': 'UGA'},
  {'id': '52', 'teamShortName': 'VIC'},
  {'id': '53', 'teamShortName': 'ACTXI'},
  {'id': '54', 'teamShortName': 'INDU19'},
  {'id': '55', 'teamShortName': 'NZU19'},
  {'id': '56', 'teamShortName': 'PAKU19'},
  {'id': '57', 'teamShortName': 'RSAU19'},
  {'id': '71', 'teamShortName': 'MLY'},
  {'id': '72', 'teamShortName': 'NEP'},
  {'id': '74', 'teamShortName': 'MDX'},
  {'id': '77', 'teamShortName': 'GER'},
  {'id': '25', 'teamShortName': 'BER'},
  {'id': '24', 'teamShortName': 'NED'},
  {'id': '3', 'teamShortName': 'PAK'},
  {'id': '4', 'teamShortName': 'AUS'},
  {'id': '5', 'teamShortName': 'SL'},
  {'id': '6', 'teamShortName': 'BAN'},
  {'id': '7', 'teamShortName': 'UAE'},
  {'id': '8', 'teamShortName': 'HKC'},
  {'id': '9', 'teamShortName': 'ENG'},
  {'id': '10', 'teamShortName': 'WI'},
  {'id': '11', 'teamShortName': 'RSA'},
  {'id': '12', 'teamShortName': 'ZIM'},
  {'id': '13', 'teamShortName': 'NZ'},
  {'id': '14', 'teamShortName': 'KEN'},
  {'id': '15', 'teamShortName': 'USA'},
  {'id': '18', 'teamShortName': 'INDSR'},
  {'id': '20', 'teamShortName': 'INDGREEN'},
  {'id': '21', 'teamShortName': 'INDRED'},
  {'id': '23', 'teamShortName': 'SCO'},
  {'id': '78', 'teamShortName': 'INDA'},
  {'id': '79', 'teamShortName': 'AUSA'},
  {'id': '80', 'teamShortName': 'NZA'},
  {'id': '105', 'teamShortName': 'OTG'},
  {'id': '119', 'teamShortName': 'SOM'},
  {'id': '122', 'teamShortName': 'MD'},
  {'id': '123', 'teamShortName': 'BP'},
  {'id': '125', 'teamShortName': 'BIJ'},
  {'id': '128', 'teamShortName': 'KAR'},
  {'id': '129', 'teamShortName': 'AUSU19'},
  {'id': '130', 'teamShortName': 'WIS'},
  {'id': '134', 'teamShortName': 'RGR'},
  {'id': '139', 'teamShortName': 'NOTTS'},
  {'id': '140', 'teamShortName': 'WARKS'},
  {'id': '141', 'teamShortName': 'DUR'},
  {'id': '142', 'teamShortName': 'NHNTS'},
  {'id': '143', 'teamShortName': 'LANCS'},
  {'id': '144', 'teamShortName': 'DERBY'},
  {'id': '145', 'teamShortName': 'LEIC'},
  {'id': '146', 'teamShortName': 'YORKS'},
  {'id': '104', 'teamShortName': 'NSW'},
  {'id': '103', 'teamShortName': 'WAY'},
  {'id': '81', 'teamShortName': 'DEL'},
  {'id': '82', 'teamShortName': 'ROI'},
  {'id': '84', 'teamShortName': 'TT'},
  {'id': '86', 'teamShortName': 'BPXI'},
  {'id': '87', 'teamShortName': 'WA'},
  {'id': '88', 'teamShortName': 'SKST'},
  {'id': '89', 'teamShortName': 'TIT'},
  {'id': '90', 'teamShortName': 'DOL'},
  {'id': '92', 'teamShortName': 'TN'},
  {'id': '93', 'teamShortName': 'UP'},
  {'id': '94', 'teamShortName': 'SAUR'},
  {'id': '95', 'teamShortName': 'MUM'},
  {'id': '96', 'teamShortName': 'AFG'},
  {'id': '98', 'teamShortName': 'NZW'},
  {'id': '99', 'teamShortName': 'ENGW'},
  {'id': '100', 'teamShortName': 'AUSW'},
  {'id': '101', 'teamShortName': 'COB'},
  {'id': '147', 'teamShortName': 'WORCS'},
  {'id': '323', 'teamShortName': 'BCBXI'},
  {'id': '347', 'teamShortName': 'HPCAXI'},
  {'id': '348', 'teamShortName': 'TNCAU17'},

In [164]:
import pandas as pd

# 1. Extract the list of values
# Using .get() is safer to avoid KeyErrors
testvalues = testplayers.get('values', []) 

# 2. Define the match type
selected_match_type1 = "Test"

# 3. Create the DataFrame using the 6 base columns
columns = ['playerID', 'Player', 'Matches', 'Innings', 'Runs', 'Avg']
df_val1 = pd.DataFrame([item['values'] for item in testvalues], columns=columns)

# 4. ADD THE NEW COLUMN TO THE DATAFRAME
# This ensures every row in the table has "Test" attached to it
df_val1['selectedMatchType'] = selected_match_type1

# 5. Data Cleaning: Convert 'Runs' and 'Avg' to numeric
# errors='coerce' turns non-numeric values (like '-') into NaN (Not a Number)
df_val1['Runs'] = pd.to_numeric(df_val1['Runs'], errors='coerce')
df_val1['Avg'] = pd.to_numeric(df_val1['Avg'], errors='coerce')

# 6. Sort by Runs (All rows included)
all_test_players = df_val1.sort_values(by='Runs', ascending=False)

# 7. Print all data
print(all_test_players)

   playerID           Player Matches Innings   Runs    Avg selectedMatchType
0        25        Tendulkar     200     329  15921  53.79              Test
1        27           Dravid     163     284  13265  52.64              Test
2      3817       S Gavaskar     125     214  10122  51.12              Test
3      1413      Virat Kohli     123     210   9230  46.85              Test
4        28         V Laxman     134     225   8781  45.97              Test
5        26           Sehwag     103     178   8503  49.44              Test
6        29        S Ganguly     113     188   7212  42.18              Test
7      1448           Pujara     103     176   7195  43.61              Test
8      3832     D Vengsarkar     116     185   6868  42.13              Test
9      3864     M Azharuddin      99     147   6215  45.04              Test
10     3823      G Viswanath      91     155   6080  41.93              Test
11     3838            K Dev     131     184   5248  31.05              Test
12     1447   Ajinkya Rahane      85     144   5077  38.46              Test
13      265            Dhoni      90     144   4876  38.09              Test
14     3827       M Amarnath      69     113   4378  42.50              Test
15      576     Rohit Sharma      67     116   4301  40.58              Test
16      308          Gambhir      58     104   4154  41.96              Test
17      587  Ravindra Jadeja      89     133   4095  38.27              Test
18     8733            Rahul      67     118   4053  35.87              Test
19     1597            Vijay      61     105   3982  38.29              Test

T20 data

In [170]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/team/2"

querystring = {"statsType":"mostRuns"}

headers = {
	"x-rapidapi-key": "edcc615a98msh9b529038adf520fp13b7cfjsnba97517d5849",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

t20players = response.json()

In [171]:
print(t20players.keys())

dict_keys(['filter', 'headers', 'values', 'appIndex'])

In [172]:
import pandas as pd

# 1. Extract the list of values
# Using .get() is safer to avoid KeyErrors
t20players = t20players.get('values', []) 

# 2. Define the match type
selected_match_type2 = "T20"

# 3. Create the DataFrame using the 6 base columns
columns = ['playerID', 'Player', 'Matches', 'Innings', 'Runs', 'Avg']
df_val2 = pd.DataFrame([item['values'] for item in t20players], columns=columns)

# 4. ADD THE NEW COLUMN TO THE DATAFRAME
# This ensures every row in the table has "Test" attached to it
df_val2['selectedMatchType'] = selected_match_type2

# 5. Data Cleaning: Convert 'Runs' and 'Avg' to numeric
# errors='coerce' turns non-numeric values (like '-') into NaN (Not a Number)
df_val2['Runs'] = pd.to_numeric(df_val2['Runs'], errors='coerce')
df_val2['Avg'] = pd.to_numeric(df_val2['Avg'], errors='coerce')

# 6. Sort by Runs (All rows included)
all_t20_players = df_val2.sort_values(by='Runs', ascending=False)

# 7. Print all data
print(all_t20_players)

   playerID           Player Matches Innings   Runs    Avg selectedMatchType
0        25        Tendulkar     200     329  15921  53.79               T20
1        27           Dravid     163     284  13265  52.64               T20
2      3817       S Gavaskar     125     214  10122  51.12               T20
3      1413      Virat Kohli     123     210   9230  46.85               T20
4        28         V Laxman     134     225   8781  45.97               T20
5        26           Sehwag     103     178   8503  49.44               T20
6        29        S Ganguly     113     188   7212  42.18               T20
7      1448           Pujara     103     176   7195  43.61               T20
8      3832     D Vengsarkar     116     185   6868  42.13               T20
9      3864     M Azharuddin      99     147   6215  45.04               T20
10     3823      G Viswanath      91     155   6080  41.93               T20
11     3838            K Dev     131     184   5248  31.05               T20
12     1447   Ajinkya Rahane      85     144   5077  38.46               T20
13      265            Dhoni      90     144   4876  38.09               T20
14     3827       M Amarnath      69     113   4378  42.50               T20
15      576     Rohit Sharma      67     116   4301  40.58               T20
16      308          Gambhir      58     104   4154  41.96               T20
17      587  Ravindra Jadeja      89     133   4095  38.27               T20
18     8733            Rahul      67     118   4053  35.87               T20
19     1597            Vijay      61     105   3982  38.29               T20

In [173]:
master_df = pd.concat([all_odi_players,all_test_players,all_t20_players],ignore_index=True)
print(master_df)

   playerID           Player Matches Innings   Runs    Avg selectedMatchType
0        25        Tendulkar     463     452  18426  44.83               ODI
1      1413      Virat Kohli     311     299  14797  58.72               ODI
2       576     Rohit Sharma     282     274  11577  48.85               ODI
3        29        S Ganguly     308     297  11221  40.95               ODI
4        27           Dravid     340     314  10768  39.16               ODI
5       265            Dhoni     347     294  10599  50.23               ODI
6      3864     M Azharuddin     334     308   9378  36.92               ODI
7        69           Yuvraj     301     275   8609  36.48               ODI
8        26           Sehwag     241     235   7995  35.38               ODI
9      1446           Dhawan     167     164   6793  44.11               ODI
10      413            Raina     226     194   5615  35.31               ODI
11     3898         A Jadeja     196     179   5359  37.48               ODI
12      308          Gambhir     147     143   5238  39.68               ODI
13     3874          N Sidhu     136     127   4413  37.08               ODI
14     3850      K Srikkanth     146     145   4091  29.01               ODI
15     3838            K Dev     225     198   3783  23.79               ODI
16     3832     D Vengsarkar     129     120   3508  34.73               ODI
17     8733            Rahul      94      86   3360  50.91               ODI
18     3849        R Shastri     150     128   3108  29.05               ODI
19     3817       S Gavaskar     108     102   3092  35.14               ODI
20       25        Tendulkar     200     329  15921  53.79              Test
21       27           Dravid     163     284  13265  52.64              Test
22     3817       S Gavaskar     125     214  10122  51.12              Test
23     1413      Virat Kohli     123     210   9230  46.85              Test
24       28         V Laxman     134     225   8781  45.97              Test
25       26           Sehwag     103     178   8503  49.44              Test
26       29        S Ganguly     113     188   7212  42.18              Test
27     1448           Pujara     103     176   7195  43.61              Test
28     3832     D Vengsarkar     116     185   6868  42.13              Test
29     3864     M Azharuddin      99     147   6215  45.04              Test
30     3823      G Viswanath      91     155   6080  41.93              Test
31     3838            K Dev     131     184   5248  31.05              Test
32     1447   Ajinkya Rahane      85     144   5077  38.46              Test
33      265            Dhoni      90     144   4876  38.09              Test
34     3827       M Amarnath      69     113   4378  42.50              Test
35      576     Rohit Sharma      67     116   4301  40.58              Test
36      308          Gambhir      58     104   4154  41.96              Test
37      587  Ravindra Jadeja      89     133   4095  38.27              Test
38     8733            Rahul      67     118   4053  35.87              Test
39     1597            Vijay      61     105   3982  38.29              Test
40       25        Tendulkar     200     329  15921  53.79               T20
41       27           Dravid     163     284  13265  52.64               T20
42     3817       S Gavaskar     125     214  10122  51.12               T20
43     1413      Virat Kohli     123     210   9230  46.85               T20
44       28         V Laxman     134     225   8781  45.97               T20
45       26           Sehwag     103     178   8503  49.44               T20
46       29        S Ganguly     113     188   7212  42.18               T20
47     1448           Pujara     103     176   7195  43.61               T20
48     3832     D Vengsarkar     116     185   6868  42.13               T20
49     3864     M Azharuddin      99     147   6215  45.04               T20
50     3823      G Viswanath      91     155   6080  41.93               T20
51     3838            K Dev     131     184   5248  31.05               T20
52     1447   Ajinkya Rahane      85     144   5077  38.46               T20
53      265            Dhoni      90     144   4876  38.09               T20
54     3827       M Amarnath      69     113   4378  42.50               T20
55      576     Rohit Sharma      67     116   4301  40.58               T20
56      308          Gambhir      58     104   4154  41.96               T20
57      587  Ravindra Jadeja      89     133   4095  38.27               T20
58     8733            Rahul      67     118   4053  35.87               T20
59     1597            Vijay      61     105   3982  38.29               T20

In [176]:
import urllib.parse
from sqlalchemy import create_engine

# 1. Encode the special character in password
password = urllib.parse.quote_plus("deepika@88")

# 2. Use the encoded password in your connection string
# Also, ensure 'username' is replaced with your actual DB user (usually 'postgres')
engine = create_engine(f'postgresql+psycopg2://postgres:{password}@localhost:5432/cricbuzz')

# 3. Test the connection and push the data
all_t20_players.to_sql('t20_mat', engine, if_exists='replace', index=False)

print("✅ Connection successful and table 't20 players' created!")

✅ Connection successful and table 't20 players' created!

# Q8 2024 cricket match list

In [10]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/series/v1/archives/international"

querystring = {"year":"2024"}

headers = {
	"x-rapidapi-key": "e6021fb984msh201af5139a6e2e9p149939jsn32edaa5716a4",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

matches2024_i = response.json()

In [11]:
matches2024_i

{'seriesMapProto': [{'date': '2024',
   'series': [{'id': 8553,
     'name': 'Sri Lanka tour of New Zealand, 2024-25',
     'startDt': '1734912000000',
     'endDt': '1736553600000',
     'thumborImageId': 379130},
    {'id': 9297,
     'name': 'Gulf Cricket T20I Championship, 2024',
     'startDt': '1734048000000',
     'endDt': '1734739200000',
     'thumborImageId': 379130},
    {'id': 8044,
     'name': 'Pakistan tour of South Africa, 2024 -25',
     'startDt': '1733788800000',
     'endDt': '1736208000000',
     'thumborImageId': 379130},
    {'id': 9171,
     'name': 'Afghanistan tour of Zimbabwe, 2024-25',
     'startDt': '1733702400000',
     'endDt': '1736121600000',
     'thumborImageId': 379130},
    {'id': 9265,
     'name': 'ICC Mens T20 World Cup Americas Sub Regional Qualifier, 2024',
     'startDt': '1733443200000',
     'endDt': '1734307200000',
     'thumborImageId': 379130},
    {'id': 9289,
     'name': 'Africa Continental Cup 2024',
     'startDt': '1733270400000',
     'endDt': '1734134400000',
     'thumborImageId': 379130},
    {'id': 8058,
     'name': 'Sri Lanka tour of South Africa, 2024',
     'startDt': '1732665600000',
     'endDt': '1733702400000',
     'thumborImageId': 379130},
    {'id': 8494,
     'name': 'Pakistan tour of Zimbabwe, 2024',
     'startDt': '1732406400000',
     'endDt': '1733356800000',
     'thumborImageId': 379130},
    {'id': 7853,
     'name': 'England tour of New Zealand, 2024',
     'startDt': '1732320000000',
     'endDt': '1734480000000',
     'thumborImageId': 379130},
    {'id': 9132,
     'name': 'ICC Mens T20 World Cup Africa Sub Regional Qualifier C 2024',
     'startDt': '1732320000000',
     'endDt': '1732752000000',
     'thumborImageId': 379130},
    {'id': 7745,
     'name': 'India tour of Australia, 2024-25',
     'startDt': '1732233600000',
     'endDt': '1736208000000',
     'thumborImageId': 379130},
    {'id': 9129,
     'name': 'ICC Mens T20 World Cup Asia Qualifier B 2024',
     'startDt': '1731974400000',
     'endDt': '1732752000000',
     'thumborImageId': 379130},
    {'id': 8116,
     'name': 'Bangladesh tour of West Indies, 2024',
     'startDt': '1731801600000',
     'endDt': '1734566400000',
     'thumborImageId': 379130},
    {'id': 9125,
     'name': 'Netherlands tour of Oman, 2024',
     'startDt': '1731456000000',
     'endDt': '1731715200000',
     'thumborImageId': 379130},
    {'id': 9146,
     'name': 'Myanmar tour of Indonesia, 2024',
     'startDt': '1731369600000',
     'endDt': '1731974400000',
     'thumborImageId': 379130},
    {'id': 9083,
     'name': 'New Zealand tour of Sri Lanka, 2024',
     'startDt': '1731110400000',
     'endDt': '1731974400000',
     'thumborImageId': 379130},
    {'id': 8404,
     'name': 'India tour of South Africa, 2024',
     'startDt': '1731024000000',
     'endDt': '1731628800000',
     'thumborImageId': 379130},
    {'id': 9091,
     'name': 'Afghanistan v Bangladesh in UAE, 2024',
     'startDt': '1730851200000',
     'endDt': '1731283200000',
     'thumborImageId': 379130},
    {'id': 7781,
     'name': 'Pakistan tour of Australia, 2024',
     'startDt': '1730592000000',
     'endDt': '1731801600000',
     'thumborImageId': 379130},
    {'id': 8107,
     'name': 'England tour of West Indies, 2024',
     'startDt': '1730332800000',
     'endDt': '1731801600000',
     'thumborImageId': 379130},
    {'id': 9157,
     'name': 'Bahrain in Uganda 2024',
     'startDt': '1730073600000',
     'endDt': '1730160000000',
     'thumborImageId': 379130},
    {'id': 9033,
     'name': 'South Africa tour of Bangladesh, 2024',
     'startDt': '1729468800000',
     'endDt': '1730505600000',
     'thumborImageId': 379130},
    {'id': 9041,
     'name': 'ICC Mens T20 World Cup Sub Regional Africa Qualifier Group B, 2024',
     'startDt': '1729296000000',
     'endDt': '1729728000000',
     'thumborImageId': 379130},
    {'id': 9025,
     'name': 'Quadrangular T20I Series in Bhutan, 2024',
     'startDt': '1729296000000',
     'endDt': '1729814400000',
     'thumborImageId': 379130},
    {'id': 9115,
     'name': 'Seychelles tour of Kenya, Only T20I',
     'startDt': '1729209600000',
     'endDt': '1729209600000',
     'thumborImageId': 379130},
    {'id': 9043,
     'name': 'Nepal tour of United States of America 2024',
     'startDt': '1729123200000',
     'endDt': '1729382400000',
     'thumborImageId': 379130},
    {'id': 8395,
     'name': 'New Zealand tour of India, 2024',
     'startDt': '1729036800000',
     'endDt': '1730764800000',
     'thumborImageId': 379130},
    {'id': 9009,
     'name': 'West Indies tour of Sri Lanka, 2024',
     'startDt': '1728777600000',
     'endDt': '1729900800000',
     'thumborImageId': 379130},
    {'id': 9057,
     'name': 'Rwanda tour of Malawi 2024',
     'startDt': '1728432000000',
     'endDt': '1728864000000',
     'thumborImageId': 379130},
    {'id': 8497,
     'name': 'England tour of Pakistan, 2024',
     'startDt': '1728259200000',
     'endDt': '1730073600000',
     'thumborImageId': 379130},
    {'id': 9017,
     'name': 'Serbia tour of Gibraltar, 2024',
     'startDt': '1727654400000',
     'endDt': '1727654400000',
     'thumborImageId': 379130},
    {'id': 8947,
     'name': 'Namibia T20I Tri-Series 2024',
     'startDt': '1727568000000',
     'endDt': '1728086400000',
     'thumborImageId': 379130},
    {'id': 8598,
     'name': 'ICC Mens T20 World Cup Sub Regional East Asia-Pacific Qualifier B, 2024',
     'startDt': '1727481600000',
     'endDt': '1728086400000',
     'thumborImageId': 379130},
    {'id': 8955,
     'name': 'Canada T20I Tri-Series 2024',
     'startDt': '1727481600000',
     'endDt': '1727913600000',
     'thumborImageId': 379130},
    {'id': 7981,
     'name': 'Ireland v South Africa in UAE, 2024',
     'startDt': '1727308800000',
     'endDt': '1728172800000',
     'thumborImageId': 379130},
    {'id': 8969,
     'name': 'T20I Tri-Series in South Korea, 2024',
     'startDt': '1727222400000',
     'endDt': '1727308800000',
     'thumborImageId': 379130},
    {'id': 8835,
     'name': 'ICC Mens T20 World Cup Africa Sub Regional Qualifier A 2024',
     'startDt': '1726876800000',
     'endDt': '1727308800000',
     'thumborImageId': 379130},
    {'id': 8393,
     'name': 'Bangladesh tour of India, 2024',
     'startDt': '1726704000000',
     'endDt': '1728691200000',
     'thumborImageId': 379130},
    {'id': 8818,
     'name': 'New Zealand tour of Sri Lanka, 2024',
     'startDt': '1726617600000',
     'endDt': '1727654400000',
     'thumborImageId': 379130},
    {'id': 8661,
     'name': 'Afghanistan v South Africa in UAE, 2024',
     'startDt': '1726617600000',
     'endDt': '1726963200000',
     'thumborImageId': 379130},
    {'id': 6794,
     'name': 'Australia tour of England, 2024',
     'startDt': '1726012800000',
     'endDt': '1727568000000',
     'thumborImageId': 379130},
    {'id': 8625,
     'name': 'Afghanistan v New Zealand in India, 2024',
     'startDt': '1725840000000',
     'endDt': '1726185600000',
     'thumborImageId': 379130},
    {'id': 8552,
     'name': 'Australia tour of Scotland, 2024',
     'startDt': '1725408000000',
     'endDt': '1725667200000',
     'thumborImageId': 379130},
    {'id': 8764,
     'name': 'ICC Mens T20 World Cup Asia Qualifier A 2024',
     'startDt': '1724976000000',
     'endDt': '1725840000000',
     'thumborImageId': 379130},
    {'id': 8632,
     'name': 'Netherlands T20I Tri-Series, 2024',
     'startDt': '1724371200000',
     'endDt': '1724803200000',
     'thumborImageId': 379130},
    {'id': 8596,
     'name': 'ICC Mens T20 World Cup Sub Regional Europe Qualifier C, 2024',
     'startDt': '1724198400000',
     'endDt': '1724803200000',
     'thumborImageId': 379130},
    {'id': 8495,
     'name': 'Bangladesh tour of Pakistan, 2024',
     'startDt': '1724198400000',
     'endDt': '1725321600000',
     'thumborImageId': 379130},
    {'id': 8686,
     'name': 'Malaysia T20I Tri Nations Cup, 2024',
     'startDt': '1724198400000',
     'endDt': '1724716800000',
     'thumborImageId': 379130},
    {'id': 8587,
     'name': 'ICC Mens T20 World Cup Sub Regional East Asia-Pacific Qualifier A, 2024',
     'startDt': '1723852800000',
     'endDt': '1724457600000',
     'thumborImageId': 379130},
    {'id': 6787,
     'name': 'Sri Lanka tour of England, 2024',
     'startDt': '1723593600000',
     'endDt': '1725926400000',
     'thumborImageId': 379130},
    {'id': 8578,
     'name': 'Spain tour of Croatia, 2024',
     'startDt': '1722556800000',
     'endDt': '1722902400000',
     'thumborImageId': 379130},
    {'id': 8238,
     'name': 'South Africa tour of West Indies, 2024',
     'startDt': '1722384000000',
     'endDt': '1724716800000',
     'thumborImageId': 379130},
    {'id': 8528,
     'name': 'India tour of Sri Lanka, 2024',
     'startDt': '1722038400000',
     'endDt': '1722988800000',
     'thumborImageId': 379130},
    {'id': 7979,
     'name': 'Zimbabwe tour of Ireland, 2024',
     'startDt': '1721865600000',
     'endDt': '1722211200000',
     'thumborImageId': 379130},
    {'id': 8476,
     'name': 'Nigeria tour of Kenya 2024',
     'startDt': '1720742400000',
     'endDt': '1721174400000',
     'thumborImageId': 379130},
    {'id': 8337,
     'name': 'ICC Mens T20 World Cup Sub Regional Europe Qualifier B, 2024',
     'startDt': '1720310400000',
     'endDt': '1720915200000',
     'thumborImageId': 379130},
    {'id': 7546,
     'name': 'India tour of Zimbabwe, 2024',
     'startDt': '1720224000000',
     'endDt': '1720915200000',
     'thumborImageId': 379130},
    {'id': 6780,
     'name': 'West Indies tour of England, 2024',
     'startDt': '1719964800000',
     'endDt': '1722297600000',
     'thumborImageId': 379130},
    {'id': 8422,
     'name': 'Serbia tour of Slovenia, 2024',
     'startDt': '1719619200000',
     'endDt': '1719705600000',
     'thumborImageId': 379130},
    {'id': 8382,
     'name': 'Kenya Quadrangular Cup 2024',
     'startDt': '1719532800000',
     'endDt': '1720569600000',
     'thumborImageId': 379130},
    {'id': 8413,
     'name': 'Jersey tour of Guernsey, 2024',
     'startDt': '1719014400000',
     'endDt': '1719100800000',
     'thumborImageId': 379130},
    {'id': 8310,
     'name': 'Estonia tour of Cyprus 2024',
     'startDt': '1718582400000',
     'endDt': '1718755200000',
     'thumborImageId': 379130},
    {'id': 8260,
     'name': 'Jersey tour of Denmark, 2024',
     'startDt': '1718409600000',
     'endDt': '1718496000000',
     'thumborImageId': 379130},
    {'id': 8332,
     'name': 'Nordic T20I Cup 2024',
     'startDt': '1718323200000',
     'endDt': '1718496000000',
     'thumborImageId': 379130},
    {'id': 8256,
     'name': 'ICC Mens T20 World Cup Sub Regional Europe Qualifier A, 2024',
     'startDt': '1717891200000',
     'endDt': '1718496000000',
     'thumborImageId': 379130},
    {'id': 8294,
     'name': 'Guernsey tour of Belgium, 2024',
     'startDt': '1717804800000',
     'endDt': '1717891200000',
     'thumborImageId': 379130},
    {'id': 7476,
     'name': 'ICC Mens T20 World Cup 2024',
     'startDt': '1717200000000',
     'endDt': '1719619200000',
     'thumborImageId': 379130},
    {'id': 8247,
     'name': 'Belgium tour of Austria, 2024',
     'startDt': '1716595200000',
     'endDt': '1716681600000',
     'thumborImageId': 379130},
    {'id': 8166,
     'name': 'Continental Cup 2024',
     'startDt': '1716508800000',
     'endDt': '1716681600000',
     'thumborImageId': 379130},
    {'id': 8103,
     'name': 'South Africa tour of West Indies, 2024',
     'startDt': '1716422400000',
     'endDt': '1716681600000',
     'thumborImageId': 379130},
    {'id': 6773,
     'name': 'Pakistan tour of England, 2024',
     'startDt': '1716336000000',
     'endDt': '1717027200000',
     'thumborImageId': 379130},
    {'id': 7700,
     'name': 'Bangladesh tour of USA, 2024',
     'startDt': '1716249600000',
     'endDt': '1716595200000',
     'thumborImageId': 379130},
    {'id': 7819,
     'name': 'Netherlands T20I Tri-Series, 2024',
     'startDt': '1715990400000',
     'endDt': '1716508800000',
     'thumborImageId': 379130},
    {'id': 7808,
     'name': 'Pakistan tour of Ireland, 2024',
     'startDt': '1715299200000',
     'endDt': '1715644800000',
     'thumborImageId': 379130},
    {'id': 8080,
     'name': 'Mdina Cup 2024',
     'startDt': '1715212800000',
     'endDt': '1715472000000',
     'thumborImageId': 379130},
    {'id': 7896,
     'name': 'Mongolia tour of Japan, 2024',
     'startDt': '1715040000000',
     'endDt': '1715472000000',
     'thumborImageId': 379130},
    {'id': 7706,
     'name': 'Zimbabwe tour of Bangladesh, 2024',
     'startDt': '1714694400000',
     'endDt': '1715472000000',
     'thumborImageId': 379130},
    {'id': 8042,
     'name': 'Thailand tour of Indonesia 2024',
     'startDt': '1714521600000',
     'endDt': '1714953600000',
     'thumborImageId': 379130},
    {'id': 7679,
     'name': 'New Zealand tour of Pakistan, 2024',
     'startDt': '1713398400000',
     'endDt': '1714176000000',
     'thumborImageId': 379130},
    {'id': 7817,
     'name': 'Jersey tour of Spain, 2024',
     'startDt': '1713052800000',
     'endDt': '1713052800000',
     'thumborImageId': 379130},
    {'id': 7667,
     'name': 'ACC Mens T20I Premier Cup, 2024',
     'startDt': '1712880000000',
     'endDt': '1713657600000',
     'thumborImageId': 379130},
    {'id': 7900,
     'name': 'Central American Cricket Championships 2024',
     'startDt': '1712793600000',
     'endDt': '1713052800000',
     'thumborImageId': 379130},
    {'id': 7693,
     'name': 'Canada tour of USA, 2024',
     'startDt': '1712448000000',
     'endDt': '1712966400000',
     'thumborImageId': 379130},
    {'id': 7727,
     'name': 'Namibia tour of Oman, 2024',
     'startDt': '1711929600000',
     'endDt': '1712448000000',
     'thumborImageId': 379130},
    {'id': 7790,
     'name': 'Lesotho tour of Eswatini, 2024',
     'startDt': '1711670400000',
     'endDt': '1711843200000',
     'thumborImageId': 379130},
    {'id': 7672,
     'name': 'Mens African Games, 2024',
     'startDt': '1710633600000',
     'endDt': '1711152000000',
     'thumborImageId': 379130},
    {'id': 7686,
     'name': 'Papua New Guinea tour of Malaysia, 2024',
     'startDt': '1710547200000',
     'endDt': '1710633600000',
     'thumborImageId': 379130},
    {'id': 7590,
     'name': 'Scotland tour of United Arab Emirates 2024',
     'startDt': '1710115200000',
     'endDt': '1710374400000',
     'thumborImageId': 379130},
    {'id': 7644,
     'name': 'Hong Kong T20I Tri-Series, 2024',
     'startDt': '1710028800000',
     'endDt': '1710288000000',
     'thumborImageId': 379130},
    {'id': 7637,
     'name': 'Hong Kong Friendship Cup, 2024',
     'startDt': '1709942400000',
     'endDt': '1709942400000',
     'thumborImageId': 379130},
    {'id': 7586,
     'name': 'Malaysia Open T20I Championship, 2024',
     'startDt': '1709596800000',
     'endDt': '1710115200000',
     'thumborImageId': 379130},
    {'id': 7534,
     'name': 'Sri Lanka tour of Bangladesh, 2024',
     'startDt': '1709510400000',
     'endDt': '1712102400000',
     'thumborImageId': 379130},
    {'id': 7623,
     'name': 'Papua New Guinea tour of Oman 2024',
     'startDt': '1709424000000',
     'endDt': '1709856000000',
     'thumborImageId': 379130},
    {'id': 7485,
     'name': 'Afghanistan v Ireland in UAE, 2024',
     'startDt': '1709078400000',
     'endDt': '1710720000000',
     'thumborImageId': 379130},
    {'id': 7618,
     'name': 'Hong Kong tour of Qatar 2024',
     'startDt': '1708992000000',
     'endDt': '1709251200000',
     'thumborImageId': 379130},
    {'id': 7583,
     'name': 'Nepal T20I Tri-Series 2024',
     'startDt': '1708992000000',
     'endDt': '1709596800000',
     'thumborImageId': 379130},
    {'id': 6899,
     'name': 'Australia tour of New Zealand, 2024',
     'startDt': '1708473600000',
     'endDt': '1710201600000',
     'thumborImageId': 379130},
    {'id': 7572,
     'name': 'ICC Cricket World Cup League Two 2023-27',
     'startDt': '1707955200000',
     'endDt': '1806364800000',
     'thumborImageId': 379130},
    {'id': 7558,
     'name': 'East Asia Cup 2024',
     'startDt': '1707868800000',
     'endDt': '1708128000000',
     'thumborImageId': 379130},
    {'id': 7579,
     'name': 'Quadrangular Twenty20 Series in Thailand 2024',
     'startDt': '1707696000000',
     'endDt': '1708041600000',
     'thumborImageId': 379130},
    {'id': 7553,
     'name': 'Canada tour of Nepal, 2024',
     'startDt': '1707350400000',
     'endDt': '1707696000000',
     'thumborImageId': 379130},
    {'id': 7481,
     'name': 'Afghanistan tour of Sri Lanka, 2024',
     'startDt': '1706832000000',
     'endDt': '1708473600000',
     'thumborImageId': 379130},
    {'id': 6892,
     'name': 'South Africa tour of New Zealand, 2024',
     'startDt': '1706486400000',
     'endDt': '1708128000000',
     'thumborImageId': 379130},
    {'id': 7511,
     'name': 'ACC Mens T20I Challenger Cup 2024',
     'startDt': '1706313600000',
     'endDt': '1707609600000',
     'thumborImageId': 379130},
    {'id': 6927,
     'name': 'England tour of India, 2024',
     'startDt': '1706140800000',
     'endDt': '1710115200000',
     'thumborImageId': 379130},
    {'id': 6885,
     'name': 'Pakistan tour of New Zealand, 2024',
     'startDt': '1705017600000',
     'endDt': '1705795200000',
     'thumborImageId': 379130},
    {'id': 6920,
     'name': 'Afghanistan tour of India, 2024',
     'startDt': '1704931200000',
     'endDt': '1705449600000',
     'thumborImageId': 379130},
    {'id': 6297,
     'name': 'West Indies tour of Australia, 2024',
     'startDt': '1704844800000',
     'endDt': '1707782400000',
     'thumborImageId': 379130},
    {'id': 7411,
     'name': 'Zimbabwe tour of Sri Lanka 2024',
     'startDt': '1704499200000',
     'endDt': '1705536000000',
     'thumborImageId': 379130}]}],
 'appIndex': {'seoTitle': 'Current Running Cricket Series - Cricbuzz | Cricbuzz.com',
  'webURL': 'www.cricbuzz.com/cricket-series/'},
 'contentFilters': [{'filterId': 'fantasy', 'filterName': 'Fantasy Handbook'}]}

In [22]:
import pandas as pd
from datetime import datetime

series_list = []

series_data = matches2024_i['seriesMapProto'][0]['series']

for s in series_data:

    series_name = s['name']
    
    # Convert timestamp to date
    start_date = datetime.fromtimestamp(int(s['startDt'])/1000).strftime('%Y-%m-%d')

    # Extract host country (simple logic)
    if "tour of" in series_name:
        host_country = series_name.split("tour of")[-1].split(",")[0].strip()
    elif "in" in series_name:
        host_country = series_name.split("in")[-1].split(",")[0].strip()
    else:
        host_country = "Unknown"

    # Match type detection
    if "T20" in series_name:
        match_type = "T20"
    elif "ODI" in series_name:
        match_type = "ODI"
    elif "Test" in series_name:
        match_type = "Test"
    else:
        match_type = "Internatonal"

    series_list.append({
        "Series Name": series_name,
        "Host Country": host_country,
        "Match Type": match_type,
        "Start Date": start_date
    })

df = pd.DataFrame(series_list)

print(df.head())

                                         Series Name  Host Country  \
0             Sri Lanka tour of New Zealand, 2024-25   New Zealand
1               Gulf Cricket T20I Championship, 2024       Unknown
2            Pakistan tour of South Africa, 2024 -25  South Africa
3              Afghanistan tour of Zimbabwe, 2024-25      Zimbabwe
4  ICC Mens T20 World Cup Americas Sub Regional Q...       Unknown

     Match Type  Start Date
0  Internatonal  2024-12-23
1           T20  2024-12-13
2  Internatonal  2024-12-10
3  Internatonal  2024-12-09
4           T20  2024-12-06

In [14]:
df

,Series Name,Host Country,Match Type,Start Date
0,"Sri Lanka tour of New Zealand, 2024-25",New Zealand,Mixed,2024-12-23
1,"Gulf Cricket T20I Championship, 2024",Unknown,T20,2024-12-13
2,"Pakistan tour of South Africa, 2024 -25",South Africa,Mixed,2024-12-10
3,"Afghanistan tour of Zimbabwe, 2024-25",Zimbabwe,Mixed,2024-12-09
4,ICC Mens T20 World Cup Americas Sub Regional Q...,Unknown,T20,2024-12-06
...,...,...,...,...
104,"England tour of India, 2024",India,Mixed,2024-01-25
105,"Pakistan tour of New Zealand, 2024",New Zealand,Mixed,2024-01-12
106,"Afghanistan tour of India, 2024",India,Mixed,2024-01-11
107,"West Indies tour of Australia, 2024",Australia,Mixed,2024-01-10
108,Zimbabwe tour of Sri Lanka 2024,Sri Lanka 2024,Mixed,2024-01-06

In [17]:
import urllib.parse
from sqlalchemy import create_engine

# 1. Encode the special character in password
password = urllib.parse.quote_plus("deepika@88")

# 2. Use the encoded password in your connection string
# Also, ensure 'username' is replaced with your actual DB user (usually 'postgres')
engine = create_engine(f'postgresql+psycopg2://postgres:{password}@localhost:5432/cricbuzz')

# 3. Test the connection and push the data
df.to_sql('q8_match_2024', engine, if_exists='replace', index=False)

print("✅ Connection successful and table 'q8_match_2024' created!")

✅ Connection successful and table 'q8_match_2024' created!

# Example of 2 api connection

In [66]:
import requests
import pandas as pd

headers = {
    "X-RapidAPI-Key": "edcc615a98msh9b529038adf520fp13b7cfjsnba97517d5849",
    "X-RapidAPI-Host": "cricbuzz-cricket.p.rapidapi.com"
}

# 1. Fetch Live Matches
live_response = requests.get("https://cricbuzz-cricket.p.rapidapi.com/matches/v1/live", headers=headers).json()

# 2. Fetch International Archives
archive_response = requests.get("https://cricbuzz-cricket.p.rapidapi.com/series/v1/archives/international", headers=headers).json()

# Now you have both in memory
print(live_response.keys())
print(archive_response.keys())

dict_keys(['typeMatches', 'filters', 'appIndex', 'responseLastUpdated'])
dict_keys(['seriesMapProto', 'appIndex'])

# Q12 get data from first info

In [80]:
import pandas as pd

# 1. Extraction logic
all_matches = []

for type_match in data.get("typeMatches", []):
    m_type = type_match.get('matchType') # Usually 'International', 'League', etc.
    
    for series_matches in type_match.get('seriesMatches', []):
        series_data = series_matches.get('seriesAdWrapper', {})
        series_id = series_data.get('seriesId')
        series_name = series_data.get('seriesName')

        for match in series_data.get('matches', []):
            info = match.get('matchInfo', {})
            score = match.get('matchScore', {})
            venue_info = info.get('venueInfo', {}) # Nested venue details
            
            all_matches.append({
                "series_id": series_id,
                "series_name": series_name,
                "matchId": info.get('matchId'),
                "match_desc": info.get('matchDesc'),
                "match_format": info.get('matchFormat'),
                "start_ts": info.get('startDate'), # Keeping raw timestamp for conversion
                "end_ts": info.get('endDate'),
                "status": info.get('status'),
                "team1": info.get('team1', {}).get('teamName'),
                "team2": info.get('team2', {}).get('teamName'),
                "venue": venue_info.get('ground'),
                "city": venue_info.get('city'),       # ADDED
                "country": venue_info.get('country'), # ADDED
            })

# 2. Convert the LIST to a DATAFRAME first
df_matches = pd.DataFrame(all_matches)

# 3. Convert timestamps to Readable Dates (Corrected column names)
df_matches['start_date'] = pd.to_datetime(pd.to_numeric(df_matches['start_ts'], errors='coerce'), unit='ms')
df_matches['end_date'] = pd.to_datetime(pd.to_numeric(df_matches['end_ts'], errors='coerce'), unit='ms')

# 4. Cleanup raw timestamp columns
df_matches = df_matches.drop(columns=['start_ts', 'end_ts'])

print(df_matches.head())

   series_id                                        series_name  matchId  \
0      11553  CSA Provincial One-Day Challenge Division One ...   147104
1      11553  CSA Provincial One-Day Challenge Division One ...   147112
2      11559  CSA Provincial One-Day Challenge Division Two ...   147378
3      11559  CSA Provincial One-Day Challenge Division Two ...   147310
4      11559  CSA Provincial One-Day Challenge Division Two ...   147359

   match_desc match_format                                             status  \
0   6th Match          ODI                                  Boland opt to bat
1   7th Match          ODI  North West - Eastvaal Renault Dragons opt to bowl
2  15th Match          ODI              Match abandoned without a ball bowled
3  13th Match          ODI                                      Innings Break
4  14th Match          ODI                          38 Overs game due to rain

                           team1                                  team2  \
0                         Boland         KwaZulu-Natal Inland - Tuskers
1                          Lions  North West - Eastvaal Renault Dragons
2  South Africa Emerging Players                          Northern Cape
3                         Border                          Eastern Storm
4              Mpumalanga Rhinos                                Limpopo

                    venue           city country          start_date  \
0             Boland Park          Paarl    None 2026-03-04 11:00:00
1             Senwes Park  Potchefstroom    None 2026-03-04 11:00:00
2     LC de Villiers Oval       Pretoria    None 2026-03-04 08:00:00
3            Buffalo Park    East London    None 2026-03-04 08:00:00
4  Polokwane Cricket Club      Polokwane    None 2026-03-04 08:00:00

             end_date
0 2026-03-04 19:00:00
1 2026-03-04 19:00:00
2 2026-03-04 16:00:00
3 2026-03-04 16:00:00
4 2026-03-04 16:00:00

In [90]:
import pandas as pd
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
import time

# --- STEP 1: Extraction Logic ---
all_matches = []

for type_match in data.get("typeMatches", []):
    for series_matches in type_match.get('seriesMatches', []):
        series_data = series_matches.get('seriesAdWrapper', {})
        s_id = series_data.get('seriesId')
        s_name = series_data.get('seriesName')

        for match in series_data.get('matches', []):
            info = match.get('matchInfo', {})
            venue_info = info.get('venueInfo', {})
            
            all_matches.append({
                "series_id": s_id,
                "series_name": s_name,
                "matchId": info.get('matchId'),
                "match_desc": info.get('matchDesc'),
                "match_format": info.get('matchFormat'),
                "start_ts": info.get('startDate'), 
                "status": info.get('status'),
                "team1": info.get('team1', {}).get('teamName'),
                "team2": info.get('team2', {}).get('teamName'),
                "venue": venue_info.get('ground'),
                "city": venue_info.get('city'),
                "country": venue_info.get('country'), # Pulling what API gives us
            })

# --- STEP 2: Create DataFrame ---
df_matches = pd.DataFrame(all_matches)

# --- STEP 3: Handle Dates ---
# Convert start_ts to a readable start_date for Question 8 filtering
df_matches['start_date'] = pd.to_datetime(pd.to_numeric(df_matches['start_ts'], errors='coerce'), unit='ms')

# --- STEP 4: Fill Missing Countries using Geopy ---
# We only want to search for cities where 'country' is currently empty/NaN
missing_country_mask = df_matches['country'].isna() | (df_matches['country'] == "")
cities_to_lookup = df_matches.loc[missing_country_mask, 'city'].unique()

if len(cities_to_lookup) > 0:
    geolocator = Nominatim(user_agent="my_cricket_analyzer_v2")
    geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)

    def get_country_safe(city_name):
        if not city_name or city_name == "null": return "Unknown"
        try:
            location = geocode(city_name, language='en')
            if location:
                return location.address.split(',')[-1].strip()
            return "Unknown"
        except:
            return "Error"

    # Map only the missing ones to save API quota
    city_map = {city: get_country_safe(city) for city in cities_to_lookup}
    df_matches.loc[missing_country_mask, 'country'] = df_matches.loc[missing_country_mask, 'city'].map(city_map)

# --- STEP 5: Final Cleanup & View ---
# We keep start_ts as requested, but also have start_date for filtering
print(df_matches[['series_id', 'series_name', 'matchId', 'match_desc', 'match_format', 
                  'start_ts', 'status', 'team1', 'team2', 'venue', 'city', 'country']].head())

   series_id                                        series_name  matchId  \
0      11553  CSA Provincial One-Day Challenge Division One ...   147104
1      11553  CSA Provincial One-Day Challenge Division One ...   147112
2      11559  CSA Provincial One-Day Challenge Division Two ...   147378
3      11559  CSA Provincial One-Day Challenge Division Two ...   147310
4      11559  CSA Provincial One-Day Challenge Division Two ...   147359

   match_desc match_format       start_ts  \
0   6th Match          ODI  1772622000000
1   7th Match          ODI  1772622000000
2  15th Match          ODI  1772611200000
3  13th Match          ODI  1772611200000
4  14th Match          ODI  1772611200000

                                              status  \
0                                  Boland opt to bat
1  North West - Eastvaal Renault Dragons opt to bowl
2              Match abandoned without a ball bowled
3                                      Innings Break
4                          38 Overs game due to rain

                           team1                                  team2  \
0                         Boland         KwaZulu-Natal Inland - Tuskers
1                          Lions  North West - Eastvaal Renault Dragons
2  South Africa Emerging Players                          Northern Cape
3                         Border                          Eastern Storm
4              Mpumalanga Rhinos                                Limpopo

                    venue           city       country
0             Boland Park          Paarl  South Africa
1             Senwes Park  Potchefstroom  South Africa
2     LC de Villiers Oval       Pretoria  South Africa
3            Buffalo Park    East London  South Africa
4  Polokwane Cricket Club      Polokwane  South Africa

In [91]:

df_matches

,series_id,series_name,matchId,match_desc,match_format,start_ts,status,team1,team2,venue,city,country,start_date
0,11553,CSA Provincial One-Day Challenge Division One ...,147104,6th Match,ODI,1772622000000,Boland opt to bat,Boland,KwaZulu-Natal Inland - Tuskers,Boland Park,Paarl,South Africa,2026-03-04 11:00:00
1,11553,CSA Provincial One-Day Challenge Division One ...,147112,7th Match,ODI,1772622000000,North West - Eastvaal Renault Dragons opt to bowl,Lions,North West - Eastvaal Renault Dragons,Senwes Park,Potchefstroom,South Africa,2026-03-04 11:00:00
2,11559,CSA Provincial One-Day Challenge Division Two ...,147378,15th Match,ODI,1772611200000,Match abandoned without a ball bowled,South Africa Emerging Players,Northern Cape,LC de Villiers Oval,Pretoria,South Africa,2026-03-04 08:00:00
3,11559,CSA Provincial One-Day Challenge Division Two ...,147310,13th Match,ODI,1772611200000,Innings Break,Border,Eastern Storm,Buffalo Park,East London,South Africa,2026-03-04 08:00:00
4,11559,CSA Provincial One-Day Challenge Division Two ...,147359,14th Match,ODI,1772611200000,38 Overs game due to rain,Mpumalanga Rhinos,Limpopo,Polokwane Cricket Club,Polokwane,South Africa,2026-03-04 08:00:00

In [100]:
for m_id in df_matches['matchId'].head(5): # Let's try first 5
    url = f"https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/{m_id}/scard"
    # Call the API here...
    print(m_id)

147104
147112
147378
147310
147359

In [101]:
import time

all_scorecards = []

# Limit to a small number first to test
for m_id in df_matches['matchId'].unique()[:10]: 
    url = f"https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/{m_id}/scard"
    
    res = requests.get(url, headers=headers)
    if res.status_code == 200:
        all_scorecards.append(res.json())
    
    # Respect the API rate limit (e.g., 1 request per second)
    time.sleep(1)

In [104]:
df_s = pd.DataFrame(all_scorecards)
df_s

,scorecard,ismatchcomplete,appindex,status,responselastupdated
0,[],False,{'seotitle': 'Cricket scorecard - BOL vs KZNIN...,,1772630210
1,[],False,{'seotitle': 'Cricket scorecard - NWEST vs LIO...,,1772630213
2,[],True,{'seotitle': 'Cricket scorecard - SAEP vs NCAP...,,1772630044
3,"[{'inningsid': 1, 'batsman': [{'id': 23936, 'b...",False,{'seotitle': 'Cricket scorecard - BOR vs ESTOR...,Innings Break,1772630215
4,"[{'inningsid': 1, 'batsman': [{'id': 1431603, ...",False,{'seotitle': 'Cricket scorecard - LIMPO vs MPR...,Innings Break,1772630220

# Away list

In [ ]:
# Create combined team-country dataset
team1_df = dfsql[['team1', 'country']].rename(columns={'team1': 'team'})
team2_df = dfsql[['team2', 'country']].rename(columns={'team2': 'team'})

all_teams = pd.concat([team1_df, team2_df])

# Infer home country (most frequent venue country)
team_home_country = (
    all_teams
    .groupby(['team', 'country'])
    .size()
    .reset_index(name='matches')
    .sort_values(['team', 'matches'], ascending=[True, False])
    .drop_duplicates(subset='team')
    .rename(columns={'country': 'home_country'})
)

print(team_home_country.head())

dfsql['winner'] = df.apply(
    lambda row: row['team1'] if row['t1_runs'] > row['t2_runs']
    else (row['team2'] if row['t2_runs'] > row['t1_runs'] else None),
    axis=1
)

# Remove ties
dfsql = dfsql[dfsql['winner'].notna()]
this nt works help me for this

In [105]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/8733/bowling"

headers = {
	"x-rapidapi-key": "edcc615a98msh9b529038adf520fp13b7cfjsnba97517d5849",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

bowl = response.json()

In [106]:
print(bowl.keys())

dict_keys(['headers', 'values', 'appIndex', 'seriesSpinner'])

In [111]:
bowl['headers']

['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL']

In [112]:
bowl['values']

[{'values': ['Matches', '67', '94', '72', '145']},
 {'values': ['Innings', '0', '0', '0', '0']},
 {'values': ['Balls', '0', '0', '0', '0']},
 {'values': ['Runs', '0', '0', '0', '0']},
 {'values': ['Maidens', '0', '0', '0', '0']},
 {'values': ['Wickets', '0', '0', '0', '0']},
 {'values': ['Avg', '0.0', '0.0', '0.0', '0.0']},
 {'values': ['Eco', '0', '0', '0', '0']},
 {'values': ['SR', '0.0', '0.0', '0.0', '0.0']},
 {'values': ['BBI', '-/-', '-/-', '-/-', '-/-']},
 {'values': ['BBM', '-/-', '-/-', '-/-', '-/-']},
 {'values': ['4w', '0', '0', '0', '0']},
 {'values': ['5w', '0', '0', '0', '0']},
 {'values': ['10w', '0', '0', '0', '0']}]

# Q19 analysis

In [ ]:
import requests
import pandas as pd

headers = {
    "X-RapidAPI-Key": "e6021fb984msh201af5139a6e2e9p149939jsn32edaa5716a4",
    "X-RapidAPI-Host": "cricbuzz-cricket.p.rapidapi.com"
}

# 1. Fetch Live Matches
live_response = requests.get("https://cricbuzz-cricket.p.rapidapi.com/matches/v1/live", headers=headers).json()

# 2. Fetch International Archives
archive_response = requests.get("https://cricbuzz-cricket.p.rapidapi.com/series/v1/archives/international", headers=headers).json()

# Now you have both in memory
print(live_response.keys())
print(archive_response.keys())

# Series at 2022
Step 1: Q19 get the series details

In [64]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/series/v1/archives/international"

querystring = {"year":"2022"}

headers = {
	"x-rapidapi-key": "e6021fb984msh201af5139a6e2e9p149939jsn32edaa5716a4",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

series_2022 = response.json()

In [9]:
series_2022

{'seriesMapProto': [{'date': '2022',
   'series': [{'id': 4889,
     'name': 'New Zealand tour of Pakistan, 2022-23',
     'startDt': '1672012800000',
     'endDt': '1673568000000',
     'thumborImageId': 379130},
    {'id': 5248,
     'name': 'Malaysia Quadrangular Series 2022-23',
     'startDt': '1671062400000',
     'endDt': '1671753600000',
     'thumborImageId': 379130},
    {'id': 5225,
     'name': 'East Africa T20I Series 2022',
     'startDt': '1670889600000',
     'endDt': '1671753600000',
     'thumborImageId': 379130},
    {'id': 4254,
     'name': 'South Africa tour of Australia, 2022-23',
     'startDt': '1670544000000',
     'endDt': '1673136000000',
     'thumborImageId': 379130},
    {'id': 4905,
     'name': 'India tour of Bangladesh, 2022',
     'startDt': '1670112000000',
     'endDt': '1672012800000',
     'thumborImageId': 379130},
    {'id': 5029,
     'name': 'ICC Mens T20 World Cup Sub Regional Africa Qualifier B 2022',
     'startDt': '1669852800000',
     'endDt': '1670544000000',
     'thumborImageId': 379130},
    {'id': 4903,
     'name': 'Afghanistan tour of Sri Lanka, 2022',
     'startDt': '1669334400000',
     'endDt': '1669766400000',
     'thumborImageId': 379130},
    {'id': 4399,
     'name': 'India tour of New Zealand, 2022',
     'startDt': '1668729600000',
     'endDt': '1669766400000',
     'thumborImageId': 379130},
    {'id': 5024,
     'name': 'ICC Mens T20 World Cup Sub Regional Africa Qualifier A 2022',
     'startDt': '1668643200000',
     'endDt': '1669334400000',
     'thumborImageId': 379130},
    {'id': 4947,
     'name': 'United Arab Emirates tour of Nepal, 2022',
     'startDt': '1668384000000',
     'endDt': '1668729600000',
     'thumborImageId': 379130},
    {'id': 5022,
     'name': 'Desert Cup T20I Series 2022',
     'startDt': '1668384000000',
     'endDt': '1668988800000',
     'thumborImageId': 379130},
    {'id': 4917,
     'name': 'Spain Triangular T20I Series, 2022-23',
     'startDt': '1667520000000',
     'endDt': '1667692800000',
     'thumborImageId': 379130},
    {'id': 4931,
     'name': 'Rwanda tour of Tanzania, 2022',
     'startDt': '1667174400000',
     'endDt': '1667692800000',
     'thumborImageId': 379130},
    {'id': 3961,
     'name': 'ICC Mens T20 World Cup 2022',
     'startDt': '1665878400000',
     'endDt': '1668297600000',
     'thumborImageId': 379130},
    {'id': 4625,
     'name': 'ICC Mens T20 World Cup East Asia Pacific Qualifier B, 2022',
     'startDt': '1665792000000',
     'endDt': '1666051200000',
     'thumborImageId': 379130},
    {'id': 4247,
     'name': 'England tour of Australia, 2022',
     'startDt': '1665273600000',
     'endDt': '1669075200000',
     'thumborImageId': 379130},
    {'id': 4807,
     'name': 'Indonesia tour of Japan, 2022',
     'startDt': '1665273600000',
     'endDt': '1665446400000',
     'thumborImageId': 379130},
    {'id': 4385,
     'name': 'New Zealand T20I Tri-Series 2022',
     'startDt': '1665100800000',
     'endDt': '1665705600000',
     'thumborImageId': 379130},
    {'id': 4245,
     'name': 'West Indies tour of Australia, 2022',
     'startDt': '1664928000000',
     'endDt': '1670803200000',
     'thumborImageId': 379130},
    {'id': 4471,
     'name': 'South Africa tour of India, 2022',
     'startDt': '1664323200000',
     'endDt': '1665446400000',
     'thumborImageId': 379130},
    {'id': 4728,
     'name': 'Bangladesh tour of United Arab Emirates, 2022',
     'startDt': '1664064000000',
     'endDt': '1664236800000',
     'thumborImageId': 379130},
    {'id': 4492,
     'name': 'England tour of Pakistan, 2022',
     'startDt': '1663632000000',
     'endDt': '1671580800000',
     'thumborImageId': 379130},
    {'id': 4464,
     'name': 'Australia tour of India, 2022',
     'startDt': '1663632000000',
     'endDt': '1664064000000',
     'thumborImageId': 379130},
    {'id': 4709,
     'name': 'Africa Cricket Association Cup 2022',
     'startDt': '1663200000000',
     'endDt': '1663804800000',
     'thumborImageId': 379130},
    {'id': 4623,
     'name': 'ICC Mens T20 World Cup East Asia Pacific Qualifier A, 2022',
     'startDt': '1662595200000',
     'endDt': '1663200000000',
     'thumborImageId': 379130},
    {'id': 4240,
     'name': 'New Zealand tour of Australia, 2022',
     'startDt': '1662422400000',
     'endDt': '1662854400000',
     'thumborImageId': 379130},
    {'id': 4233,
     'name': 'Zimbabwe tour of Australia, 2022',
     'startDt': '1661644800000',
     'endDt': '1662163200000',
     'thumborImageId': 379130},
    {'id': 4499,
     'name': 'Asia Cup, 2022',
     'startDt': '1661558400000',
     'endDt': '1662854400000',
     'thumborImageId': 379130},
    {'id': 4560,
     'name': 'Nepal tour of Kenya, 2022',
     'startDt': '1661385600000',
     'endDt': '1662336000000',
     'thumborImageId': 379130},
    {'id': 4506,
     'name': 'Asia Cup Qualifier, 2022',
     'startDt': '1660953600000',
     'endDt': '1661299200000',
     'thumborImageId': 379130},
    {'id': 4436,
     'name': 'India tour of Zimbabwe, 2022',
     'startDt': '1660780800000',
     'endDt': '1661126400000',
     'thumborImageId': 379130},
    {'id': 2913,
     'name': 'Pakistan tour of Netherlands, 2022',
     'startDt': '1660608000000',
     'endDt': '1661040000000',
     'thumborImageId': 379130},
    {'id': 4553,
     'name': 'Bahrain v Kuwait in Oman T20I Series, 2022',
     'startDt': '1660176000000',
     'endDt': '1660694400000',
     'thumborImageId': 379130},
    {'id': 4268,
     'name': 'New Zealand tour of West Indies, 2022',
     'startDt': '1660089600000',
     'endDt': '1661040000000',
     'thumborImageId': 379130},
    {'id': 4079,
     'name': 'Afghanistan tour of Ireland, 2022',
     'startDt': '1660003200000',
     'endDt': '1660694400000',
     'thumborImageId': 379130},
    {'id': 4107,
     'name': 'New Zealand tour of Netherlands, 2022',
     'startDt': '1659571200000',
     'endDt': '1659657600000',
     'thumborImageId': 379130},
    {'id': 4051,
     'name': 'South Africa v Ireland in England, 2022',
     'startDt': '1659484800000',
     'endDt': '1659657600000',
     'thumborImageId': 379130},
    {'id': 4427,
     'name': 'Bangladesh tour of Zimbabwe, 2022',
     'startDt': '1659139200000',
     'endDt': '1660089600000',
     'thumborImageId': 379130},
    {'id': 8154,
     'name': 'Mozambique tour of Eswatini, 2022',
     'startDt': '1659052800000',
     'endDt': '1659225600000',
     'thumborImageId': 379130},
    {'id': 4091,
     'name': 'New Zealand tour of Scotland, 2022',
     'startDt': '1658880000000',
     'endDt': '1659225600000',
     'thumborImageId': 379130},
    {'id': 4329,
     'name': 'ICC Mens T20 World Cup Europe Qualifier Group B 2022',
     'startDt': '1658620800000',
     'endDt': '1659225600000',
     'thumborImageId': 379130},
    {'id': 4261,
     'name': 'India tour of West Indies, 2022',
     'startDt': '1658448000000',
     'endDt': '1659830400000',
     'thumborImageId': 379130},
    {'id': 4324,
     'name': 'ICC Mens T20 World Cup Europe Qualifier Group A 2022',
     'startDt': '1657584000000',
     'endDt': '1658188800000',
     'thumborImageId': 379130},
    {'id': 3646,
     'name': 'South Africa tour of England, 2022',
     'startDt': '1657584000000',
     'endDt': '1662940800000',
     'thumborImageId': 379130},
    {'id': 4315,
     'name': 'Pakistan tour of Sri Lanka, 2022',
     'startDt': '1657497600000',
     'endDt': '1658966400000',
     'thumborImageId': 379130},
    {'id': 4364,
     'name': 'ICC Mens T20 World Cup Qualifier B 2022',
     'startDt': '1657497600000',
     'endDt': '1658016000000',
     'thumborImageId': 379130},
    {'id': 4046,
     'name': 'New Zealand tour of Ireland, 2022',
     'startDt': '1657411200000',
     'endDt': '1658448000000',
     'thumborImageId': 379130},
    {'id': 4359,
     'name': 'Central Europe Cup 2022',
     'startDt': '1657238400000',
     'endDt': '1657411200000',
     'thumborImageId': 379130},
    {'id': 4434,
     'name': 'Bulgaria tour of Serbia, 2022',
     'startDt': '1657238400000',
     'endDt': '1657324800000',
     'thumborImageId': 379130},
    {'id': 4378,
     'name': 'Malaysia Quadrangular Series 2022',
     'startDt': '1656720000000',
     'endDt': '1657497600000',
     'thumborImageId': 379130},
    {'id': 4366,
     'name': 'Papua New Guinea tour of Singapore, 2022',
     'startDt': '1656720000000',
     'endDt': '1657065600000',
     'thumborImageId': 379130},
    {'id': 4317,
     'name': 'ICC Mens T20 World Cup Europe Qualifier Group C 2022',
     'startDt': '1656374400000',
     'endDt': '1656892800000',
     'thumborImageId': 379130},
    {'id': 4336,
     'name': 'Malaysia tour of Singapore, 2022',
     'startDt': '1656374400000',
     'endDt': '1656547200000',
     'thumborImageId': 379130},
    {'id': 4041,
     'name': 'India tour of Ireland, 2022',
     'startDt': '1656201600000',
     'endDt': '1656374400000',
     'thumborImageId': 379130},
    {'id': 4310,
     'name': 'Serbia tour of Bulgaria, 2022',
     'startDt': '1656028800000',
     'endDt': '1656201600000',
     'thumborImageId': 379130},
    {'id': 3636,
     'name': 'India tour of England, 2022',
     'startDt': '1655942400000',
     'endDt': '1658016000000',
     'thumborImageId': 379130},
    {'id': 4303,
     'name': 'Estonia tour of Finland, 2022',
     'startDt': '1655596800000',
     'endDt': '1655596800000',
     'thumborImageId': 379130},
    {'id': 3722,
     'name': 'England tour of Netherlands, 2022',
     'startDt': '1655424000000',
     'endDt': '1655856000000',
     'thumborImageId': 379130},
    {'id': 4212,
     'name': 'Bangladesh tour of West Indies, 2022',
     'startDt': '1655337600000',
     'endDt': '1657929600000',
     'thumborImageId': 379130},
    {'id': 4282,
     'name': 'Malta tour of Belgium, 2022',
     'startDt': '1654905600000',
     'endDt': '1654992000000',
     'thumborImageId': 379130},
    {'id': 4289,
     'name': 'Switzerland tour of Luxembourg, 2022',
     'startDt': '1654905600000',
     'endDt': '1654905600000',
     'thumborImageId': 379130},
    {'id': 4275,
     'name': 'Germany T20I Tri-Series 2022',
     'startDt': '1654732800000',
     'endDt': '1654992000000',
     'thumborImageId': 379130},
    {'id': 3697,
     'name': 'South Africa tour of India, 2022',
     'startDt': '1654732800000',
     'endDt': '1655596800000',
     'thumborImageId': 379130},
    {'id': 4086,
     'name': 'Australia tour of Sri Lanka, 2022',
     'startDt': '1654560000000',
     'endDt': '1657584000000',
     'thumborImageId': 379130},
    {'id': 4156,
     'name': 'Afghanistan tour of Zimbabwe, 2022',
     'startDt': '1654300800000',
     'endDt': '1655164800000',
     'thumborImageId': 379130},
    {'id': 4226,
     'name': 'Hungary tour of Austria, 2022',
     'startDt': '1654300800000',
     'endDt': '1654387200000',
     'thumborImageId': 379130},
    {'id': 3806,
     'name': 'West Indies tour of Netherlands, 2022',
     'startDt': '1653955200000',
     'endDt': '1654300800000',
     'thumborImageId': 379130},
    {'id': 3641,
     'name': 'New Zealand tour of England, 2022',
     'startDt': '1653004800000',
     'endDt': '1656288000000',
     'thumborImageId': 379130},
    {'id': 4203,
     'name': 'Jersey tour of Guernsey, 2022',
     'startDt': '1653004800000',
     'endDt': '1653177600000',
     'thumborImageId': 379130},
    {'id': 4149,
     'name': 'Namibia tour of Zimbabwe, 2022',
     'startDt': '1652745600000',
     'endDt': '1653350400000',
     'thumborImageId': 379130},
    {'id': 4100,
     'name': 'Sri Lanka tour of Bangladesh, 2022',
     'startDt': '1652227200000',
     'endDt': '1653609600000',
     'thumborImageId': 379130},
    {'id': 4205,
     'name': 'Valletta Cup 2022',
     'startDt': '1652140800000',
     'endDt': '1652572800000',
     'thumborImageId': 379130},
    {'id': 4168,
     'name': 'Finland tour of Denmark, 2022',
     'startDt': '1651881600000',
     'endDt': '1651968000000',
     'thumborImageId': 379130},
    {'id': 4177,
     'name': 'Spain Triangular T20I Series, 2022',
     'startDt': '1651190400000',
     'endDt': '1651363200000',
     'thumborImageId': 379130},
    {'id': 4140,
     'name': 'Bahamas tour of Cayman Islands, 2022',
     'startDt': '1649808000000',
     'endDt': '1650153600000',
     'thumborImageId': 379130},
    {'id': 4114,
     'name': 'Uganda tour of Namibia, 2022',
     'startDt': '1649376000000',
     'endDt': '1649548800000',
     'thumborImageId': 379130},
    {'id': 4075,
     'name': 'Nepal T20I Tri-Series 2022',
     'startDt': '1648425600000',
     'endDt': '1649030400000',
     'thumborImageId': 379130},
    {'id': 4068,
     'name': 'Papua New Guinea tour of Nepal, 2022',
     'startDt': '1648166400000',
     'endDt': '1648252800000',
     'thumborImageId': 379130},
    {'id': 3657,
     'name': 'Bangladesh tour of South Africa, 2022',
     'startDt': '1647561600000',
     'endDt': '1649635200000',
     'thumborImageId': 379130},
    {'id': 3873,
     'name': 'Australia tour of New Zealand, 2022 (Cancelled)',
     'startDt': '1647475200000',
     'endDt': '1647734400000',
     'thumborImageId': 379130},
    {'id': 3888,
     'name': 'Netherlands tour of New Zealand, 2022',
     'startDt': '1647475200000',
     'endDt': '1649030400000',
     'thumborImageId': 379130},
    {'id': 3863,
     'name': 'Australia tour of Pakistan, 2022',
     'startDt': '1646352000000',
     'endDt': '1649116800000',
     'thumborImageId': 379130},
    {'id': 3692,
     'name': 'Sri Lanka tour of India, 2022',
     'startDt': '1645660800000',
     'endDt': '1647388800000',
     'thumborImageId': 379130},
    {'id': 3996,
     'name': 'Afghanistan tour of Bangladesh, 2022',
     'startDt': '1645574400000',
     'endDt': '1646438400000',
     'thumborImageId': 379130},
    {'id': 3976,
     'name': 'ICC Mens T20 World Cup Qualifier A 2022',
     'startDt': '1645142400000',
     'endDt': '1645660800000',
     'thumborImageId': 379130},
    {'id': 3881,
     'name': 'South Africa tour of New Zealand, 2022',
     'startDt': '1645056000000',
     'endDt': '1646092800000',
     'thumborImageId': 379130},
    {'id': 3971,
     'name': 'Oman Quadrangular T20I Series 2022',
     'startDt': '1644537600000',
     'endDt': '1644796800000',
     'thumborImageId': 379130},
    {'id': 3547,
     'name': 'Sri Lanka tour of Australia, 2022',
     'startDt': '1644537600000',
     'endDt': '1645315200000',
     'thumborImageId': 379130},
    {'id': 3687,
     'name': 'West Indies tour of India, 2022',
     'startDt': '1644105600000',
     'endDt': '1645315200000',
     'thumborImageId': 379130},
    {'id': 3541,
     'name': 'New Zealand tour of Australia, 2022 (Postponed)',
     'startDt': '1642809600000',
     'endDt': '1642982400000',
     'thumborImageId': 379130},
    {'id': 3482,
     'name': 'England tour of West Indies, 2022',
     'startDt': '1642809600000',
     'endDt': '1648425600000',
     'thumborImageId': 379130},
    {'id': 3921,
     'name': 'Afghanistan v Netherlands in Qatar, 2022',
     'startDt': '1642723200000',
     'endDt': '1643068800000',
     'thumborImageId': 379130},
    {'id': 3936,
     'name': 'Zimbabwe tour of Sri Lanka, 2022',
     'startDt': '1642291200000',
     'endDt': '1642723200000',
     'thumborImageId': 379130},
    {'id': 3916,
     'name': 'Ireland tour of West Indies, 2022',
     'startDt': '1641600000000',
     'endDt': '1642291200000',
     'thumborImageId': 379130}]}],
 'appIndex': {'seoTitle': 'Current Running Cricket Series - Cricbuzz | Cricbuzz.com',
  'webURL': 'www.cricbuzz.com/cricket-series/'}}

In [26]:
import pandas as pd
from datetime import datetime

series_list2 = []

series_data_2022 = series_2022['seriesMapProto'][0]['series']

for s in series_data_2022:

    series_name = s['name']
    series_id = s['id']
    
    # Convert timestamp to date
    start_date = datetime.fromtimestamp(int(s['startDt'])/1000).strftime('%Y-%m-%d')

    # Extract host country (simple logic)
    if "tour of" in series_name:
        host_country = series_name.split("tour of")[-1].split(",")[0].strip()
    elif "in" in series_name:
        host_country = series_name.split("in")[-1].split(",")[0].strip()
    else:
        host_country = "Unknown"

    # Match type detection
    if "T20" in series_name:
        match_type = "T20"
    elif "ODI" in series_name:
        match_type = "ODI"
    elif "Test" in series_name:
        match_type = "Test"
    else:
        match_type = "Internatonal"

    series_list2.append({
        "Series_id" : series_id,
        "Series Name": series_name,
        "Host Country": host_country,
        "Match Type": match_type,
        "Start Date": start_date
    })

df2022 = pd.DataFrame(series_list2)

print(df2022.head())

   Series_id                              Series Name Host Country  \
0       4889    New Zealand tour of Pakistan, 2022-23     Pakistan
1       5248     Malaysia Quadrangular Series 2022-23      Unknown
2       5225             East Africa T20I Series 2022      Unknown
3       4254  South Africa tour of Australia, 2022-23    Australia
4       4905           India tour of Bangladesh, 2022   Bangladesh

     Match Type  Start Date
0  Internatonal  2022-12-26
1  Internatonal  2022-12-15
2           T20  2022-12-13
3  Internatonal  2022-12-09
4  Internatonal  2022-12-04

In [27]:
df2022

,Series_id,Series Name,Host Country,Match Type,Start Date
0,4889,"New Zealand tour of Pakistan, 2022-23",Pakistan,Internatonal,2022-12-26
1,5248,Malaysia Quadrangular Series 2022-23,Unknown,Internatonal,2022-12-15
2,5225,East Africa T20I Series 2022,Unknown,T20,2022-12-13
3,4254,"South Africa tour of Australia, 2022-23",Australia,Internatonal,2022-12-09
4,4905,"India tour of Bangladesh, 2022",Bangladesh,Internatonal,2022-12-04
...,...,...,...,...,...
89,3541,"New Zealand tour of Australia, 2022 (Postponed)",Australia,Internatonal,2022-01-22
90,3482,"England tour of West Indies, 2022",West Indies,Internatonal,2022-01-22
91,3921,"Afghanistan v Netherlands in Qatar, 2022",Qatar,Internatonal,2022-01-21
92,3936,"Zimbabwe tour of Sri Lanka, 2022",Sri Lanka,Internatonal,2022-01-16
93,3916,"Ireland tour of West Indies, 2022",West Indies,Internatonal,2022-01-08

# one whole series data to get match details

In [ ]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/series/v1/4889/4114"

headers = {
	"x-rapidapi-key": "e6021fb984msh201af5139a6e2e9p149939jsn32edaa5716a4",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

ser_4889 = response.json()

In [ ]:
ser_mat_det = ser_4889['matchDetails']

{'matchDetails': [{'matchDetailsMap': {'key': 'Mon, 26 Dec 2022 - Fri, 30 Dec 2022',
    'match': [{'matchInfo': {'matchId': 56717,
       'seriesId': 4889,
       'seriesName': 'New Zealand tour of Pakistan, 2022-23',
       'matchDesc': '1st Test',
       'matchFormat': 'TEST',
       'startDate': '1672030800000',
       'endDate': '1672376400000',
       'state': 'complete',
       'status': 'Match drawn',
       'team1': {'teamId': 3,
        'teamName': 'PAKISTAN',
        'teamSName': 'PAK',
        'imageId': 776308},
       'team2': {'teamId': 13,
        'teamName': 'NEW ZEALAND',
        'teamSName': 'NZ',
        'imageId': 776333},
       'venueInfo': {'ground': 'National Stadium',
        'city': 'Karachi',
        'timezone': '+05:00'},
       'currBatTeamId': 13,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 438,
         'wickets': 10,
         'overs': 130.5},
        'inngs2': {'inningsId': 3,
         'runs': 311,
         'wickets': 8,
         'overs': 103.5,
         'isDeclared': True}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 612,
         'wickets': 9,
         'overs': 194.5,
         'isDeclared': True},
        'inngs2': {'inningsId': 4, 'runs': 61, 'wickets': 1, 'overs': 7.3}}}}],
    'seriesId': 4889}},
  {'adDetail': {'name': 'native_news_index_random_1',
    'layout': 'native_large',
    'position': 1}},
  {'matchDetailsMap': {'key': 'Mon, 02 Jan 2023 - Fri, 06 Jan 2023',
    'match': [{'matchInfo': {'matchId': 56724,
       'seriesId': 4889,
       'seriesName': 'New Zealand tour of Pakistan, 2022-23',
       'matchDesc': '2nd Test',
       'matchFormat': 'TEST',
       'startDate': '1672635600000',
       'endDate': '1672981200000',
       'state': 'complete',
       'status': 'Match drawn',
       'team1': {'teamId': 3,
        'teamName': 'PAKISTAN',
        'teamSName': 'PAK',
        'imageId': 776308},
       'team2': {'teamId': 13,
        'teamName': 'NEW ZEALAND',
        'teamSName': 'NZ',
        'imageId': 776333},
       'venueInfo': {'ground': 'National Stadium',
        'city': 'Karachi',
        'timezone': '+05:00'},
       'currBatTeamId': 3,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 408,
         'wickets': 10,
         'overs': 133.0},
        'inngs2': {'inningsId': 4, 'runs': 304, 'wickets': 9, 'overs': 90.0}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 449,
         'wickets': 10,
         'overs': 131.0},
        'inngs2': {'inningsId': 3,
         'runs': 277,
         'wickets': 5,
         'overs': 82.0,
         'isDeclared': True}}}}],
    'seriesId': 4889}},
  {'matchDetailsMap': {'key': 'Mon, 09 Jan 2023',
    'match': [{'matchInfo': {'matchId': 56726,
       'seriesId': 4889,
       'seriesName': 'New Zealand tour of Pakistan, 2022-23',
       'matchDesc': '1st ODI',
       'matchFormat': 'ODI',
       'startDate': '1673256600000',
       'endDate': '1673256600000',
       'state': 'complete',
       'status': 'Pakistan won by 6 wkts',
       'team1': {'teamId': 3,
        'teamName': 'PAKISTAN',
        'teamSName': 'PAK',
        'imageId': 776308},
       'team2': {'teamId': 13,
        'teamName': 'NEW ZEALAND',
        'teamSName': 'NZ',
        'imageId': 776333},
       'venueInfo': {'ground': 'National Stadium',
        'city': 'Karachi',
        'timezone': '+05:00'},
       'currBatTeamId': 3,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 258,
         'wickets': 4,
         'overs': 48.1}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 255,
         'wickets': 9,
         'overs': 50.0}}}}],
    'seriesId': 4889}},
  {'matchDetailsMap': {'key': 'Wed, 11 Jan 2023',
    'match': [{'matchInfo': {'matchId': 56733,
       'seriesId': 4889,
       'seriesName': 'New Zealand tour of Pakistan, 2022-23',
       'matchDesc': '2nd ODI',
       'matchFormat': 'ODI',
       'startDate': '1673429400000',
       'endDate': '1673429400000',
       'state': 'complete',
       'status': 'New Zealand won by 79 runs',
       'team1': {'teamId': 3,
        'teamName': 'PAKISTAN',
        'teamSName': 'PAK',
        'imageId': 776308},
       'team2': {'teamId': 13,
        'teamName': 'NEW ZEALAND',
        'teamSName': 'NZ',
        'imageId': 776333},
       'venueInfo': {'ground': 'National Stadium',
        'city': 'Karachi',
        'timezone': '+05:00'},
       'currBatTeamId': 13,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 182,
         'wickets': 10,
         'overs': 43.0}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 261,
         'wickets': 10,
         'overs': 49.5}}}}],
    'seriesId': 4889}},
  {'matchDetailsMap': {'key': 'Fri, 13 Jan 2023',
    'match': [{'matchInfo': {'matchId': 56740,
       'seriesId': 4889,
       'seriesName': 'New Zealand tour of Pakistan, 2022-23',
       'matchDesc': '3rd ODI',
       'matchFormat': 'ODI',
       'startDate': '1673602200000',
       'endDate': '1673602200000',
       'state': 'complete',
       'status': 'New Zealand won by 2 wkts',
       'team1': {'teamId': 3,
        'teamName': 'PAKISTAN',
        'teamSName': 'PAK',
        'imageId': 776308},
       'team2': {'teamId': 13,
        'teamName': 'NEW ZEALAND',
        'teamSName': 'NZ',
        'imageId': 776333},
       'venueInfo': {'ground': 'National Stadium',
        'city': 'Karachi',
        'timezone': '+05:00'},
       'currBatTeamId': 13,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 280,
         'wickets': 9,
         'overs': 50.0}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 281,
         'wickets': 8,
         'overs': 48.1}}}}],
    'seriesId': 4889}}],
 'appIndex': {'seoTitle': 'New Zealand tour of Pakistan, 2022-23 live scores, schedule and results - Cricbuzz | Cricbuzz.com',
  'webURL': 'www.cricbuzz.com/cricket-series/'}}

In [31]:
import pandas as pd
from datetime import datetime

series_matches = []

for item in ser_4889['matchDetails']:
    
    match_map = item.get('matchDetailsMap', {})
    
    for m in match_map.get('match', []):
        
        info = m.get('matchInfo', {})
        
        match_id = info.get('matchId')
        series_name = info.get('seriesName')
        match_desc = info.get('matchDesc')
        match_format = info.get('matchFormat')
        
        team1 = info.get('team1', {}).get('teamName')
        team2 = info.get('team2', {}).get('teamName')
        
        venue = info.get('venueInfo', {}).get('ground')
        city = info.get('venueInfo', {}).get('city')
        
        start_date = datetime.fromtimestamp(
            int(info.get('startDate'))/1000
        ).strftime('%Y-%m-%d')
        
        status = info.get('status')
        
        series_matches.append({
            "Match ID": match_id,
            "Series": series_name,
            "Match": match_desc,
            "Format": match_format,
            "Team1": team1,
            "Team2": team2,
            "Venue": venue,
            "City": city,
            "Start Date": start_date,
            "Result": status
        })

df_series_matches = pd.DataFrame(series_matches)

df_series_matches.head()

,Match ID,Series,Match,Format,Team1,Team2,Venue,City,Start Date,Result
0,56717,"New Zealand tour of Pakistan, 2022-23",1st Test,TEST,PAKISTAN,NEW ZEALAND,National Stadium,Karachi,2022-12-26,Match drawn
1,56724,"New Zealand tour of Pakistan, 2022-23",2nd Test,TEST,PAKISTAN,NEW ZEALAND,National Stadium,Karachi,2023-01-02,Match drawn
2,56726,"New Zealand tour of Pakistan, 2022-23",1st ODI,ODI,PAKISTAN,NEW ZEALAND,National Stadium,Karachi,2023-01-09,Pakistan won by 6 wkts
3,56733,"New Zealand tour of Pakistan, 2022-23",2nd ODI,ODI,PAKISTAN,NEW ZEALAND,National Stadium,Karachi,2023-01-11,New Zealand won by 79 runs
4,56740,"New Zealand tour of Pakistan, 2022-23",3rd ODI,ODI,PAKISTAN,NEW ZEALAND,National Stadium,Karachi,2023-01-13,New Zealand won by 2 wkts

In [38]:
mat_ids = df_series_matches['Match ID'].tolist()
print(mat_ids[:5])

[56717, 56724, 56726, 56733, 56740]

# Get scorecard for each match

Use the match id to Calculate the average runs scored and the standard deviation of runs for each player

In [27]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/56733/scard"

headers = {
	"x-rapidapi-key": "e6021fb984msh201af5139a6e2e9p149939jsn32edaa5716a4",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

data_56717 = response.json()

In [28]:
data_56717

{'scorecard': [{'inningsid': 1,
   'batsman': [{'id': 11172,
     'balls': 4,
     'runs': 1,
     'fours': 0,
     'sixes': 0,
     'strkrate': '25',
     'name': 'Finn Allen',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c Nawaz b Naseem Shah',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 9838,
     'balls': 92,
     'runs': 101,
     'fours': 13,
     'sixes': 1,
     'strkrate': '109.78',
     'name': 'Conway',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'b Naseem Shah',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 6326,
     'balls': 100,
     'runs': 85,
     'fours': 10,
     'sixes': 0,
     'strkrate': '85',
     'name': 'Williamson',
     'nickname': '',
     'iscaptain': True,
     'iskeeper': False,
     'outdec': 'b Nawaz',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 10713,
     'balls': 7,
     'runs': 5,
     'fours': 1,
     'sixes': 0,
     'strkrate': '71.43',
     'name': 'Daryl Mitchell',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c Rizwan b Nawaz',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 8216,
     'balls': 3,
     'runs': 2,
     'fours': 0,
     'sixes': 0,
     'strkrate': '66.67',
     'name': 'Latham',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': True,
     'outdec': 'lbw b Nawaz',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 10693,
     'balls': 8,
     'runs': 3,
     'fours': 0,
     'sixes': 0,
     'strkrate': '37.5',
     'name': 'Glenn Phillips',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c Fakhar Zaman b Nawaz',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 9551,
     'balls': 14,
     'runs': 8,
     'fours': 0,
     'sixes': 0,
     'strkrate': '57.14',
     'name': 'M Bracewell',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'lbw b Usama Mir',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 10100,
     'balls': 40,
     'runs': 37,
     'fours': 1,
     'sixes': 1,
     'strkrate': '92.5',
     'name': 'Santner',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'run out (Mohammad Wasim Jr/Rizwan)',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 8561,
     'balls': 22,
     'runs': 7,
     'fours': 0,
     'sixes': 0,
     'strkrate': '31.82',
     'name': 'Ish Sodhi',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'b Haris Rauf',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 1057,
     'balls': 4,
     'runs': 0,
     'fours': 0,
     'sixes': 0,
     'strkrate': '0',
     'name': 'Southee',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c Usama Mir b Naseem Shah',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 10692,
     'balls': 5,
     'runs': 0,
     'fours': 0,
     'sixes': 0,
     'strkrate': '0',
     'name': 'Lockie Ferguson',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'not out',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''}],
   'bowler': [{'id': 14247,
     'overs': '8.5',
     'maidens': 0,
     'wickets': 3,
     'runs': 58,
     'economy': '6.6',
     'name': 'Naseem Shah',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'dots': 0,
     'balls': 53,
     'rpb': 0.0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 14561,
     'overs': '10',
     'maidens': 0,
     'wickets': 1,
     'runs': 47,
     'economy': '4.7',
     'name': 'Haris Rauf',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'dots': 0,
     'balls': 60,
     'rpb': 0.0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 15040,
     'overs': '7',
     'maidens': 0,
     'wickets': 0,
     'runs': 46,
     'economy': '6.6',
     'name': 'Mohammad Wasim Jr',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'dots': 0,
     'balls': 42,
     'rpb': 0.0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 8367,
     'overs': '10',
     'maidens': 0,
     'wickets': 4,
     'runs': 38,
     'economy': '3.8',
     'name': 'Nawaz',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'dots': 0,
     'balls': 60,
     'rpb': 0.0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 11318,
     'overs': '10',
     'maidens': 0,
     'wickets': 1,
     'runs': 42,
     'economy': '4.2',
     'name': 'Usama Mir',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'dots': 0,
     'balls': 60,
     'rpb': 0.0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 10101,
     'overs': '4',
     'maidens': 0,
     'wickets': 0,
     'runs': 28,
     'economy': '7',
     'name': 'Agha Salman',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'dots': 0,
     'balls': 24,
     'rpb': 0.0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''}],
   'fow': {'fow': [{'batsmanid': 11172,
      'batsmanname': 'Finn Allen',
      'overnbr': 0.5,
      'runs': 2,
      'ballnbr': 5},
     {'batsmanid': 9838,
      'batsmanname': 'Conway',
      'overnbr': 29.6,
      'runs': 183,
      'ballnbr': 180},
     {'batsmanid': 10713,
      'batsmanname': 'Daryl Mitchell',
      'overnbr': 32.3,
      'runs': 196,
      'ballnbr': 195},
     {'batsmanid': 8216,
      'batsmanname': 'Latham',
      'overnbr': 32.6,
      'runs': 198,
      'ballnbr': 198},
     {'batsmanid': 6326,
      'batsmanname': 'Williamson',
      'overnbr': 34.5,
      'runs': 201,
      'ballnbr': 209},
     {'batsmanid': 10693,
      'batsmanname': 'Glenn Phillips',
      'overnbr': 36.3,
      'runs': 206,
      'ballnbr': 219},
     {'batsmanid': 9551,
      'batsmanname': 'M Bracewell',
      'overnbr': 40.3,
      'runs': 220,
      'ballnbr': 243},
     {'batsmanid': 8561,
      'batsmanname': 'Ish Sodhi',
      'overnbr': 46.3,
      'runs': 238,
      'ballnbr': 279},
     {'batsmanid': 1057,
      'batsmanname': 'Southee',
      'overnbr': 47.2,
      'runs': 240,
      'ballnbr': 284},
     {'batsmanid': 10100,
      'batsmanname': 'Santner',
      'overnbr': 49.5,
      'runs': 261,
      'ballnbr': 299}]},
   'extras': {'legbyes': 2,
    'byes': 0,
    'wides': 10,
    'noballs': 0,
    'penalty': 0,
    'total': 12},
   'pp': {'powerplay': [{'id': 1,
      'ovrfrom': 0.1,
      'ovrto': 10.0,
      'pptype': 'Mandatory',
      'run': 63,
      'wickets': 0}]},
   'score': 261,
   'wickets': 10,
   'overs': 49.5,
   'runrate': 5.24,
   'batteamname': 'New Zealand',
   'batteamsname': 'NZ',
   'isdeclared': False,
   'isfollowon': False,
   'ballnbr': 299,
   'rpb': 0.87,
   'partnership': {'partnership': [{'id': 0,
      'bat1id': 11172,
      'bat1name': 'Finn Allen',
      'bat1runs': 1,
      'bat1fours': 0,
      'bat1sixes': 0,
      'bat2id': 9838,
      'bat2name': 'Conway',
      'bat2runs': 0,
      'bat2fours': 0,
      'bat2sixes': 0,
      'totalruns': 2,
      'totalballs': 5,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 6326,
      'bat1name': 'Williamson',
      'bat1runs': 76,
      'bat1fours': 9,
      'bat1sixes': 0,
      'bat2id': 9838,
      'bat2name': 'Conway',
      'bat2runs': 101,
      'bat2fours': 13,
      'bat2sixes': 1,
      'totalruns': 181,
      'totalballs': 175,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 6326,
      'bat1name': 'Williamson',
      'bat1runs': 8,
      'bat1fours': 1,
      'bat1sixes': 0,
      'bat2id': 10713,
      'bat2name': 'Mitchell',
      'bat2runs': 5,
      'bat2fours': 1,
      'bat2sixes': 0,
      'totalruns': 13,
      'totalballs': 15,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 6326,
      'bat1name': 'Williamson',
      'bat1runs': 0,
      'bat1fours': 0,
      'bat1sixes': 0,
      'bat2id': 8216,
      'bat2name': 'Latham',
      'bat2runs': 2,
      'bat2fours': 0,
      'bat2sixes': 0,
      'totalruns': 2,
      'totalballs': 3,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 6326,
      'bat1name': 'Williamson',
      'bat1runs': 1,
      'bat1fours': 0,
      'bat1sixes': 0,
      'bat2id': 10693,
      'bat2name': 'Glenn Phillips',
      'bat2runs': 2,
      'bat2fours': 0,
      'bat2sixes': 0,
      'totalruns': 3,
      'totalballs': 11,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 9551,
      'bat1name': 'M Bracewell',
      'bat1runs': 4,
      'bat1fours': 0,
      'bat1sixes': 0,
      'bat2id': 10693,
      'bat2name': 'Glenn Phillips',
      'bat2runs': 1,
      'bat2fours': 0,
      'bat2sixes': 0,
      'totalruns': 5,
      'totalballs': 10,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 9551,
      'bat1name': 'M Bracewell',
      'bat1runs': 4,
      'bat1fours': 0,
      'bat1sixes': 0,
      'bat2id': 10100,
      'bat2name': 'Santner',
      'bat2runs': 9,
      'bat2fours': 0,
      'bat2sixes': 0,
      'totalruns': 14,
      'totalballs': 24,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 8561,
      'bat1name': 'Ish Sodhi',
      'bat1runs': 7,
      'bat1fours': 0,
      'bat1sixes': 0,
      'bat2id': 10100,
      'bat2name': 'Santner',
      'bat2runs': 9,
      'bat2fours': 0,
      'bat2sixes': 0,
      'totalruns': 18,
      'totalballs': 36,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 1057,
      'bat1name': 'Southee',
      'bat1runs': 0,
      'bat1fours': 0,
      'bat1sixes': 0,
      'bat2id': 10100,
      'bat2name': 'Santner',
      'bat2runs': 1,
      'bat2fours': 0,
      'bat2sixes': 0,
      'totalruns': 2,
      'totalballs': 5,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 10692,
      'bat1name': 'Ferguson',
      'bat1runs': 0,
      'bat1fours': 0,
      'bat1sixes': 0,
      'bat2id': 10100,
      'bat2name': 'Santner',
      'bat2runs': 17,
      'bat2fours': 1,
      'bat2sixes': 1,
      'totalruns': 20,
      'totalballs': 15,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0}]}},
  {'inningsid': 2,
   'batsman': [{'id': 10863,
     'balls': 7,
     'runs': 0,
     'fours': 0,
     'sixes': 0,
     'strkrate': '0',
     'name': 'Fakhar Zaman',
     'nickname': 'Fakhar Zaman',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c Latham b Southee',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 8364,
     'balls': 12,
     'runs': 6,
     'fours': 1,
     'sixes': 0,
     'strkrate': '50',
     'name': 'Imam-ul-Haq',
     'nickname': 'Imam-ul-Haq',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c Daryl Mitchell b Lockie Ferguson',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 8359,
     'balls': 114,
     'runs': 79,
     'fours': 8,
     'sixes': 1,
     'strkrate': '69.3',
     'name': 'Babar Azam',
     'nickname': 'Babar Azam',
     'iscaptain': True,
     'iskeeper': False,
     'outdec': 'st Latham b Ish Sodhi',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 9468,
     'balls': 50,
     'runs': 28,
     'fours': 2,
     'sixes': 0,
     'strkrate': '56',
     'name': 'Mohammad Rizwan',
     'nickname': 'Rizwan',
     'iscaptain': False,
     'iskeeper': True,
     'outdec': 'b Santner',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 8299,
     'balls': 21,
     'runs': 10,
     'fours': 0,
     'sixes': 0,
     'strkrate': '47.62',
     'name': 'Haris Sohail',
     'nickname': 'Haris Sohail',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'lbw b Glenn Phillips',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 10101,
     'balls': 22,
     'runs': 25,
     'fours': 2,
     'sixes': 0,
     'strkrate': '113.64',
     'name': 'Agha Salman',
     'nickname': 'Agha Salman',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'run out (Glenn Phillips)',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,

Extract batting data & Bowling data

In [29]:
import pandas as pd
import re

# We will store all player data here
player_performance = []

# Process each inning in the scorecard
for inning in data_56717.get("scorecard", []):
    # --- 1. BATSMAN DATA ---
    for b in inning.get("batsman", []):
        name = b.get("name")
        runs = int(b.get("runs", 0))
        balls = int(b.get("balls", 0))
        sr = float(b.get("strkrate", 0))
        out_desc = b.get("outdec", "")
        
        # Determine if the player is "Out" for the average calculation
        # In a single match, if they are out, average = runs. If not out, average is higher.
        is_out = 1 if out_desc.lower() != "not out" else 0
        bat_avg = runs / is_out if is_out > 0 else runs * 1.5 # Not out bonus
        
        # Batting formula: (runs * 0.01) + (avg * 0.5) + (sr * 0.3)
        bat_pts = (runs * 0.01) + (bat_avg * 0.5) + (sr * 0.3)
        
        # --- 2. FIELDING DATA (Parsed from out_desc) ---
        # We look for the player's name in the dismissal descriptions of OTHER players
        # Note: This logic usually requires checking all innings to see who caught whom.
        
        player_performance.append({
            "player": name,
            "format_score": round(bat_pts, 2),
            "runs": runs,
            "balls": balls,
            "strike": sr,
            "type": "Batsman"
        })

    # --- 3. BOWLER DATA ---
    for bw in inning.get("bowler", []):
        bw_name = bw.get("name")
        wkts = int(bw.get("wickets", 0))
        econ = float(bw.get("economy", 0))
        runs_conceded = int(bw.get("runs", 0))
        
        # Bowling average = runs / wickets
        bw_avg = runs_conceded / wkts if wkts > 0 else 50.0
        
        # Bowling formula: (wkts * 2) + (50 - avg) * 0.5 + (6 - econ) * 2
        bowl_pts = (wkts * 2) + ((50 - bw_avg) * 0.5) + ((6 - econ) * 2)
        
        player_performance.append({
            "player": bw_name,
            "format_score": round(bowl_pts, 2),
            "wickets": wkts,
            "economy": econ,
            "type": "Bowler"
        })

# Create the q2024 DataFrame
q19 = pd.DataFrame(player_performance)

# Rank players by total performance score
q19 = q19.sort_values(by="format_score", ascending=False)

print("### TOP PERFORMER RANKINGS ###")
print(q19[["player", "type", "format_score"]].head(10))

### TOP PERFORMER RANKINGS ###
               player     type  format_score
1              Conway  Batsman         84.44
2          Williamson  Batsman         68.85
19         Babar Azam  Batsman         61.08
22        Agha Salman  Batsman         46.84
7             Santner  Batsman         46.62
24          Usama Mir  Batsman         46.12
14              Nawaz   Bowler         32.65
20    Mohammad Rizwan  Batsman         31.08
25  Mohammad Wasim Jr  Batsman         28.18
3      Daryl Mitchell  Batsman         23.98

In [30]:
q19

,player,format_score,runs,balls,strike,type,wickets,economy
1,Conway,84.44,101.0,92.0,109.78,Batsman,NaN,NaN
2,Williamson,68.85,85.0,100.0,85.00,Batsman,NaN,NaN
19,Babar Azam,61.08,79.0,114.0,69.30,Batsman,NaN,NaN
22,Agha Salman,46.84,25.0,22.0,113.64,Batsman,NaN,NaN
7,Santner,46.62,37.0,40.0,92.50,Batsman,NaN,NaN
24,Usama Mir,46.12,12.0,9.0,133.33,Batsman,NaN,NaN
14,Nawaz,32.65,NaN,NaN,NaN,Bowler,4.0,3.8
20,Mohammad Rizwan,31.08,28.0,50.0,56.00,Batsman,NaN,NaN
25,Mohammad Wasim Jr,28.18,10.0,13.0,76.92,Batsman,NaN,NaN
3,Daryl Mitchell,23.98,5.0,7.0,71.43,Batsman,NaN,NaN
32,Ish Sodhi,21.90,NaN,NaN,NaN,Bowler,2.0,4.8
28,Tim Southee,21.75,NaN,NaN,NaN,Bowler,2.0,5.5
6,M Bracewell,21.22,8.0,14.0,57.14,Batsman,NaN,NaN
4,Latham,21.02,2.0,3.0,66.67,Batsman,NaN,NaN
11,Naseem Shah,20.13,NaN,NaN,NaN,Bowler,3.0,6.6
23,Mohammad Nawaz,19.53,3.0,5.0,60.00,Batsman,NaN,NaN
33,Glenn Phillips,19.50,NaN,NaN,NaN,Bowler,1.0,6.5
21,Haris Sohail,19.39,10.0,21.0,47.62,Batsman,NaN,NaN
31,Michael Bracewell,18.70,NaN,NaN,NaN,Bowler,1.0,2.9
18,Imam-ul-Haq,18.06,6.0,12.0,50.00,Batsman,NaN,NaN
30,Mitchell Santner,15.20,NaN,NaN,NaN,Bowler,1.0,3.4
29,Lockie Ferguson,14.70,NaN,NaN,NaN,Bowler,1.0,4.4
8,Ish Sodhi,13.12,7.0,22.0,31.82,Batsman,NaN,NaN
5,Glenn Phillips,12.78,3.0,8.0,37.50,Batsman,NaN,NaN
15,Usama Mir,9.60,NaN,NaN,NaN,Bowler,1.0,4.2
0,Finn Allen,8.01,1.0,4.0,25.00,Batsman,NaN,NaN
12,Haris Rauf,6.10,NaN,NaN,NaN,Bowler,1.0,4.7
9,Southee,0.00,0.0,4.0,0.00,Batsman,NaN,NaN
10,Lockie Ferguson,0.00,0.0,5.0,0.00,Batsman,NaN,NaN
17,Fakhar Zaman,0.00,0.0,7.0,0.00,Batsman,NaN,NaN
26,Naseem Shah,0.00,0.0,2.0,0.00,Batsman,NaN,NaN
27,Haris Rauf,0.00,0.0,3.0,0.00,Batsman,NaN,NaN
13,Mohammad Wasim Jr,-1.20,NaN,NaN,NaN,Bowler,0.0,6.6
16,Agha Salman,-2.00,NaN,NaN,NaN,Bowler,0.0,7.0

In [57]:
import urllib.parse
from sqlalchemy import create_engine

# 1. Encode the special character in password
password = urllib.parse.quote_plus("deepika@88")

# 2. Use the encoded password in your connection string
# Also, ensure 'username' is replaced with your actual DB user (usually 'postgres')
engine = create_engine(f'postgresql+psycopg2://postgres:{password}@localhost:5432/cricbuzz')

# 3. Test the connection and push the data
q19.to_sql('q19_stddev_2022', engine, if_exists='replace', index=False)

print("✅ Connection successful and table 'Player details stored' created!")

✅ Connection successful and table 'Player details stored' created!

# q19 final data

In [4]:
import pandas as pd
import numpy as np

# 'data' is the variable containing your JSON structure
raw_innings = []

# Step 1: Extract match data from JSON
for inning in data_56717['scorecard']:
    for batsman in inning['batsman']:
        raw_innings.append({
            'name': batsman['name'],
            'runs': int(batsman['runs']),
            'balls': int(batsman['balls'])
        })

df_matches = pd.DataFrame(raw_innings)

# Step 2: Apply the "Question 19" filter (at least 10 balls faced)
df_filtered = df_matches[df_matches['balls'] >= 10]

# Step 3: Calculate Average and Standard Deviation
# Standard Deviation (std) measures the variation in runs (Consistency)
consistency_df = df_filtered.groupby('name')['runs'].agg(['mean', 'std', 'count']).reset_index()
consistency_df.columns = ['Batsman', 'Avg_Runs', 'Std_Dev', 'Innings_Count']

# Step 4: Sort by lowest Std_Dev (Most Consistent)
# Note: We filter for Innings_Count > 1 because SD requires at least two data points
consistent_batsmen = consistency_df[consistency_df['Innings_Count'] > 1].sort_values('Std_Dev')

print(consistent_batsmen)

         Batsman  Avg_Runs     Std_Dev  Innings_Count
11     Mir Hamza       2.0    1.414214              2
13    Nauman Ali       5.5    2.121320              2
10        Masood       6.5    4.949747              2
16      Shafique      12.0    7.071068              2
15  Saud Shakeel      38.5   23.334524              2
14      Sarfaraz      69.5   23.334524              2
6    Imam-ul-Haq      60.0   50.911688              2
0    Agha Salman      54.5   68.589358              2
1     Babar Azam      87.5  103.944697              2

In [17]:
import urllib.parse
from sqlalchemy import create_engine

# 1. Encode the special character in password
password = urllib.parse.quote_plus("deepika@88")

# 2. Use the encoded password in your connection string
# Also, ensure 'username' is replaced with your actual DB user (usually 'postgres')
engine = create_engine(f'postgresql+psycopg2://postgres:{password}@localhost:5432/cricbuzz')

# 3. Test the connection and push the data
consistent_batsmen.to_sql('q19_stddevi_2022', engine, if_exists='replace', index=False)

print("✅ Connection successful and table 'Player standard deviation stored' created!")

✅ Connection successful and table 'Player standard deviation stored' created!

# Q21 analysis

In [31]:
import pandas as pd
import numpy as np

# Assuming 'data' contains your JSON scorecard structure
batting_records = []

for inning in data_56717['scorecard']:
    for b in inning.get('batsman', []):
        # Determine if the player was out to calculate average correctly
        is_out = 0 if "not out" in b.get('outdec', '').lower() else 1
        
        batting_records.append({
            'name': b['name'],
            'runs': int(b['runs']),
            'balls': int(b['balls']),
            'is_out': is_out
        })

df_batting = pd.DataFrame(batting_records)

# 1. Aggregate totals across all innings
perf = df_batting.groupby('name').agg({
    'runs': 'sum',
    'balls': 'sum',
    'is_out': 'sum'  # Total times dismissed
}).reset_index()

# 2. Apply Question 19 Filter: Minimum 10 balls faced in total
perf = perf[perf['balls'] >= 10]

# 3. Calculate Batting Average (Total Runs / Total Dismissals)
# If a player was never out (is_out == 0), the average is their total runs
perf['batting_avg'] = np.where(
    perf['is_out'] > 0, 
    perf['runs'] / perf['is_out'], 
    perf['runs']
)

# 4. Calculate Strike Rate (Runs / Balls * 100)
perf['strike_rate'] = (perf['runs'] / perf['balls']) * 100

# 5. Final Sorting by Runs Scored
perf = perf.sort_values(by='runs', ascending=False)

print(perf[['name', 'runs', 'batting_avg', 'strike_rate']].round(2))

                 name  runs  batting_avg  strike_rate
2              Conway   101        101.0       109.78
21         Williamson    85         85.0        85.00
1          Babar Azam    79         79.0        69.30
18            Santner    37         37.0        92.50
15    Mohammad Rizwan    28         28.0        56.00
0         Agha Salman    25         25.0       113.64
8        Haris Sohail    10         10.0        47.62
16  Mohammad Wasim Jr    10         10.0        76.92
13        M Bracewell     8          8.0        57.14
10          Ish Sodhi     7          7.0        31.82
9         Imam-ul-Haq     6          6.0        50.00

# q21 bwler

In [32]:
import pandas as pd
import numpy as np

# Assuming 'data' is your JSON variable
bowling_data = []

for inning in data_56717['scorecard']:
    for b in inning.get('bowler', []):
        bowling_data.append({
            'name': b['name'],
            'wickets': int(b['wickets']),
            'runs': int(b['runs']),
            'economy': float(b['economy']),
            'balls': int(b['balls'])
        })

df_bowling = pd.DataFrame(bowling_data)

# 1. Aggregate totals (in case a bowler bowled in multiple innings)
perf_bow = df_bowling.groupby('name').agg({
    'wickets': 'sum',
    'runs': 'sum',
    'economy': 'mean', # Average economy across innings
    'balls': 'sum'
}).reset_index()

# 2. Calculate the "Missing" Bowling Average
# We use 0.5 as a divisor for 0-wicket hauls to avoid Infinity, or handle via np.where
perf_bow['bowling_avg'] = np.where(perf_bow['wickets'] > 0, perf_bow['runs'] / perf_bow['wickets'], perf_bow['runs'] + 10) 

# 3. Calculate Weighted Bowling Score
# Formula: (Wickets * 25) + ((3.5 - Economy) * 10) + ((35 - Avg) * 0.5)
perf_bow['Bowling_Score'] = (
    (perf_bow['wickets'] * 25) + 
    ((3.5 - perf_bow['economy']) * 10) + 
    ((35 - perf_bow['bowling_avg']) * 0.5)
)

# 4. Final Formatting
perf_bow = perf_bow.sort_values(by='Bowling_Score', ascending=False)
print(perf_bow[['name', 'wickets', 'bowling_avg', 'economy', 'Bowling_Score']].round(2))

                 name  wickets  bowling_avg  economy  Bowling_Score
9               Nawaz        4         9.50      3.8         109.75
8         Naseem Shah        3        19.33      6.6          51.83
3           Ish Sodhi        2        19.00      4.8          45.00
10        Tim Southee        2        16.50      5.5          39.25
5   Michael Bracewell        1        29.00      2.9          34.00
6    Mitchell Santner        1        34.00      3.4          26.50
4     Lockie Ferguson        1        31.00      4.4          18.00
11          Usama Mir        1        42.00      4.2          14.50
2          Haris Rauf        1        47.00      4.7           7.00
1      Glenn Phillips        1        13.00      6.5           6.00
0         Agha Salman        0        38.00      7.0         -36.50
7   Mohammad Wasim Jr        0        56.00      6.6         -41.50

# q21 fielding

In [33]:
import pandas as pd
import re

# Assuming 'data' contains your JSON scorecard structure
fielding_stats = {}

def add_stat(player_name, stat_type):
    player_name = player_name.strip()
    if player_name not in fielding_stats:
        fielding_stats[player_name] = {'catches': 0, 'stumpings': 0, 'run_outs': 0}
    fielding_stats[player_name][stat_type] += 1

# Process each inning in the scorecard
for inning in data_56717['scorecard']:
    for batsman in inning.get('batsman', []):
        out_desc = batsman.get('outdec', "").lower()
        
        # 1. Parse Catches: "c Fielder b Bowler" or "c & b Bowler"
        if out_desc.startswith('c '):
            if '& b' in out_desc: # Caught and Bowled
                fielder = out_desc.split('& b')[1].strip()
            else: # Standard Catch
                # Extract text between 'c ' and ' b '
                match = re.search(r'c (.*?) b ', out_desc)
                if match:
                    fielder = match.group(1)
            add_stat(fielder, 'catches')

        # 2. Parse Stumpings: "st Fielder b Bowler"
        elif out_desc.startswith('st '):
            match = re.search(r'st (.*?) b ', out_desc)
            if match:
                fielder = match.group(1)
                add_stat(fielder, 'stumpings')

        # 3. Parse Run Outs: "run out (Fielder)"
        elif 'run out' in out_desc:
            match = re.search(r'\((.*?)\)', out_desc)
            if match:
                fielder = match.group(1)
                # Note: If multiple fielders are listed (e.g., Fielder1/Fielder2), 
                # you can split by '/' and give both credit.
                for f in fielder.split('/'):
                    add_stat(f, 'run_outs')

# Convert to DataFrame for scoring
df_fielding = pd.DataFrame.from_dict(fielding_stats, orient='index').reset_index()
df_fielding.columns = ['Player', 'Catches', 'Stumpings', 'Run_Outs']

# Calculate Weighted Score
# Catch = 10, Stumping = 15, Run Out = 20
df_fielding['Fielding_Score'] = (
    (df_fielding['Catches'] * 10) + 
    (df_fielding['Stumpings'] * 15) + 
    (df_fielding['Run_Outs'] * 20)
)

# Sort by best performers
df_fielding = df_fielding.sort_values(by='Fielding_Score', ascending=False)
print(df_fielding)

               Player  Catches  Stumpings  Run_Outs  Fielding_Score
5              latham        2          1         0              35
1              rizwan        1          0         1              30
3   mohammad wasim jr        0          0         1              20
9             santner        0          0         1              20
7      glenn phillips        0          0         1              20
8          williamson        0          0         1              20
0               nawaz        1          0         0              10
2        fakhar zaman        1          0         0              10
4           usama mir        1          0         0              10
6      daryl mitchell        1          0         0              10
10        m bracewell        1          0         0              10

In [36]:
import pandas as pd
import numpy as np
import re

def calculate_player_rankings(data_56717):
    """
    Calculates weighted performance scores for all players in the scorecard.
    """
    players = {}

    def get_player(name):
        name = name.strip().title()
        if name not in players:
            players[name] = {
                'bat_runs': 0, 'bat_balls': 0, 'bat_outs': 0,
                'bowl_wickets': 0, 'bowl_runs': 0, 'bowl_inns': 0, 'bowl_econ_sum': 0,
                'f_catches': 0, 'f_stumpings': 0, 'f_runouts': 0
            }
        return players[name]

    # Step 1: Extract Data from Scorecard
    for inning in data_56717.get('scorecard', []):
        # Batting & Fielding Extraction
        for b in inning.get('batsman', []):
            p = get_player(b['name'])
            p['bat_runs'] += int(b.get('runs', 0))
            p['bat_balls'] += int(b.get('balls', 0))
            out_desc = b.get('outdec', '').lower()
            if out_desc and 'not out' not in out_desc:
                p['bat_outs'] += 1
            
            # Parsing Fielding (Catches, Stumpings, Run Outs)
            if out_desc.startswith('c '):
                # Handle Caught & Bowled
                if '& b' in out_desc:
                    fielder_name = out_desc.split('& b')[1].strip()
                else:
                    match = re.search(r'^c (.*?) b ', out_desc)
                    fielder_name = match.group(1).replace('(sub)', '').strip() if match else None
                if fielder_name: get_player(fielder_name)['f_catches'] += 1
            
            elif out_desc.startswith('st '):
                match = re.search(r'^st (.*?) b ', out_desc)
                fielder_name = match.group(1).strip() if match else None
                if fielder_name: get_player(fielder_name)['f_stumpings'] += 1
                
            elif 'run out' in out_desc:
                match = re.search(r'\((.*?)\)', out_desc)
                if match:
                    for f in match.group(1).split('/'):
                        get_player(f.strip())['f_runouts'] += 1

        # Bowling Extraction
        for bowl in inning.get('bowler', []):
            p = get_player(bowl['name'])
            p['bowl_wickets'] += int(bowl.get('wickets', 0))
            p['bowl_runs'] += int(bowl.get('runs', 0))
            p['bowl_econ_sum'] += float(bowl.get('economy', 0))
            p['bowl_inns'] += 1

    # Step 2: Apply Weighted Formulas
    results = []
    for name, s in players.items():
        # Batting Points
        bat_avg = s['bat_runs'] / max(1, s['bat_outs'])
        bat_sr = (s['bat_runs'] / max(1, s['bat_balls'])) * 100
        bat_pts = (s['bat_runs'] * 0.01) + (bat_avg * 0.5) + (bat_sr * 0.3) if s['bat_balls'] > 0 else 0
        
        # Bowling Points
        if s['bowl_inns'] > 0:
            # Handle cases where wickets = 0 for average
            b_avg = s['bowl_runs'] / s['bowl_wickets'] if s['bowl_wickets'] > 0 else 50
            avg_econ = s['bowl_econ_sum'] / s['bowl_inns']
            bowl_pts = (s['bowl_wickets'] * 2) + ((50 - b_avg) * 0.5) + ((6 - avg_econ) * 2)
        else:
            bowl_pts = 0
            
        # Fielding Points
        field_pts = (s['f_catches'] * 10) + (s['f_stumpings'] * 15) + (s['f_runouts'] * 20)
        
        total_score = bat_pts + bowl_pts + field_pts
        
        results.append({
            'Player': name,
            'Batting': round(bat_pts, 2),
            'Bowling': round(bowl_pts, 2),
            'Fielding': round(field_pts, 2),
            'Total Score': round(total_score, 2),
            'format' : 'ODI'
        })

    # Return final DataFrame ranked by Total Score
    return pd.DataFrame(results).sort_values(by='Total Score', ascending=False)

# usage:
df_rankings = calculate_player_rankings(data_56717)
print(df_rankings)

               Player  Batting  Bowling  Fielding  Total Score format
3          Williamson    68.85     0.00        20        88.85    ODI
2              Conway    84.44     0.00         0        84.44    ODI
10            Santner    46.62     0.00        20        66.62    ODI
14          Usama Mir    46.12     9.60        10        65.72    ODI
20         Babar Azam    61.08     0.00         0        61.08    ODI
6              Latham    21.02     0.00        35        56.02    ODI
7      Glenn Phillips    12.78    19.50        20        52.28    ODI
11  Mohammad Wasim Jr    28.18    -1.20        20        46.98    ODI
18        Agha Salman    46.84    -2.00         0        44.84    ODI
1               Nawaz     0.00    32.65        10        42.65    ODI
12          Ish Sodhi    13.12    21.90         0        35.02    ODI
4      Daryl Mitchell    23.98     0.00        10        33.98    ODI
9         M Bracewell    21.22     0.00        10        31.22    ODI
21    Mohammad Rizwan    31.08     0.00         0        31.08    ODI
5              Rizwan     0.00     0.00        30        30.00    ODI
24        Tim Southee     0.00    21.75         0        21.75    ODI
16        Naseem Shah     0.00    20.13         0        20.13    ODI
23     Mohammad Nawaz    19.53     0.00         0        19.53    ODI
22       Haris Sohail    19.39     0.00         0        19.39    ODI
26  Michael Bracewell     0.00    18.70         0        18.70    ODI
19        Imam-Ul-Haq    18.06     0.00         0        18.06    ODI
25   Mitchell Santner     0.00    15.20         0        15.20    ODI
15    Lockie Ferguson     0.00    14.70         0        14.70    ODI
8        Fakhar Zaman     0.00     0.00        10        10.00    ODI
0          Finn Allen     8.01     0.00         0         8.01    ODI
17         Haris Rauf     0.00     6.10         0         6.10    ODI
13            Southee     0.00     0.00         0         0.00    ODI

In [37]:
df_rankings

               Player  Batting  Bowling  Fielding  Total Score format
3          Williamson    68.85     0.00        20        88.85    ODI
2              Conway    84.44     0.00         0        84.44    ODI
10            Santner    46.62     0.00        20        66.62    ODI
14          Usama Mir    46.12     9.60        10        65.72    ODI
20         Babar Azam    61.08     0.00         0        61.08    ODI
6              Latham    21.02     0.00        35        56.02    ODI
7      Glenn Phillips    12.78    19.50        20        52.28    ODI
11  Mohammad Wasim Jr    28.18    -1.20        20        46.98    ODI
18        Agha Salman    46.84    -2.00         0        44.84    ODI
1               Nawaz     0.00    32.65        10        42.65    ODI
12          Ish Sodhi    13.12    21.90         0        35.02    ODI
4      Daryl Mitchell    23.98     0.00        10        33.98    ODI
9         M Bracewell    21.22     0.00        10        31.22    ODI
21    Mohammad Rizwan    31.08     0.00         0        31.08    ODI
5              Rizwan     0.00     0.00        30        30.00    ODI
24        Tim Southee     0.00    21.75         0        21.75    ODI
16        Naseem Shah     0.00    20.13         0        20.13    ODI
23     Mohammad Nawaz    19.53     0.00         0        19.53    ODI
22       Haris Sohail    19.39     0.00         0        19.39    ODI
26  Michael Bracewell     0.00    18.70         0        18.70    ODI
19        Imam-Ul-Haq    18.06     0.00         0        18.06    ODI
25   Mitchell Santner     0.00    15.20         0        15.20    ODI
15    Lockie Ferguson     0.00    14.70         0        14.70    ODI
8        Fakhar Zaman     0.00     0.00        10        10.00    ODI
0          Finn Allen     8.01     0.00         0         8.01    ODI
17         Haris Rauf     0.00     6.10         0         6.10    ODI
13            Southee     0.00     0.00         0         0.00    ODI

In [38]:
import urllib.parse
from sqlalchemy import create_engine

# 1. Encode the special character in password
password = urllib.parse.quote_plus("deepika@88")

# 2. Use the encoded password in your connection string
# Also, ensure 'username' is replaced with your actual DB user (usually 'postgres')
engine = create_engine(f'postgresql+psycopg2://postgres:{password}@localhost:5432/cricbuzz')

# 3. Test the connection and push the data
df_rankings.to_sql('q21_player_rank', engine, if_exists='append', index=False)

print("✅ Connection successful and table 'Player standard deviation stored' created!")

✅ Connection successful and table 'Player standard deviation stored' created!

# Recent match

In [41]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/matches/v1/recent"

headers = {
	"x-rapidapi-key": "e6021fb984msh201af5139a6e2e9p149939jsn32edaa5716a4",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

recent=response.json()

In [42]:
recent

{'typeMatches': [{'matchType': 'International',
   'seriesMatches': [{'seriesAdWrapper': {'seriesId': 11253,
      'seriesName': "ICC Men's T20 World Cup 2026",
      'matches': [{'matchInfo': {'matchId': 139489,
         'seriesId': 11253,
         'seriesName': "ICC Men's T20 World Cup 2026",
         'matchDesc': 'Final',
         'matchFormat': 'T20',
         'startDate': '1772976600000',
         'endDate': '1772989200000',
         'state': 'Complete',
         'status': 'India won by 96 runs',
         'team1': {'teamId': 2,
          'teamName': 'India',
          'teamSName': 'IND',
          'imageId': 776162},
         'team2': {'teamId': 13,
          'teamName': 'New Zealand',
          'teamSName': 'NZ',
          'imageId': 776333},
         'venueInfo': {'id': 50,
          'ground': 'Narendra Modi Stadium',
          'city': 'Ahmedabad',
          'timezone': '+05:30',
          'latitude': '23.091785',
          'longitude': '72.597465'},
         'currBatTeamId': 2,
         'seriesStartDt': '1770422400000',
         'seriesEndDt': '1773100800000',
         'isTimeAnnounced': True,
         'stateTitle': 'IND Won',
         'isFantasyEnabled': True},
        'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
           'runs': 255,
           'wickets': 5,
           'overs': 19.6}},
         'team2Score': {'inngs1': {'inningsId': 2,
           'runs': 159,
           'wickets': 10,
           'overs': 18.6}}}},
       {'matchInfo': {'matchId': 139478,
         'seriesId': 11253,
         'seriesName': "ICC Men's T20 World Cup 2026",
         'matchDesc': '2nd Semi-Final',
         'matchFormat': 'T20',
         'startDate': '1772717400000',
         'endDate': '1772730000000',
         'state': 'Complete',
         'status': 'India won by 7 runs',
         'team1': {'teamId': 2,
          'teamName': 'India',
          'teamSName': 'IND',
          'imageId': 776162},
         'team2': {'teamId': 9,
          'teamName': 'England',
          'teamSName': 'ENG',
          'imageId': 776237},
         'venueInfo': {'id': 81,
          'ground': 'Wankhede Stadium',
          'city': 'Mumbai',
          'timezone': '+05:30',
          'latitude': '18.938956',
          'longitude': '72.825719'},
         'currBatTeamId': 2,
         'seriesStartDt': '1770422400000',
         'seriesEndDt': '1773100800000',
         'isTimeAnnounced': True,
         'stateTitle': 'IND Won',
         'isFantasyEnabled': True},
        'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
           'runs': 253,
           'wickets': 7,
           'overs': 19.6}},
         'team2Score': {'inngs1': {'inningsId': 2,
           'runs': 246,
           'wickets': 7,
           'overs': 19.6}}}},
       {'matchInfo': {'matchId': 139472,
         'seriesId': 11253,
         'seriesName': "ICC Men's T20 World Cup 2026",
         'matchDesc': '1st Semi-Final',
         'matchFormat': 'T20',
         'startDate': '1772631000000',
         'endDate': '1772643600000',
         'state': 'Complete',
         'status': 'New Zealand won by 9 wkts',
         'team1': {'teamId': 11,
          'teamName': 'South Africa',
          'teamSName': 'RSA',
          'imageId': 776287},
         'team2': {'teamId': 13,
          'teamName': 'New Zealand',
          'teamSName': 'NZ',
          'imageId': 776333},
         'venueInfo': {'id': 31,
          'ground': 'Eden Gardens',
          'city': 'Kolkata',
          'timezone': '+05:30',
          'latitude': '22.564527',
          'longitude': '88.343247'},
         'currBatTeamId': 13,
         'seriesStartDt': '1770422400000',
         'seriesEndDt': '1773100800000',
         'isTimeAnnounced': True,
         'stateTitle': 'NZ Won',
         'isFantasyEnabled': True},
        'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
           'runs': 169,
           'wickets': 8,
           'overs': 19.6}},
         'team2Score': {'inngs1': {'inningsId': 2,
           'runs': 173,
           'wickets': 1,
           'overs': 12.5}}}}]}},
    {'seriesAdWrapper': {'seriesId': 11584,
      'seriesName': 'Pakistan tour of Bangladesh, 2026',
      'matches': [{'matchInfo': {'matchId': 147863,
         'seriesId': 11584,
         'seriesName': 'Pakistan tour of Bangladesh, 2026',
         'matchDesc': '1st ODI',
         'matchFormat': 'ODI',
         'startDate': '1773216900000',
         'endDate': '1773245700000',
         'state': 'Complete',
         'status': 'Bangladesh won by 8 wkts',
         'team1': {'teamId': 3,
          'teamName': 'Pakistan',
          'teamSName': 'PAK',
          'imageId': 776308},
         'team2': {'teamId': 6,
          'teamName': 'Bangladesh',
          'teamSName': 'BAN',
          'imageId': 776210},
         'venueInfo': {'id': 128,
          'ground': 'Shere Bangla National Stadium',
          'city': 'Dhaka',
          'timezone': '+06:00',
          'latitude': '23.806966',
          'longitude': '90.363576'},
         'currBatTeamId': 6,
         'seriesStartDt': '1773187200000',
         'seriesEndDt': '1773705600000',
         'isTimeAnnounced': True,
         'stateTitle': 'Complete',
         'isFantasyEnabled': True},
        'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
           'runs': 114,
           'wickets': 10,
           'overs': 30.4}},
         'team2Score': {'inngs1': {'inningsId': 2,
           'runs': 115,
           'wickets': 2,
           'overs': 15.1}}}}]}},
    {'seriesAdWrapper': {'seriesId': 11689,
      'seriesName': 'Bahrain tour of Malaysia, 2026',
      'matches': [{'matchInfo': {'matchId': 148742,
         'seriesId': 11689,
         'seriesName': 'Bahrain tour of Malaysia, 2026',
         'matchDesc': '3rd T20I',
         'matchFormat': 'T20',
         'startDate': '1773126000000',
         'endDate': '1773138600000',
         'state': 'Complete',
         'status': 'Bahrain won by 7 wkts  -  DLS Method (Target : 132)',
         'team1': {'teamId': 71,
          'teamName': 'Malaysia',
          'teamSName': 'MLY',
          'imageId': 776319},
         'team2': {'teamId': 543,
          'teamName': 'Bahrain',
          'teamSName': 'BHR',
          'imageId': 172594},
         'venueInfo': {'id': 394,
          'ground': 'Bayuemas Oval',
          'city': 'Kuala Lumpur',
          'timezone': '+08:00',
          'latitude': '2.819586',
          'longitude': '101.5199'},
         'currBatTeamId': 543,
         'seriesStartDt': '1772841600000',
         'seriesEndDt': '1773273600000',
         'isTimeAnnounced': True,
         'stateTitle': 'BHR Won'},
        'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
           'runs': 131,
           'wickets': 7,
           'overs': 18.6}},
         'team2Score': {'inngs1': {'inningsId': 2,
           'runs': 135,
           'wickets': 3,
           'overs': 17.1}}}},
       {'matchInfo': {'matchId': 148731,
         'seriesId': 11689,
         'seriesName': 'Bahrain tour of Malaysia, 2026',
         'matchDesc': '2nd T20I',
         'matchFormat': 'T20',
         'startDate': '1772953200000',
         'endDate': '1772965800000',
         'state': 'Complete',
         'status': 'Bahrain won by 2 runs',
         'team1': {'teamId': 543,
          'teamName': 'Bahrain',
          'teamSName': 'BHR',
          'imageId': 172594},
         'team2': {'teamId': 71,
          'teamName': 'Malaysia',
          'teamSName': 'MLY',
          'imageId': 776319},
         'venueInfo': {'id': 394,
          'ground': 'Bayuemas Oval',
          'city': 'Kuala Lumpur',
          'timezone': '+08:00',
          'latitude': '2.819586',
          'longitude': '101.5199'},
         'currBatTeamId': 543,
         'seriesStartDt': '1772841600000',
         'seriesEndDt': '1773273600000',
         'isTimeAnnounced': True,
         'stateTitle': 'BHR Won'},
        'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
           'runs': 130,
           'wickets': 7,
           'overs': 19.6}},
         'team2Score': {'inngs1': {'inningsId': 2,
           'runs': 128,
           'wickets': 10,
           'overs': 19.5}}}},
       {'matchInfo': {'matchId': 148720,
         'seriesId': 11689,
         'seriesName': 'Bahrain tour of Malaysia, 2026',
         'matchDesc': '1st T20I',
         'matchFormat': 'T20',
         'startDate': '1772866800000',
         'endDate': '1772879400000',
         'state': 'Complete',
         'status': 'Malaysia won by 34 runs',
         'team1': {'teamId': 71,
          'teamName': 'Malaysia',
          'teamSName': 'MLY',
          'imageId': 776319},
         'team2': {'teamId': 543,
          'teamName': 'Bahrain',
          'teamSName': 'BHR',
          'imageId': 172594},
         'venueInfo': {'id': 394,
          'ground': 'Bayuemas Oval',
          'city': 'Kuala Lumpur',
          'timezone': '+08:00',
          'latitude': '2.819586',
          'longitude': '101.5199'},
         'currBatTeamId': 71,
         'seriesStartDt': '1772841600000',
         'seriesEndDt': '1773273600000',
         'isTimeAnnounced': True,
         'stateTitle': 'MLY Won'},
        'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
           'runs': 140,
           'wickets': 7,
           'overs': 19.6}},
         'team2Score': {'inngs1': {'inningsId': 2,
           'runs': 106,
           'wickets': 10,
           'overs': 18.5}}}}]}},
    {'ad': {'name': 'native_matches',
      'layout': 'native_large',
      'position': 3}},
    {'seriesAdWrapper': {'seriesId': 11570,
      'seriesName': "ICC Men's T20 2028 World Cup Americas Sub Regional Qualifier B, 2026",
      'matches': [{'matchInfo': {'matchId': 147535,
         'seriesId': 11570,
         'seriesName': "ICC Men's T20 2028 World Cup Americas Sub Regional Qualifier B, 2026",
         'matchDesc': '4th Match',
         'matchFormat': 'T20',
         'startDate': '1773084600000',
         'endDate': '1773097200000',
         'state': 'Complete',
         'status': 'Cayman Islands won by 9 wkts',
         'team1': {'teamId': 544,
          'teamName': 'Mexico',
          'teamSName': 'MEX',
          'imageId': 172595},
         'team2': {'teamId': 1020,
          'teamName': 'Cayman Islands',
          'teamSName': 'CAYM',
          'imageId': 248399},
         'venueInfo': {'id': 892,
          'ground': 'Jimmy Powell Oval',
          'city': 'George Town',
          'timezone': '-05:00',
          'latitude': '19.286932',
          'longitude': '-81.367439'},
         'currBatTeamId': 1020,
         'seriesStartDt': '1772928000000',
         'seriesEndDt': '1773792000000',
         'isTimeAnnounced': True,
         'stateTitle': 'CAYM Won'},
        'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
           'runs': 94,
           'wickets': 9,
           'overs': 19.6}},
         'team2Score': {'inngs1': {'inningsId': 2,
           'runs': 95,
           'wickets': 1,
           'overs': 13.3}}}},
       {'matchInfo': {'matchId': 147488,
         'seriesId': 11570,
         'seriesName': "ICC Men's T20 2028 World Cup Americas Sub Regional Qualifier B, 2026",
         'matchDesc': '3rd Match',
         'matchFormat': 'T20',
         'startDate': '1773066600000',
         'endDate': '1773079200000',
         'state': 'Complete',
         'status': 'Argentina won by 15 runs',
         'team1': {'teamId': 549,
          'teamName': 'Argentina',
          'teamSName': 'ARG',
          'imageId': 172601},
         'team2': {'teamId': 2285,
          'teamName': 'Suriname',
          'teamSName': 'SN',
          'imageId': 582333},
         'venueInfo': {'id': 892,
          'ground': 'Jimmy Powell Oval',
          'city': 'George Town',
          'timezone': '-05:00',
          'latitude': '19.286932',
          'longitude': '-81.367439'},
         'currBatTeamId': 549,
         'seriesStartDt': '1772928000000',
         'seriesEndDt': '1773792000000',
         'isTimeAnnounced': True,
         'stateTitle': 'ARG Won'},
        'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
           'runs': 129,
           'wickets': 9,
           'overs': 19.6}},
         'team2Score': {'inngs1': {'inningsId': 2,
           'runs': 114,
           'wickets': 8,
           'overs': 19.6}}}},
       {'matchInfo': {'matchId': 147486,
         'seriesId': 11570,
         'seriesName': "ICC Men's T20 2028 World Cup Americas Sub Regional Qualifier B, 2026",
         'matchDesc': '2nd Match',
         'matchFormat': 'T20',
         'startDate': '1772998200000',
         'endDate': '1773010800000',
         'state': 'Complete',
         'status': 'Mexico won by 9 runs',
         'team1': {'teamId': 544,
          'teamName': 'Mexico',
          'teamSName': 'MEX',
          'imageId': 172595},
         'team2': {'teamId': 2285,
          'teamName': 'Suriname',
          'teamSName': 'SN',
          'imageId': 582333},
         'venueInfo': {'id': 892,
          'ground': 'Jimmy Powell Oval',
          'city': 'George Town',
          'timezone': '-05:00',
          'latitude': '19.286932',
          'longitude': '-81.367439'},
         'currBatTeamId': 544,
         'seriesStartDt': '1772928000000',
         'seriesEndDt': '1773792000000',
         'isTimeAnnounced': True,
         'stateTitle': 'MEX Won'},
        'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
           'runs': 97,
           'wickets': 10,
           'overs': 19.5}},
         'team2Score': {'inngs1': {'inningsId': 2,
           'runs': 88,
           'wickets': 8,
           'overs': 19.6}}}},
       {'matchInfo': {'matchId': 147192,
         'seriesId': 11570,
         'seriesName': "ICC Men's T20 2028 World Cup Americas Sub Regional Qualifier B, 2026",
         'matchDesc': '1st Match',
         'matchFormat': 'T20',
         'startDate': '1772980200000',
         'endDate': '1772992800000',
         'state': 'Complete',
         'status': 'Cayman Islands won by 10 wkts',
         'team1': {'teamId': 549,
          'teamName': 'Argentina',
          'teamSName': 'ARG',
          'imageId': 172601},
         'team2': {'teamId': 1020,
          'teamName': 'Cayman Islands',
          'teamSName': 'CAYM',
          'imageId': 248399},
         'venueInfo': {'id': 892,
          'ground': 'Jimmy Powell Oval',
          'city': 'George Town',
          'timezone': '-05:00',
          'latitude': '19.286932',
          'longitude': '-81.367439'},
         'currBatTeamId': 1020,
         'seriesStartDt': '1772928000000',
         'seriesEndDt': '1773792000000',
         'isTimeAnnounced': True,
         'stateTitle': 'CAYM Won'},
        'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
           'runs': 96,
           'wickets': 10,
           'overs': 17.1}},
         'team2Score': {'inngs1': {'inningsId': 2,
           'runs': 102,
           'overs': 8.6}}}}]}},
    {'seriesAdWrapper': {'seriesId': 11711,
      'seriesName': 'Lesotho tour of Botswana, 2026',
      'matches': [{'matchInfo': {'matchId': 148925,
         'seriesId': 11711,
         'seriesName': 'Lesotho tour of Botswana, 2026',
         'matchDesc': '2nd T20I',
         'matchFormat': 'T20',
         'startDate': '1773144000000',
         'endDate': '1773156600000',
         'state': 'Complete',
         'status': 'Botswana won by 6 wkts',
         'team1': {'teamId': 570,
          'teamName': 'Lesotho',
          'teamSName': 'LSO',
          'imageId': 172622},
         'team2': {'teamId': 529,
          'teamName': 'Botswana',
          'teamSName': 'BW',
          'imageId': 776225},
         'venueInfo': {'id': 1305,
          'ground': 'Botswana Cricket Association Oval 1',
          'city': 'Gaborone',
          'timezone': '+02:00',
          'latitude': '24.661180',
          'longitude': '25.911751'},
         'currBatTeamId': 529,
         'seriesStartDt': '1773014400000',
         'seriesEndDt': '1773705600000',
         'isTimeAnnounced': True,
         'stateTitle': 'BW Won'},
        'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
           'runs': 81,
           'wickets': 8,
           'overs': 19.6}},
         'team2Score': {'inngs1': {'inningsId': 2,
           'runs': 83,
           'wickets': 4,
           'overs': 12.3}}}},
       {'matchInfo': {'matchId': 148914,
         'seriesId': 11711,
         'seriesName': 'Lesotho tour of Botswana, 2026',
         'matchDesc': '1st T20I',
         'matchFormat': 'T20',
         'startDate': '1773041400000',
         'endDate': '1773054000000',
         'state': 'Complete',
         'status': 'Botswana won by 6 wkts',
         'team1': {'teamId': 570,
          'teamName': 'Lesotho',
          'teamSName': 'LSO',
          'imageId': 172622},
         'team2': {'teamId': 529,
          'teamName': 'Botswana',
          'teamSName': 'BW',
          'imageId': 776225},
         'venueInfo': {'id': 1305,
          'ground': 'Botswana Cricket Association Oval 1',
          'city': 'Gaborone',
          'timezone': '+02:00',
          'latitude': '24.661180',
          'longitude': '25.911751'},
         'currBatTeamId': 529,
         'seriesStartDt': '1773014400000',
         'seriesEndDt': '1773705600000',
         'isTimeAnnounced': True,
         'stateTitle': 'BW Won'},
        'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
           'runs': 60,
           'wickets': 10,
           'overs': 19.3}},
         'team2Score': {'inngs1': {'inningsId': 2,
           'runs': 61,
           'wickets': 4,
           'overs': 10.6}}}}]}}]},
  {'matchType': 'Domestic',
   'seriesMatches': [{'seriesAdWrapper': {'seriesId': 11553,
      'seriesName': 'CSA Provincial One-Day Challenge Division One 2026',
      'matches': [{'matchInfo': {'matchId': 147260,
         'seriesId': 11553,
         'seriesName': 'CSA Provincial One-Day Challenge Division One 2026',
         'matchDesc': '13th Match',
         'matchFormat': 'ODI',
         'startDate': '1773140400000',
         'endDate': '1773169200000',
         'state': 'Complete',
         'status': 'Warriors won by 11 runs',
         'team1': {'teamId': 155,
          'teamName': 'Warriors',
          'teamSName': 'WAR',
          'imageId': 172222},
         'team2': {'teamId': 922,
          'teamName': 'North West - Eastvaal Renault Dragons',
          'teamSName': 'NWEST',
          'imageId': 248439},
         'venueInfo': {'id': 73,
          'ground': "St George's Park",
          'city': 'Gqeberha',
          'timezone': '+02:00',
          'latitude': '-33.966545',
          'longitude': '25.610332'},
         'currBatTeamId': 155,
         'seriesStartDt': '1772150400000',
         'seriesEndDt': '1774915200000',
         'isTimeAnnounced': True,
         'stateTitle': 'WAR Won'},
        'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
           'runs': 262,
           'wickets': 8,
           'overs': 50.0}},
         'team2Score': {'inngs1': {'inningsId': 2,
           'runs': 251,
           'wickets': 10,
           'overs': 49.0}}}},
       {'matchInfo': {'matchId': 147181,
         'seriesId': 11553,
         'seriesName': 'CSA Provincial One-Day Challenge Division One 2026',
         'matchDesc': '11th Match',
         'matchFormat': 'ODI',
         'startDate': '1772956800000',
         'endDate': '1772985600000',
         'state': 'Complete',
         'status': 'No result due to rain',
         'team1': {'teamId': 1766,
          'teamName': 'KwaZulu-Natal Inland - Tuskers',
          'teamSName': 'KZNIN',
          'imageId': 349611},
         'team2': {'teamId': 90,
          'teamName': 'Dolphins',
          'teamSName': 'DOL',
          'imageId': 172183},
         'venueInfo': {'id': 206,
          'ground': 'City Oval',
          'city': 'Pietermaritzburg',
          'timezone': '+02:00',
          'latitude': '-29.551181',
          'longitude': '30.407238'},
         'seriesStartDt': '1772150400000',
         'seriesEndDt': '1774915200000',
         'isTimeAnnounced': True,

In [43]:
import pandas as pd
import requests
from datetime import datetime

flattened_data = []

# 2. Iterate through Match Types (International, Domestic, etc.)
for match_type_group in recent.get('typeMatches', []):
    m_type = match_type_group.get('matchType')
    
    # Iterate through Series
    for series_group in match_type_group.get('seriesMatches', []):
        series_wrapper = series_group.get('seriesAdWrapper')
        if not series_wrapper: continue # Skip ads
        
        series_name = series_wrapper.get('seriesName')
        
        # Iterate through Matches in that series
        for match in series_wrapper.get('matches', []):
            info = match.get('matchInfo', {})
            score = match.get('matchScore', {})
            
            # Extract Score Strings
            t1_score = score.get('team1Score', {}).get('inngs1', {})
            t2_score = score.get('team2Score', {}).get('inngs1', {})
            
            # Convert milliseconds to date
            start_ms = int(info.get('startDate', 0))
            match_date = datetime.fromtimestamp(start_ms / 1000.0).strftime('%Y-%m-%d')

            # Create the flat row
            row = {
                "Match Type": m_type,
                "Series Name": series_name,
                "Match Desc": info.get('matchDesc'),
                "Format": info.get('matchFormat'),
                "Date": match_date,
                "Venue": f"{info.get('venueInfo', {}).get('ground')}, {info.get('venueInfo', {}).get('city')}",
                "Team 1": info.get('team1', {}).get('teamName'),
                "T1 Score": f"{t1_score.get('runs', 0)}/{t1_score.get('wickets', 0)} ({t1_score.get('overs', 0)})",
                "Team 2": info.get('team2', {}).get('teamName'),
                "T2 Score": f"{t2_score.get('runs', 0)}/{t2_score.get('wickets', 0)} ({t2_score.get('overs', 0)})",
                "Status": info.get('status')
            }
            flattened_data.append(row)

# 3. Create and Display DataFrame
df_recent = pd.DataFrame(flattened_data)

# To see ALL columns in your terminal/IDE
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

print(df_recent)

       Match Type                                        Series Name          Match Desc Format        Date                                          Venue                          Team 1        T1 Score                                 Team 2        T2 Score                                             Status
0   International                       ICC Men's T20 World Cup 2026               Final    T20  2026-03-08               Narendra Modi Stadium, Ahmedabad                           India    255/5 (19.6)                            New Zealand   159/10 (18.6)                               India won by 96 runs
1   International                       ICC Men's T20 World Cup 2026      2nd Semi-Final    T20  2026-03-05                       Wankhede Stadium, Mumbai                           India    253/7 (19.6)                                England    246/7 (19.6)                                India won by 7 runs
2   International                       ICC Men's T20 World Cup 2026      1st Semi-Final    T20  2026-03-04                          Eden Gardens, Kolkata                    South Africa    169/8 (19.6)                            New Zealand    173/1 (12.5)                          New Zealand won by 9 wkts
3   International                  Pakistan tour of Bangladesh, 2026             1st ODI    ODI  2026-03-11           Shere Bangla National Stadium, Dhaka                        Pakistan   114/10 (30.4)                             Bangladesh    115/2 (15.1)                           Bangladesh won by 8 wkts
4   International                     Bahrain tour of Malaysia, 2026            3rd T20I    T20  2026-03-10                    Bayuemas Oval, Kuala Lumpur                        Malaysia    131/7 (18.6)                                Bahrain    135/3 (17.1)  Bahrain won by 7 wkts  -  DLS Method (Target :...
5   International                     Bahrain tour of Malaysia, 2026            2nd T20I    T20  2026-03-08                    Bayuemas Oval, Kuala Lumpur                         Bahrain    130/7 (19.6)                               Malaysia   128/10 (19.5)                              Bahrain won by 2 runs
6   International                     Bahrain tour of Malaysia, 2026            1st T20I    T20  2026-03-07                    Bayuemas Oval, Kuala Lumpur                        Malaysia    140/7 (19.6)                                Bahrain   106/10 (18.5)                            Malaysia won by 34 runs
7   International  ICC Men's T20 2028 World Cup Americas Sub Regi...           4th Match    T20  2026-03-10                 Jimmy Powell Oval, George Town                          Mexico     94/9 (19.6)                         Cayman Islands     95/1 (13.3)                       Cayman Islands won by 9 wkts
8   International  ICC Men's T20 2028 World Cup Americas Sub Regi...           3rd Match    T20  2026-03-09                 Jimmy Powell Oval, George Town                       Argentina    129/9 (19.6)                               Suriname    114/8 (19.6)                           Argentina won by 15 runs
9   International  ICC Men's T20 2028 World Cup Americas Sub Regi...           2nd Match    T20  2026-03-09                 Jimmy Powell Oval, George Town                          Mexico    97/10 (19.5)                               Suriname     88/8 (19.6)                               Mexico won by 9 runs
10  International  ICC Men's T20 2028 World Cup Americas Sub Regi...           1st Match    T20  2026-03-08                 Jimmy Powell Oval, George Town                       Argentina    96/10 (17.1)                         Cayman Islands     102/0 (8.6)                      Cayman Islands won by 10 wkts
11  International                     Lesotho tour of Botswana, 2026            2nd T20I    T20  2026-03-10  Botswana Cricket Association Oval 1, Gaborone                         Lesotho     81/8 (19.6)                               Botswana     83/4 (12.3)                             Botswana won by 6 wkts
12  International                     Lesotho tour of Botswana, 2026            1st T20I    T20  2026-03-09  Botswana Cricket Association Oval 1, Gaborone                         Lesotho    60/10 (19.3)                               Botswana     61/4 (10.6)                             Botswana won by 6 wkts
13       Domestic  CSA Provincial One-Day Challenge Division One ...          13th Match    ODI  2026-03-10                     St George's Park, Gqeberha                        Warriors    262/8 (50.0)  North West - Eastvaal Renault Dragons   251/10 (49.0)                            Warriors won by 11 runs
14       Domestic  CSA Provincial One-Day Challenge Division One ...          11th Match    ODI  2026-03-08                    City Oval, Pietermaritzburg  KwaZulu-Natal Inland - Tuskers    211/9 (41.0)                               Dolphins     66/2 (15.0)                              No result due to rain
15       Domestic  CSA Provincial One-Day Challenge Division One ...          12th Match    ODI  2026-03-08                     SuperSport Park, Centurion                Western Province   220/10 (44.3)                                 Titans    222/8 (48.0)                               Titans won by 2 wkts
16       Domestic  CSA Provincial One-Day Challenge Division One ...          10th Match    ODI  2026-03-07                     Senwes Park, Potchefstroom                          Boland   121/10 (23.2)  North West - Eastvaal Renault Dragons   115/10 (24.1)  Boland won by 6 runs (Match reduced to 27 over...
17       Domestic  CSA Provincial One-Day Challenge Division One ...           9th Match    ODI  2026-03-06            The Wanderers Stadium, Johannesburg                           Lions         0/0 (0)                               Warriors         0/0 (0)       Match abandoned without toss  -  due to rain
18       Domestic  CSA Provincial One-Day Challenge Division One ...           8th Match    ODI  2026-03-05                              Kingsmead, Durban                        Dolphins    281/9 (49.6)                                 Titans    152/9 (19.6)  Dolphins won by 12 runs  -  2nd Inns reduced t...
19       Domestic  CSA Provincial One-Day Challenge Division One ...           7th Match    ODI  2026-03-04                     Senwes Park, Potchefstroom                           Lions    229/3 (41.6)  North West - Eastvaal Renault Dragons         0/0 (0)                          No result  -  due to rain
20       Domestic  CSA Provincial One-Day Challenge Division One ...           6th Match    ODI  2026-03-04                             Boland Park, Paarl                          Boland    224/9 (49.6)         KwaZulu-Natal Inland - Tuskers   181/10 (44.2)                              Boland won by 43 runs
21       Domestic                           Sheffield Shield 2025-26          26th Match   TEST  2026-03-05                   Allan Border Field, Brisbane               Western Australia   210/10 (73.1)                             Queensland   173/10 (65.6)                                        Match drawn
22       Domestic                           Sheffield Shield 2025-26          27th Match   TEST  2026-03-05   Karen Rolton Oval, Adelaide, South Australia                 New South Wales   269/10 (76.2)                        South Australia   373/10 (99.2)                      South Australia won by 9 wkts
23       Domestic                           Sheffield Shield 2025-26          25th Match   TEST  2026-03-05                         Bellerive Oval, Hobart                        Victoria   222/10 (64.5)                               Tasmania    91/10 (43.2)                            Victoria won by 70 runs
24       Domestic  CSA Provincial One-Day Challenge Division Two ...          19th Match    ODI  2026-03-08                    Mangaung Oval, Bloemfontein                         Knights    307/6 (49.6)                          Northern Cape    249/9 (49.6)                             Knights won by 58 runs
25       Domestic  CSA Provincial One-Day Challenge Division Two ...          20th Match    ODI  2026-03-08                  LC de Villiers Oval, Pretoria               Mpumalanga Rhinos    277/8 (49.6)          South Africa Emerging Players   170/10 (37.1)                  Mpumalanga Rhinos won by 107 runs
26       Domestic  CSA Provincial One-Day Challenge Division Two ...          18th Match    ODI  2026-03-08                      Buffalo Park, East London         South Western Districts   252/10 (47.5)                                 Border    254/3 (43.3)                               Border won by 7 wkts
27       Domestic  CSA Provincial One-Day Challenge Division Two ...          17th Match    ODI  2026-03-07              Polokwane Cricket Club, Polokwane                         Limpopo         0/0 (0)                          Eastern Storm         0/0 (0)                        Match abandoned due to rain
28       Domestic  CSA Provincial One-Day Challenge Division Two ...          16th Match    ODI  2026-03-05                  Recreation Ground, Oudtshoorn                         Knights    250/8 (49.6)                South Western Districts    251/3 (39.2)              South Western Districts won by 7 wkts
29       Domestic  CSA Provincial One-Day Challenge Division Two ...          14th Match    ODI  2026-03-04              Polokwane Cricket Club, Polokwane               Mpumalanga Rhinos    229/7 (37.6)                                Limpopo    237/1 (35.6)                Limpopo won by 9 wkts (DLS method)
30       Domestic  CSA Provincial One-Day Challenge Division Two ...          15th Match    ODI  2026-03-04                  LC de Villiers Oval, Pretoria   South Africa Emerging Players         0/0 (0)                          Northern Cape         0/0 (0)              Match abandoned without a ball bowled
31       Domestic  CSA Provincial One-Day Challenge Division Two ...          13th Match    ODI  2026-03-04                      Buffalo Park, East London                          Border    306/5 (49.6)                          Eastern Storm   247/10 (47.6)                              Border won by 59 runs
32       Domestic                             Plunket Shield 2025-26          17th Match   TEST  2026-03-09                 Eden Park Outer Oval, Auckland                        Auckland   228/10 (71.1)                                  Otago  343/10 (101.6)                                Otago won by 9 wkts
33       Domestic                             Plunket Shield 2025-26          16th Match   TEST  2026-03-07                            McLean Park, Napier               Central Districts  373/10 (103.6)                     Northern Districts    82/10 (32.2)    Central Districts won by an innings and 27 runs
34       Domestic             Australia Domestic One-Day Cup 2025-26               Final    ODI  2026-03-11                         Bellerive Oval, Hobart                        Tasmania   118/10 (20.3)                        New South Wales    119/6 (20.1)  New South Wales won by 4 wkts (22 Overs game d...
35       Domestic            Pakistan A v England Lions in UAE, 2026  5th Unofficial ODI    ODI  2026-03-09                Sheikh Zayed Stadium, Abu Dhabi                      Pakistan A         0/0 (0)                          England Lions         0/0 (0)                                    Match Cancelled
36       Domestic            Pakistan A v England Lions in UAE, 2026  4th Unofficial ODI    ODI  2026-03-06                Sheikh Zayed Stadium, Abu Dhabi                      Pakistan A         0/0 (0)                          England Lions         0/0 (0)                                    Match Cancelled
37          Women                India Women tour of Australia, 2026           Only Test   TEST  2026-03-06                         W.A.C.A. Ground, Perth                     India Women   198/10 (62.4)                        Australia Women   323/10 (90.4)                     Australia Women won by 10 wkts
38          Women           Zimbabwe Women tour of New Zealand, 2026             3rd ODI    ODI  2026-03-11                       University Oval, Dunedin               New Zealand Women    303/6 (49.6)                         Zimbabwe Women   103/10 (27.1)                  New Zealand Women won by 200 runs
39          Women           Zimbabwe Women tour of New Zealand, 2026             2nd ODI    ODI  2026-03-08                       University Oval, Dunedin                  Zimbabwe Women   102/10 (29.1)                      New Zealand Women    106/2 (16.2)                    New Zealand Women won by 8 wkts
40          Women           Zimbabwe Women tour of New Zealand, 2026             1st ODI    ODI  2026-03-05                       University Oval, Dunedin               New Zealand Women    354/3 (49.6)                         Zimbabwe Women   174/10 (47.3)                  New Zealand Women won by 180 runs

In [44]:
df_recent

       Match Type                                        Series Name          Match Desc Format        Date                                          Venue                          Team 1        T1 Score                                 Team 2        T2 Score                                             Status
0   International                       ICC Men's T20 World Cup 2026               Final    T20  2026-03-08               Narendra Modi Stadium, Ahmedabad                           India    255/5 (19.6)                            New Zealand   159/10 (18.6)                               India won by 96 runs
1   International                       ICC Men's T20 World Cup 2026      2nd Semi-Final    T20  2026-03-05                       Wankhede Stadium, Mumbai                           India    253/7 (19.6)                                England    246/7 (19.6)                                India won by 7 runs
2   International                       ICC Men's T20 World Cup 2026      1st Semi-Final    T20  2026-03-04                          Eden Gardens, Kolkata                    South Africa    169/8 (19.6)                            New Zealand    173/1 (12.5)                          New Zealand won by 9 wkts
3   International                  Pakistan tour of Bangladesh, 2026             1st ODI    ODI  2026-03-11           Shere Bangla National Stadium, Dhaka                        Pakistan   114/10 (30.4)                             Bangladesh    115/2 (15.1)                           Bangladesh won by 8 wkts
4   International                     Bahrain tour of Malaysia, 2026            3rd T20I    T20  2026-03-10                    Bayuemas Oval, Kuala Lumpur                        Malaysia    131/7 (18.6)                                Bahrain    135/3 (17.1)  Bahrain won by 7 wkts  -  DLS Method (Target :...
5   International                     Bahrain tour of Malaysia, 2026            2nd T20I    T20  2026-03-08                    Bayuemas Oval, Kuala Lumpur                         Bahrain    130/7 (19.6)                               Malaysia   128/10 (19.5)                              Bahrain won by 2 runs
6   International                     Bahrain tour of Malaysia, 2026            1st T20I    T20  2026-03-07                    Bayuemas Oval, Kuala Lumpur                        Malaysia    140/7 (19.6)                                Bahrain   106/10 (18.5)                            Malaysia won by 34 runs
7   International  ICC Men's T20 2028 World Cup Americas Sub Regi...           4th Match    T20  2026-03-10                 Jimmy Powell Oval, George Town                          Mexico     94/9 (19.6)                         Cayman Islands     95/1 (13.3)                       Cayman Islands won by 9 wkts
8   International  ICC Men's T20 2028 World Cup Americas Sub Regi...           3rd Match    T20  2026-03-09                 Jimmy Powell Oval, George Town                       Argentina    129/9 (19.6)                               Suriname    114/8 (19.6)                           Argentina won by 15 runs
9   International  ICC Men's T20 2028 World Cup Americas Sub Regi...           2nd Match    T20  2026-03-09                 Jimmy Powell Oval, George Town                          Mexico    97/10 (19.5)                               Suriname     88/8 (19.6)                               Mexico won by 9 runs
10  International  ICC Men's T20 2028 World Cup Americas Sub Regi...           1st Match    T20  2026-03-08                 Jimmy Powell Oval, George Town                       Argentina    96/10 (17.1)                         Cayman Islands     102/0 (8.6)                      Cayman Islands won by 10 wkts
11  International                     Lesotho tour of Botswana, 2026            2nd T20I    T20  2026-03-10  Botswana Cricket Association Oval 1, Gaborone                         Lesotho     81/8 (19.6)                               Botswana     83/4 (12.3)                             Botswana won by 6 wkts
12  International                     Lesotho tour of Botswana, 2026            1st T20I    T20  2026-03-09  Botswana Cricket Association Oval 1, Gaborone                         Lesotho    60/10 (19.3)                               Botswana     61/4 (10.6)                             Botswana won by 6 wkts
13       Domestic  CSA Provincial One-Day Challenge Division One ...          13th Match    ODI  2026-03-10                     St George's Park, Gqeberha                        Warriors    262/8 (50.0)  North West - Eastvaal Renault Dragons   251/10 (49.0)                            Warriors won by 11 runs
14       Domestic  CSA Provincial One-Day Challenge Division One ...          11th Match    ODI  2026-03-08                    City Oval, Pietermaritzburg  KwaZulu-Natal Inland - Tuskers    211/9 (41.0)                               Dolphins     66/2 (15.0)                              No result due to rain
15       Domestic  CSA Provincial One-Day Challenge Division One ...          12th Match    ODI  2026-03-08                     SuperSport Park, Centurion                Western Province   220/10 (44.3)                                 Titans    222/8 (48.0)                               Titans won by 2 wkts
16       Domestic  CSA Provincial One-Day Challenge Division One ...          10th Match    ODI  2026-03-07                     Senwes Park, Potchefstroom                          Boland   121/10 (23.2)  North West - Eastvaal Renault Dragons   115/10 (24.1)  Boland won by 6 runs (Match reduced to 27 over...
17       Domestic  CSA Provincial One-Day Challenge Division One ...           9th Match    ODI  2026-03-06            The Wanderers Stadium, Johannesburg                           Lions         0/0 (0)                               Warriors         0/0 (0)       Match abandoned without toss  -  due to rain
18       Domestic  CSA Provincial One-Day Challenge Division One ...           8th Match    ODI  2026-03-05                              Kingsmead, Durban                        Dolphins    281/9 (49.6)                                 Titans    152/9 (19.6)  Dolphins won by 12 runs  -  2nd Inns reduced t...
19       Domestic  CSA Provincial One-Day Challenge Division One ...           7th Match    ODI  2026-03-04                     Senwes Park, Potchefstroom                           Lions    229/3 (41.6)  North West - Eastvaal Renault Dragons         0/0 (0)                          No result  -  due to rain
20       Domestic  CSA Provincial One-Day Challenge Division One ...           6th Match    ODI  2026-03-04                             Boland Park, Paarl                          Boland    224/9 (49.6)         KwaZulu-Natal Inland - Tuskers   181/10 (44.2)                              Boland won by 43 runs
21       Domestic                           Sheffield Shield 2025-26          26th Match   TEST  2026-03-05                   Allan Border Field, Brisbane               Western Australia   210/10 (73.1)                             Queensland   173/10 (65.6)                                        Match drawn
22       Domestic                           Sheffield Shield 2025-26          27th Match   TEST  2026-03-05   Karen Rolton Oval, Adelaide, South Australia                 New South Wales   269/10 (76.2)                        South Australia   373/10 (99.2)                      South Australia won by 9 wkts
23       Domestic                           Sheffield Shield 2025-26          25th Match   TEST  2026-03-05                         Bellerive Oval, Hobart                        Victoria   222/10 (64.5)                               Tasmania    91/10 (43.2)                            Victoria won by 70 runs
24       Domestic  CSA Provincial One-Day Challenge Division Two ...          19th Match    ODI  2026-03-08                    Mangaung Oval, Bloemfontein                         Knights    307/6 (49.6)                          Northern Cape    249/9 (49.6)                             Knights won by 58 runs
25       Domestic  CSA Provincial One-Day Challenge Division Two ...          20th Match    ODI  2026-03-08                  LC de Villiers Oval, Pretoria               Mpumalanga Rhinos    277/8 (49.6)          South Africa Emerging Players   170/10 (37.1)                  Mpumalanga Rhinos won by 107 runs
26       Domestic  CSA Provincial One-Day Challenge Division Two ...          18th Match    ODI  2026-03-08                      Buffalo Park, East London         South Western Districts   252/10 (47.5)                                 Border    254/3 (43.3)                               Border won by 7 wkts
27       Domestic  CSA Provincial One-Day Challenge Division Two ...          17th Match    ODI  2026-03-07              Polokwane Cricket Club, Polokwane                         Limpopo         0/0 (0)                          Eastern Storm         0/0 (0)                        Match abandoned due to rain
28       Domestic  CSA Provincial One-Day Challenge Division Two ...          16th Match    ODI  2026-03-05                  Recreation Ground, Oudtshoorn                         Knights    250/8 (49.6)                South Western Districts    251/3 (39.2)              South Western Districts won by 7 wkts
29       Domestic  CSA Provincial One-Day Challenge Division Two ...          14th Match    ODI  2026-03-04              Polokwane Cricket Club, Polokwane               Mpumalanga Rhinos    229/7 (37.6)                                Limpopo    237/1 (35.6)                Limpopo won by 9 wkts (DLS method)
30       Domestic  CSA Provincial One-Day Challenge Division Two ...          15th Match    ODI  2026-03-04                  LC de Villiers Oval, Pretoria   South Africa Emerging Players         0/0 (0)                          Northern Cape         0/0 (0)              Match abandoned without a ball bowled
31       Domestic  CSA Provincial One-Day Challenge Division Two ...          13th Match    ODI  2026-03-04                      Buffalo Park, East London                          Border    306/5 (49.6)                          Eastern Storm   247/10 (47.6)                              Border won by 59 runs
32       Domestic                             Plunket Shield 2025-26          17th Match   TEST  2026-03-09                 Eden Park Outer Oval, Auckland                        Auckland   228/10 (71.1)                                  Otago  343/10 (101.6)                                Otago won by 9 wkts
33       Domestic                             Plunket Shield 2025-26          16th Match   TEST  2026-03-07                            McLean Park, Napier               Central Districts  373/10 (103.6)                     Northern Districts    82/10 (32.2)    Central Districts won by an innings and 27 runs
34       Domestic             Australia Domestic One-Day Cup 2025-26               Final    ODI  2026-03-11                         Bellerive Oval, Hobart                        Tasmania   118/10 (20.3)                        New South Wales    119/6 (20.1)  New South Wales won by 4 wkts (22 Overs game d...
35       Domestic            Pakistan A v England Lions in UAE, 2026  5th Unofficial ODI    ODI  2026-03-09                Sheikh Zayed Stadium, Abu Dhabi                      Pakistan A         0/0 (0)                          England Lions         0/0 (0)                                    Match Cancelled
36       Domestic            Pakistan A v England Lions in UAE, 2026  4th Unofficial ODI    ODI  2026-03-06                Sheikh Zayed Stadium, Abu Dhabi                      Pakistan A         0/0 (0)                          England Lions         0/0 (0)                                    Match Cancelled
37          Women                India Women tour of Australia, 2026           Only Test   TEST  2026-03-06                         W.A.C.A. Ground, Perth                     India Women   198/10 (62.4)                        Australia Women   323/10 (90.4)                     Australia Women won by 10 wkts
38          Women           Zimbabwe Women tour of New Zealand, 2026             3rd ODI    ODI  2026-03-11                       University Oval, Dunedin               New Zealand Women    303/6 (49.6)                         Zimbabwe Women   103/10 (27.1)                  New Zealand Women won by 200 runs
39          Women           Zimbabwe Women tour of New Zealand, 2026             2nd ODI    ODI  2026-03-08                       University Oval, Dunedin                  Zimbabwe Women   102/10 (29.1)                      New Zealand Women    106/2 (16.2)                    New Zealand Women won by 8 wkts
40          Women           Zimbabwe Women tour of New Zealand, 2026             1st ODI    ODI  2026-03-05                       University Oval, Dunedin               New Zealand Women    354/3 (49.6)                         Zimbabwe Women   174/10 (47.3)                  New Zealand Women won by 180 runs

# scheduled thing

In [20]:
import pandas as pd
import requests
from datetime import datetime

# 1. Fetch the data
url = "https://cricbuzz-cricket.p.rapidapi.com/teams/v1/2/schedule"
headers = {
    "x-rapidapi-key": "e6021fb984msh201af5139a6e2e9p149939jsn32edaa5716a4",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)
ind_sch = response.json()

# 2. Flatten the nested structure
all_matches = []

# Navigate: teamMatchesData -> matchDetailsMap -> match
for entry in ind_sch.get('teamMatchesData', []):
    match_map = entry.get('matchDetailsMap', {})
    match_list = match_map.get('match', [])
    
    for match in match_list:
        info = match.get('matchInfo', {})
        
        # Convert millisecond timestamp to readable date
        start_ms = int(info.get('startDate', 0))
        readable_date = datetime.fromtimestamp(start_ms / 1000.0).strftime('%Y-%m-%d %H:%M')
        
        # Extract specific fields into a flat dictionary
        match_data = {
            "Match ID": info.get('matchId'),
            "Series": info.get('seriesName'),
            "Format": info.get('matchFormat'),
            "Date": readable_date,
            "Team 1": info.get('team1', {}).get('teamName'),
            "Team 2": info.get('team2', {}).get('teamName'),
            "Venue": f"{info.get('venueInfo', {}).get('ground')}, {info.get('venueInfo', {}).get('city')}",
            "Status": info.get('status')
        }
        all_matches.append(match_data)

# 3. Create the DataFrame
df_india_schedule = pd.DataFrame(all_matches)

# 4. Display the table
print(df_india_schedule)

    Match ID                          Series Format              Date  \
0     148382  Afghanistan tour of India 2026   TEST  2026-06-06 09:30
1     148393  Afghanistan tour of India 2026    ODI  2026-06-14 13:30
2     148404  Afghanistan tour of India 2026    ODI  2026-06-17 13:30
3     148415  Afghanistan tour of India 2026    ODI  2026-06-20 13:30
4     129392     India tour of England, 2026    T20  2026-07-01 23:00
5     129420     India tour of England, 2026    T20  2026-07-04 19:00
6     129442     India tour of England, 2026    T20  2026-07-07 23:00
7     129447     India tour of England, 2026    T20  2026-07-09 23:00
8     129453     India tour of England, 2026    T20  2026-07-11 23:00
9     129458     India tour of England, 2026    ODI  2026-07-14 17:30
10    129469     India tour of England, 2026    ODI  2026-07-16 17:30
11    129480     India tour of England, 2026    ODI  2026-07-19 15:30

     Team 1       Team 2                                              Venue  \
0     India  Afghanistan  Maharaja Yadavindra Singh International Cricke...
1     India  Afghanistan  Himachal Pradesh Cricket Association Stadium, ...
2     India  Afghanistan  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...
3     India  Afghanistan                    MA Chidambaram Stadium, Chennai
4   England        India                Riverside Ground, Chester-le-Street
5   England        India                  Emirates Old Trafford, Manchester
6   England        India                           Trent Bridge, Nottingham
7   England        India                             County Ground, Bristol
8   England        India                         The Rose Bowl, Southampton
9   England        India                              Edgbaston, Birmingham
10  England        India                            Sophia Gardens, Cardiff
11  England        India                                     Lord's, London

                               Status
0   Match starts at Jun 06, 04:00 GMT
1   Match starts at Jun 14, 08:00 GMT
2   Match starts at Jun 17, 08:00 GMT
3   Match starts at Jun 20, 08:00 GMT
4   Match starts at Jul 01, 17:30 GMT
5   Match starts at Jul 04, 13:30 GMT
6   Match starts at Jul 07, 17:30 GMT
7   Match starts at Jul 09, 17:30 GMT
8   Match starts at Jul 11, 17:30 GMT
9   Match starts at Jul 14, 12:00 GMT
10  Match starts at Jul 16, 12:00 GMT
11  Match starts at Jul 19, 10:00 GMT

In [18]:
df_india_schedule

,Match ID,Series,Format,Date,Team 1,Team 2,Venue,Status
0,148382,Afghanistan tour of India 2026,TEST,2026-06-06 09:30,India,Afghanistan,Maharaja Yadavindra Singh International Cricke...,"Match starts at Jun 06, 04:00 GMT"
1,148393,Afghanistan tour of India 2026,ODI,2026-06-14 13:30,India,Afghanistan,"Himachal Pradesh Cricket Association Stadium, ...","Match starts at Jun 14, 08:00 GMT"
2,148404,Afghanistan tour of India 2026,ODI,2026-06-17 13:30,India,Afghanistan,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,"Match starts at Jun 17, 08:00 GMT"
3,148415,Afghanistan tour of India 2026,ODI,2026-06-20 13:30,India,Afghanistan,"MA Chidambaram Stadium, Chennai","Match starts at Jun 20, 08:00 GMT"
4,129392,"India tour of England, 2026",T20,2026-07-01 23:00,England,India,"Riverside Ground, Chester-le-Street","Match starts at Jul 01, 17:30 GMT"
5,129420,"India tour of England, 2026",T20,2026-07-04 19:00,England,India,"Emirates Old Trafford, Manchester","Match starts at Jul 04, 13:30 GMT"
6,129442,"India tour of England, 2026",T20,2026-07-07 23:00,England,India,"Trent Bridge, Nottingham","Match starts at Jul 07, 17:30 GMT"
7,129447,"India tour of England, 2026",T20,2026-07-09 23:00,England,India,"County Ground, Bristol","Match starts at Jul 09, 17:30 GMT"
8,129453,"India tour of England, 2026",T20,2026-07-11 23:00,England,India,"The Rose Bowl, Southampton","Match starts at Jul 11, 17:30 GMT"
9,129458,"India tour of England, 2026",ODI,2026-07-14 17:30,England,India,"Edgbaston, Birmingham","Match starts at Jul 14, 12:00 GMT"
10,129469,"India tour of England, 2026",ODI,2026-07-16 17:30,England,India,"Sophia Gardens, Cardiff","Match starts at Jul 16, 12:00 GMT"
11,129480,"India tour of England, 2026",ODI,2026-07-19 15:30,England,India,"Lord's, London","Match starts at Jul 19, 10:00 GMT"

# q16 analysis

Series league for 2020

In [73]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/series/v1/archives/league"

querystring = {"year":"2020"}

headers = {
	"x-rapidapi-key": "e6021fb984msh201af5139a6e2e9p149939jsn32edaa5716a4",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

seri_2020 = response.json()

In [75]:
seri_2020

{'seriesMapProto': [{'date': '2020',
   'series': [{'id': 3290,
     'name': 'Super Smash 2020-21',
     'startDt': '1608768000000',
     'endDt': '1613174400000',
     'thumborImageId': 379130},
    {'id': 3248,
     'name': 'Big Bash League 2020-21',
     'startDt': '1607558400000',
     'endDt': '1612569600000',
     'thumborImageId': 379130},
    {'id': 3320,
     'name': 'Lanka Premier League 2020',
     'startDt': '1606348800000',
     'endDt': '1608076800000',
     'thumborImageId': 379130},
    {'id': 3348,
     'name': 'Bangabandhu T20 Cup 2020',
     'startDt': '1606176000000',
     'endDt': '1608249600000',
     'thumborImageId': 379130},
    {'id': 3130,
     'name': 'Indian Premier League 2020',
     'startDt': '1600473600000',
     'endDt': '1604966400000',
     'thumborImageId': 379130},
    {'id': 2987,
     'name': 'T20 Blast 2020',
     'startDt': '1598486400000',
     'endDt': '1601769600000',
     'thumborImageId': 379130},
    {'id': 3243,
     'name': 'Caribbean Premier League 2020',
     'startDt': '1597708800000',
     'endDt': '1599696000000',
     'thumborImageId': 379130},
    {'id': 2930,
     'name': 'The Hundred Mens Competition 2020(Postponed)',
     'startDt': '1594944000000',
     'endDt': '1594944000000',
     'thumborImageId': 379130},
    {'id': 3177,
     'name': 'Road Safety World Series T20 2020-21',
     'startDt': '1583539200000',
     'endDt': '1616284800000',
     'thumborImageId': 379130},
    {'id': 3148,
     'name': 'Pakistan Super League 2020',
     'startDt': '1582156800000',
     'endDt': '1605571200000',
     'thumborImageId': 379130},
    {'id': 3141,
     'name': 'Bushfire Bash 2020',
     'startDt': '1581206400000',
     'endDt': '1581206400000',
     'thumborImageId': 379130}]}],
 'appIndex': {'seoTitle': 'Current Running Cricket Series - Cricbuzz | Cricbuzz.com',
  'webURL': 'www.cricbuzz.com/cricket-series/'}}

Particular series 3130 details

In [82]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/series/v1/3130"

headers = {
	"x-rapidapi-key": "e6021fb984msh201af5139a6e2e9p149939jsn32edaa5716a4",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

ser_3130 = response.json()

In [77]:
ser_3130

{'matchDetails': [{'matchDetailsMap': {'key': 'Sat, 19 Sep 2020',
    'match': [{'matchInfo': {'matchId': 30330,
       'seriesId': 3130,
       'seriesName': 'Indian Premier League 2020',
       'matchDesc': '1st Match',
       'matchFormat': 'T20',
       'startDate': '1600524000000',
       'endDate': '1600524000000',
       'state': 'complete',
       'status': 'Chennai Super Kings won by 5 wkts',
       'team1': {'teamId': 62,
        'teamName': 'MUMBAI INDIANS',
        'teamSName': 'MI',
        'imageId': 860053},
       'team2': {'teamId': 58,
        'teamName': 'CHENNAI SUPER KINGS',
        'teamSName': 'CSK',
        'imageId': 860038},
       'venueInfo': {'ground': 'Sheikh Zayed Stadium',
        'city': 'Abu Dhabi',
        'timezone': '+04:00'},
       'currBatTeamId': 58,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 162,
         'wickets': 9,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 166,
         'wickets': 5,
         'overs': 19.2}}}}],
    'seriesId': 3130}},
  {'adDetail': {'name': 'native_news_index_random_1',
    'layout': 'native_large',
    'position': 1}},
  {'matchDetailsMap': {'key': 'Sun, 20 Sep 2020',
    'match': [{'matchInfo': {'matchId': 30340,
       'seriesId': 3130,
       'seriesName': 'Indian Premier League 2020',
       'matchDesc': '2nd Match',
       'matchFormat': 'T20',
       'startDate': '1600610400000',
       'endDate': '1600610400000',
       'state': 'complete',
       'status': 'Match tied (Delhi Capitals won the Super Over)',
       'team1': {'teamId': 61,
        'teamName': 'DELHI CAPITALS',
        'teamSName': 'DC',
        'imageId': 860040},
       'team2': {'teamId': 65,
        'teamName': 'PUNJAB KINGS',
        'teamSName': 'PBKS',
        'imageId': 860084},
       'venueInfo': {'ground': 'Dubai International Cricket Stadium',
        'city': 'Dubai',
        'timezone': '+04:00'},
       'currBatTeamId': 61,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 157,
         'wickets': 8,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 157,
         'wickets': 8,
         'overs': 20.0}}}}],
    'seriesId': 3130}},
  {'matchDetailsMap': {'key': 'Mon, 21 Sep 2020',
    'match': [{'matchInfo': {'matchId': 30345,
       'seriesId': 3130,
       'seriesName': 'Indian Premier League 2020',
       'matchDesc': '3rd Match',
       'matchFormat': 'T20',
       'startDate': '1600696800000',
       'endDate': '1600696800000',
       'state': 'complete',
       'status': 'Royal Challengers Bangalore won by 10 runs',
       'team1': {'teamId': 255,
        'teamName': 'SUNRISERS HYDERABAD',
        'teamSName': 'SRH',
        'imageId': 860066},
       'team2': {'teamId': 59,
        'teamName': 'ROYAL CHALLENGERS BENGALURU',
        'teamSName': 'RCB',
        'imageId': 860056},
       'venueInfo': {'ground': 'Dubai International Cricket Stadium',
        'city': 'Dubai',
        'timezone': '+04:00'},
       'currBatTeamId': 59,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 153,
         'wickets': 10,
         'overs': 19.4}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 163,
         'wickets': 5,
         'overs': 20.0}}}}],
    'seriesId': 3130}},
  {'matchDetailsMap': {'key': 'Tue, 22 Sep 2020',
    'match': [{'matchInfo': {'matchId': 30350,
       'seriesId': 3130,
       'seriesName': 'Indian Premier League 2020',
       'matchDesc': '4th Match',
       'matchFormat': 'T20',
       'startDate': '1600783200000',
       'endDate': '1600783200000',
       'state': 'complete',
       'status': 'Rajasthan Royals won by 16 runs',
       'team1': {'teamId': 64,
        'teamName': 'RAJASTHAN ROYALS',
        'teamSName': 'RR',
        'imageId': 860055},
       'team2': {'teamId': 58,
        'teamName': 'CHENNAI SUPER KINGS',
        'teamSName': 'CSK',
        'imageId': 860038},
       'venueInfo': {'ground': 'Sharjah Cricket Stadium',
        'city': 'Sharjah',
        'timezone': '+04:00'},
       'currBatTeamId': 64,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 216,
         'wickets': 7,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 200,
         'wickets': 6,
         'overs': 20.0}}}}],
    'seriesId': 3130}},
  {'matchDetailsMap': {'key': 'Wed, 23 Sep 2020',
    'match': [{'matchInfo': {'matchId': 30354,
       'seriesId': 3130,
       'seriesName': 'Indian Premier League 2020',
       'matchDesc': '5th Match',
       'matchFormat': 'T20',
       'startDate': '1600869600000',
       'endDate': '1600869600000',
       'state': 'complete',
       'status': 'Mumbai Indians won by 49 runs',
       'team1': {'teamId': 63,
        'teamName': 'KOLKATA KNIGHT RIDERS',
        'teamSName': 'KKR',
        'imageId': 860046},
       'team2': {'teamId': 62,
        'teamName': 'MUMBAI INDIANS',
        'teamSName': 'MI',
        'imageId': 860053},
       'venueInfo': {'ground': 'Sheikh Zayed Stadium',
        'city': 'Abu Dhabi',
        'timezone': '+04:00'},
       'currBatTeamId': 62,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 146,
         'wickets': 9,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 195,
         'wickets': 5,
         'overs': 20.0}}}}],
    'seriesId': 3130}},
  {'matchDetailsMap': {'key': 'Thu, 24 Sep 2020',
    'match': [{'matchInfo': {'matchId': 30355,
       'seriesId': 3130,
       'seriesName': 'Indian Premier League 2020',
       'matchDesc': '6th Match',
       'matchFormat': 'T20',
       'startDate': '1600956000000',
       'endDate': '1600956000000',
       'state': 'complete',
       'status': 'Kings XI Punjab won by 97 runs',
       'team1': {'teamId': 65,
        'teamName': 'PUNJAB KINGS',
        'teamSName': 'PBKS',
        'imageId': 860084},
       'team2': {'teamId': 59,
        'teamName': 'ROYAL CHALLENGERS BENGALURU',
        'teamSName': 'RCB',
        'imageId': 860056},
       'venueInfo': {'ground': 'Dubai International Cricket Stadium',
        'city': 'Dubai',
        'timezone': '+04:00'},
       'currBatTeamId': 65,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 206,
         'wickets': 3,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 109,
         'wickets': 10,
         'overs': 17.0}}}}],
    'seriesId': 3130}},
  {'matchDetailsMap': {'key': 'Fri, 25 Sep 2020',
    'match': [{'matchInfo': {'matchId': 30360,
       'seriesId': 3130,
       'seriesName': 'Indian Premier League 2020',
       'matchDesc': '7th Match',
       'matchFormat': 'T20',
       'startDate': '1601042400000',
       'endDate': '1601042400000',
       'state': 'complete',
       'status': 'Delhi Capitals won by 44 runs',
       'team1': {'teamId': 58,
        'teamName': 'CHENNAI SUPER KINGS',
        'teamSName': 'CSK',
        'imageId': 860038},
       'team2': {'teamId': 61,
        'teamName': 'DELHI CAPITALS',
        'teamSName': 'DC',
        'imageId': 860040},
       'venueInfo': {'ground': 'Dubai International Cricket Stadium',
        'city': 'Dubai',
        'timezone': '+04:00'},
       'currBatTeamId': 61,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 131,
         'wickets': 7,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 175,
         'wickets': 3,
         'overs': 20.0}}}}],
    'seriesId': 3130}},
  {'matchDetailsMap': {'key': 'Sat, 26 Sep 2020',
    'match': [{'matchInfo': {'matchId': 30365,
       'seriesId': 3130,
       'seriesName': 'Indian Premier League 2020',
       'matchDesc': '8th Match',
       'matchFormat': 'T20',
       'startDate': '1601128800000',
       'endDate': '1601128800000',
       'state': 'complete',
       'status': 'Kolkata Knight Riders won by 7 wkts',
       'team1': {'teamId': 63,
        'teamName': 'KOLKATA KNIGHT RIDERS',
        'teamSName': 'KKR',
        'imageId': 860046},
       'team2': {'teamId': 255,
        'teamName': 'SUNRISERS HYDERABAD',
        'teamSName': 'SRH',
        'imageId': 860066},
       'venueInfo': {'ground': 'Sheikh Zayed Stadium',
        'city': 'Abu Dhabi',
        'timezone': '+04:00'},
       'currBatTeamId': 63,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 145,
         'wickets': 3,
         'overs': 18.0}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 142,
         'wickets': 4,
         'overs': 20.0}}}}],
    'seriesId': 3130}},
  {'matchDetailsMap': {'key': 'Sun, 27 Sep 2020',
    'match': [{'matchInfo': {'matchId': 30369,
       'seriesId': 3130,
       'seriesName': 'Indian Premier League 2020',
       'matchDesc': '9th Match',
       'matchFormat': 'T20',
       'startDate': '1601215200000',
       'endDate': '1601215200000',
       'state': 'complete',
       'status': 'Rajasthan Royals won by 4 wkts',
       'team1': {'teamId': 64,
        'teamName': 'RAJASTHAN ROYALS',
        'teamSName': 'RR',
        'imageId': 860055},
       'team2': {'teamId': 65,
        'teamName': 'PUNJAB KINGS',
        'teamSName': 'PBKS',
        'imageId': 860084},
       'venueInfo': {'ground': 'Sharjah Cricket Stadium',
        'city': 'Sharjah',
        'timezone': '+04:00'},
       'currBatTeamId': 64,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 226,
         'wickets': 6,
         'overs': 19.3}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 223,
         'wickets': 2,
         'overs': 20.0}}}}],
    'seriesId': 3130}},
  {'matchDetailsMap': {'key': 'Mon, 28 Sep 2020',
    'match': [{'matchInfo': {'matchId': 30370,
       'seriesId': 3130,
       'seriesName': 'Indian Premier League 2020',
       'matchDesc': '10th Match',
       'matchFormat': 'T20',
       'startDate': '1601301600000',
       'endDate': '1601301600000',
       'state': 'complete',
       'status': 'Match tied (Royal Challengers Bangalore won the Super Over)',
       'team1': {'teamId': 59,
        'teamName': 'ROYAL CHALLENGERS BENGALURU',
        'teamSName': 'RCB',
        'imageId': 860056},
       'team2': {'teamId': 62,
        'teamName': 'MUMBAI INDIANS',
        'teamSName': 'MI',
        'imageId': 860053},
       'venueInfo': {'ground': 'Dubai International Cricket Stadium',
        'city': 'Dubai',
        'timezone': '+04:00'},
       'currBatTeamId': 59,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 201,
         'wickets': 3,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 201,
         'wickets': 5,
         'overs': 20.0}}}}],
    'seriesId': 3130}},
  {'matchDetailsMap': {'key': 'Tue, 29 Sep 2020',
    'match': [{'matchInfo': {'matchId': 30375,
       'seriesId': 3130,
       'seriesName': 'Indian Premier League 2020',
       'matchDesc': '11th Match',
       'matchFormat': 'T20',
       'startDate': '1601388000000',
       'endDate': '1601388000000',
       'state': 'complete',
       'status': 'Sunrisers Hyderabad won by 15 runs',
       'team1': {'teamId': 61,
        'teamName': 'DELHI CAPITALS',
        'teamSName': 'DC',
        'imageId': 860040},
       'team2': {'teamId': 255,
        'teamName': 'SUNRISERS HYDERABAD',
        'teamSName': 'SRH',
        'imageId': 860066},
       'venueInfo': {'ground': 'Sheikh Zayed Stadium',
        'city': 'Abu Dhabi',
        'timezone': '+04:00'},
       'currBatTeamId': 255,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 147,
         'wickets': 7,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 162,
         'wickets': 4,
         'overs': 20.0}}}}],
    'seriesId': 3130}},
  {'matchDetailsMap': {'key': 'Wed, 30 Sep 2020',
    'match': [{'matchInfo': {'matchId': 30380,
       'seriesId': 3130,
       'seriesName': 'Indian Premier League 2020',
       'matchDesc': '12th Match',
       'matchFormat': 'T20',
       'startDate': '1601474400000',
       'endDate': '1601474400000',
       'state': 'complete',
       'status': 'Kolkata Knight Riders won by 37 runs',
       'team1': {'teamId': 64,
        'teamName': 'RAJASTHAN ROYALS',
        'teamSName': 'RR',
        'imageId': 860055},
       'team2': {'teamId': 63,
        'teamName': 'KOLKATA KNIGHT RIDERS',
        'teamSName': 'KKR',
        'imageId': 860046},
       'venueInfo': {'ground': 'Dubai International Cricket Stadium',
        'city': 'Dubai',
        'timezone': '+04:00'},
       'currBatTeamId': 63,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 137,
         'wickets': 9,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 174,
         'wickets': 6,
         'overs': 20.0}}}}],
    'seriesId': 3130}},
  {'matchDetailsMap': {'key': 'Thu, 01 Oct 2020',
    'match': [{'matchInfo': {'matchId': 30384,
       'seriesId': 3130,
       'seriesName': 'Indian Premier League 2020',
       'matchDesc': '13th Match',
       'matchFormat': 'T20',
       'startDate': '1601560800000',
       'endDate': '1601560800000',
       'state': 'complete',
       'status': 'Mumbai Indians won by 48 runs',
       'team1': {'teamId': 65,
        'teamName': 'PUNJAB KINGS',
        'teamSName': 'PBKS',
        'imageId': 860084},
       'team2': {'teamId': 62,
        'teamName': 'MUMBAI INDIANS',
        'teamSName': 'MI',
        'imageId': 860053},
       'venueInfo': {'ground': 'Sheikh Zayed Stadium',
        'city': 'Abu Dhabi',
        'timezone': '+04:00'},
       'currBatTeamId': 62,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 143,
         'wickets': 8,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 191,
         'wickets': 4,
         'overs': 20.0}}}}],
    'seriesId': 3130}},
  {'matchDetailsMap': {'key': 'Fri, 02 Oct 2020',
    'match': [{'matchInfo': {'matchId': 30385,
       'seriesId': 3130,
       'seriesName': 'Indian Premier League 2020',
       'matchDesc': '14th Match',
       'matchFormat': 'T20',
       'startDate': '1601647200000',
       'endDate': '1601647200000',
       'state': 'complete',
       'status': 'Sunrisers Hyderabad won by 7 runs',
       'team1': {'teamId': 58,
        'teamName': 'CHENNAI SUPER KINGS',
        'teamSName': 'CSK',
        'imageId': 860038},
       'team2': {'teamId': 255,
        'teamName': 'SUNRISERS HYDERABAD',
        'teamSName': 'SRH',
        'imageId': 860066},
       'venueInfo': {'ground': 'Dubai International Cricket Stadium',
        'city': 'Dubai',
        'timezone': '+04:00'},
       'currBatTeamId': 255,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 157,
         'wickets': 5,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 164,
         'wickets': 5,
         'overs': 20.0}}}}],
    'seriesId': 3130}},
  {'matchDetailsMap': {'key': 'Sat, 03 Oct 2020',
    'match': [{'matchInfo': {'matchId': 30390,
       'seriesId': 3130,
       'seriesName': 'Indian Premier League 2020',
       'matchDesc': '15th Match',
       'matchFormat': 'T20',
       'startDate': '1601719200000',
       'endDate': '1601719200000',
       'state': 'complete',
       'status': 'Royal Challengers Bangalore won by 8 wkts',
       'team1': {'teamId': 59,
        'teamName': 'ROYAL CHALLENGERS BENGALURU',
        'teamSName': 'RCB',
        'imageId': 860056},
       'team2': {'teamId': 64,
        'teamName': 'RAJASTHAN ROYALS',
        'teamSName': 'RR',
        'imageId': 860055},
       'venueInfo': {'ground': 'Sheikh Zayed Stadium',
        'city': 'Abu Dhabi',
        'timezone': '+04:00'},
       'currBatTeamId': 59,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 158,
         'wickets': 2,
         'overs': 19.1}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 154,
         'wickets': 6,
         'overs': 20.0}}}},
     {'matchInfo': {'matchId': 30395,
       'seriesId': 3130,
       'seriesName': 'Indian Premier League 2020',
       'matchDesc': '16th Match',
       'matchFormat': 'T20',
       'startDate': '1601733600000',
       'endDate': '1601733600000',
       'state': 'complete',
       'status': 'Delhi Capitals won by 18 runs',
       'team1': {'teamId': 61,
        'teamName': 'DELHI CAPITALS',
        'teamSName': 'DC',
        'imageId': 860040},
       'team2': {'teamId': 63,
        'teamName': 'KOLKATA KNIGHT RIDERS',
        'teamSName': 'KKR',
        'imageId': 860046},
       'venueInfo': {'ground': 'Sharjah Cricket Stadium',
        'city': 'Sharjah',
        'timezone': '+04:00'},
       'currBatTeamId': 61,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 228,
         'wickets': 4,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 210,
         'wickets': 8,
         'overs': 20.0}}}}],
    'seriesId': 3130}},
  {'matchDetailsMap': {'key': 'Sun, 04 Oct 2020',
    'match': [{'matchInfo': {'matchId': 30399,
       'seriesId': 3130,
       'seriesName': 'Indian Premier League 2020',
       'matchDesc': '17th Match',
       'matchFormat': 'T20',
       'startDate': '1601805600000',
       'endDate': '1601805600000',
       'state': 'complete',
       'status': 'Mumbai Indians won by 34 runs',
       'team1': {'teamId': 62,
        'teamName': 'MUMBAI INDIANS',
        'teamSName': 'MI',
        'imageId': 860053},
       'team2': {'teamId': 255,
        'teamName': 'SUNRISERS HYDERABAD',
        'teamSName': 'SRH',
        'imageId': 860066},
       'venueInfo': {'ground': 'Sharjah Cricket Stadium',
        'city': 'Sharjah',
        'timezone': '+04:00'},
       'currBatTeamId': 62,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 208,
         'wickets': 5,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 174,
         'wickets': 7,
         'overs': 20.0}}}},
     {'matchInfo': {'matchId': 30404,
       'seriesId': 3130,
       'seriesName': 'Indian Premier League 2020',
       'matchDesc': '18th Match',
       'matchFormat': 'T20',
       'startDate': '1601820000000',
       'endDate': '1601820000000',
       'state': 'complete',
       'status': 'Chennai Super Kings won by 10 wkts',
       'team1': {'teamId': 65,
        'teamName': 'PUNJAB KINGS',
        'teamSName': 'PBKS',
        'imageId': 860084},
       'team2': {'teamId': 58,
        'teamName': 'CHENNAI SUPER KINGS',
        'teamSName': 'CSK',
        'imageId': 860038},
       'venueInfo': {'ground': 'Dubai International Cricket Stadium',
        'city': 'Dubai',
        'timezone': '+04:00'},
       'currBatTeamId': 58,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 178,
         'wickets': 4,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 181,
         'overs': 17.4}}}}],
    'seriesId': 3130}},
  {'matchDetailsMap': {'key': 'Mon, 05 Oct 2020',

In [78]:
s_m_detail = ser_3130['matchDetails']
s_m_detail

[{'matchDetailsMap': {'key': 'Sat, 19 Sep 2020',
   'match': [{'matchInfo': {'matchId': 30330,
      'seriesId': 3130,
      'seriesName': 'Indian Premier League 2020',
      'matchDesc': '1st Match',
      'matchFormat': 'T20',
      'startDate': '1600524000000',
      'endDate': '1600524000000',
      'state': 'complete',
      'status': 'Chennai Super Kings won by 5 wkts',
      'team1': {'teamId': 62,
       'teamName': 'MUMBAI INDIANS',
       'teamSName': 'MI',
       'imageId': 860053},
      'team2': {'teamId': 58,
       'teamName': 'CHENNAI SUPER KINGS',
       'teamSName': 'CSK',
       'imageId': 860038},
      'venueInfo': {'ground': 'Sheikh Zayed Stadium',
       'city': 'Abu Dhabi',
       'timezone': '+04:00'},
      'currBatTeamId': 58,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
        'runs': 162,
        'wickets': 9,
        'overs': 20.0}},
      'team2Score': {'inngs1': {'inningsId': 2,
        'runs': 166,
        'wickets': 5,
        'overs': 19.2}}}}],
   'seriesId': 3130}},
 {'adDetail': {'name': 'native_news_index_random_1',
   'layout': 'native_large',
   'position': 1}},
 {'matchDetailsMap': {'key': 'Sun, 20 Sep 2020',
   'match': [{'matchInfo': {'matchId': 30340,
      'seriesId': 3130,
      'seriesName': 'Indian Premier League 2020',
      'matchDesc': '2nd Match',
      'matchFormat': 'T20',
      'startDate': '1600610400000',
      'endDate': '1600610400000',
      'state': 'complete',
      'status': 'Match tied (Delhi Capitals won the Super Over)',
      'team1': {'teamId': 61,
       'teamName': 'DELHI CAPITALS',
       'teamSName': 'DC',
       'imageId': 860040},
      'team2': {'teamId': 65,
       'teamName': 'PUNJAB KINGS',
       'teamSName': 'PBKS',
       'imageId': 860084},
      'venueInfo': {'ground': 'Dubai International Cricket Stadium',
       'city': 'Dubai',
       'timezone': '+04:00'},
      'currBatTeamId': 61,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
        'runs': 157,
        'wickets': 8,
        'overs': 20.0}},
      'team2Score': {'inngs1': {'inningsId': 2,
        'runs': 157,
        'wickets': 8,
        'overs': 20.0}}}}],
   'seriesId': 3130}},
 {'matchDetailsMap': {'key': 'Mon, 21 Sep 2020',
   'match': [{'matchInfo': {'matchId': 30345,
      'seriesId': 3130,
      'seriesName': 'Indian Premier League 2020',
      'matchDesc': '3rd Match',
      'matchFormat': 'T20',
      'startDate': '1600696800000',
      'endDate': '1600696800000',
      'state': 'complete',
      'status': 'Royal Challengers Bangalore won by 10 runs',
      'team1': {'teamId': 255,
       'teamName': 'SUNRISERS HYDERABAD',
       'teamSName': 'SRH',
       'imageId': 860066},
      'team2': {'teamId': 59,
       'teamName': 'ROYAL CHALLENGERS BENGALURU',
       'teamSName': 'RCB',
       'imageId': 860056},
      'venueInfo': {'ground': 'Dubai International Cricket Stadium',
       'city': 'Dubai',
       'timezone': '+04:00'},
      'currBatTeamId': 59,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
        'runs': 153,
        'wickets': 10,
        'overs': 19.4}},
      'team2Score': {'inngs1': {'inningsId': 1,
        'runs': 163,
        'wickets': 5,
        'overs': 20.0}}}}],
   'seriesId': 3130}},
 {'matchDetailsMap': {'key': 'Tue, 22 Sep 2020',
   'match': [{'matchInfo': {'matchId': 30350,
      'seriesId': 3130,
      'seriesName': 'Indian Premier League 2020',
      'matchDesc': '4th Match',
      'matchFormat': 'T20',
      'startDate': '1600783200000',
      'endDate': '1600783200000',
      'state': 'complete',
      'status': 'Rajasthan Royals won by 16 runs',
      'team1': {'teamId': 64,
       'teamName': 'RAJASTHAN ROYALS',
       'teamSName': 'RR',
       'imageId': 860055},
      'team2': {'teamId': 58,
       'teamName': 'CHENNAI SUPER KINGS',
       'teamSName': 'CSK',
       'imageId': 860038},
      'venueInfo': {'ground': 'Sharjah Cricket Stadium',
       'city': 'Sharjah',
       'timezone': '+04:00'},
      'currBatTeamId': 64,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
        'runs': 216,
        'wickets': 7,
        'overs': 20.0}},
      'team2Score': {'inngs1': {'inningsId': 2,
        'runs': 200,
        'wickets': 6,
        'overs': 20.0}}}}],
   'seriesId': 3130}},
 {'matchDetailsMap': {'key': 'Wed, 23 Sep 2020',
   'match': [{'matchInfo': {'matchId': 30354,
      'seriesId': 3130,
      'seriesName': 'Indian Premier League 2020',
      'matchDesc': '5th Match',
      'matchFormat': 'T20',
      'startDate': '1600869600000',
      'endDate': '1600869600000',
      'state': 'complete',
      'status': 'Mumbai Indians won by 49 runs',
      'team1': {'teamId': 63,
       'teamName': 'KOLKATA KNIGHT RIDERS',
       'teamSName': 'KKR',
       'imageId': 860046},
      'team2': {'teamId': 62,
       'teamName': 'MUMBAI INDIANS',
       'teamSName': 'MI',
       'imageId': 860053},
      'venueInfo': {'ground': 'Sheikh Zayed Stadium',
       'city': 'Abu Dhabi',
       'timezone': '+04:00'},
      'currBatTeamId': 62,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
        'runs': 146,
        'wickets': 9,
        'overs': 20.0}},
      'team2Score': {'inngs1': {'inningsId': 1,
        'runs': 195,
        'wickets': 5,
        'overs': 20.0}}}}],
   'seriesId': 3130}},
 {'matchDetailsMap': {'key': 'Thu, 24 Sep 2020',
   'match': [{'matchInfo': {'matchId': 30355,
      'seriesId': 3130,
      'seriesName': 'Indian Premier League 2020',
      'matchDesc': '6th Match',
      'matchFormat': 'T20',
      'startDate': '1600956000000',
      'endDate': '1600956000000',
      'state': 'complete',
      'status': 'Kings XI Punjab won by 97 runs',
      'team1': {'teamId': 65,
       'teamName': 'PUNJAB KINGS',
       'teamSName': 'PBKS',
       'imageId': 860084},
      'team2': {'teamId': 59,
       'teamName': 'ROYAL CHALLENGERS BENGALURU',
       'teamSName': 'RCB',
       'imageId': 860056},
      'venueInfo': {'ground': 'Dubai International Cricket Stadium',
       'city': 'Dubai',
       'timezone': '+04:00'},
      'currBatTeamId': 65,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
        'runs': 206,
        'wickets': 3,
        'overs': 20.0}},
      'team2Score': {'inngs1': {'inningsId': 2,
        'runs': 109,
        'wickets': 10,
        'overs': 17.0}}}}],
   'seriesId': 3130}},
 {'matchDetailsMap': {'key': 'Fri, 25 Sep 2020',
   'match': [{'matchInfo': {'matchId': 30360,
      'seriesId': 3130,
      'seriesName': 'Indian Premier League 2020',
      'matchDesc': '7th Match',
      'matchFormat': 'T20',
      'startDate': '1601042400000',
      'endDate': '1601042400000',
      'state': 'complete',
      'status': 'Delhi Capitals won by 44 runs',
      'team1': {'teamId': 58,
       'teamName': 'CHENNAI SUPER KINGS',
       'teamSName': 'CSK',
       'imageId': 860038},
      'team2': {'teamId': 61,
       'teamName': 'DELHI CAPITALS',
       'teamSName': 'DC',
       'imageId': 860040},
      'venueInfo': {'ground': 'Dubai International Cricket Stadium',
       'city': 'Dubai',
       'timezone': '+04:00'},
      'currBatTeamId': 61,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
        'runs': 131,
        'wickets': 7,
        'overs': 20.0}},
      'team2Score': {'inngs1': {'inningsId': 1,
        'runs': 175,
        'wickets': 3,
        'overs': 20.0}}}}],
   'seriesId': 3130}},
 {'matchDetailsMap': {'key': 'Sat, 26 Sep 2020',
   'match': [{'matchInfo': {'matchId': 30365,
      'seriesId': 3130,
      'seriesName': 'Indian Premier League 2020',
      'matchDesc': '8th Match',
      'matchFormat': 'T20',
      'startDate': '1601128800000',
      'endDate': '1601128800000',
      'state': 'complete',
      'status': 'Kolkata Knight Riders won by 7 wkts',
      'team1': {'teamId': 63,
       'teamName': 'KOLKATA KNIGHT RIDERS',
       'teamSName': 'KKR',
       'imageId': 860046},
      'team2': {'teamId': 255,
       'teamName': 'SUNRISERS HYDERABAD',
       'teamSName': 'SRH',
       'imageId': 860066},
      'venueInfo': {'ground': 'Sheikh Zayed Stadium',
       'city': 'Abu Dhabi',
       'timezone': '+04:00'},
      'currBatTeamId': 63,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
        'runs': 145,
        'wickets': 3,
        'overs': 18.0}},
      'team2Score': {'inngs1': {'inningsId': 1,
        'runs': 142,
        'wickets': 4,
        'overs': 20.0}}}}],
   'seriesId': 3130}},
 {'matchDetailsMap': {'key': 'Sun, 27 Sep 2020',
   'match': [{'matchInfo': {'matchId': 30369,
      'seriesId': 3130,
      'seriesName': 'Indian Premier League 2020',
      'matchDesc': '9th Match',
      'matchFormat': 'T20',
      'startDate': '1601215200000',
      'endDate': '1601215200000',
      'state': 'complete',
      'status': 'Rajasthan Royals won by 4 wkts',
      'team1': {'teamId': 64,
       'teamName': 'RAJASTHAN ROYALS',
       'teamSName': 'RR',
       'imageId': 860055},
      'team2': {'teamId': 65,
       'teamName': 'PUNJAB KINGS',
       'teamSName': 'PBKS',
       'imageId': 860084},
      'venueInfo': {'ground': 'Sharjah Cricket Stadium',
       'city': 'Sharjah',
       'timezone': '+04:00'},
      'currBatTeamId': 64,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
        'runs': 226,
        'wickets': 6,
        'overs': 19.3}},
      'team2Score': {'inngs1': {'inningsId': 1,
        'runs': 223,
        'wickets': 2,
        'overs': 20.0}}}}],
   'seriesId': 3130}},
 {'matchDetailsMap': {'key': 'Mon, 28 Sep 2020',
   'match': [{'matchInfo': {'matchId': 30370,
      'seriesId': 3130,
      'seriesName': 'Indian Premier League 2020',
      'matchDesc': '10th Match',
      'matchFormat': 'T20',
      'startDate': '1601301600000',
      'endDate': '1601301600000',
      'state': 'complete',
      'status': 'Match tied (Royal Challengers Bangalore won the Super Over)',
      'team1': {'teamId': 59,
       'teamName': 'ROYAL CHALLENGERS BENGALURU',
       'teamSName': 'RCB',
       'imageId': 860056},
      'team2': {'teamId': 62,
       'teamName': 'MUMBAI INDIANS',
       'teamSName': 'MI',
       'imageId': 860053},
      'venueInfo': {'ground': 'Dubai International Cricket Stadium',
       'city': 'Dubai',
       'timezone': '+04:00'},
      'currBatTeamId': 59,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
        'runs': 201,
        'wickets': 3,
        'overs': 20.0}},
      'team2Score': {'inngs1': {'inningsId': 2,
        'runs': 201,
        'wickets': 5,
        'overs': 20.0}}}}],
   'seriesId': 3130}},
 {'matchDetailsMap': {'key': 'Tue, 29 Sep 2020',
   'match': [{'matchInfo': {'matchId': 30375,
      'seriesId': 3130,
      'seriesName': 'Indian Premier League 2020',
      'matchDesc': '11th Match',
      'matchFormat': 'T20',
      'startDate': '1601388000000',
      'endDate': '1601388000000',
      'state': 'complete',
      'status': 'Sunrisers Hyderabad won by 15 runs',
      'team1': {'teamId': 61,
       'teamName': 'DELHI CAPITALS',
       'teamSName': 'DC',
       'imageId': 860040},
      'team2': {'teamId': 255,
       'teamName': 'SUNRISERS HYDERABAD',
       'teamSName': 'SRH',
       'imageId': 860066},
      'venueInfo': {'ground': 'Sheikh Zayed Stadium',
       'city': 'Abu Dhabi',
       'timezone': '+04:00'},
      'currBatTeamId': 255,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
        'runs': 147,
        'wickets': 7,
        'overs': 20.0}},
      'team2Score': {'inngs1': {'inningsId': 1,
        'runs': 162,
        'wickets': 4,
        'overs': 20.0}}}}],
   'seriesId': 3130}},
 {'matchDetailsMap': {'key': 'Wed, 30 Sep 2020',
   'match': [{'matchInfo': {'matchId': 30380,
      'seriesId': 3130,
      'seriesName': 'Indian Premier League 2020',
      'matchDesc': '12th Match',
      'matchFormat': 'T20',
      'startDate': '1601474400000',
      'endDate': '1601474400000',
      'state': 'complete',
      'status': 'Kolkata Knight Riders won by 37 runs',
      'team1': {'teamId': 64,
       'teamName': 'RAJASTHAN ROYALS',
       'teamSName': 'RR',
       'imageId': 860055},
      'team2': {'teamId': 63,
       'teamName': 'KOLKATA KNIGHT RIDERS',
       'teamSName': 'KKR',
       'imageId': 860046},
      'venueInfo': {'ground': 'Dubai International Cricket Stadium',
       'city': 'Dubai',
       'timezone': '+04:00'},
      'currBatTeamId': 63,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
        'runs': 137,
        'wickets': 9,
        'overs': 20.0}},
      'team2Score': {'inngs1': {'inningsId': 1,
        'runs': 174,
        'wickets': 6,
        'overs': 20.0}}}}],
   'seriesId': 3130}},
 {'matchDetailsMap': {'key': 'Thu, 01 Oct 2020',
   'match': [{'matchInfo': {'matchId': 30384,
      'seriesId': 3130,
      'seriesName': 'Indian Premier League 2020',
      'matchDesc': '13th Match',
      'matchFormat': 'T20',
      'startDate': '1601560800000',
      'endDate': '1601560800000',
      'state': 'complete',
      'status': 'Mumbai Indians won by 48 runs',
      'team1': {'teamId': 65,
       'teamName': 'PUNJAB KINGS',
       'teamSName': 'PBKS',
       'imageId': 860084},
      'team2': {'teamId': 62,
       'teamName': 'MUMBAI INDIANS',
       'teamSName': 'MI',
       'imageId': 860053},
      'venueInfo': {'ground': 'Sheikh Zayed Stadium',
       'city': 'Abu Dhabi',
       'timezone': '+04:00'},
      'currBatTeamId': 62,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
        'runs': 143,
        'wickets': 8,
        'overs': 20.0}},
      'team2Score': {'inngs1': {'inningsId': 1,
        'runs': 191,
        'wickets': 4,
        'overs': 20.0}}}}],
   'seriesId': 3130}},
 {'matchDetailsMap': {'key': 'Fri, 02 Oct 2020',
   'match': [{'matchInfo': {'matchId': 30385,
      'seriesId': 3130,
      'seriesName': 'Indian Premier League 2020',
      'matchDesc': '14th Match',
      'matchFormat': 'T20',
      'startDate': '1601647200000',
      'endDate': '1601647200000',
      'state': 'complete',
      'status': 'Sunrisers Hyderabad won by 7 runs',
      'team1': {'teamId': 58,
       'teamName': 'CHENNAI SUPER KINGS',
       'teamSName': 'CSK',
       'imageId': 860038},
      'team2': {'teamId': 255,
       'teamName': 'SUNRISERS HYDERABAD',
       'teamSName': 'SRH',
       'imageId': 860066},
      'venueInfo': {'ground': 'Dubai International Cricket Stadium',
       'city': 'Dubai',
       'timezone': '+04:00'},
      'currBatTeamId': 255,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
        'runs': 157,
        'wickets': 5,
        'overs': 20.0}},
      'team2Score': {'inngs1': {'inningsId': 1,
        'runs': 164,
        'wickets': 5,
        'overs': 20.0}}}}],
   'seriesId': 3130}},
 {'matchDetailsMap': {'key': 'Sat, 03 Oct 2020',
   'match': [{'matchInfo': {'matchId': 30390,
      'seriesId': 3130,
      'seriesName': 'Indian Premier League 2020',
      'matchDesc': '15th Match',
      'matchFormat': 'T20',
      'startDate': '1601719200000',
      'endDate': '1601719200000',
      'state': 'complete',
      'status': 'Royal Challengers Bangalore won by 8 wkts',
      'team1': {'teamId': 59,
       'teamName': 'ROYAL CHALLENGERS BENGALURU',
       'teamSName': 'RCB',
       'imageId': 860056},
      'team2': {'teamId': 64,
       'teamName': 'RAJASTHAN ROYALS',
       'teamSName': 'RR',
       'imageId': 860055},
      'venueInfo': {'ground': 'Sheikh Zayed Stadium',
       'city': 'Abu Dhabi',
       'timezone': '+04:00'},
      'currBatTeamId': 59,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
        'runs': 158,
        'wickets': 2,
        'overs': 19.1}},
      'team2Score': {'inngs1': {'inningsId': 1,
        'runs': 154,
        'wickets': 6,
        'overs': 20.0}}}},
    {'matchInfo': {'matchId': 30395,
      'seriesId': 3130,
      'seriesName': 'Indian Premier League 2020',
      'matchDesc': '16th Match',
      'matchFormat': 'T20',
      'startDate': '1601733600000',
      'endDate': '1601733600000',
      'state': 'complete',
      'status': 'Delhi Capitals won by 18 runs',
      'team1': {'teamId': 61,
       'teamName': 'DELHI CAPITALS',
       'teamSName': 'DC',
       'imageId': 860040},
      'team2': {'teamId': 63,
       'teamName': 'KOLKATA KNIGHT RIDERS',
       'teamSName': 'KKR',
       'imageId': 860046},
      'venueInfo': {'ground': 'Sharjah Cricket Stadium',
       'city': 'Sharjah',
       'timezone': '+04:00'},
      'currBatTeamId': 61,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
        'runs': 228,
        'wickets': 4,
        'overs': 20.0}},
      'team2Score': {'inngs1': {'inningsId': 2,
        'runs': 210,
        'wickets': 8,
        'overs': 20.0}}}}],
   'seriesId': 3130}},
 {'matchDetailsMap': {'key': 'Sun, 04 Oct 2020',
   'match': [{'matchInfo': {'matchId': 30399,
      'seriesId': 3130,
      'seriesName': 'Indian Premier League 2020',
      'matchDesc': '17th Match',
      'matchFormat': 'T20',
      'startDate': '1601805600000',
      'endDate': '1601805600000',
      'state': 'complete',
      'status': 'Mumbai Indians won by 34 runs',
      'team1': {'teamId': 62,
       'teamName': 'MUMBAI INDIANS',
       'teamSName': 'MI',
       'imageId': 860053},
      'team2': {'teamId': 255,
       'teamName': 'SUNRISERS HYDERABAD',
       'teamSName': 'SRH',
       'imageId': 860066},
      'venueInfo': {'ground': 'Sharjah Cricket Stadium',
       'city': 'Sharjah',
       'timezone': '+04:00'},
      'currBatTeamId': 62,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
        'runs': 208,
        'wickets': 5,
        'overs': 20.0}},
      'team2Score': {'inngs1': {'inningsId': 2,
        'runs': 174,
        'wickets': 7,
        'overs': 20.0}}}},
    {'matchInfo': {'matchId': 30404,
      'seriesId': 3130,
      'seriesName': 'Indian Premier League 2020',
      'matchDesc': '18th Match',
      'matchFormat': 'T20',
      'startDate': '1601820000000',
      'endDate': '1601820000000',
      'state': 'complete',
      'status': 'Chennai Super Kings won by 10 wkts',
      'team1': {'teamId': 65,
       'teamName': 'PUNJAB KINGS',
       'teamSName': 'PBKS',
       'imageId': 860084},
      'team2': {'teamId': 58,
       'teamName': 'CHENNAI SUPER KINGS',
       'teamSName': 'CSK',
       'imageId': 860038},
      'venueInfo': {'ground': 'Dubai International Cricket Stadium',
       'city': 'Dubai',
       'timezone': '+04:00'},
      'currBatTeamId': 58,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
        'runs': 178,
        'wickets': 4,
        'overs': 20.0}},
      'team2Score': {'inngs1': {'inningsId': 2,
        'runs': 181,
        'overs': 17.4}}}}],
   'seriesId': 3130}},
 {'matchDetailsMap': {'key': 'Mon, 05 Oct 2020',
   'match': [{'matchInfo': {'matchId': 30409,
      'seriesId': 3130,
      'seriesName': 'Indian Premier League 2020',
      'matchDesc': '19th Match',
      'matchFormat': 'T20',
      'startDate': '1601906400000',
      'endDate': '1601906400000',
      'state': 'complete',
      'status': 'Delhi Capitals won by 59 runs',
      'team1': {'teamId': 59,
       'teamName': 'ROYAL CHALLENGERS BENGALURU',
       'teamSName': 'RCB',
       'imageId': 860056},
      'team2': {'teamId': 61,
       'teamName': 'DELHI CAPITALS',
       'teamSName': 'DC',
       'imageId': 860040},

In [79]:
import pandas as pd
from datetime import datetime

series_matches = []

for item in s_m_detail:
    
    match_map = item.get('matchDetailsMap', {})
    
    for m in match_map.get('match', []):
        
        info = m.get('matchInfo', {})
        
        match_id = info.get('matchId')
        series_name = info.get('seriesName')
        match_desc = info.get('matchDesc')
        match_format = info.get('matchFormat')
        
        team1 = info.get('team1', {}).get('teamName')
        team2 = info.get('team2', {}).get('teamName')
        
        venue = info.get('venueInfo', {}).get('ground')
        city = info.get('venueInfo', {}).get('city')
        
        start_date = datetime.fromtimestamp(
            int(info.get('startDate'))/1000
        ).strftime('%Y-%m-%d')
        
        status = info.get('status')
        
        series_matches.append({
            "Match ID": match_id,
            "Series": series_name,
            "Match": match_desc,
            "Format": match_format,
            "Team1": team1,
            "Team2": team2,
            "Venue": venue,
            "City": city,
            "Start Date": start_date,
            "Result": status
        })

df_2020 = pd.DataFrame(series_matches)

df_2020.head()

,Match ID,Series,Match,Format,Team1,Team2,Venue,City,Start Date,Result
0,30330,Indian Premier League 2020,1st Match,T20,MUMBAI INDIANS,CHENNAI SUPER KINGS,Sheikh Zayed Stadium,Abu Dhabi,2020-09-19,Chennai Super Kings won by 5 wkts
1,30340,Indian Premier League 2020,2nd Match,T20,DELHI CAPITALS,PUNJAB KINGS,Dubai International Cricket Stadium,Dubai,2020-09-20,Match tied (Delhi Capitals won the Super Over)
2,30345,Indian Premier League 2020,3rd Match,T20,SUNRISERS HYDERABAD,ROYAL CHALLENGERS BENGALURU,Dubai International Cricket Stadium,Dubai,2020-09-21,Royal Challengers Bangalore won by 10 runs
3,30350,Indian Premier League 2020,4th Match,T20,RAJASTHAN ROYALS,CHENNAI SUPER KINGS,Sharjah Cricket Stadium,Sharjah,2020-09-22,Rajasthan Royals won by 16 runs
4,30354,Indian Premier League 2020,5th Match,T20,KOLKATA KNIGHT RIDERS,MUMBAI INDIANS,Sheikh Zayed Stadium,Abu Dhabi,2020-09-23,Mumbai Indians won by 49 runs

# Get the details of 2021

In [81]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/series/v1/3417"

headers = {
	"x-rapidapi-key": "e6021fb984msh201af5139a6e2e9p149939jsn32edaa5716a4",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

ser_3417 = response.json()

In [83]:
ser_3417

{'matchDetails': [{'matchDetailsMap': {'key': 'Wed, 09 Jun 2021',
    'match': [{'matchInfo': {'matchId': 33828,
       'seriesId': 3417,
       'seriesName': 'T20 Blast 2021',
       'matchDesc': 'North Group',
       'matchFormat': 'T20',
       'startDate': '1623245400000',
       'endDate': '1623245400000',
       'state': 'complete',
       'status': 'Lancashire won by 6 wkts',
       'team1': {'teamId': 143,
        'teamName': 'LANCASHIRE',
        'teamSName': 'LANCS',
        'imageId': 172210},
       'team2': {'teamId': 144,
        'teamName': 'DERBYSHIRE',
        'teamSName': 'DERBY',
        'imageId': 172211},
       'venueInfo': {'ground': 'Emirates Old Trafford',
        'city': 'Manchester',
        'timezone': '+01:00'},
       'currBatTeamId': 143,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 171,
         'wickets': 4,
         'overs': 19.3}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 168,
         'wickets': 7,
         'overs': 20.0}}}},
     {'matchInfo': {'matchId': 33833,
       'seriesId': 3417,
       'seriesName': 'T20 Blast 2021',
       'matchDesc': 'North Group',
       'matchFormat': 'T20',
       'startDate': '1623256200000',
       'endDate': '1623256200000',
       'state': 'complete',
       'status': 'Match tied',
       'team1': {'teamId': 147,
        'teamName': 'WORCESTERSHIRE',
        'teamSName': 'WORCS',
        'imageId': 172214},
       'team2': {'teamId': 139,
        'teamName': 'NOTTINGHAMSHIRE',
        'teamSName': 'NOTTS',
        'imageId': 172206},
       'venueInfo': {'ground': 'New Road',
        'city': 'Worcester',
        'timezone': '+01:00'},
       'currBatTeamId': 139,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 152,
         'wickets': 6,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 152,
         'wickets': 8,
         'overs': 20.0}}}},
     {'matchInfo': {'matchId': 33842,
       'seriesId': 3417,
       'seriesName': 'T20 Blast 2021',
       'matchDesc': 'South Group',
       'matchFormat': 'T20',
       'startDate': '1623259800000',
       'endDate': '1623259800000',
       'state': 'complete',
       'status': 'Essex won by 3 wkts',
       'team1': {'teamId': 119,
        'teamName': 'SOMERSET',
        'teamSName': 'SOM',
        'imageId': 172199},
       'team2': {'teamId': 152,
        'teamName': 'ESSEX',
        'teamSName': 'ESS',
        'imageId': 172219},
       'venueInfo': {'ground': 'The Cooper Associates County Ground',
        'city': 'Taunton',
        'timezone': '+01:00'},
       'currBatTeamId': 152,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 185,
         'wickets': 7,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 187,
         'wickets': 7,
         'overs': 18.5}}}},
     {'matchInfo': {'matchId': 33837,
       'seriesId': 3417,
       'seriesName': 'T20 Blast 2021',
       'matchDesc': 'South Group',
       'matchFormat': 'T20',
       'startDate': '1623261600000',
       'endDate': '1623261600000',
       'state': 'complete',
       'status': 'Kent won by 38 runs',
       'team1': {'teamId': 150,
        'teamName': 'KENT',
        'teamSName': 'KENT',
        'imageId': 172217},
       'team2': {'teamId': 153,
        'teamName': 'HAMPSHIRE',
        'teamSName': 'HAM',
        'imageId': 172220},
       'venueInfo': {'ground': 'St Lawrence Ground',
        'city': 'Canterbury',
        'timezone': '+01:00'},
       'currBatTeamId': 150,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 176,
         'wickets': 6,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 138,
         'wickets': 9,
         'overs': 20.0}}}}],
    'seriesId': 3417}},
  {'adDetail': {'name': 'native_news_index_random_1',
    'layout': 'native_large',
    'position': 1}},
  {'matchDetailsMap': {'key': 'Thu, 10 Jun 2021',
    'match': [{'matchInfo': {'matchId': 33862,
       'seriesId': 3417,
       'seriesName': 'T20 Blast 2021',
       'matchDesc': 'South Group',
       'matchFormat': 'T20',
       'startDate': '1623342600000',
       'endDate': '1623342600000',
       'state': 'complete',
       'status': 'Gloucestershire won by 4 runs',
       'team1': {'teamId': 149,
        'teamName': 'GLAMORGAN',
        'teamSName': 'GLAM',
        'imageId': 172216},
       'team2': {'teamId': 151,
        'teamName': 'GLOUCESTERSHIRE',
        'teamSName': 'GLOUCS',
        'imageId': 172218},
       'venueInfo': {'ground': 'Sophia Gardens',
        'city': 'Cardiff',
        'timezone': '+01:00'},
       'currBatTeamId': 151,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 175,
         'wickets': 9,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 179,
         'wickets': 6,
         'overs': 20.0}}}},
     {'matchInfo': {'matchId': 33847,
       'seriesId': 3417,
       'seriesName': 'T20 Blast 2021',
       'matchDesc': 'North Group',
       'matchFormat': 'T20',
       'startDate': '1623346200000',
       'endDate': '1623346200000',
       'state': 'complete',
       'status': 'Yorkshire won by 6 wkts',
       'team1': {'teamId': 146,
        'teamName': 'YORKSHIRE',
        'teamSName': 'YORKS',
        'imageId': 172213},
       'team2': {'teamId': 140,
        'teamName': 'WARWICKSHIRE',
        'teamSName': 'WARKS',
        'imageId': 172207},
       'venueInfo': {'ground': 'Headingley',
        'city': 'Leeds',
        'timezone': '+01:00'},
       'currBatTeamId': 146,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 147,
         'wickets': 4,
         'overs': 18.3}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 144,
         'wickets': 8,
         'overs': 20.0}}}},
     {'matchInfo': {'matchId': 33852,
       'seriesId': 3417,
       'seriesName': 'T20 Blast 2021',
       'matchDesc': 'North Group',
       'matchFormat': 'T20',
       'startDate': '1623346200000',
       'endDate': '1623346200000',
       'state': 'complete',
       'status': 'Lancashire won by 16 runs',
       'team1': {'teamId': 143,
        'teamName': 'LANCASHIRE',
        'teamSName': 'LANCS',
        'imageId': 172210},
       'team2': {'teamId': 145,
        'teamName': 'LEICESTERSHIRE',
        'teamSName': 'LEIC',
        'imageId': 172212},
       'venueInfo': {'ground': 'Emirates Old Trafford',
        'city': 'Manchester',
        'timezone': '+01:00'},
       'currBatTeamId': 143,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 172,
         'wickets': 8,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 156,
         'wickets': 5,
         'overs': 20.0}}}},
     {'matchInfo': {'matchId': 33857,
       'seriesId': 3417,
       'seriesName': 'T20 Blast 2021',
       'matchDesc': 'South Group',
       'matchFormat': 'T20',
       'startDate': '1623348000000',
       'endDate': '1623348000000',
       'state': 'complete',
       'status': 'Surrey won by 54 runs',
       'team1': {'teamId': 74,
        'teamName': 'MIDDLESEX',
        'teamSName': 'MDX',
        'imageId': 172170},
       'team2': {'teamId': 148,
        'teamName': 'SURREY',
        'teamSName': 'SUR',
        'imageId': 172215},
       'venueInfo': {'ground': "Lord's",
        'city': 'London',
        'timezone': '+01:00'},
       'currBatTeamId': 148,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 169,
         'wickets': 9,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 223,
         'wickets': 7,
         'overs': 20.0}}}}],
    'seriesId': 3417}},
  {'matchDetailsMap': {'key': 'Fri, 11 Jun 2021',
    'match': [{'matchInfo': {'matchId': 33867,
       'seriesId': 3417,
       'seriesName': 'T20 Blast 2021',
       'matchDesc': 'South Group',
       'matchFormat': 'T20',
       'startDate': '1623432600000',
       'endDate': '1623432600000',
       'state': 'complete',
       'status': 'Sussex won by 5 wkts',
       'team1': {'teamId': 151,
        'teamName': 'GLOUCESTERSHIRE',
        'teamSName': 'GLOUCS',
        'imageId': 172218},
       'team2': {'teamId': 41,
        'teamName': 'SUSSEX',
        'teamSName': 'SUS',
        'imageId': 172148},
       'venueInfo': {'ground': 'County Ground',
        'city': 'Bristol',
        'timezone': '+01:00'},
       'currBatTeamId': 41,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 177,
         'wickets': 7,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 178,
         'wickets': 5,
         'overs': 17.2}}}},
     {'matchInfo': {'matchId': 33892,
       'seriesId': 3417,
       'seriesName': 'T20 Blast 2021',
       'matchDesc': 'North Group',
       'matchFormat': 'T20',
       'startDate': '1623432600000',
       'endDate': '1623432600000',
       'state': 'complete',
       'status': 'Derbyshire won by 23 runs',
       'team1': {'teamId': 145,
        'teamName': 'LEICESTERSHIRE',
        'teamSName': 'LEIC',
        'imageId': 172212},
       'team2': {'teamId': 144,
        'teamName': 'DERBYSHIRE',
        'teamSName': 'DERBY',
        'imageId': 172211},
       'venueInfo': {'ground': 'Grace Road',
        'city': 'Leicester',
        'timezone': '+01:00'},
       'currBatTeamId': 144,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 186,
         'wickets': 10,
         'overs': 19.0}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 209,
         'wickets': 6,
         'overs': 20.0}}}},
     {'matchInfo': {'matchId': 33872,
       'seriesId': 3417,
       'seriesName': 'T20 Blast 2021',
       'matchDesc': 'North Group',
       'matchFormat': 'T20',
       'startDate': '1623432600000',
       'endDate': '1623432600000',
       'state': 'complete',
       'status': 'Durham won by 20 runs',
       'team1': {'teamId': 141,
        'teamName': 'DURHAM',
        'teamSName': 'DUR',
        'imageId': 172208},
       'team2': {'teamId': 146,
        'teamName': 'YORKSHIRE',
        'teamSName': 'YORKS',
        'imageId': 172213},
       'venueInfo': {'ground': 'Riverside Ground',
        'city': 'Chester-le-Street',
        'timezone': '+01:00'},
       'currBatTeamId': 141,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 181,
         'wickets': 8,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 161,
         'wickets': 6,
         'overs': 20.0}}}},
     {'matchInfo': {'matchId': 33887,
       'seriesId': 3417,
       'seriesName': 'T20 Blast 2021',
       'matchDesc': 'North Group',
       'matchFormat': 'T20',
       'startDate': '1623432600000',
       'endDate': '1623432600000',
       'state': 'complete',
       'status': 'Warwickshire won by 18 runs',
       'team1': {'teamId': 139,
        'teamName': 'NOTTINGHAMSHIRE',
        'teamSName': 'NOTTS',
        'imageId': 172206},
       'team2': {'teamId': 140,
        'teamName': 'WARWICKSHIRE',
        'teamSName': 'WARKS',
        'imageId': 172207},
       'venueInfo': {'ground': 'Trent Bridge',
        'city': 'Nottingham',
        'timezone': '+01:00'},
       'currBatTeamId': 140,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 211,
         'wickets': 9,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 229,
         'wickets': 5,
         'overs': 20.0}}}},
     {'matchInfo': {'matchId': 33878,
       'seriesId': 3417,
       'seriesName': 'T20 Blast 2021',
       'matchDesc': 'South Group',
       'matchFormat': 'T20',
       'startDate': '1623432600000',
       'endDate': '1623432600000',
       'state': 'complete',
       'status': 'Surrey won by 7 wkts',
       'team1': {'teamId': 119,
        'teamName': 'SOMERSET',
        'teamSName': 'SOM',
        'imageId': 172199},
       'team2': {'teamId': 148,
        'teamName': 'SURREY',
        'teamSName': 'SUR',
        'imageId': 172215},
       'venueInfo': {'ground': 'The Cooper Associates County Ground',
        'city': 'Taunton',
        'timezone': '+01:00'},
       'currBatTeamId': 148,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 187,
         'wickets': 6,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 188,
         'wickets': 3,
         'overs': 16.0}}}},
     {'matchInfo': {'matchId': 33883,
       'seriesId': 3417,
       'seriesName': 'T20 Blast 2021',
       'matchDesc': 'North Group',
       'matchFormat': 'T20',
       'startDate': '1623434400000',
       'endDate': '1623434400000',
       'state': 'complete',
       'status': 'Worcestershire won by 32 runs',
       'team1': {'teamId': 142,
        'teamName': 'NORTHAMPTONSHIRE',
        'teamSName': 'NHNTS',
        'imageId': 172209},
       'team2': {'teamId': 147,
        'teamName': 'WORCESTERSHIRE',
        'teamSName': 'WORCS',
        'imageId': 172214},
       'venueInfo': {'ground': 'County Ground',
        'city': 'Northampton',
        'timezone': '+01:00'},
       'currBatTeamId': 147,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 153,
         'wickets': 9,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 185,
         'wickets': 7,
         'overs': 20.0}}}},
     {'matchInfo': {'matchId': 33877,
       'seriesId': 3417,
       'seriesName': 'T20 Blast 2021',
       'matchDesc': 'South Group',
       'matchFormat': 'T20',
       'startDate': '1623434400000',
       'endDate': '1623434400000',
       'state': 'complete',
       'status': 'Hampshire won by 13 runs',
       'team1': {'teamId': 152,
        'teamName': 'ESSEX',
        'teamSName': 'ESS',
        'imageId': 172219},
       'team2': {'teamId': 153,
        'teamName': 'HAMPSHIRE',
        'teamSName': 'HAM',
        'imageId': 172220},
       'venueInfo': {'ground': 'County Ground',
        'city': 'Chelmsford',
        'timezone': '+01:00'},
       'currBatTeamId': 153,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 142,
         'wickets': 10,
         'overs': 19.2}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 155,
         'wickets': 6,
         'overs': 20.0}}}},
     {'matchInfo': {'matchId': 33868,
       'seriesId': 3417,
       'seriesName': 'T20 Blast 2021',
       'matchDesc': 'South Group',
       'matchFormat': 'T20',
       'startDate': '1623434400000',
       'endDate': '1623434400000',
       'state': 'complete',
       'status': 'Kent won by 16 runs',
       'team1': {'teamId': 150,
        'teamName': 'KENT',
        'teamSName': 'KENT',
        'imageId': 172217},
       'team2': {'teamId': 74,
        'teamName': 'MIDDLESEX',
        'teamSName': 'MDX',
        'imageId': 172170},
       'venueInfo': {'ground': 'St Lawrence Ground',
        'city': 'Canterbury',
        'timezone': '+01:00'},
       'currBatTeamId': 150,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 178,
         'wickets': 8,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 162,
         'wickets': 8,
         'overs': 20.0}}}}],
    'seriesId': 3417}},
  {'matchDetailsMap': {'key': 'Sat, 12 Jun 2021',
    'match': [{'matchInfo': {'matchId': 33893,
       'seriesId': 3417,
       'seriesName': 'T20 Blast 2021',
       'matchDesc': 'South Group',
       'matchFormat': 'T20',
       'startDate': '1623520800000',
       'endDate': '1623520800000',
       'state': 'complete',
       'status': 'Sussex won by 9 wkts',
       'team1': {'teamId': 41,
        'teamName': 'SUSSEX',
        'teamSName': 'SUS',
        'imageId': 172148},
       'team2': {'teamId': 153,
        'teamName': 'HAMPSHIRE',
        'teamSName': 'HAM',
        'imageId': 172220},
       'venueInfo': {'ground': 'County Ground',
        'city': 'Hove',
        'timezone': '+01:00'},
       'currBatTeamId': 41,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 155,
         'wickets': 1,
         'overs': 16.2}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 154,
         'wickets': 7,
         'overs': 20.0}}}}],
    'seriesId': 3417}},
  {'matchDetailsMap': {'key': 'Sun, 13 Jun 2021',
    'match': [{'matchInfo': {'matchId': 33908,
       'seriesId': 3417,
       'seriesName': 'T20 Blast 2021',
       'matchDesc': 'North Group',
       'matchFormat': 'T20',
       'startDate': '1623591000000',
       'endDate': '1623591000000',
       'state': 'complete',
       'status': 'Durham won by 2 wkts',
       'team1': {'teamId': 145,
        'teamName': 'LEICESTERSHIRE',
        'teamSName': 'LEIC',
        'imageId': 172212},
       'team2': {'teamId': 141,
        'teamName': 'DURHAM',
        'teamSName': 'DUR',
        'imageId': 172208},
       'venueInfo': {'ground': 'Grace Road',
        'city': 'Leicester',
        'timezone': '+01:00'},
       'currBatTeamId': 141,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 168,
         'wickets': 9,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 170,
         'wickets': 8,
         'overs': 19.0}}}},
     {'matchInfo': {'matchId': 33898,
       'seriesId': 3417,
       'seriesName': 'T20 Blast 2021',
       'matchDesc': 'North Group',
       'matchFormat': 'T20',
       'startDate': '1623591000000',
       'endDate': '1623591000000',
       'state': 'complete',
       'status': 'Worcestershire won by 8 wkts',
       'team1': {'teamId': 147,
        'teamName': 'WORCESTERSHIRE',
        'teamSName': 'WORCS',
        'imageId': 172214},
       'team2': {'teamId': 143,
        'teamName': 'LANCASHIRE',
        'teamSName': 'LANCS',
        'imageId': 172210},
       'venueInfo': {'ground': 'New Road',
        'city': 'Worcester',
        'timezone': '+01:00'},
       'currBatTeamId': 147,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 133,
         'wickets': 2,
         'overs': 17.2}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 132,
         'wickets': 4,
         'overs': 20.0}}}},
     {'matchInfo': {'matchId': 33902,
       'seriesId': 3417,
       'seriesName': 'T20 Blast 2021',
       'matchDesc': 'South Group',
       'matchFormat': 'T20',
       'startDate': '1623591000000',
       'endDate': '1623591000000',
       'state': 'complete',
       'status': 'Glamorgan won by 7 wkts',
       'team1': {'teamId': 149,
        'teamName': 'GLAMORGAN',
        'teamSName': 'GLAM',
        'imageId': 172216},
       'team2': {'teamId': 152,
        'teamName': 'ESSEX',
        'teamSName': 'ESS',
        'imageId': 172219},
       'venueInfo': {'ground': 'Sophia Gardens',
        'city': 'Cardiff',
        'timezone': '+01:00'},
       'currBatTeamId': 149,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,

In [84]:
s_m_detail2 = ser_3417['matchDetails']
s_m_detail2

[{'matchDetailsMap': {'key': 'Wed, 09 Jun 2021',
   'match': [{'matchInfo': {'matchId': 33828,
      'seriesId': 3417,
      'seriesName': 'T20 Blast 2021',
      'matchDesc': 'North Group',
      'matchFormat': 'T20',
      'startDate': '1623245400000',
      'endDate': '1623245400000',
      'state': 'complete',
      'status': 'Lancashire won by 6 wkts',
      'team1': {'teamId': 143,
       'teamName': 'LANCASHIRE',
       'teamSName': 'LANCS',
       'imageId': 172210},
      'team2': {'teamId': 144,
       'teamName': 'DERBYSHIRE',
       'teamSName': 'DERBY',
       'imageId': 172211},
      'venueInfo': {'ground': 'Emirates Old Trafford',
       'city': 'Manchester',
       'timezone': '+01:00'},
      'currBatTeamId': 143,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
        'runs': 171,
        'wickets': 4,
        'overs': 19.3}},
      'team2Score': {'inngs1': {'inningsId': 1,
        'runs': 168,
        'wickets': 7,
        'overs': 20.0}}}},
    {'matchInfo': {'matchId': 33833,
      'seriesId': 3417,
      'seriesName': 'T20 Blast 2021',
      'matchDesc': 'North Group',
      'matchFormat': 'T20',
      'startDate': '1623256200000',
      'endDate': '1623256200000',
      'state': 'complete',
      'status': 'Match tied',
      'team1': {'teamId': 147,
       'teamName': 'WORCESTERSHIRE',
       'teamSName': 'WORCS',
       'imageId': 172214},
      'team2': {'teamId': 139,
       'teamName': 'NOTTINGHAMSHIRE',
       'teamSName': 'NOTTS',
       'imageId': 172206},
      'venueInfo': {'ground': 'New Road',
       'city': 'Worcester',
       'timezone': '+01:00'},
      'currBatTeamId': 139,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
        'runs': 152,
        'wickets': 6,
        'overs': 20.0}},
      'team2Score': {'inngs1': {'inningsId': 2,
        'runs': 152,
        'wickets': 8,
        'overs': 20.0}}}},
    {'matchInfo': {'matchId': 33842,
      'seriesId': 3417,
      'seriesName': 'T20 Blast 2021',
      'matchDesc': 'South Group',
      'matchFormat': 'T20',
      'startDate': '1623259800000',
      'endDate': '1623259800000',
      'state': 'complete',
      'status': 'Essex won by 3 wkts',
      'team1': {'teamId': 119,
       'teamName': 'SOMERSET',
       'teamSName': 'SOM',
       'imageId': 172199},
      'team2': {'teamId': 152,
       'teamName': 'ESSEX',
       'teamSName': 'ESS',
       'imageId': 172219},
      'venueInfo': {'ground': 'The Cooper Associates County Ground',
       'city': 'Taunton',
       'timezone': '+01:00'},
      'currBatTeamId': 152,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
        'runs': 185,
        'wickets': 7,
        'overs': 20.0}},
      'team2Score': {'inngs1': {'inningsId': 2,
        'runs': 187,
        'wickets': 7,
        'overs': 18.5}}}},
    {'matchInfo': {'matchId': 33837,
      'seriesId': 3417,
      'seriesName': 'T20 Blast 2021',
      'matchDesc': 'South Group',
      'matchFormat': 'T20',
      'startDate': '1623261600000',
      'endDate': '1623261600000',
      'state': 'complete',
      'status': 'Kent won by 38 runs',
      'team1': {'teamId': 150,
       'teamName': 'KENT',
       'teamSName': 'KENT',
       'imageId': 172217},
      'team2': {'teamId': 153,
       'teamName': 'HAMPSHIRE',
       'teamSName': 'HAM',
       'imageId': 172220},
      'venueInfo': {'ground': 'St Lawrence Ground',
       'city': 'Canterbury',
       'timezone': '+01:00'},
      'currBatTeamId': 150,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
        'runs': 176,
        'wickets': 6,
        'overs': 20.0}},
      'team2Score': {'inngs1': {'inningsId': 2,
        'runs': 138,
        'wickets': 9,
        'overs': 20.0}}}}],
   'seriesId': 3417}},
 {'adDetail': {'name': 'native_news_index_random_1',
   'layout': 'native_large',
   'position': 1}},
 {'matchDetailsMap': {'key': 'Thu, 10 Jun 2021',
   'match': [{'matchInfo': {'matchId': 33862,
      'seriesId': 3417,
      'seriesName': 'T20 Blast 2021',
      'matchDesc': 'South Group',
      'matchFormat': 'T20',
      'startDate': '1623342600000',
      'endDate': '1623342600000',
      'state': 'complete',
      'status': 'Gloucestershire won by 4 runs',
      'team1': {'teamId': 149,
       'teamName': 'GLAMORGAN',
       'teamSName': 'GLAM',
       'imageId': 172216},
      'team2': {'teamId': 151,
       'teamName': 'GLOUCESTERSHIRE',
       'teamSName': 'GLOUCS',
       'imageId': 172218},
      'venueInfo': {'ground': 'Sophia Gardens',
       'city': 'Cardiff',
       'timezone': '+01:00'},
      'currBatTeamId': 151,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
        'runs': 175,
        'wickets': 9,
        'overs': 20.0}},
      'team2Score': {'inngs1': {'inningsId': 1,
        'runs': 179,
        'wickets': 6,
        'overs': 20.0}}}},
    {'matchInfo': {'matchId': 33847,
      'seriesId': 3417,
      'seriesName': 'T20 Blast 2021',
      'matchDesc': 'North Group',
      'matchFormat': 'T20',
      'startDate': '1623346200000',
      'endDate': '1623346200000',
      'state': 'complete',
      'status': 'Yorkshire won by 6 wkts',
      'team1': {'teamId': 146,
       'teamName': 'YORKSHIRE',
       'teamSName': 'YORKS',
       'imageId': 172213},
      'team2': {'teamId': 140,
       'teamName': 'WARWICKSHIRE',
       'teamSName': 'WARKS',
       'imageId': 172207},
      'venueInfo': {'ground': 'Headingley',
       'city': 'Leeds',
       'timezone': '+01:00'},
      'currBatTeamId': 146,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
        'runs': 147,
        'wickets': 4,
        'overs': 18.3}},
      'team2Score': {'inngs1': {'inningsId': 1,
        'runs': 144,
        'wickets': 8,
        'overs': 20.0}}}},
    {'matchInfo': {'matchId': 33852,
      'seriesId': 3417,
      'seriesName': 'T20 Blast 2021',
      'matchDesc': 'North Group',
      'matchFormat': 'T20',
      'startDate': '1623346200000',
      'endDate': '1623346200000',
      'state': 'complete',
      'status': 'Lancashire won by 16 runs',
      'team1': {'teamId': 143,
       'teamName': 'LANCASHIRE',
       'teamSName': 'LANCS',
       'imageId': 172210},
      'team2': {'teamId': 145,
       'teamName': 'LEICESTERSHIRE',
       'teamSName': 'LEIC',
       'imageId': 172212},
      'venueInfo': {'ground': 'Emirates Old Trafford',
       'city': 'Manchester',
       'timezone': '+01:00'},
      'currBatTeamId': 143,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
        'runs': 172,
        'wickets': 8,
        'overs': 20.0}},
      'team2Score': {'inngs1': {'inningsId': 2,
        'runs': 156,
        'wickets': 5,
        'overs': 20.0}}}},
    {'matchInfo': {'matchId': 33857,
      'seriesId': 3417,
      'seriesName': 'T20 Blast 2021',
      'matchDesc': 'South Group',
      'matchFormat': 'T20',
      'startDate': '1623348000000',
      'endDate': '1623348000000',
      'state': 'complete',
      'status': 'Surrey won by 54 runs',
      'team1': {'teamId': 74,
       'teamName': 'MIDDLESEX',
       'teamSName': 'MDX',
       'imageId': 172170},
      'team2': {'teamId': 148,
       'teamName': 'SURREY',
       'teamSName': 'SUR',
       'imageId': 172215},
      'venueInfo': {'ground': "Lord's",
       'city': 'London',
       'timezone': '+01:00'},
      'currBatTeamId': 148,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
        'runs': 169,
        'wickets': 9,
        'overs': 20.0}},
      'team2Score': {'inngs1': {'inningsId': 1,
        'runs': 223,
        'wickets': 7,
        'overs': 20.0}}}}],
   'seriesId': 3417}},
 {'matchDetailsMap': {'key': 'Fri, 11 Jun 2021',
   'match': [{'matchInfo': {'matchId': 33867,
      'seriesId': 3417,
      'seriesName': 'T20 Blast 2021',
      'matchDesc': 'South Group',
      'matchFormat': 'T20',
      'startDate': '1623432600000',
      'endDate': '1623432600000',
      'state': 'complete',
      'status': 'Sussex won by 5 wkts',
      'team1': {'teamId': 151,
       'teamName': 'GLOUCESTERSHIRE',
       'teamSName': 'GLOUCS',
       'imageId': 172218},
      'team2': {'teamId': 41,
       'teamName': 'SUSSEX',
       'teamSName': 'SUS',
       'imageId': 172148},
      'venueInfo': {'ground': 'County Ground',
       'city': 'Bristol',
       'timezone': '+01:00'},
      'currBatTeamId': 41,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
        'runs': 177,
        'wickets': 7,
        'overs': 20.0}},
      'team2Score': {'inngs1': {'inningsId': 2,
        'runs': 178,
        'wickets': 5,
        'overs': 17.2}}}},
    {'matchInfo': {'matchId': 33892,
      'seriesId': 3417,
      'seriesName': 'T20 Blast 2021',
      'matchDesc': 'North Group',
      'matchFormat': 'T20',
      'startDate': '1623432600000',
      'endDate': '1623432600000',
      'state': 'complete',
      'status': 'Derbyshire won by 23 runs',
      'team1': {'teamId': 145,
       'teamName': 'LEICESTERSHIRE',
       'teamSName': 'LEIC',
       'imageId': 172212},
      'team2': {'teamId': 144,
       'teamName': 'DERBYSHIRE',
       'teamSName': 'DERBY',
       'imageId': 172211},
      'venueInfo': {'ground': 'Grace Road',
       'city': 'Leicester',
       'timezone': '+01:00'},
      'currBatTeamId': 144,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
        'runs': 186,
        'wickets': 10,
        'overs': 19.0}},
      'team2Score': {'inngs1': {'inningsId': 1,
        'runs': 209,
        'wickets': 6,
        'overs': 20.0}}}},
    {'matchInfo': {'matchId': 33872,
      'seriesId': 3417,
      'seriesName': 'T20 Blast 2021',
      'matchDesc': 'North Group',
      'matchFormat': 'T20',
      'startDate': '1623432600000',
      'endDate': '1623432600000',
      'state': 'complete',
      'status': 'Durham won by 20 runs',
      'team1': {'teamId': 141,
       'teamName': 'DURHAM',
       'teamSName': 'DUR',
       'imageId': 172208},
      'team2': {'teamId': 146,
       'teamName': 'YORKSHIRE',
       'teamSName': 'YORKS',
       'imageId': 172213},
      'venueInfo': {'ground': 'Riverside Ground',
       'city': 'Chester-le-Street',
       'timezone': '+01:00'},
      'currBatTeamId': 141,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
        'runs': 181,
        'wickets': 8,
        'overs': 20.0}},
      'team2Score': {'inngs1': {'inningsId': 2,
        'runs': 161,
        'wickets': 6,
        'overs': 20.0}}}},
    {'matchInfo': {'matchId': 33887,
      'seriesId': 3417,
      'seriesName': 'T20 Blast 2021',
      'matchDesc': 'North Group',
      'matchFormat': 'T20',
      'startDate': '1623432600000',
      'endDate': '1623432600000',
      'state': 'complete',
      'status': 'Warwickshire won by 18 runs',
      'team1': {'teamId': 139,
       'teamName': 'NOTTINGHAMSHIRE',
       'teamSName': 'NOTTS',
       'imageId': 172206},
      'team2': {'teamId': 140,
       'teamName': 'WARWICKSHIRE',
       'teamSName': 'WARKS',
       'imageId': 172207},
      'venueInfo': {'ground': 'Trent Bridge',
       'city': 'Nottingham',
       'timezone': '+01:00'},
      'currBatTeamId': 140,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
        'runs': 211,
        'wickets': 9,
        'overs': 20.0}},
      'team2Score': {'inngs1': {'inningsId': 1,
        'runs': 229,
        'wickets': 5,
        'overs': 20.0}}}},
    {'matchInfo': {'matchId': 33878,
      'seriesId': 3417,
      'seriesName': 'T20 Blast 2021',
      'matchDesc': 'South Group',
      'matchFormat': 'T20',
      'startDate': '1623432600000',
      'endDate': '1623432600000',
      'state': 'complete',
      'status': 'Surrey won by 7 wkts',
      'team1': {'teamId': 119,
       'teamName': 'SOMERSET',
       'teamSName': 'SOM',
       'imageId': 172199},
      'team2': {'teamId': 148,
       'teamName': 'SURREY',
       'teamSName': 'SUR',
       'imageId': 172215},
      'venueInfo': {'ground': 'The Cooper Associates County Ground',
       'city': 'Taunton',
       'timezone': '+01:00'},
      'currBatTeamId': 148,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
        'runs': 187,
        'wickets': 6,
        'overs': 20.0}},
      'team2Score': {'inngs1': {'inningsId': 2,
        'runs': 188,
        'wickets': 3,
        'overs': 16.0}}}},
    {'matchInfo': {'matchId': 33883,
      'seriesId': 3417,
      'seriesName': 'T20 Blast 2021',
      'matchDesc': 'North Group',
      'matchFormat': 'T20',
      'startDate': '1623434400000',
      'endDate': '1623434400000',
      'state': 'complete',
      'status': 'Worcestershire won by 32 runs',
      'team1': {'teamId': 142,
       'teamName': 'NORTHAMPTONSHIRE',
       'teamSName': 'NHNTS',
       'imageId': 172209},
      'team2': {'teamId': 147,
       'teamName': 'WORCESTERSHIRE',
       'teamSName': 'WORCS',
       'imageId': 172214},
      'venueInfo': {'ground': 'County Ground',
       'city': 'Northampton',
       'timezone': '+01:00'},
      'currBatTeamId': 147,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
        'runs': 153,
        'wickets': 9,
        'overs': 20.0}},
      'team2Score': {'inngs1': {'inningsId': 1,
        'runs': 185,
        'wickets': 7,
        'overs': 20.0}}}},
    {'matchInfo': {'matchId': 33877,
      'seriesId': 3417,
      'seriesName': 'T20 Blast 2021',
      'matchDesc': 'South Group',
      'matchFormat': 'T20',
      'startDate': '1623434400000',
      'endDate': '1623434400000',
      'state': 'complete',
      'status': 'Hampshire won by 13 runs',
      'team1': {'teamId': 152,
       'teamName': 'ESSEX',
       'teamSName': 'ESS',
       'imageId': 172219},
      'team2': {'teamId': 153,
       'teamName': 'HAMPSHIRE',
       'teamSName': 'HAM',
       'imageId': 172220},
      'venueInfo': {'ground': 'County Ground',
       'city': 'Chelmsford',
       'timezone': '+01:00'},
      'currBatTeamId': 153,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
        'runs': 142,
        'wickets': 10,
        'overs': 19.2}},
      'team2Score': {'inngs1': {'inningsId': 1,
        'runs': 155,
        'wickets': 6,
        'overs': 20.0}}}},
    {'matchInfo': {'matchId': 33868,
      'seriesId': 3417,
      'seriesName': 'T20 Blast 2021',
      'matchDesc': 'South Group',
      'matchFormat': 'T20',
      'startDate': '1623434400000',
      'endDate': '1623434400000',
      'state': 'complete',
      'status': 'Kent won by 16 runs',
      'team1': {'teamId': 150,
       'teamName': 'KENT',
       'teamSName': 'KENT',
       'imageId': 172217},
      'team2': {'teamId': 74,
       'teamName': 'MIDDLESEX',
       'teamSName': 'MDX',
       'imageId': 172170},
      'venueInfo': {'ground': 'St Lawrence Ground',
       'city': 'Canterbury',
       'timezone': '+01:00'},
      'currBatTeamId': 150,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
        'runs': 178,
        'wickets': 8,
        'overs': 20.0}},
      'team2Score': {'inngs1': {'inningsId': 2,
        'runs': 162,
        'wickets': 8,
        'overs': 20.0}}}}],
   'seriesId': 3417}},
 {'matchDetailsMap': {'key': 'Sat, 12 Jun 2021',
   'match': [{'matchInfo': {'matchId': 33893,
      'seriesId': 3417,
      'seriesName': 'T20 Blast 2021',
      'matchDesc': 'South Group',
      'matchFormat': 'T20',
      'startDate': '1623520800000',
      'endDate': '1623520800000',
      'state': 'complete',
      'status': 'Sussex won by 9 wkts',
      'team1': {'teamId': 41,
       'teamName': 'SUSSEX',
       'teamSName': 'SUS',
       'imageId': 172148},
      'team2': {'teamId': 153,
       'teamName': 'HAMPSHIRE',
       'teamSName': 'HAM',
       'imageId': 172220},
      'venueInfo': {'ground': 'County Ground',
       'city': 'Hove',
       'timezone': '+01:00'},
      'currBatTeamId': 41,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
        'runs': 155,
        'wickets': 1,
        'overs': 16.2}},
      'team2Score': {'inngs1': {'inningsId': 1,
        'runs': 154,
        'wickets': 7,
        'overs': 20.0}}}}],
   'seriesId': 3417}},
 {'matchDetailsMap': {'key': 'Sun, 13 Jun 2021',
   'match': [{'matchInfo': {'matchId': 33908,
      'seriesId': 3417,
      'seriesName': 'T20 Blast 2021',
      'matchDesc': 'North Group',
      'matchFormat': 'T20',
      'startDate': '1623591000000',
      'endDate': '1623591000000',
      'state': 'complete',
      'status': 'Durham won by 2 wkts',
      'team1': {'teamId': 145,
       'teamName': 'LEICESTERSHIRE',
       'teamSName': 'LEIC',
       'imageId': 172212},
      'team2': {'teamId': 141,
       'teamName': 'DURHAM',
       'teamSName': 'DUR',
       'imageId': 172208},
      'venueInfo': {'ground': 'Grace Road',
       'city': 'Leicester',
       'timezone': '+01:00'},
      'currBatTeamId': 141,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
        'runs': 168,
        'wickets': 9,
        'overs': 20.0}},
      'team2Score': {'inngs1': {'inningsId': 2,
        'runs': 170,
        'wickets': 8,
        'overs': 19.0}}}},
    {'matchInfo': {'matchId': 33898,
      'seriesId': 3417,
      'seriesName': 'T20 Blast 2021',
      'matchDesc': 'North Group',
      'matchFormat': 'T20',
      'startDate': '1623591000000',
      'endDate': '1623591000000',
      'state': 'complete',
      'status': 'Worcestershire won by 8 wkts',
      'team1': {'teamId': 147,
       'teamName': 'WORCESTERSHIRE',
       'teamSName': 'WORCS',
       'imageId': 172214},
      'team2': {'teamId': 143,
       'teamName': 'LANCASHIRE',
       'teamSName': 'LANCS',
       'imageId': 172210},
      'venueInfo': {'ground': 'New Road',
       'city': 'Worcester',
       'timezone': '+01:00'},
      'currBatTeamId': 147,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
        'runs': 133,
        'wickets': 2,
        'overs': 17.2}},
      'team2Score': {'inngs1': {'inningsId': 1,
        'runs': 132,
        'wickets': 4,
        'overs': 20.0}}}},
    {'matchInfo': {'matchId': 33902,
      'seriesId': 3417,
      'seriesName': 'T20 Blast 2021',
      'matchDesc': 'South Group',
      'matchFormat': 'T20',
      'startDate': '1623591000000',
      'endDate': '1623591000000',
      'state': 'complete',
      'status': 'Glamorgan won by 7 wkts',
      'team1': {'teamId': 149,
       'teamName': 'GLAMORGAN',
       'teamSName': 'GLAM',
       'imageId': 172216},
      'team2': {'teamId': 152,
       'teamName': 'ESSEX',
       'teamSName': 'ESS',
       'imageId': 172219},
      'venueInfo': {'ground': 'Sophia Gardens',
       'city': 'Cardiff',
       'timezone': '+01:00'},
      'currBatTeamId': 149,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
        'runs': 156,
        'wickets': 3,
        'overs': 19.0}},
      'team2Score': {'inngs1': {'inningsId': 1,
        'runs': 153,
        'wickets': 6,
        'overs': 20.0}}}},
    {'matchInfo': {'matchId': 33907,
      'seriesId': 3417,
      'seriesName': 'T20 Blast 2021',
      'matchDesc': 'North Group',
      'matchFormat': 'T20',
      'startDate': '1623591000000',
      'endDate': '1623591000000',
      'state': 'complete',
      'status': 'Warwickshire won by 3 wkts',
      'team1': {'teamId': 144,
       'teamName': 'DERBYSHIRE',
       'teamSName': 'DERBY',
       'imageId': 172211},
      'team2': {'teamId': 140,

In [85]:
import pandas as pd
from datetime import datetime

series_matches = []

for item in s_m_detail2:
    
    match_map = item.get('matchDetailsMap', {})
    
    for m in match_map.get('match', []):
        
        info = m.get('matchInfo', {})
        
        match_id = info.get('matchId')
        series_name = info.get('seriesName')
        match_desc = info.get('matchDesc')
        match_format = info.get('matchFormat')
        
        team1 = info.get('team1', {}).get('teamName')
        team2 = info.get('team2', {}).get('teamName')
        
        venue = info.get('venueInfo', {}).get('ground')
        city = info.get('venueInfo', {}).get('city')
        
        start_date = datetime.fromtimestamp(
            int(info.get('startDate'))/1000
        ).strftime('%Y-%m-%d')
        
        status = info.get('status')
        
        series_matches.append({
            "Match ID": match_id,
            "Series": series_name,
            "Match": match_desc,
            "Format": match_format,
            "Team1": team1,
            "Team2": team2,
            "Venue": venue,
            "City": city,
            "Start Date": start_date,
            "Result": status
        })

df_2021 = pd.DataFrame(series_matches)

df_2021.head()

,Match ID,Series,Match,Format,Team1,Team2,Venue,City,Start Date,Result
0,33828,T20 Blast 2021,North Group,T20,LANCASHIRE,DERBYSHIRE,Emirates Old Trafford,Manchester,2021-06-09,Lancashire won by 6 wkts
1,33833,T20 Blast 2021,North Group,T20,WORCESTERSHIRE,NOTTINGHAMSHIRE,New Road,Worcester,2021-06-09,Match tied
2,33842,T20 Blast 2021,South Group,T20,SOMERSET,ESSEX,The Cooper Associates County Ground,Taunton,2021-06-09,Essex won by 3 wkts
3,33837,T20 Blast 2021,South Group,T20,KENT,HAMPSHIRE,St Lawrence Ground,Canterbury,2021-06-09,Kent won by 38 runs
4,33862,T20 Blast 2021,South Group,T20,GLAMORGAN,GLOUCESTERSHIRE,Sophia Gardens,Cardiff,2021-06-10,Gloucestershire won by 4 runs

In [87]:
df_q16 = pd.concat([df_2020, df_2021])
df_q16

,Match ID,Series,Match,Format,Team1,Team2,Venue,City,Start Date,Result
0,30330,Indian Premier League 2020,1st Match,T20,MUMBAI INDIANS,CHENNAI SUPER KINGS,Sheikh Zayed Stadium,Abu Dhabi,2020-09-19,Chennai Super Kings won by 5 wkts
1,30340,Indian Premier League 2020,2nd Match,T20,DELHI CAPITALS,PUNJAB KINGS,Dubai International Cricket Stadium,Dubai,2020-09-20,Match tied (Delhi Capitals won the Super Over)
2,30345,Indian Premier League 2020,3rd Match,T20,SUNRISERS HYDERABAD,ROYAL CHALLENGERS BENGALURU,Dubai International Cricket Stadium,Dubai,2020-09-21,Royal Challengers Bangalore won by 10 runs
3,30350,Indian Premier League 2020,4th Match,T20,RAJASTHAN ROYALS,CHENNAI SUPER KINGS,Sharjah Cricket Stadium,Sharjah,2020-09-22,Rajasthan Royals won by 16 runs
4,30354,Indian Premier League 2020,5th Match,T20,KOLKATA KNIGHT RIDERS,MUMBAI INDIANS,Sheikh Zayed Stadium,Abu Dhabi,2020-09-23,Mumbai Indians won by 49 runs
...,...,...,...,...,...,...,...,...,...,...
128,34317,T20 Blast 2021,Quarter Final 3,T20,SOMERSET,LANCASHIRE,The Cooper Associates County Ground,Taunton,2021-08-26,Somerset won by 7 wkts
129,34322,T20 Blast 2021,Quarter Final 4,T20,KENT,WARWICKSHIRE,St Lawrence Ground,Canterbury,2021-08-27,Kent won by 21 runs
130,34323,T20 Blast 2021,Semi Final 1,T20,HAMPSHIRE,SOMERSET,Edgbaston,Birmingham,2021-09-18,Somerset won by 2 wkts
131,34327,T20 Blast 2021,Semi Final 2,T20,SUSSEX,KENT,Edgbaston,Birmingham,2021-09-18,Kent won by 21 runs
132,34328,T20 Blast 2021,Final,T20,SOMERSET,KENT,Edgbaston,Birmingham,2021-09-18,Kent won by 25 runs

In [93]:
import urllib.parse
from sqlalchemy import create_engine

# 1. Encode the special character in password
password = urllib.parse.quote_plus("deepika@88")

# 2. Use the encoded password in your connection string
# Also, ensure 'username' is replaced with your actual DB user (usually 'postgres')
engine = create_engine(f'postgresql+psycopg2://postgres:{password}@localhost:5432/cricbuzz')

# 3. Test the connection and push the data
df_q16.to_sql('table2020_2021', engine, if_exists='replace', index=False)

print("✅ Connection successful and table '2020 & 2021' created!")

✅ Connection successful and table '2020 & 2021' created!

# Q16 Get the match details from scard

In [96]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/30494/scard"

headers = {
	"x-rapidapi-key": "e6021fb984msh201af5139a6e2e9p149939jsn32edaa5716a4",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

m5 = response.json()

In [99]:
m3

{'scorecard': [{'inningsid': 1,
   'batsman': [{'id': 8733,
     'balls': 52,
     'runs': 63,
     'fours': 7,
     'sixes': 1,
     'strkrate': '121.15',
     'name': 'Rahul',
     'nickname': '',
     'iscaptain': True,
     'iskeeper': False,
     'outdec': 'c Dhoni b SN Thakur',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 2195,
     'balls': 19,
     'runs': 26,
     'fours': 3,
     'sixes': 0,
     'strkrate': '136.84',
     'name': 'Mayank Agarwal',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c Sam Curran b Chawla',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 6319,
     'balls': 16,
     'runs': 27,
     'fours': 0,
     'sixes': 2,
     'strkrate': '168.75',
     'name': 'Mandeep',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c Rayudu b Ravindra Jadeja',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 9406,
     'balls': 17,
     'runs': 33,
     'fours': 1,
     'sixes': 3,
     'strkrate': '194.12',
     'name': 'Pooran',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': True,
     'outdec': 'c Ravindra Jadeja b SN Thakur',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 7662,
     'balls': 7,
     'runs': 11,
     'fours': 1,
     'sixes': 0,
     'strkrate': '157.14',
     'name': 'Maxwell',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'not out',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 9429,
     'balls': 9,
     'runs': 14,
     'fours': 2,
     'sixes': 0,
     'strkrate': '155.56',
     'name': 'Sarfaraz Khan',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'not out',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 6532,
     'balls': 0,
     'runs': 0,
     'fours': 0,
     'sixes': 0,
     'strkrate': '0',
     'name': 'Chris Jordan',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': '',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 14452,
     'balls': 0,
     'runs': 0,
     'fours': 0,
     'sixes': 0,
     'strkrate': '0',
     'name': 'Harpreet Brar',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': '',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 14659,
     'balls': 0,
     'runs': 0,
     'fours': 0,
     'sixes': 0,
     'strkrate': '0',
     'name': 'Ravi Bishnoi',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': '',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 7909,
     'balls': 0,
     'runs': 0,
     'fours': 0,
     'sixes': 0,
     'strkrate': '0',
     'name': 'Shami',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': '',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 9395,
     'balls': 0,
     'runs': 0,
     'fours': 0,
     'sixes': 0,
     'strkrate': '0',
     'name': 'Cottrell',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': '',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''}],
   'bowler': [{'id': 7836,
     'overs': '3',
     'maidens': 0,
     'wickets': 0,
     'runs': 17,
     'economy': '5.7',
     'name': 'D Chahar',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'dots': 0,
     'balls': 18,
     'rpb': 0.0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 10420,
     'overs': '3',
     'maidens': 0,
     'wickets': 0,
     'runs': 31,
     'economy': '10.3',
     'name': 'Sam Curran',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'dots': 0,
     'balls': 18,
     'rpb': 0.0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 8683,
     'overs': '4',
     'maidens': 0,
     'wickets': 2,
     'runs': 39,
     'economy': '9.8',
     'name': 'SN Thakur',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'dots': 0,
     'balls': 24,
     'rpb': 0.0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 242,
     'overs': '4',
     'maidens': 0,
     'wickets': 0,
     'runs': 38,
     'economy': '9.5',
     'name': 'DJ Bravo',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'dots': 0,
     'balls': 24,
     'rpb': 0.0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 587,
     'overs': '4',
     'maidens': 0,
     'wickets': 1,
     'runs': 30,
     'economy': '7.5',
     'name': 'Ravindra Jadeja',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'dots': 0,
     'balls': 24,
     'rpb': 0.0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 466,
     'overs': '2',
     'maidens': 0,
     'wickets': 1,
     'runs': 22,
     'economy': '11',
     'name': 'Chawla',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'dots': 0,
     'balls': 12,
     'rpb': 0.0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''}],
   'fow': {'fow': [{'batsmanid': 2195,
      'batsmanname': 'Mayank Agarwal',
      'overnbr': 8.1,
      'runs': 61,
      'ballnbr': 49},
     {'batsmanid': 6319,
      'batsmanname': 'Mandeep',
      'overnbr': 11.6,
      'runs': 94,
      'ballnbr': 72},
     {'batsmanid': 9406,
      'batsmanname': 'Pooran',
      'overnbr': 17.1,
      'runs': 152,
      'ballnbr': 103},
     {'batsmanid': 8733,
      'batsmanname': 'Rahul',
      'overnbr': 17.2,
      'runs': 152,
      'ballnbr': 104}]},
   'extras': {'legbyes': 1,
    'byes': 0,
    'wides': 3,
    'noballs': 0,
    'penalty': 0,
    'total': 4},
   'pp': {'powerplay': [{'id': 3,
      'ovrfrom': 0.1,
      'ovrto': 6.0,
      'pptype': 'Mandatory',
      'run': 46,
      'wickets': 0}]},
   'score': 178,
   'wickets': 4,
   'overs': 20.0,
   'runrate': 8.9,
   'batteamname': 'Kings XI Punjab',
   'batteamsname': 'KXIP',
   'isdeclared': False,
   'isfollowon': False,
   'ballnbr': 120,
   'rpb': 1.48,
   'partnership': {'partnership': [{'id': 0,
      'bat1id': 8733,
      'bat1name': 'Rahul',
      'bat1runs': 32,
      'bat1fours': 4,
      'bat1sixes': 0,
      'bat2id': 2195,
      'bat2name': 'Agarwal',
      'bat2runs': 26,
      'bat2fours': 3,
      'bat2sixes': 0,
      'totalruns': 61,
      'totalballs': 49,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 8733,
      'bat1name': 'Rahul',
      'bat1runs': 6,
      'bat1fours': 0,
      'bat1sixes': 0,
      'bat2id': 6319,
      'bat2name': 'Mandeep',
      'bat2runs': 27,
      'bat2fours': 0,
      'bat2sixes': 2,
      'totalruns': 33,
      'totalballs': 23,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 8733,
      'bat1name': 'Rahul',
      'bat1runs': 25,
      'bat1fours': 3,
      'bat1sixes': 1,
      'bat2id': 9406,
      'bat2name': 'Pooran',
      'bat2runs': 33,
      'bat2fours': 1,
      'bat2sixes': 3,
      'totalruns': 58,
      'totalballs': 31,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 8733,
      'bat1name': 'Rahul',
      'bat1runs': 0,
      'bat1fours': 0,
      'bat1sixes': 0,
      'bat2id': 7662,
      'bat2name': 'Maxwell',
      'bat2runs': 0,
      'bat2fours': 0,
      'bat2sixes': 0,
      'totalruns': 0,
      'totalballs': 1,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 9429,
      'bat1name': 'Sarfaraz Khan',
      'bat1runs': 14,
      'bat1fours': 2,
      'bat1sixes': 0,
      'bat2id': 7662,
      'bat2name': 'Maxwell',
      'bat2runs': 11,
      'bat2fours': 1,
      'bat2sixes': 0,
      'totalruns': 26,
      'totalballs': 16,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0}]}},
  {'inningsid': 2,
   'batsman': [{'id': 158,
     'balls': 53,
     'runs': 83,
     'fours': 11,
     'sixes': 3,
     'strkrate': '156.6',
     'name': 'Shane Watson',
     'nickname': 'Watson',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'not out',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 7825,
     'balls': 53,
     'runs': 87,
     'fours': 11,
     'sixes': 1,
     'strkrate': '164.15',
     'name': 'Faf du Plessis',
     'nickname': 'du Plessis',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'not out',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 6311,
     'balls': 0,
     'runs': 0,
     'fours': 0,
     'sixes': 0,
     'strkrate': '0',
     'name': 'Ambati Rayudu',
     'nickname': 'Rayudu',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': '',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 265,
     'balls': 0,
     'runs': 0,
     'fours': 0,
     'sixes': 0,
     'strkrate': '0',
     'name': 'MS Dhoni',
     'nickname': 'Dhoni',
     'iscaptain': True,
     'iskeeper': True,
     'outdec': '',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 1851,
     'balls': 0,
     'runs': 0,
     'fours': 0,
     'sixes': 0,
     'strkrate': '0',
     'name': 'Kedar Jadhav',
     'nickname': 'Kedar Jadhav',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': '',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 587,
     'balls': 0,
     'runs': 0,
     'fours': 0,
     'sixes': 0,
     'strkrate': '0',
     'name': 'Ravindra Jadeja',
     'nickname': 'Ravindra Jadeja',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': '',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 242,
     'balls': 0,
     'runs': 0,
     'fours': 0,
     'sixes': 0,
     'strkrate': '0',
     'name': 'Dwayne Bravo',
     'nickname': 'DJ Bravo',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': '',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 10420,
     'balls': 0,
     'runs': 0,
     'fours': 0,
     'sixes': 0,
     'strkrate': '0',
     'name': 'Sam Curran',
     'nickname': 'Sam Curran',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': '',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 8683,
     'balls': 0,
     'runs': 0,
     'fours': 0,
     'sixes': 0,
     'strkrate': '0',
     'name': 'Shardul Thakur',
     'nickname': 'SN Thakur',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': '',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 466,
     'balls': 0,
     'runs': 0,
     'fours': 0,
     'sixes': 0,
     'strkrate': '0',
     'name': 'Piyush Chawla',
     'nickname': 'Chawla',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': '',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 7836,
     'balls': 0,
     'runs': 0,
     'fours': 0,
     'sixes': 0,
     'strkrate': '0',
     'name': 'Deepak Chahar',
     'nickname': 'D Chahar',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': '',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''}],
   'bowler': [{'id': 9395,
     'overs': '3',
     'maidens': 0,
     'wickets': 0,
     'runs': 30,
     'economy': '10',
     'name': 'Sheldon Cottrell',
     'nickname': 'Cottrell',
     'iscaptain': False,
     'iskeeper': False,
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'dots': 0,
     'balls': 18,
     'rpb': 0.0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 7909,
     'overs': '3.4',
     'maidens': 0,
     'wickets': 0,
     'runs': 35,
     'economy': '9.5',
     'name': 'Mohammed Shami',
     'nickname': 'Shami',
     'iscaptain': False,
     'iskeeper': False,
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'dots': 0,
     'balls': 22,
     'rpb': 0.0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 14452,
     'overs': '4',
     'maidens': 0,
     'wickets': 0,
     'runs': 41,
     'economy': '10.2',
     'name': 'Harpreet Brar',
     'nickname': 'Harpreet Brar',
     'iscaptain': False,
     'iskeeper': False,
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'dots': 0,
     'balls': 24,
     'rpb': 0.0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 6532,
     'overs': '3',
     'maidens': 0,
     'wickets': 0,
     'runs': 42,

In [97]:
m2

{'scorecard': [{'inningsid': 1,
   'batsman': [{'id': 13940,
     'balls': 6,
     'runs': 6,
     'fours': 1,
     'sixes': 0,
     'strkrate': '100',
     'name': 'Jaiswal',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c and b D Chahar',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 2250,
     'balls': 47,
     'runs': 69,
     'fours': 4,
     'sixes': 4,
     'strkrate': '146.81',
     'name': 'Steven Smith',
     'nickname': '',
     'iscaptain': True,
     'iskeeper': False,
     'outdec': 'c Kedar Jadhav b Sam Curran',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 8271,
     'balls': 32,
     'runs': 74,
     'fours': 1,
     'sixes': 9,
     'strkrate': '231.25',
     'name': 'Samson',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': True,
     'outdec': 'c D Chahar b Lungi Ngidi',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 6349,
     'balls': 0,
     'runs': 0,
     'fours': 0,
     'sixes': 0,
     'strkrate': '0',
     'name': 'Miller',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'run out (Ruturaj Gaikwad/Kedar Jadhav)',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 527,
     'balls': 9,
     'runs': 5,
     'fours': 0,
     'sixes': 0,
     'strkrate': '55.56',
     'name': 'Uthappa',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c du Plessis b Chawla',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 9693,
     'balls': 8,
     'runs': 10,
     'fours': 1,
     'sixes': 0,
     'strkrate': '125',
     'name': 'Rahul Tewatia',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'lbw b Sam Curran',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 12305,
     'balls': 4,
     'runs': 6,
     'fours': 1,
     'sixes': 0,
     'strkrate': '150',
     'name': 'Riyan Parag',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c Dhoni b Sam Curran',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 9522,
     'balls': 9,
     'runs': 10,
     'fours': 1,
     'sixes': 0,
     'strkrate': '111.11',
     'name': 'Tom Curran',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'not out',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 11540,
     'balls': 8,
     'runs': 27,
     'fours': 0,
     'sixes': 4,
     'strkrate': '337.5',
     'name': 'Jofra Archer',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'not out',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 9746,
     'balls': 0,
     'runs': 0,
     'fours': 0,
     'sixes': 0,
     'strkrate': '0',
     'name': 'Shreyas Gopal',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': '',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 6327,
     'balls': 0,
     'runs': 0,
     'fours': 0,
     'sixes': 0,
     'strkrate': '0',
     'name': 'Unadkat',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': '',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''}],
   'bowler': [{'id': 7836,
     'overs': '4',
     'maidens': 0,
     'wickets': 1,
     'runs': 31,
     'economy': '7.8',
     'name': 'D Chahar',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'dots': 0,
     'balls': 24,
     'rpb': 0.0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 10420,
     'overs': '4',
     'maidens': 0,
     'wickets': 3,
     'runs': 33,
     'economy': '8.2',
     'name': 'Sam Curran',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'dots': 0,
     'balls': 24,
     'rpb': 0.0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 9603,
     'overs': '4',
     'maidens': 0,
     'wickets': 1,
     'runs': 56,
     'economy': '14',
     'name': 'Lungi Ngidi',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'dots': 0,
     'balls': 24,
     'rpb': 0.0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 587,
     'overs': '4',
     'maidens': 0,
     'wickets': 0,
     'runs': 40,
     'economy': '10',
     'name': 'Ravindra Jadeja',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'dots': 0,
     'balls': 24,
     'rpb': 0.0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 466,
     'overs': '4',
     'maidens': 0,
     'wickets': 1,
     'runs': 55,
     'economy': '13.8',
     'name': 'Chawla',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'dots': 0,
     'balls': 24,
     'rpb': 0.0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''}],
   'fow': {'fow': [{'batsmanid': 13940,
      'batsmanname': 'Jaiswal',
      'overnbr': 2.2,
      'runs': 11,
      'ballnbr': 14},
     {'batsmanid': 8271,
      'batsmanname': 'Samson',
      'overnbr': 11.4,
      'runs': 132,
      'ballnbr': 70},
     {'batsmanid': 6349,
      'batsmanname': 'Miller',
      'overnbr': 12.0,
      'runs': 134,
      'ballnbr': 72},
     {'batsmanid': 527,
      'batsmanname': 'Uthappa',
      'overnbr': 14.1,
      'runs': 149,
      'ballnbr': 85},
     {'batsmanid': 9693,
      'batsmanname': 'Rahul Tewatia',
      'overnbr': 16.2,
      'runs': 167,
      'ballnbr': 98},
     {'batsmanid': 12305,
      'batsmanname': 'Riyan Parag',
      'overnbr': 16.6,
      'runs': 173,
      'ballnbr': 102},
     {'batsmanid': 2250,
      'batsmanname': 'Steven Smith',
      'overnbr': 18.2,
      'runs': 178,
      'ballnbr': 110}]},
   'extras': {'legbyes': 0,
    'byes': 1,
    'wides': 5,
    'noballs': 3,
    'penalty': 0,
    'total': 9},
   'pp': {'powerplay': [{'id': 11,
      'ovrfrom': 0.1,
      'ovrto': 6.0,
      'pptype': 'Mandatory',
      'run': 54,
      'wickets': 0}]},
   'score': 216,
   'wickets': 7,
   'overs': 20.0,
   'runrate': 10.8,
   'batteamname': 'Rajasthan Royals',
   'batteamsname': 'RR',
   'isdeclared': False,
   'isfollowon': False,
   'ballnbr': 120,
   'rpb': 1.8,
   'partnership': {'partnership': [{'id': 0,
      'bat1id': 13940,
      'bat1name': 'Jaiswal',
      'bat1runs': 6,
      'bat1fours': 1,
      'bat1sixes': 0,
      'bat2id': 2250,
      'bat2name': 'Smith',
      'bat2runs': 4,
      'bat2fours': 0,
      'bat2sixes': 0,
      'totalruns': 11,
      'totalballs': 14,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 8271,
      'bat1name': 'Samson',
      'bat1runs': 74,
      'bat1fours': 1,
      'bat1sixes': 9,
      'bat2id': 2250,
      'bat2name': 'Smith',
      'bat2runs': 45,
      'bat2fours': 3,
      'bat2sixes': 3,
      'totalruns': 121,
      'totalballs': 57,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 6349,
      'bat1name': 'Miller',
      'bat1runs': 0,
      'bat1fours': 0,
      'bat1sixes': 0,
      'bat2id': 2250,
      'bat2name': 'Smith',
      'bat2runs': 0,
      'bat2fours': 0,
      'bat2sixes': 0,
      'totalruns': 2,
      'totalballs': 2,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 527,
      'bat1name': 'Uthappa',
      'bat1runs': 5,
      'bat1fours': 0,
      'bat1sixes': 0,
      'bat2id': 2250,
      'bat2name': 'Smith',
      'bat2runs': 9,
      'bat2fours': 0,
      'bat2sixes': 1,
      'totalruns': 15,
      'totalballs': 13,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 9693,
      'bat1name': 'Rahul Tewatia',
      'bat1runs': 10,
      'bat1fours': 1,
      'bat1sixes': 0,
      'bat2id': 2250,
      'bat2name': 'Smith',
      'bat2runs': 8,
      'bat2fours': 1,
      'bat2sixes': 0,
      'totalruns': 18,
      'totalballs': 13,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 12305,
      'bat1name': 'Riyan Parag',
      'bat1runs': 6,
      'bat1fours': 1,
      'bat1sixes': 0,
      'bat2id': 2250,
      'bat2name': 'Smith',
      'bat2runs': 0,
      'bat2fours': 0,
      'bat2sixes': 0,
      'totalruns': 6,
      'totalballs': 4,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 9522,
      'bat1name': 'Tom Curran',
      'bat1runs': 2,
      'bat1fours': 0,
      'bat1sixes': 0,
      'bat2id': 2250,
      'bat2name': 'Smith',
      'bat2runs': 2,
      'bat2fours': 0,
      'bat2sixes': 0,
      'totalruns': 5,
      'totalballs': 8,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 9522,
      'bat1name': 'Tom Curran',
      'bat1runs': 8,
      'bat1fours': 1,
      'bat1sixes': 0,
      'bat2id': 11540,
      'bat2name': 'Jofra Archer',
      'bat2runs': 27,
      'bat2fours': 0,
      'bat2sixes': 4,
      'totalruns': 38,
      'totalballs': 12,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0}]}},
  {'inningsid': 2,
   'batsman': [{'id': 1597,
     'balls': 21,
     'runs': 21,
     'fours': 3,
     'sixes': 0,
     'strkrate': '100',
     'name': 'Murali Vijay',
     'nickname': 'Vijay',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c Tom Curran b Shreyas Gopal',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 158,
     'balls': 21,
     'runs': 33,
     'fours': 1,
     'sixes': 4,
     'strkrate': '157.14',
     'name': 'Shane Watson',
     'nickname': 'Watson',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'b Rahul Tewatia',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 7825,
     'balls': 37,
     'runs': 72,
     'fours': 1,
     'sixes': 7,
     'strkrate': '194.59',
     'name': 'Faf du Plessis',
     'nickname': 'du Plessis',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c Samson b Jofra Archer',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 10420,
     'balls': 6,
     'runs': 17,
     'fours': 1,
     'sixes': 2,
     'strkrate': '283.33',
     'name': 'Sam Curran',
     'nickname': 'Sam Curran',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'st Samson b Rahul Tewatia',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 11813,
     'balls': 1,
     'runs': 0,
     'fours': 0,
     'sixes': 0,
     'strkrate': '0',
     'name': 'Ruturaj Gaikwad',
     'nickname': 'Ruturaj Gaikwad',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'st Samson b Rahul Tewatia',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 1851,
     'balls': 16,
     'runs': 22,
     'fours': 3,
     'sixes': 0,
     'strkrate': '137.5',
     'name': 'Kedar Jadhav',
     'nickname': 'Kedar Jadhav',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c Samson b Tom Curran',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 265,
     'balls': 17,
     'runs': 29,
     'fours': 0,
     'sixes': 3,
     'strkrate': '170.59',
     'name': 'MS Dhoni',
     'nickname': 'Dhoni',
     'iscaptain': True,
     'iskeeper': True,
     'outdec': 'not out',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 587,
     'balls': 2,
     'runs': 1,
     'fours': 0,
     'sixes': 0,
     'strkrate': '50',
     'name': 'Ravindra Jadeja',
     'nickname': 'Ravindra Jadeja',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'not out',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 7836,
     'balls': 0,
     'runs': 0,
     'fours': 0,
     'sixes': 0,
     'strkrate': '0',
     'name': 'Deepak Chahar',
     'nickname': 'D Chahar',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': '',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 466,
     'balls': 0,
     'runs': 0,
     'fours': 0,
     'sixes': 0,
     'strkrate': '0',
     'name': 'Piyush Chawla',
     'nickname': 'Chawla',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': '',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 9603,
     'balls': 0,
     'runs': 0,

In [101]:
import pandas as pd

def process_match_json(match_data, match_year):
    stats = []
    # Navigate the Cricbuzz JSON structure
    for inning in match_data.get('scorecard', []):
        for b in inning.get('batsman', []):
            stats.append({
                'player_name': b.get('name'),
                'runs': int(b.get('runs', 0)),
                'strike_rate': float(b.get('strkrate', 0)),
                'year': match_year
            })
    return pd.DataFrame(stats)

# 2. Convert each match JSON (m1, m2... m5) into a clean DataFrame
# Assuming m1-m3 are 2020 and m4-m5 are 2021
df1m1 = process_match_json(m1, 2020)
df2m2 = process_match_json(m2, 2020)
df3m3 = process_match_json(m3, 2020)
df4m4 = process_match_json(m4, 2021)
df5m5 = process_match_json(m5, 2021)

# 3. NOW you can concat them safely
df_q16 = pd.concat([df1m1, df2m2, df3m3, df4m4, df5m5], ignore_index=True)

In [ ]:
df_q16

In [104]:
import urllib.parse
from sqlalchemy import create_engine

# 1. Encode the special character in password
password = urllib.parse.quote_plus("deepika@88")

# 2. Use the encoded password in your connection string
# Also, ensure 'username' is replaced with your actual DB user (usually 'postgres')
engine = create_engine(f'postgresql+psycopg2://postgres:{password}@localhost:5432/cricbuzz')

# 3. Test the connection and push the data
df_q16.to_sql('q16_test', engine, if_exists='replace', index=False)

print("✅ Connection successful and table 'q16' created!")

✅ Connection successful and table 'q16' created!

# Q 22 scrap

In [45]:
import requests
import pandas as pd

headers = {
    "x-rapidapi-key": "e6021fb984msh201af5139a6e2e9p149939jsn32edaa5716a4",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

# API URLs
international_url2 = "https://cricbuzz-cricket.p.rapidapi.com/series/v1/archives/international"
league_url = "https://cricbuzz-cricket.p.rapidapi.com/series/v1/archives/league"
international_url = "https://cricbuzz-cricket.p.rapidapi.com/series/v1/archives/international"

# Parameters
league_params = {"year": "2024"}
international_params = {"year": "2024"}
international_params2 = {"year": "2025"}
# 1️⃣ Live Matches API
# live_response = requests.get(live_url, headers=headers).json()

# 2️⃣ League Series Archive API
league_response = requests.get(league_url, headers=headers, params=league_params).json()

# 3️⃣ International Series Archive API
international_response = requests.get(international_url, headers=headers, params=international_params).json()
international_response2 = requests.get(international_url, headers=headers, params=international_params2).json()


# Print basic info
print("League Series Keys:", league_response.keys())
print("International Series Keys 2024:", international_response.keys())
print("International Series Keys 2025:", international_response2.keys())

# Optional: store in dataframe
league_df = pd.json_normalize(league_response)
international_df = pd.json_normalize(international_response)
international_df2 = pd.json_normalize(international_response2)

print("League Data Rows:", len(league_df))
print("International Data Rows 2024:", len(international_df))
print("International Data Rows 2025:", len(international_df2))

League Series Keys: dict_keys(['seriesMapProto', 'appIndex', 'contentFilters'])
International Series Keys 2024: dict_keys(['seriesMapProto', 'appIndex', 'contentFilters'])
International Series Keys 2025: dict_keys(['seriesMapProto', 'appIndex'])
League Data Rows: 1
International Data Rows 2024: 1
International Data Rows 2025: 1

# series 2025

In [48]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/series/v1/archives/international"

querystring = {"year":"2025"}

headers = {
	"x-rapidapi-key": "e6021fb984msh201af5139a6e2e9p149939jsn32edaa5716a4",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

international_df2 =response.json()

In [57]:
international_df2['seriesMapProto']

[{'date': '2025',
  'series': [{'id': 11141,
    'name': 'Myanmar tour of Bhutan, 2025',
    'startDt': '1766448000000',
    'endDt': '1766966400000',
    'thumborImageId': 379130},
   {'id': 11377,
    'name': 'Cambodia tour of Indonesia, 2025',
    'startDt': '1766448000000',
    'endDt': '1766880000000',
    'thumborImageId': 379130},
   {'id': 11363,
    'name': 'SEA Games Mens Twenty20 Cricket Competition 2025',
    'startDt': '1765238400000',
    'endDt': '1765584000000',
    'thumborImageId': 379130},
   {'id': 11132,
    'name': 'Bahrain tour of Bhutan, 2025',
    'startDt': '1765152000000',
    'endDt': '1765670400000',
    'thumborImageId': 379130},
   {'id': 11364,
    'name': 'Croatia tour of Spain, 2025',
    'startDt': '1764892800000',
    'endDt': '1765065600000',
    'thumborImageId': 379130},
   {'id': 11295,
    'name': 'West Africa Trophy 2025',
    'startDt': '1764806400000',
    'endDt': '1765670400000',
    'thumborImageId': 379130},
   {'id': 11220,
    'name': 'Brazil tour of Argentina 2025',
    'startDt': '1764288000000',
    'endDt': '1764460800000',
    'thumborImageId': 379130},
   {'id': 11234,
    'name': 'Mini SEA Mens Twenty20 Cricket Competition 2025',
    'startDt': '1763942400000',
    'endDt': '1764547200000',
    'thumborImageId': 379130},
   {'id': 9107,
    'name': 'The Ashes, 2025-26',
    'startDt': '1763683200000',
    'endDt': '1767830400000',
    'thumborImageId': 784768},
   {'id': 11198,
    'name': 'Bahrain tour of Indonesia, 2025',
    'startDt': '1763424000000',
    'endDt': '1763683200000',
    'thumborImageId': 379130},
   {'id': 10906,
    'name': 'Pakistan T20I Tri-Series 2025',
    'startDt': '1763337600000',
    'endDt': '1764374400000',
    'thumborImageId': 788589},
   {'id': 9638,
    'name': 'South Africa tour of India, 2025',
    'startDt': '1763078400000',
    'endDt': '1766102400000',
    'thumborImageId': 795388},
   {'id': 11183,
    'name': 'Hong Kong tour of Qatar 2025',
    'startDt': '1762905600000',
    'endDt': '1762992000000',
    'thumborImageId': 379130},
   {'id': 10933,
    'name': 'Sri Lanka tour of Pakistan 2025',
    'startDt': '1762819200000',
    'endDt': '1763164800000',
    'thumborImageId': 781590},
   {'id': 11179,
    'name': 'Afghanistan tour of Qatar, 2025',
    'startDt': '1762819200000',
    'endDt': '1762819200000',
    'thumborImageId': 379130},
   {'id': 10972,
    'name': 'Ireland tour of Bangladesh, 2025',
    'startDt': '1762819200000',
    'endDt': '1764633600000',
    'thumborImageId': 379130},
   {'id': 11108,
    'name': 'Indonesia Tri-Series 2025',
    'startDt': '1762387200000',
    'endDt': '1763078400000',
    'thumborImageId': 379130},
   {'id': 10223,
    'name': 'West Indies tour of New Zealand, 2025',
    'startDt': '1762300800000',
    'endDt': '1766361600000',
    'thumborImageId': 379130},
   {'id': 11069,
    'name': 'Bulgaria tour of Cyprus 2025',
    'startDt': '1762128000000',
    'endDt': '1762128000000',
    'thumborImageId': 379130},
   {'id': 11062,
    'name': 'Cyprus Tri-Series 2025',
    'startDt': '1761868800000',
    'endDt': '1762041600000',
    'thumborImageId': 379130},
   {'id': 11089,
    'name': 'South American Mens Championships 2025',
    'startDt': '1761782400000',
    'endDt': '1761955200000',
    'thumborImageId': 379130},
   {'id': 11052,
    'name': 'Afghanistan tour of Zimbabwe 2025',
    'startDt': '1760918400000',
    'endDt': '1762041600000',
    'thumborImageId': 379130},
   {'id': 9596,
    'name': 'India tour of Australia, 2025',
    'startDt': '1760832000000',
    'endDt': '1762560000000',
    'thumborImageId': 776370},
   {'id': 10955,
    'name': 'West Indies tour of Bangladesh, 2025',
    'startDt': '1760745600000',
    'endDt': '1761868800000',
    'thumborImageId': 379130},
   {'id': 11078,
    'name': 'Austria tour of Romania, 2025',
    'startDt': '1760745600000',
    'endDt': '1760832000000',
    'thumborImageId': 379130},
   {'id': 10212,
    'name': 'England tour of New Zealand, 2025',
    'startDt': '1760745600000',
    'endDt': '1761955200000',
    'thumborImageId': 379130},
   {'id': 10895,
    'name': 'South Africa tour of Pakistan, 2025',
    'startDt': '1760227200000',
    'endDt': '1762560000000',
    'thumborImageId': 779718},
   {'id': 10504,
    'name': 'South Africa tour of Namibia 2025',
    'startDt': '1760140800000',
    'endDt': '1760140800000',
    'thumborImageId': 379130},
   {'id': 10625,
    'name': 'ICC Mens T20 World Cup East Asia Pacific Qualifier 2025',
    'startDt': '1759881600000',
    'endDt': '1760659200000',
    'thumborImageId': 379130},
   {'id': 10840,
    'name': 'Afghanistan vs Bangladesh in UAE 2025',
    'startDt': '1759363200000',
    'endDt': '1760400000000',
    'thumborImageId': 379130},
   {'id': 9629,
    'name': 'West Indies tour of India, 2025',
    'startDt': '1759363200000',
    'endDt': '1760400000000',
    'thumborImageId': 767232},
   {'id': 10201,
    'name': 'Australia tour of New Zealand, 2025',
    'startDt': '1759276800000',
    'endDt': '1759536000000',
    'thumborImageId': 379130},
   {'id': 11016,
    'name': 'Kuwait tour of Oman, 2025',
    'startDt': '1759104000000',
    'endDt': '1759190400000',
    'thumborImageId': 379130},
   {'id': 10091,
    'name': 'West Indies vs Nepal in UAE, 2025',
    'startDt': '1758931200000',
    'endDt': '1759190400000',
    'thumborImageId': 379130},
   {'id': 10944,
    'name': 'ICC Mens T20 World Cup Africa Regional Final 2025',
    'startDt': '1758844800000',
    'endDt': '1759536000000',
    'thumborImageId': 379130},
   {'id': 8802,
    'name': 'England tour of Ireland, 2025',
    'startDt': '1758067200000',
    'endDt': '1758412800000',
    'thumborImageId': 379130},
   {'id': 10928,
    'name': 'Namibia tour of Zimbabwe 2025',
    'startDt': '1757894400000',
    'endDt': '1758153600000',
    'thumborImageId': 379130},
   {'id': 10917,
    'name': 'Mozambique tour of Eswatini 2025',
    'startDt': '1757635200000',
    'endDt': '1757808000000',
    'thumborImageId': 379130},
   {'id': 10587,
    'name': 'Asia Cup 2025',
    'startDt': '1757376000000',
    'endDt': '1759017600000',
    'thumborImageId': 748468},
   {'id': 10812,
    'name': 'Sweden tour of Isle Of Man 2025',
    'startDt': '1757116800000',
    'endDt': '1757203200000',
    'thumborImageId': 379130},
   {'id': 8788,
    'name': 'South Africa tour of England, 2025',
    'startDt': '1756771200000',
    'endDt': '1757808000000',
    'thumborImageId': 748476},
   {'id': 10801,
    'name': 'Switzerland tour of Guernsey, 2025',
    'startDt': '1756512000000',
    'endDt': '1756598400000',
    'thumborImageId': 379130},
   {'id': 10647,
    'name': 'Netherlands tour of Bangladesh 2025',
    'startDt': '1756512000000',
    'endDt': '1756857600000',
    'thumborImageId': 379130},
   {'id': 10790,
    'name': 'Eastern Europe Cup 2025',
    'startDt': '1756425600000',
    'endDt': '1756598400000',
    'thumborImageId': 379130},
   {'id': 10267,
    'name': 'Sri Lanka tour of Zimbabwe, 2025',
    'startDt': '1756425600000',
    'endDt': '1757203200000',
    'thumborImageId': 746295},
   {'id': 10642,
    'name': 'United Arab Emirates T20I Tri-Series 2025',
    'startDt': '1756425600000',
    'endDt': '1757203200000',
    'thumborImageId': 379130},
   {'id': 10746,
    'name': 'Belgium tour of Austria 2025',
    'startDt': '1755907200000',
    'endDt': '1755993600000',
    'thumborImageId': 379130},
   {'id': 10719,
    'name': 'Czech Republic tour of Romania 2025',
    'startDt': '1755734400000',
    'endDt': '1755820800000',
    'thumborImageId': 379130},
   {'id': 10658,
    'name': 'Norway T20I Tri-Series 2025',
    'startDt': '1755388800000',
    'endDt': '1755388800000',
    'thumborImageId': 379130},
   {'id': 9686,
    'name': 'India tour of Bangladesh, 2025 (Called off)',
    'startDt': '1755388800000',
    'endDt': '1756598400000',
    'thumborImageId': 379130},
   {'id': 10713,
    'name': 'Papua New Guinea tour of Guernsey 2025',
    'startDt': '1755129600000',
    'endDt': '1755129600000',
    'thumborImageId': 379130},
   {'id': 9602,
    'name': 'South Africa tour of Australia, 2025',
    'startDt': '1754784000000',
    'endDt': '1755993600000',
    'thumborImageId': 379130},
   {'id': 10598,
    'name': 'Cyprus tour of Croatia 2025',
    'startDt': '1754524800000',
    'endDt': '1754611200000',
    'thumborImageId': 379130},
   {'id': 10609,
    'name': 'Viking Cup 2025',
    'startDt': '1754524800000',
    'endDt': '1754784000000',
    'thumborImageId': 379130},
   {'id': 10465,
    'name': 'Switzerland tour of Estonia, 2025',
    'startDt': '1754092800000',
    'endDt': '1754179200000',
    'thumborImageId': 379130},
   {'id': 9399,
    'name': 'Pakistan tour of West Indies, 2025',
    'startDt': '1754006400000',
    'endDt': '1754956800000',
    'thumborImageId': 379130},
   {'id': 9584,
    'name': 'New Zealand tour of Zimbabwe, 2025',
    'startDt': '1753833600000',
    'endDt': '1754870400000',
    'thumborImageId': 379130},
   {'id': 10498,
    'name': 'Budapest Cup, 2025',
    'startDt': '1753401600000',
    'endDt': '1753574400000',
    'thumborImageId': 379130},
   {'id': 10443,
    'name': 'Finland tour of Estonia 2025',
    'startDt': '1753401600000',
    'endDt': '1753574400000',
    'thumborImageId': 379130},
   {'id': 10256,
    'name': 'Pakistan tour of Bangladesh, 2025',
    'startDt': '1752969600000',
    'endDt': '1753315200000',
    'thumborImageId': 379130},
   {'id': 10471,
    'name': 'Rwanda T20I Tri-Series, 2025',
    'startDt': '1752796800000',
    'endDt': '1753574400000',
    'thumborImageId': 379130},
   {'id': 10432,
    'name': 'Saudi Arabia tour of Qatar 2025',
    'startDt': '1752796800000',
    'endDt': '1753228800000',
    'thumborImageId': 379130},
   {'id': 10421,
    'name': 'Asia Pacific Cricket Champions Trophy 2025',
    'startDt': '1752796800000',
    'endDt': '1753488000000',
    'thumborImageId': 379130},
   {'id': 10410,
    'name': 'Pearl of Africa T20I Series 2025',
    'startDt': '1752710400000',
    'endDt': '1753574400000',
    'thumborImageId': 379130},
   {'id': 9587,
    'name': 'Zimbabwe T20I Tri-Series, 2025',
    'startDt': '1752451200000',
    'endDt': '1753488000000',
    'thumborImageId': 379130},
   {'id': 10190,
    'name': 'Bulgaria T20I Tri-Series 2025',
    'startDt': '1752105600000',
    'endDt': '1752364800000',
    'thumborImageId': 379130},
   {'id': 10168,
    'name': 'Indonesia T20I Tri-Series 2025',
    'startDt': '1751760000000',
    'endDt': '1752364800000',
    'thumborImageId': 379130},
   {'id': 10108,
    'name': 'ICC Mens T20 World Cup Europe Qualifier 2025',
    'startDt': '1751673600000',
    'endDt': '1752192000000',
    'thumborImageId': 379130},
   {'id': 10278,
    'name': 'Quadrangular T20I Series in Malawi 2025',
    'startDt': '1751673600000',
    'endDt': '1752364800000',
    'thumborImageId': 379130},
   {'id': 9578,
    'name': 'South Africa tour of Zimbabwe, 2025',
    'startDt': '1751068800000',
    'endDt': '1752105600000',
    'thumborImageId': 379130},
   {'id': 10157,
    'name': 'Continental Cup, 2025',
    'startDt': '1750896000000',
    'endDt': '1751155200000',
    'thumborImageId': 379130},
   {'id': 9408,
    'name': 'Australia tour of West Indies, 2025',
    'startDt': '1750809600000',
    'endDt': '1753660800000',
    'thumborImageId': 379130},
   {'id': 9908,
    'name': 'Switzerland tour of Luxembourg, 2025',
    'startDt': '1750464000000',
    'endDt': '1750550400000',
    'thumborImageId': 379130},
   {'id': 9899,
    'name': 'Slovenia tour of Hungary, 2025',
    'startDt': '1750464000000',
    'endDt': '1750550400000',
    'thumborImageId': 379130},
   {'id': 8786,
    'name': 'India tour of England, 2025',
    'startDt': '1750377600000',
    'endDt': '1754265600000',
    'thumborImageId': 379130},
   {'id': 9809,
    'name': 'Bangladesh tour of Sri Lanka, 2025',
    'startDt': '1750118400000',
    'endDt': '1752624000000',
    'thumborImageId': 379130},
   {'id': 9992,
    'name': 'ICC Mens T20 World Cup Americas Region Final 2025',
    'startDt': '1749945600000',
    'endDt': '1750550400000',
    'thumborImageId': 379130},
   {'id': 10036,
    'name': 'Norway tour of Denmark, 2025',
    'startDt': '1749945600000',
    'endDt': '1749945600000',
    'thumborImageId': 379130},
   {'id': 9737,
    'name': 'Scotland T20I Tri-Series 2025',
    'startDt': '1749945600000',
    'endDt': '1750377600000',
    'thumborImageId': 379130},
   {'id': 10031,
    'name': 'Nordic T20I Cup 2025',
    'startDt': '1749772800000',
    'endDt': '1749945600000',
    'thumborImageId': 379130},
   {'id': 8881,
    'name': 'ICC World Test Championship Final 2025',
    'startDt': '1749600000000',
    'endDt': '1749945600000',
    'thumborImageId': 379130},
   {'id': 9981,
    'name': 'Cambodia tour of Indonesia, 2025',
    'startDt': '1749600000000',
    'endDt': '1749945600000',
    'thumborImageId': 379130},
   {'id': 10080,
    'name': 'Quadrangular T20I Series in Canada, 2025',
    'startDt': '1749600000000',
    'endDt': '1749859200000',
    'thumborImageId': 379130},
   {'id': 9827,
    'name': 'Central Europe Cup 2025',
    'startDt': '1749340800000',
    'endDt': '1749513600000',
    'thumborImageId': 379130},
   {'id': 9911,
    'name': 'Slovenia tour of Serbia, 2025',
    'startDt': '1749254400000',
    'endDt': '1749340800000',
    'thumborImageId': 379130},
   {'id': 9954,
    'name': 'Guernsey tour of Jersey, 2025',
    'startDt': '1749168000000',
    'endDt': '1749254400000',
    'thumborImageId': 379130},
   {'id': 9920,
    'name': 'Switzerland tour of Austria, 2025',
    'startDt': '1748563200000',
    'endDt': '1748736000000',
    'thumborImageId': 379130},
   {'id': 9818,
    'name': 'Mdina Cup 2025',
    'startDt': '1748563200000',
    'endDt': '1748736000000',
    'thumborImageId': 379130},
   {'id': 8796,
    'name': 'West Indies tour of England, 2025',
    'startDt': '1748476800000',
    'endDt': '1749513600000',
    'thumborImageId': 379130},
   {'id': 9785,
    'name': 'Bangladesh tour of Pakistan, 2025',
    'startDt': '1748390400000',
    'endDt': '1748736000000',
    'thumborImageId': 379130},
   {'id': 9390,
    'name': 'West Indies tour of Ireland, 2025',
    'startDt': '1747785600000',
    'endDt': '1749945600000',
    'thumborImageId': 379130},
   {'id': 9857,
    'name': 'Slovenia tour of Austria 2025',
    'startDt': '1747440000000',
    'endDt': '1747526400000',
    'thumborImageId': 379130},
   {'id': 9800,
    'name': 'Bangladesh tour of UAE, 2025',
    'startDt': '1747440000000',
    'endDt': '1747785600000',
    'thumborImageId': 379130},
   {'id': 7065,
    'name': 'Zimbabwe tour of England, 2025',
    'startDt': '1747267200000',
    'endDt': '1748131200000',
    'thumborImageId': 379130},
   {'id': 9731,
    'name': 'Cook Islands tour of Japan, 2025',
    'startDt': '1747094400000',
    'endDt': '1747180800000',
    'thumborImageId': 379130},
   {'id': 9728,
    'name': 'Japan T20I Tri-Series, 2025',
    'startDt': '1746576000000',
    'endDt': '1746921600000',
    'thumborImageId': 379130},
   {'id': 9719,
    'name': 'Estonia tour of Malta, 2025',
    'startDt': '1746489600000',
    'endDt': '1746576000000',
    'thumborImageId': 379130},
   {'id': 9710,
    'name': 'Malaysia Quadrangular T20I Series, 2025',
    'startDt': '1745452800000',
    'endDt': '1746144000000',
    'thumborImageId': 379130},
   {'id': 9514,
    'name': 'Zimbabwe tour of Bangladesh, 2025',
    'startDt': '1745107200000',
    'endDt': '1746144000000',
    'thumborImageId': 379130},
   {'id': 9677,
    'name': 'The North American T20 Cup, 2025',
    'startDt': '1745020800000',
    'endDt': '1745712000000',
    'thumborImageId': 379130},
   {'id': 9692,
    'name': 'Central American Cricket Championships, 2025',
    'startDt': '1744848000000',
    'endDt': '1745107200000',
    'thumborImageId': 379130},
   {'id': 9647,
    'name': 'Hong Kong T20I Quadrangular Series, 2025',
    'startDt': '1744156800000',
    'endDt': '1744502400000',
    'thumborImageId': 379130},
   {'id': 9534,
    'name': 'Portugal tour of Norway, 2025',
    'startDt': '1743984000000',
    'endDt': '1744156800000',
    'thumborImageId': 379130},
   {'id': 9523,
    'name': 'Canada tour of Namibia, 2025',
    'startDt': '1742256000000',
    'endDt': '1742688000000',
    'thumborImageId': 379130},
   {'id': 8562,
    'name': 'Pakistan tour of New Zealand, 2025',
    'startDt': '1742083200000',
    'endDt': '1743811200000',
    'thumborImageId': 379130},
   {'id': 9507,
    'name': 'Falkland Islands tour of Costa Rica 2025',
    'startDt': '1741651200000',
    'endDt': '1741824000000',
    'thumborImageId': 379130},
   {'id': 9480,
    'name': 'Malaysia Tri-Nation T20I Series, 2025',
    'startDt': '1741564800000',
    'endDt': '1742169600000',
    'thumborImageId': 379130},
   {'id': 9453,
    'name': 'Bahrain tour of Singapore, 2025',
    'startDt': '1740700800000',
    'endDt': '1741132800000',
    'thumborImageId': 379130},
   {'id': 9451,
    'name': 'USA tour of Oman T20I Series, 2025',
    'startDt': '1740009600000',
    'endDt': '1740268800000',
    'thumborImageId': 379130},
   {'id': 9325,
    'name': 'ICC Champions Trophy, 2025',
    'startDt': '1739923200000',
    'endDt': '1741478400000',
    'thumborImageId': 379130},
   {'id': 9426,
    'name': 'Bahrain tour of Indonesia, 2025',
    'startDt': '1739923200000',
    'endDt': '1740355200000',
    'thumborImageId': 379130},
   {'id': 8511,
    'name': 'Pakistan ODI Tri-Series, 2025',
    'startDt': '1738972800000',
    'endDt': '1739491200000',
    'thumborImageId': 379130},
   {'id': 9331,
    'name': 'Ireland tour of Zimbabwe, 2025',
    'startDt': '1738800000000',
    'endDt': '1740441600000',
    'thumborImageId': 379130},
   {'id': 9375,
    'name': 'Malta T20I Tri-Series, 2025',
    'startDt': '1738540800000',
    'endDt': '1738713600000',
    'thumborImageId': 379130},
   {'id': 9181,
    'name': 'Australia tour of Sri Lanka, 2025',
    'startDt': '1738108800000',
    'endDt': '1739491200000',
    'thumborImageId': 379130},
   {'id': 8402,
    'name': 'England tour of India, 2025',
    'startDt': '1737504000000',
    'endDt': '1739318400000',
    'thumborImageId': 379130},
   {'id': 8504,
    'name': 'West Indies tour of Pakistan, 2025',
    'startDt': '1736467200000',
    'endDt': '1738022400000',
    'thumborImageId': 379130}]}]

In [58]:
import pandas as pd
from datetime import datetime

series_2025 = []

series_data_2025 = international_df2['seriesMapProto'][0]['series']

for s in series_data_2025:

    series_name = s['name']
    series_id = s['id']
    
    # Convert timestamp to date
    start_date = datetime.fromtimestamp(int(s['startDt'])/1000).strftime('%Y-%m-%d')

    # Extract host country (simple logic)
    if "tour of" in series_name:
        host_country = series_name.split("tour of")[-1].split(",")[0].strip()
    elif "in" in series_name:
        host_country = series_name.split("in")[-1].split(",")[0].strip()
    else:
        host_country = "Unknown"

    # Match type detection
    if "T20" in series_name:
        match_type = "T20"
    elif "ODI" in series_name:
        match_type = "ODI"
    elif "Test" in series_name:
        match_type = "Test"
    else:
        match_type = "Internatonal"

    series_2025.append({
        "Series_id" : series_id,
        "Series Name": series_name,
        "Host Country": host_country,
        "Match Type": match_type,
        "Start Date": start_date
    })

df2025 = pd.DataFrame(series_2025)

print(df2025.head())

   Series_id                                       Series Name Host Country    Match Type  Start Date
0      11141                      Myanmar tour of Bhutan, 2025       Bhutan  Internatonal  2025-12-23
1      11377                  Cambodia tour of Indonesia, 2025    Indonesia  Internatonal  2025-12-23
2      11363  SEA Games Mens Twenty20 Cricket Competition 2025      Unknown  Internatonal  2025-12-09
3      11132                      Bahrain tour of Bhutan, 2025       Bhutan  Internatonal  2025-12-08
4      11364                       Croatia tour of Spain, 2025        Spain  Internatonal  2025-12-05

In [213]:
df2025.iloc[0:25]

    Series_id                                       Series Name                                  Host Country    Match Type  Start Date
0       11141                      Myanmar tour of Bhutan, 2025                                        Bhutan  Internatonal  2025-12-23
1       11377                  Cambodia tour of Indonesia, 2025                                     Indonesia  Internatonal  2025-12-23
2       11363  SEA Games Mens Twenty20 Cricket Competition 2025                                       Unknown  Internatonal  2025-12-09
3       11132                      Bahrain tour of Bhutan, 2025                                        Bhutan  Internatonal  2025-12-08
4       11364                       Croatia tour of Spain, 2025                                         Spain  Internatonal  2025-12-05
5       11295                           West Africa Trophy 2025                                       Unknown  Internatonal  2025-12-04
6       11220                     Brazil tour of Argentina 2025                                Argentina 2025  Internatonal  2025-11-28
7       11234   Mini SEA Mens Twenty20 Cricket Competition 2025  i SEA Mens Twenty20 Cricket Competition 2025  Internatonal  2025-11-24
8        9107                                The Ashes, 2025-26                                       Unknown  Internatonal  2025-11-21
9       11198                   Bahrain tour of Indonesia, 2025                                     Indonesia  Internatonal  2025-11-18
10      10906                     Pakistan T20I Tri-Series 2025                                       Unknown           T20  2025-11-17
11       9638                  South Africa tour of India, 2025                                         India  Internatonal  2025-11-14
12      11183                      Hong Kong tour of Qatar 2025                                    Qatar 2025  Internatonal  2025-11-12
13      10933                   Sri Lanka tour of Pakistan 2025                                 Pakistan 2025  Internatonal  2025-11-11
14      11179                   Afghanistan tour of Qatar, 2025                                         Qatar  Internatonal  2025-11-11
15      10972                  Ireland tour of Bangladesh, 2025                                    Bangladesh  Internatonal  2025-11-11
16      11108                         Indonesia Tri-Series 2025                                       Unknown  Internatonal  2025-11-06
17      10223             West Indies tour of New Zealand, 2025                                   New Zealand  Internatonal  2025-11-05
18      11069                      Bulgaria tour of Cyprus 2025                                   Cyprus 2025  Internatonal  2025-11-03
19      11062                            Cyprus Tri-Series 2025                                       Unknown  Internatonal  2025-10-31
20      11089            South American Mens Championships 2025                                       Unknown  Internatonal  2025-10-30
21      11052                 Afghanistan tour of Zimbabwe 2025                                 Zimbabwe 2025  Internatonal  2025-10-20
22       9596                     India tour of Australia, 2025                                     Australia  Internatonal  2025-10-19
23      10955              West Indies tour of Bangladesh, 2025                                    Bangladesh  Internatonal  2025-10-18
24      11078                     Austria tour of Romania, 2025                                       Romania  Internatonal  2025-10-18

In [60]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/series/v1/8402"

headers = {
	"x-rapidapi-key": "e6021fb984msh201af5139a6e2e9p149939jsn32edaa5716a4",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

ser_8402 = response.json()

In [61]:
ser_8402

{'matchDetails': [{'matchDetailsMap': {'key': 'Wed, 22 Jan 2025',
    'match': [{'matchInfo': {'matchId': 100283,
       'seriesId': 8402,
       'seriesName': 'England tour of India, 2025',
       'matchDesc': '1st T20I',
       'matchFormat': 'T20',
       'startDate': '1737552600000',
       'endDate': '1737552600000',
       'state': 'complete',
       'status': 'India won by 7 wkts',
       'team1': {'teamId': 2,
        'teamName': 'INDIA',
        'teamSName': 'IND',
        'imageId': 776162},
       'team2': {'teamId': 9,
        'teamName': 'ENGLAND',
        'teamSName': 'ENG',
        'imageId': 776237},
       'venueInfo': {'ground': 'Eden Gardens',
        'city': 'Kolkata',
        'timezone': '+05:30'},
       'currBatTeamId': 2,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 133,
         'wickets': 3,
         'overs': 12.5}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 132,
         'wickets': 10,
         'overs': 20.0}}}}],
    'seriesId': 8402}},
  {'adDetail': {'name': 'native_news_index_random_1',
    'layout': 'native_large',
    'position': 1}},
  {'matchDetailsMap': {'key': 'Sat, 25 Jan 2025',
    'match': [{'matchInfo': {'matchId': 100290,
       'seriesId': 8402,
       'seriesName': 'England tour of India, 2025',
       'matchDesc': '2nd T20I',
       'matchFormat': 'T20',
       'startDate': '1737811800000',
       'endDate': '1737811800000',
       'state': 'complete',
       'status': 'India won by 2 wkts',
       'team1': {'teamId': 2,
        'teamName': 'INDIA',
        'teamSName': 'IND',
        'imageId': 776162},
       'team2': {'teamId': 9,
        'teamName': 'ENGLAND',
        'teamSName': 'ENG',
        'imageId': 776237},
       'venueInfo': {'ground': 'MA Chidambaram Stadium',
        'city': 'Chennai',
        'timezone': '+05:30'},
       'currBatTeamId': 2,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 166,
         'wickets': 8,
         'overs': 19.2}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 165,
         'wickets': 9,
         'overs': 20.0}}}}],
    'seriesId': 8402}},
  {'matchDetailsMap': {'key': 'Tue, 28 Jan 2025',
    'match': [{'matchInfo': {'matchId': 100292,
       'seriesId': 8402,
       'seriesName': 'England tour of India, 2025',
       'matchDesc': '3rd T20I',
       'matchFormat': 'T20',
       'startDate': '1738071000000',
       'endDate': '1738071000000',
       'state': 'complete',
       'status': 'England won by 26 runs',
       'team1': {'teamId': 2,
        'teamName': 'INDIA',
        'teamSName': 'IND',
        'imageId': 776162},
       'team2': {'teamId': 9,
        'teamName': 'ENGLAND',
        'teamSName': 'ENG',
        'imageId': 776237},
       'venueInfo': {'ground': 'Niranjan Shah Stadium, Khandheri',
        'city': 'Rajkot',
        'timezone': '+05:30'},
       'currBatTeamId': 9,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 145,
         'wickets': 9,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 171,
         'wickets': 9,
         'overs': 20.0}}}}],
    'seriesId': 8402}},
  {'matchDetailsMap': {'key': 'Fri, 31 Jan 2025',
    'match': [{'matchInfo': {'matchId': 100301,
       'seriesId': 8402,
       'seriesName': 'England tour of India, 2025',
       'matchDesc': '4th T20I',
       'matchFormat': 'T20',
       'startDate': '1738330200000',
       'endDate': '1738330200000',
       'state': 'complete',
       'status': 'India won by 15 runs',
       'team1': {'teamId': 2,
        'teamName': 'INDIA',
        'teamSName': 'IND',
        'imageId': 776162},
       'team2': {'teamId': 9,
        'teamName': 'ENGLAND',
        'teamSName': 'ENG',
        'imageId': 776237},
       'venueInfo': {'ground': 'Maharashtra Cricket Association Stadium',
        'city': 'Pune',
        'timezone': '+05:30'},
       'currBatTeamId': 2,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 181,
         'wickets': 9,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 166,
         'wickets': 10,
         'overs': 19.4}}}}],
    'seriesId': 8402}},
  {'matchDetailsMap': {'key': 'Sun, 02 Feb 2025',
    'match': [{'matchInfo': {'matchId': 100310,
       'seriesId': 8402,
       'seriesName': 'England tour of India, 2025',
       'matchDesc': '5th T20I',
       'matchFormat': 'T20',
       'startDate': '1738503000000',
       'endDate': '1738503000000',
       'state': 'complete',
       'status': 'India won by 150 runs',
       'team1': {'teamId': 2,
        'teamName': 'INDIA',
        'teamSName': 'IND',
        'imageId': 776162},
       'team2': {'teamId': 9,
        'teamName': 'ENGLAND',
        'teamSName': 'ENG',
        'imageId': 776237},
       'venueInfo': {'ground': 'Wankhede Stadium',
        'city': 'Mumbai',
        'timezone': '+05:30'},
       'currBatTeamId': 2,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 247,
         'wickets': 9,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 97,
         'wickets': 10,
         'overs': 10.3}}}}],
    'seriesId': 8402}},
  {'matchDetailsMap': {'key': 'Thu, 06 Feb 2025',
    'match': [{'matchInfo': {'matchId': 100312,
       'seriesId': 8402,
       'seriesName': 'England tour of India, 2025',
       'matchDesc': '1st ODI',
       'matchFormat': 'ODI',
       'startDate': '1738828800000',
       'endDate': '1738828800000',
       'state': 'complete',
       'status': 'India won by 4 wkts',
       'team1': {'teamId': 2,
        'teamName': 'INDIA',
        'teamSName': 'IND',
        'imageId': 776162},
       'team2': {'teamId': 9,
        'teamName': 'ENGLAND',
        'teamSName': 'ENG',
        'imageId': 776237},
       'venueInfo': {'ground': 'Vidarbha Cricket Association Stadium',
        'city': 'Nagpur',
        'timezone': '+05:30'},
       'currBatTeamId': 2,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 251,
         'wickets': 6,
         'overs': 38.4}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 248,
         'wickets': 10,
         'overs': 47.4}}}}],
    'seriesId': 8402}},
  {'matchDetailsMap': {'key': 'Sun, 09 Feb 2025',
    'match': [{'matchInfo': {'matchId': 100321,
       'seriesId': 8402,
       'seriesName': 'England tour of India, 2025',
       'matchDesc': '2nd ODI',
       'matchFormat': 'ODI',
       'startDate': '1739088000000',
       'endDate': '1739088000000',
       'state': 'complete',
       'status': 'India won by 4 wkts',
       'team1': {'teamId': 2,
        'teamName': 'INDIA',
        'teamSName': 'IND',
        'imageId': 776162},
       'team2': {'teamId': 9,
        'teamName': 'ENGLAND',
        'teamSName': 'ENG',
        'imageId': 776237},
       'venueInfo': {'ground': 'Barabati Stadium',
        'city': 'Cuttack',
        'timezone': '+05:30'},
       'currBatTeamId': 2,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 308,
         'wickets': 6,
         'overs': 44.3}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 304,
         'wickets': 10,
         'overs': 49.5}}}}],
    'seriesId': 8402}},
  {'matchDetailsMap': {'key': 'Wed, 12 Feb 2025',
    'match': [{'matchInfo': {'matchId': 100328,
       'seriesId': 8402,
       'seriesName': 'England tour of India, 2025',
       'matchDesc': '3rd ODI',
       'matchFormat': 'ODI',
       'startDate': '1739347200000',
       'endDate': '1739347200000',
       'state': 'complete',
       'status': 'India won by 142 runs',
       'team1': {'teamId': 2,
        'teamName': 'INDIA',
        'teamSName': 'IND',
        'imageId': 776162},
       'team2': {'teamId': 9,
        'teamName': 'ENGLAND',
        'teamSName': 'ENG',
        'imageId': 776237},
       'venueInfo': {'ground': 'Narendra Modi Stadium',
        'city': 'Ahmedabad',
        'timezone': '+05:30'},
       'currBatTeamId': 2,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 356,
         'wickets': 10,
         'overs': 50.0}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 214,
         'wickets': 10,
         'overs': 34.2}}}}],
    'seriesId': 8402}}],
 'appIndex': {'seoTitle': 'England tour of India, 2025 live scores, schedule and results - Cricbuzz | Cricbuzz.com',
  'webURL': 'www.cricbuzz.com/cricket-series/'}}

In [78]:
import pandas as pd
from datetime import datetime

series_matches2025 = []

for item in ser_8402['matchDetails']:
    
    match_map = item.get('matchDetailsMap', {})
    
    for m in match_map.get('match', []):
        
        info = m.get('matchInfo', {})
        
        match_id = info.get('matchId')
        series_name = info.get('seriesName')
        match_desc = info.get('matchDesc')
        match_format = info.get('matchFormat')
        
        team1 = info.get('team1', {}).get('teamName')
        team2 = info.get('team2', {}).get('teamName')
        
        venue = info.get('venueInfo', {}).get('ground')
        city = info.get('venueInfo', {}).get('city')
        
        start_date = datetime.fromtimestamp(
            int(info.get('startDate'))/1000
        ).strftime('%Y-%m-%d')
        
        status = info.get('status')
        
        series_matches2025.append({
            "Match ID": match_id,
            "Series": series_name,
            "Match": match_desc,
            "Format": match_format,
            "Team1": team1,
            "Team2": team2,
            "Venue": venue,
            "City": city,
            "Start Date": start_date,
            "Result": status
        })

df_series_mat2025 = pd.DataFrame(series_matches2025)

df_series_mat2025.head()

   Match ID                       Series     Match Format  Team1    Team2                                    Venue     City  Start Date                  Result
0    100283  England tour of India, 2025  1st T20I    T20  INDIA  ENGLAND                             Eden Gardens  Kolkata  2025-01-22     India won by 7 wkts
1    100290  England tour of India, 2025  2nd T20I    T20  INDIA  ENGLAND                   MA Chidambaram Stadium  Chennai  2025-01-25     India won by 2 wkts
2    100292  England tour of India, 2025  3rd T20I    T20  INDIA  ENGLAND         Niranjan Shah Stadium, Khandheri   Rajkot  2025-01-28  England won by 26 runs
3    100301  England tour of India, 2025  4th T20I    T20  INDIA  ENGLAND  Maharashtra Cricket Association Stadium     Pune  2025-01-31    India won by 15 runs
4    100310  England tour of India, 2025  5th T20I    T20  INDIA  ENGLAND                         Wankhede Stadium   Mumbai  2025-02-02   India won by 150 runs

In [79]:
df_series_mat2025

   Match ID                       Series     Match Format  Team1    Team2                                    Venue       City  Start Date                  Result
0    100283  England tour of India, 2025  1st T20I    T20  INDIA  ENGLAND                             Eden Gardens    Kolkata  2025-01-22     India won by 7 wkts
1    100290  England tour of India, 2025  2nd T20I    T20  INDIA  ENGLAND                   MA Chidambaram Stadium    Chennai  2025-01-25     India won by 2 wkts
2    100292  England tour of India, 2025  3rd T20I    T20  INDIA  ENGLAND         Niranjan Shah Stadium, Khandheri     Rajkot  2025-01-28  England won by 26 runs
3    100301  England tour of India, 2025  4th T20I    T20  INDIA  ENGLAND  Maharashtra Cricket Association Stadium       Pune  2025-01-31    India won by 15 runs
4    100310  England tour of India, 2025  5th T20I    T20  INDIA  ENGLAND                         Wankhede Stadium     Mumbai  2025-02-02   India won by 150 runs
5    100312  England tour of India, 2025   1st ODI    ODI  INDIA  ENGLAND     Vidarbha Cricket Association Stadium     Nagpur  2025-02-06     India won by 4 wkts
6    100321  England tour of India, 2025   2nd ODI    ODI  INDIA  ENGLAND                         Barabati Stadium    Cuttack  2025-02-09     India won by 4 wkts
7    100328  England tour of India, 2025   3rd ODI    ODI  INDIA  ENGLAND                    Narendra Modi Stadium  Ahmedabad  2025-02-12   India won by 142 runs

In [80]:
mat_ids2025 = df_series_mat2025['Match ID'].tolist()
print(mat_ids2025[:5])

[100283, 100290, 100292, 100301, 100310]

# series 2024

In [49]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/series/v1/archives/international"

querystring = {"year":"2024"}

headers = {
	"x-rapidapi-key": "e6021fb984msh201af5139a6e2e9p149939jsn32edaa5716a4",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

international_df =response.json()

In [52]:
international_df

{'seriesMapProto': [{'date': '2024',
   'series': [{'id': 8553,
     'name': 'Sri Lanka tour of New Zealand, 2024-25',
     'startDt': '1734912000000',
     'endDt': '1736553600000',
     'thumborImageId': 379130},
    {'id': 9297,
     'name': 'Gulf Cricket T20I Championship, 2024',
     'startDt': '1734048000000',
     'endDt': '1734739200000',
     'thumborImageId': 379130},
    {'id': 8044,
     'name': 'Pakistan tour of South Africa, 2024 -25',
     'startDt': '1733788800000',
     'endDt': '1736208000000',
     'thumborImageId': 379130},
    {'id': 9171,
     'name': 'Afghanistan tour of Zimbabwe, 2024-25',
     'startDt': '1733702400000',
     'endDt': '1736121600000',
     'thumborImageId': 379130},
    {'id': 9265,
     'name': 'ICC Mens T20 World Cup Americas Sub Regional Qualifier, 2024',
     'startDt': '1733443200000',
     'endDt': '1734307200000',
     'thumborImageId': 379130},
    {'id': 9289,
     'name': 'Africa Continental Cup 2024',
     'startDt': '1733270400000',
     'endDt': '1734134400000',
     'thumborImageId': 379130},
    {'id': 8058,
     'name': 'Sri Lanka tour of South Africa, 2024',
     'startDt': '1732665600000',
     'endDt': '1733702400000',
     'thumborImageId': 379130},
    {'id': 8494,
     'name': 'Pakistan tour of Zimbabwe, 2024',
     'startDt': '1732406400000',
     'endDt': '1733356800000',
     'thumborImageId': 379130},
    {'id': 7853,
     'name': 'England tour of New Zealand, 2024',
     'startDt': '1732320000000',
     'endDt': '1734480000000',
     'thumborImageId': 379130},
    {'id': 9132,
     'name': 'ICC Mens T20 World Cup Africa Sub Regional Qualifier C 2024',
     'startDt': '1732320000000',
     'endDt': '1732752000000',
     'thumborImageId': 379130},
    {'id': 7745,
     'name': 'India tour of Australia, 2024-25',
     'startDt': '1732233600000',
     'endDt': '1736208000000',
     'thumborImageId': 379130},
    {'id': 9129,
     'name': 'ICC Mens T20 World Cup Asia Qualifier B 2024',
     'startDt': '1731974400000',
     'endDt': '1732752000000',
     'thumborImageId': 379130},
    {'id': 8116,
     'name': 'Bangladesh tour of West Indies, 2024',
     'startDt': '1731801600000',
     'endDt': '1734566400000',
     'thumborImageId': 379130},
    {'id': 9125,
     'name': 'Netherlands tour of Oman, 2024',
     'startDt': '1731456000000',
     'endDt': '1731715200000',
     'thumborImageId': 379130},
    {'id': 9146,
     'name': 'Myanmar tour of Indonesia, 2024',
     'startDt': '1731369600000',
     'endDt': '1731974400000',
     'thumborImageId': 379130},
    {'id': 9083,
     'name': 'New Zealand tour of Sri Lanka, 2024',
     'startDt': '1731110400000',
     'endDt': '1731974400000',
     'thumborImageId': 379130},
    {'id': 8404,
     'name': 'India tour of South Africa, 2024',
     'startDt': '1731024000000',
     'endDt': '1731628800000',
     'thumborImageId': 379130},
    {'id': 9091,
     'name': 'Afghanistan v Bangladesh in UAE, 2024',
     'startDt': '1730851200000',
     'endDt': '1731283200000',
     'thumborImageId': 379130},
    {'id': 7781,
     'name': 'Pakistan tour of Australia, 2024',
     'startDt': '1730592000000',
     'endDt': '1731801600000',
     'thumborImageId': 379130},
    {'id': 8107,
     'name': 'England tour of West Indies, 2024',
     'startDt': '1730332800000',
     'endDt': '1731801600000',
     'thumborImageId': 379130},
    {'id': 9157,
     'name': 'Bahrain in Uganda 2024',
     'startDt': '1730073600000',
     'endDt': '1730160000000',
     'thumborImageId': 379130},
    {'id': 9033,
     'name': 'South Africa tour of Bangladesh, 2024',
     'startDt': '1729468800000',
     'endDt': '1730505600000',
     'thumborImageId': 379130},
    {'id': 9041,
     'name': 'ICC Mens T20 World Cup Sub Regional Africa Qualifier Group B, 2024',
     'startDt': '1729296000000',
     'endDt': '1729728000000',
     'thumborImageId': 379130},
    {'id': 9025,
     'name': 'Quadrangular T20I Series in Bhutan, 2024',
     'startDt': '1729296000000',
     'endDt': '1729814400000',
     'thumborImageId': 379130},
    {'id': 9115,
     'name': 'Seychelles tour of Kenya, Only T20I',
     'startDt': '1729209600000',
     'endDt': '1729209600000',
     'thumborImageId': 379130},
    {'id': 9043,
     'name': 'Nepal tour of United States of America 2024',
     'startDt': '1729123200000',
     'endDt': '1729382400000',
     'thumborImageId': 379130},
    {'id': 8395,
     'name': 'New Zealand tour of India, 2024',
     'startDt': '1729036800000',
     'endDt': '1730764800000',
     'thumborImageId': 379130},
    {'id': 9009,
     'name': 'West Indies tour of Sri Lanka, 2024',
     'startDt': '1728777600000',
     'endDt': '1729900800000',
     'thumborImageId': 379130},
    {'id': 9057,
     'name': 'Rwanda tour of Malawi 2024',
     'startDt': '1728432000000',
     'endDt': '1728864000000',
     'thumborImageId': 379130},
    {'id': 8497,
     'name': 'England tour of Pakistan, 2024',
     'startDt': '1728259200000',
     'endDt': '1730073600000',
     'thumborImageId': 379130},
    {'id': 9017,
     'name': 'Serbia tour of Gibraltar, 2024',
     'startDt': '1727654400000',
     'endDt': '1727654400000',
     'thumborImageId': 379130},
    {'id': 8947,
     'name': 'Namibia T20I Tri-Series 2024',
     'startDt': '1727568000000',
     'endDt': '1728086400000',
     'thumborImageId': 379130},
    {'id': 8598,
     'name': 'ICC Mens T20 World Cup Sub Regional East Asia-Pacific Qualifier B, 2024',
     'startDt': '1727481600000',
     'endDt': '1728086400000',
     'thumborImageId': 379130},
    {'id': 8955,
     'name': 'Canada T20I Tri-Series 2024',
     'startDt': '1727481600000',
     'endDt': '1727913600000',
     'thumborImageId': 379130},
    {'id': 7981,
     'name': 'Ireland v South Africa in UAE, 2024',
     'startDt': '1727308800000',
     'endDt': '1728172800000',
     'thumborImageId': 379130},
    {'id': 8969,
     'name': 'T20I Tri-Series in South Korea, 2024',
     'startDt': '1727222400000',
     'endDt': '1727308800000',
     'thumborImageId': 379130},
    {'id': 8835,
     'name': 'ICC Mens T20 World Cup Africa Sub Regional Qualifier A 2024',
     'startDt': '1726876800000',
     'endDt': '1727308800000',
     'thumborImageId': 379130},
    {'id': 8393,
     'name': 'Bangladesh tour of India, 2024',
     'startDt': '1726704000000',
     'endDt': '1728691200000',
     'thumborImageId': 379130},
    {'id': 8818,
     'name': 'New Zealand tour of Sri Lanka, 2024',
     'startDt': '1726617600000',
     'endDt': '1727654400000',
     'thumborImageId': 379130},
    {'id': 8661,
     'name': 'Afghanistan v South Africa in UAE, 2024',
     'startDt': '1726617600000',
     'endDt': '1726963200000',
     'thumborImageId': 379130},
    {'id': 6794,
     'name': 'Australia tour of England, 2024',
     'startDt': '1726012800000',
     'endDt': '1727568000000',
     'thumborImageId': 379130},
    {'id': 8625,
     'name': 'Afghanistan v New Zealand in India, 2024',
     'startDt': '1725840000000',
     'endDt': '1726185600000',
     'thumborImageId': 379130},
    {'id': 8552,
     'name': 'Australia tour of Scotland, 2024',
     'startDt': '1725408000000',
     'endDt': '1725667200000',
     'thumborImageId': 379130},
    {'id': 8764,
     'name': 'ICC Mens T20 World Cup Asia Qualifier A 2024',
     'startDt': '1724976000000',
     'endDt': '1725840000000',
     'thumborImageId': 379130},
    {'id': 8632,
     'name': 'Netherlands T20I Tri-Series, 2024',
     'startDt': '1724371200000',
     'endDt': '1724803200000',
     'thumborImageId': 379130},
    {'id': 8596,
     'name': 'ICC Mens T20 World Cup Sub Regional Europe Qualifier C, 2024',
     'startDt': '1724198400000',
     'endDt': '1724803200000',
     'thumborImageId': 379130},
    {'id': 8495,
     'name': 'Bangladesh tour of Pakistan, 2024',
     'startDt': '1724198400000',
     'endDt': '1725321600000',
     'thumborImageId': 379130},
    {'id': 8686,
     'name': 'Malaysia T20I Tri Nations Cup, 2024',
     'startDt': '1724198400000',
     'endDt': '1724716800000',
     'thumborImageId': 379130},
    {'id': 8587,
     'name': 'ICC Mens T20 World Cup Sub Regional East Asia-Pacific Qualifier A, 2024',
     'startDt': '1723852800000',
     'endDt': '1724457600000',
     'thumborImageId': 379130},
    {'id': 6787,
     'name': 'Sri Lanka tour of England, 2024',
     'startDt': '1723593600000',
     'endDt': '1725926400000',
     'thumborImageId': 379130},
    {'id': 8578,
     'name': 'Spain tour of Croatia, 2024',
     'startDt': '1722556800000',
     'endDt': '1722902400000',
     'thumborImageId': 379130},
    {'id': 8238,
     'name': 'South Africa tour of West Indies, 2024',
     'startDt': '1722384000000',
     'endDt': '1724716800000',
     'thumborImageId': 379130},
    {'id': 8528,
     'name': 'India tour of Sri Lanka, 2024',
     'startDt': '1722038400000',
     'endDt': '1722988800000',
     'thumborImageId': 379130},
    {'id': 7979,
     'name': 'Zimbabwe tour of Ireland, 2024',
     'startDt': '1721865600000',
     'endDt': '1722211200000',
     'thumborImageId': 379130},
    {'id': 8476,
     'name': 'Nigeria tour of Kenya 2024',
     'startDt': '1720742400000',
     'endDt': '1721174400000',
     'thumborImageId': 379130},
    {'id': 8337,
     'name': 'ICC Mens T20 World Cup Sub Regional Europe Qualifier B, 2024',
     'startDt': '1720310400000',
     'endDt': '1720915200000',
     'thumborImageId': 379130},
    {'id': 7546,
     'name': 'India tour of Zimbabwe, 2024',
     'startDt': '1720224000000',
     'endDt': '1720915200000',
     'thumborImageId': 379130},
    {'id': 6780,
     'name': 'West Indies tour of England, 2024',
     'startDt': '1719964800000',
     'endDt': '1722297600000',
     'thumborImageId': 379130},
    {'id': 8422,
     'name': 'Serbia tour of Slovenia, 2024',
     'startDt': '1719619200000',
     'endDt': '1719705600000',
     'thumborImageId': 379130},
    {'id': 8382,
     'name': 'Kenya Quadrangular Cup 2024',
     'startDt': '1719532800000',
     'endDt': '1720569600000',
     'thumborImageId': 379130},
    {'id': 8413,
     'name': 'Jersey tour of Guernsey, 2024',
     'startDt': '1719014400000',
     'endDt': '1719100800000',
     'thumborImageId': 379130},
    {'id': 8310,
     'name': 'Estonia tour of Cyprus 2024',
     'startDt': '1718582400000',
     'endDt': '1718755200000',
     'thumborImageId': 379130},
    {'id': 8260,
     'name': 'Jersey tour of Denmark, 2024',
     'startDt': '1718409600000',
     'endDt': '1718496000000',
     'thumborImageId': 379130},
    {'id': 8332,
     'name': 'Nordic T20I Cup 2024',
     'startDt': '1718323200000',
     'endDt': '1718496000000',
     'thumborImageId': 379130},
    {'id': 8256,
     'name': 'ICC Mens T20 World Cup Sub Regional Europe Qualifier A, 2024',
     'startDt': '1717891200000',
     'endDt': '1718496000000',
     'thumborImageId': 379130},
    {'id': 8294,
     'name': 'Guernsey tour of Belgium, 2024',
     'startDt': '1717804800000',
     'endDt': '1717891200000',
     'thumborImageId': 379130},
    {'id': 7476,
     'name': 'ICC Mens T20 World Cup 2024',
     'startDt': '1717200000000',
     'endDt': '1719619200000',
     'thumborImageId': 379130},
    {'id': 8247,
     'name': 'Belgium tour of Austria, 2024',
     'startDt': '1716595200000',
     'endDt': '1716681600000',
     'thumborImageId': 379130},
    {'id': 8166,
     'name': 'Continental Cup 2024',
     'startDt': '1716508800000',
     'endDt': '1716681600000',
     'thumborImageId': 379130},
    {'id': 8103,
     'name': 'South Africa tour of West Indies, 2024',
     'startDt': '1716422400000',
     'endDt': '1716681600000',
     'thumborImageId': 379130},
    {'id': 6773,
     'name': 'Pakistan tour of England, 2024',
     'startDt': '1716336000000',
     'endDt': '1717027200000',
     'thumborImageId': 379130},
    {'id': 7700,
     'name': 'Bangladesh tour of USA, 2024',
     'startDt': '1716249600000',
     'endDt': '1716595200000',
     'thumborImageId': 379130},
    {'id': 7819,
     'name': 'Netherlands T20I Tri-Series, 2024',
     'startDt': '1715990400000',
     'endDt': '1716508800000',
     'thumborImageId': 379130},
    {'id': 7808,
     'name': 'Pakistan tour of Ireland, 2024',
     'startDt': '1715299200000',
     'endDt': '1715644800000',
     'thumborImageId': 379130},
    {'id': 8080,
     'name': 'Mdina Cup 2024',
     'startDt': '1715212800000',
     'endDt': '1715472000000',
     'thumborImageId': 379130},
    {'id': 7896,
     'name': 'Mongolia tour of Japan, 2024',
     'startDt': '1715040000000',
     'endDt': '1715472000000',
     'thumborImageId': 379130},
    {'id': 7706,
     'name': 'Zimbabwe tour of Bangladesh, 2024',
     'startDt': '1714694400000',
     'endDt': '1715472000000',
     'thumborImageId': 379130},
    {'id': 8042,
     'name': 'Thailand tour of Indonesia 2024',
     'startDt': '1714521600000',
     'endDt': '1714953600000',
     'thumborImageId': 379130},
    {'id': 7679,
     'name': 'New Zealand tour of Pakistan, 2024',
     'startDt': '1713398400000',
     'endDt': '1714176000000',
     'thumborImageId': 379130},
    {'id': 7817,
     'name': 'Jersey tour of Spain, 2024',
     'startDt': '1713052800000',
     'endDt': '1713052800000',
     'thumborImageId': 379130},
    {'id': 7667,
     'name': 'ACC Mens T20I Premier Cup, 2024',
     'startDt': '1712880000000',
     'endDt': '1713657600000',
     'thumborImageId': 379130},
    {'id': 7900,
     'name': 'Central American Cricket Championships 2024',
     'startDt': '1712793600000',
     'endDt': '1713052800000',
     'thumborImageId': 379130},
    {'id': 7693,
     'name': 'Canada tour of USA, 2024',
     'startDt': '1712448000000',
     'endDt': '1712966400000',
     'thumborImageId': 379130},
    {'id': 7727,
     'name': 'Namibia tour of Oman, 2024',
     'startDt': '1711929600000',
     'endDt': '1712448000000',
     'thumborImageId': 379130},
    {'id': 7790,
     'name': 'Lesotho tour of Eswatini, 2024',
     'startDt': '1711670400000',
     'endDt': '1711843200000',
     'thumborImageId': 379130},
    {'id': 7672,
     'name': 'Mens African Games, 2024',
     'startDt': '1710633600000',
     'endDt': '1711152000000',
     'thumborImageId': 379130},
    {'id': 7686,
     'name': 'Papua New Guinea tour of Malaysia, 2024',
     'startDt': '1710547200000',
     'endDt': '1710633600000',
     'thumborImageId': 379130},
    {'id': 7590,
     'name': 'Scotland tour of United Arab Emirates 2024',
     'startDt': '1710115200000',
     'endDt': '1710374400000',
     'thumborImageId': 379130},
    {'id': 7644,
     'name': 'Hong Kong T20I Tri-Series, 2024',
     'startDt': '1710028800000',
     'endDt': '1710288000000',
     'thumborImageId': 379130},
    {'id': 7637,
     'name': 'Hong Kong Friendship Cup, 2024',
     'startDt': '1709942400000',
     'endDt': '1709942400000',
     'thumborImageId': 379130},
    {'id': 7586,
     'name': 'Malaysia Open T20I Championship, 2024',
     'startDt': '1709596800000',
     'endDt': '1710115200000',
     'thumborImageId': 379130},
    {'id': 7534,
     'name': 'Sri Lanka tour of Bangladesh, 2024',
     'startDt': '1709510400000',
     'endDt': '1712102400000',
     'thumborImageId': 379130},
    {'id': 7623,
     'name': 'Papua New Guinea tour of Oman 2024',
     'startDt': '1709424000000',
     'endDt': '1709856000000',
     'thumborImageId': 379130},
    {'id': 7485,
     'name': 'Afghanistan v Ireland in UAE, 2024',
     'startDt': '1709078400000',
     'endDt': '1710720000000',
     'thumborImageId': 379130},
    {'id': 7618,
     'name': 'Hong Kong tour of Qatar 2024',
     'startDt': '1708992000000',
     'endDt': '1709251200000',
     'thumborImageId': 379130},
    {'id': 7583,
     'name': 'Nepal T20I Tri-Series 2024',
     'startDt': '1708992000000',
     'endDt': '1709596800000',
     'thumborImageId': 379130},
    {'id': 6899,
     'name': 'Australia tour of New Zealand, 2024',
     'startDt': '1708473600000',
     'endDt': '1710201600000',
     'thumborImageId': 379130},
    {'id': 7572,
     'name': 'ICC Cricket World Cup League Two 2023-27',
     'startDt': '1707955200000',
     'endDt': '1806364800000',
     'thumborImageId': 379130},
    {'id': 7558,
     'name': 'East Asia Cup 2024',
     'startDt': '1707868800000',
     'endDt': '1708128000000',
     'thumborImageId': 379130},
    {'id': 7579,
     'name': 'Quadrangular Twenty20 Series in Thailand 2024',
     'startDt': '1707696000000',
     'endDt': '1708041600000',
     'thumborImageId': 379130},
    {'id': 7553,
     'name': 'Canada tour of Nepal, 2024',
     'startDt': '1707350400000',
     'endDt': '1707696000000',
     'thumborImageId': 379130},
    {'id': 7481,
     'name': 'Afghanistan tour of Sri Lanka, 2024',
     'startDt': '1706832000000',
     'endDt': '1708473600000',
     'thumborImageId': 379130},
    {'id': 6892,
     'name': 'South Africa tour of New Zealand, 2024',
     'startDt': '1706486400000',
     'endDt': '1708128000000',
     'thumborImageId': 379130},
    {'id': 7511,
     'name': 'ACC Mens T20I Challenger Cup 2024',
     'startDt': '1706313600000',
     'endDt': '1707609600000',
     'thumborImageId': 379130},
    {'id': 6927,
     'name': 'England tour of India, 2024',
     'startDt': '1706140800000',
     'endDt': '1710115200000',
     'thumborImageId': 379130},
    {'id': 6885,
     'name': 'Pakistan tour of New Zealand, 2024',
     'startDt': '1705017600000',
     'endDt': '1705795200000',
     'thumborImageId': 379130},
    {'id': 6920,
     'name': 'Afghanistan tour of India, 2024',
     'startDt': '1704931200000',
     'endDt': '1705449600000',
     'thumborImageId': 379130},
    {'id': 6297,
     'name': 'West Indies tour of Australia, 2024',
     'startDt': '1704844800000',
     'endDt': '1707782400000',
     'thumborImageId': 379130},
    {'id': 7411,
     'name': 'Zimbabwe tour of Sri Lanka 2024',
     'startDt': '1704499200000',
     'endDt': '1705536000000',
     'thumborImageId': 379130}]}],
 'appIndex': {'seoTitle': 'Current Running Cricket Series - Cricbuzz | Cricbuzz.com',
  'webURL': 'www.cricbuzz.com/cricket-series/'},
 'contentFilters': [{'filterId': 'fantasy', 'filterName': 'Fantasy Handbook'}]}

In [ ]:
import pandas as pd
from datetime import datetime

series_2024 = []

series_data_2024 = international_df['seriesMapProto'][0]['series']

for s in series_data_2024:

    series_name = s['name']
    series_id = s['id']
    
    # Convert timestamp to date
    start_date = datetime.fromtimestamp(int(s['startDt'])/1000).strftime('%Y-%m-%d')

    # Extract host country (simple logic)
    if "tour of" in series_name:
        host_country = series_name.split("tour of")[-1].split(",")[0].strip()
    elif "in" in series_name:
        host_country = series_name.split("in")[-1].split(",")[0].strip()
    else:
        host_country = "Unknown"

    # Match type detection
    if "T20" in series_name:
        match_type = "T20"
    elif "ODI" in series_name:
        match_type = "ODI"
    elif "Test" in series_name:
        match_type = "Test"
    else:
        match_type = "Internatonal"

    series_2024.append({
        "Series_id" : series_id,
        "Series Name": series_name,
        "Host Country": host_country,
        "Match Type": match_type,
        "Start Date": start_date
    })

df1_2024 = pd.DataFrame(series_2024)

print(df1_2024.head())

   Series_id                                        Series Name  Host Country    Match Type  Start Date
0       8553             Sri Lanka tour of New Zealand, 2024-25   New Zealand  Internatonal  2024-12-23
1       9297               Gulf Cricket T20I Championship, 2024       Unknown           T20  2024-12-13
2       8044            Pakistan tour of South Africa, 2024 -25  South Africa  Internatonal  2024-12-10
3       9171              Afghanistan tour of Zimbabwe, 2024-25      Zimbabwe  Internatonal  2024-12-09
4       9265  ICC Mens T20 World Cup Americas Sub Regional Q...       Unknown           T20  2024-12-06

In [74]:
df1_2024

     Series_id                                        Series Name    Host Country    Match Type  Start Date
0         8553             Sri Lanka tour of New Zealand, 2024-25     New Zealand  Internatonal  2024-12-23
1         9297               Gulf Cricket T20I Championship, 2024         Unknown           T20  2024-12-13
2         8044            Pakistan tour of South Africa, 2024 -25    South Africa  Internatonal  2024-12-10
3         9171              Afghanistan tour of Zimbabwe, 2024-25        Zimbabwe  Internatonal  2024-12-09
4         9265  ICC Mens T20 World Cup Americas Sub Regional Q...         Unknown           T20  2024-12-06
..         ...                                                ...             ...           ...         ...
104       6927                        England tour of India, 2024           India  Internatonal  2024-01-25
105       6885                 Pakistan tour of New Zealand, 2024     New Zealand  Internatonal  2024-01-12
106       6920                    Afghanistan tour of India, 2024           India  Internatonal  2024-01-11
107       6297                West Indies tour of Australia, 2024       Australia  Internatonal  2024-01-10
108       7411                    Zimbabwe tour of Sri Lanka 2024  Sri Lanka 2024  Internatonal  2024-01-06

[109 rows x 5 columns]

In [75]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/series/v1/6927"

headers = {
	"x-rapidapi-key": "e6021fb984msh201af5139a6e2e9p149939jsn32edaa5716a4",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

ser_6927 = response.json()

In [77]:
import pandas as pd
from datetime import datetime

series_matches2024 = []

for item in ser_6927['matchDetails']:
    
    match_map = item.get('matchDetailsMap', {})
    
    for m in match_map.get('match', []):
        
        info = m.get('matchInfo', {})
        
        match_id = info.get('matchId')
        series_name = info.get('seriesName')
        match_desc = info.get('matchDesc')
        match_format = info.get('matchFormat')
        
        team1 = info.get('team1', {}).get('teamName')
        team2 = info.get('team2', {}).get('teamName')
        
        venue = info.get('venueInfo', {}).get('ground')
        city = info.get('venueInfo', {}).get('city')
        
        start_date = datetime.fromtimestamp(
            int(info.get('startDate'))/1000
        ).strftime('%Y-%m-%d')
        
        status = info.get('status')
        
        series_matches2024.append({
            "Match ID": match_id,
            "Series": series_name,
            "Match": match_desc,
            "Format": match_format,
            "Team1": team1,
            "Team2": team2,
            "Venue": venue,
            "City": city,
            "Start Date": start_date,
            "Result": status
        })

df_series_mat2024 = pd.DataFrame(series_matches2024)

df_series_mat2024.head()

   Match ID                       Series     Match Format  Team1    Team2                                         Venue           City  Start Date                               Result
0     78628  England tour of India, 2024  1st Test   TEST  INDIA  ENGLAND            Rajiv Gandhi International Stadium      Hyderabad  2024-01-25               England won by 28 runs
1     78635  England tour of India, 2024  2nd Test   TEST  INDIA  ENGLAND                      ACA-VDCA Cricket Stadium  Visakhapatnam  2024-02-02                India won by 106 runs
2     78642  England tour of India, 2024  3rd Test   TEST  INDIA  ENGLAND              Niranjan Shah Stadium, Khandheri         Rajkot  2024-02-15                India won by 434 runs
3     78649  England tour of India, 2024  4th Test   TEST  INDIA  ENGLAND            JSCA International Stadium Complex         Ranchi  2024-02-23                  India won by 5 wkts
4     78656  England tour of India, 2024  5th Test   TEST  INDIA  ENGLAND  Himachal Pradesh Cricket Association Stadium     Dharamsala  2024-03-07  India won by an innings and 64 runs

# series 2023

In [50]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/series/v1/archives/international"

querystring = {"year":"2023"}

headers = {
	"x-rapidapi-key": "e6021fb984msh201af5139a6e2e9p149939jsn32edaa5716a4",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

international_df3 =response.json()

In [53]:
international_df3

{'seriesMapProto': [{'date': '2023',
   'series': [{'id': 7404,
     'name': 'Afghanistan tour of United Arab Emirates 2023-24',
     'startDt': '1703808000000',
     'endDt': '1704153600000',
     'thumborImageId': 379130},
    {'id': 7415,
     'name': 'Philippines tour of Indonesia T20I Series 2023',
     'startDt': '1703203200000',
     'endDt': '1703548800000',
     'thumborImageId': 379130},
    {'id': 6878,
     'name': 'Bangladesh tour of New Zealand, 2023',
     'startDt': '1702771200000',
     'endDt': '1703980800000',
     'thumborImageId': 379130},
    {'id': 7399,
     'name': 'Africa Cricket Association Cup 2023',
     'startDt': '1702252800000',
     'endDt': '1702944000000',
     'thumborImageId': 379130},
    {'id': 6857,
     'name': 'India tour of South Africa, 2023-24',
     'startDt': '1702166400000',
     'endDt': '1704585600000',
     'thumborImageId': 379130},
    {'id': 7275,
     'name': 'Ireland tour of Zimbabwe, 2023',
     'startDt': '1701907200000',
     'endDt': '1702771200000',
     'thumborImageId': 379130},
    {'id': 7383,
     'name': 'East-West Africa Cup Qualifiers 2023',
     'startDt': '1701820800000',
     'endDt': '1702166400000',
     'thumborImageId': 379130},
    {'id': 6290,
     'name': 'Pakistan tour of Australia, 2023-24',
     'startDt': '1701820800000',
     'endDt': '1704585600000',
     'thumborImageId': 379130},
    {'id': 6228,
     'name': 'England tour of West Indies, 2023',
     'startDt': '1701561600000',
     'endDt': '1703203200000',
     'thumborImageId': 379130},
    {'id': 7233,
     'name': 'Australia tour of India, 2023',
     'startDt': '1700697600000',
     'endDt': '1701561600000',
     'thumborImageId': 379130},
    {'id': 7268,
     'name': 'ICC Mens T20 World Cup Africa Region Qualifier 2023',
     'startDt': '1700611200000',
     'endDt': '1701302400000',
     'thumborImageId': 379130},
    {'id': 7264,
     'name': 'Cambodia tour of Indonesia 2023',
     'startDt': '1700438400000',
     'endDt': '1700697600000',
     'thumborImageId': 379130},
    {'id': 7231,
     'name': 'ICC Mens T20I World Cup Asia Finals 2023',
     'startDt': '1698624000000',
     'endDt': '1699142400000',
     'thumborImageId': 379130},
    {'id': 7226,
     'name': 'Zimbabwe tour of Namibia 2023',
     'startDt': '1698105600000',
     'endDt': '1698624000000',
     'thumborImageId': 379130},
    {'id': 7198,
     'name': 'Nepal T20I Tri-Series 2023',
     'startDt': '1697587200000',
     'endDt': '1698364800000',
     'thumborImageId': 379130},
    {'id': 7212,
     'name': 'Luxembourg tour of Gibraltar 2023',
     'startDt': '1697328000000',
     'endDt': '1697328000000',
     'thumborImageId': 379130},
    {'id': 7196,
     'name': 'Serbia tour of Gibraltar 2023',
     'startDt': '1696464000000',
     'endDt': '1696464000000',
     'thumborImageId': 379130},
    {'id': 6732,
     'name': 'ICC Cricket World Cup 2023',
     'startDt': '1696464000000',
     'endDt': '1700352000000',
     'thumborImageId': 379130},
    {'id': 7189,
     'name': 'West Africa Trophy 2023',
     'startDt': '1696377600000',
     'endDt': '1697328000000',
     'thumborImageId': 379130},
    {'id': 7004,
     'name': 'Estonia tour of Gibraltar 2023',
     'startDt': '1696032000000',
     'endDt': '1696032000000',
     'thumborImageId': 379130},
    {'id': 7180,
     'name': 'ICC Mens T20 World Cup Americas Region Final 2023',
     'startDt': '1696032000000',
     'endDt': '1696636800000',
     'thumborImageId': 379130},
    {'id': 7158,
     'name': 'ICC Mens T20 World Cup Sub Regional Asia Qualifier A 2023',
     'startDt': '1695859200000',
     'endDt': '1696464000000',
     'thumborImageId': 379130},
    {'id': 7163,
     'name': 'Asian Games Mens T20I 2023',
     'startDt': '1695772800000',
     'endDt': '1696636800000',
     'thumborImageId': 379130},
    {'id': 6913,
     'name': 'Australia tour of India, 2023',
     'startDt': '1695340800000',
     'endDt': '1695772800000',
     'thumborImageId': 379130},
    {'id': 6694,
     'name': 'New Zealand tour of Bangladesh, 2023',
     'startDt': '1695254400000',
     'endDt': '1702166400000',
     'thumborImageId': 379130},
    {'id': 4805,
     'name': 'Ireland tour of England ODI Series, 2023',
     'startDt': '1695168000000',
     'endDt': '1695686400000',
     'thumborImageId': 379130},
    {'id': 7149,
     'name': 'Malaysia T20I Tri-Series 2023',
     'startDt': '1695081600000',
     'endDt': '1695513600000',
     'thumborImageId': 379130},
    {'id': 7135,
     'name': 'Gulf Cricket T20I Championship 2023',
     'startDt': '1694736000000',
     'endDt': '1695427200000',
     'thumborImageId': 379130},
    {'id': 6906,
     'name': 'Asia Cup, 2023',
     'startDt': '1693353600000',
     'endDt': '1694908800000',
     'thumborImageId': 379130},
    {'id': 6242,
     'name': 'Australia tour of South Africa, 2023',
     'startDt': '1693353600000',
     'endDt': '1694908800000',
     'thumborImageId': 379130},
    {'id': 4791,
     'name': 'New Zealand tour of England, 2023',
     'startDt': '1692921600000',
     'endDt': '1694736000000',
     'thumborImageId': 379130},
    {'id': 6934,
     'name': 'Afghanistan v Pakistan in Sri Lanka, 2023',
     'startDt': '1692662400000',
     'endDt': '1693008000000',
     'thumborImageId': 379130},
    {'id': 7066,
     'name': 'East Africa Cup 2023',
     'startDt': '1692489600000',
     'endDt': '1693440000000',
     'thumborImageId': 379130},
    {'id': 6997,
     'name': 'Continental Cup 2023',
     'startDt': '1692316800000',
     'endDt': '1692489600000',
     'thumborImageId': 379130},
    {'id': 6836,
     'name': 'India tour of Ireland, 2023',
     'startDt': '1692316800000',
     'endDt': '1692748800000',
     'thumborImageId': 379130},
    {'id': 5973,
     'name': 'New Zealand tour of United Arab Emirates, 2023',
     'startDt': '1692230400000',
     'endDt': '1692489600000',
     'thumborImageId': 379130},
    {'id': 6955,
     'name': 'Germany v Guernsey in Netherlands, 2023',
     'startDt': '1691971200000',
     'endDt': '1692057600000',
     'thumborImageId': 379130},
    {'id': 6948,
     'name': 'Budapest Cup 2023',
     'startDt': '1691193600000',
     'endDt': '1691280000000',
     'thumborImageId': 379130},
    {'id': 6687,
     'name': 'ICC Mens T20 World Cup Asia Qualifier B 2023',
     'startDt': '1690329600000',
     'endDt': '1690848000000',
     'thumborImageId': 379130},
    {'id': 6340,
     'name': 'ICC Mens T20 World Cup East Asia Pacific Qualifier 2023',
     'startDt': '1689984000000',
     'endDt': '1690588800000',
     'thumborImageId': 379130},
    {'id': 6333,
     'name': 'ICC Mens T20 World Cup Europe Qualifier 2023',
     'startDt': '1689811200000',
     'endDt': '1690502400000',
     'thumborImageId': 379130},
    {'id': 6752,
     'name': 'Valletta Cup 2023',
     'startDt': '1689120000000',
     'endDt': '1689465600000',
     'thumborImageId': 379130},
    {'id': 6582,
     'name': 'India tour of West Indies, 2023',
     'startDt': '1689120000000',
     'endDt': '1691884800000',
     'thumborImageId': 379130},
    {'id': 6652,
     'name': 'Pakistan tour of Sri Lanka, 2023',
     'startDt': '1689033600000',
     'endDt': '1690502400000',
     'thumborImageId': 379130},
    {'id': 6759,
     'name': 'Mdina Cup 2023',
     'startDt': '1688947200000',
     'endDt': '1689120000000',
     'thumborImageId': 379130},
    {'id': 6683,
     'name': 'Austria tour of Isle of Man, 2023',
     'startDt': '1688860800000',
     'endDt': '1688947200000',
     'thumborImageId': 379130},
    {'id': 6676,
     'name': 'Inter-Insular Mens T20I Series 2023',
     'startDt': '1688688000000',
     'endDt': '1688774400000',
     'thumborImageId': 379130},
    {'id': 6669,
     'name': 'Austria v Germany in Netherlands, 2023',
     'startDt': '1687996800000',
     'endDt': '1688083200000',
     'thumborImageId': 379130},
    {'id': 6666,
     'name': 'Switzerland tour of Luxembourg, 2023',
     'startDt': '1687564800000',
     'endDt': '1687651200000',
     'thumborImageId': 379130},
    {'id': 6659,
     'name': 'Bulgaria Quadrangular Series 2023',
     'startDt': '1687478400000',
     'endDt': '1687651200000',
     'thumborImageId': 379130},
    {'id': 6437,
     'name': 'ICC Cricket World Cup Qualifiers 2023',
     'startDt': '1687046400000',
     'endDt': '1688860800000',
     'thumborImageId': 379130},
    {'id': 4777,
     'name': 'The Ashes, 2023',
     'startDt': '1686873600000',
     'endDt': '1690761600000',
     'thumborImageId': 379130},
    {'id': 6351,
     'name': 'Afghanistan tour of Bangladesh, 2023',
     'startDt': '1686700800000',
     'endDt': '1689465600000',
     'thumborImageId': 379130},
    {'id': 6606,
     'name': 'Central Europe Cup 2023',
     'startDt': '1686355200000',
     'endDt': '1686441600000',
     'thumborImageId': 379130},
    {'id': 6599,
     'name': 'Belgium tour of Germany, 2023',
     'startDt': '1686268800000',
     'endDt': '1686441600000',
     'thumborImageId': 379130},
    {'id': 6589,
     'name': 'Africa Continental Cup 2023',
     'startDt': '1686268800000',
     'endDt': '1687305600000',
     'thumborImageId': 379130},
    {'id': 5917,
     'name': 'ICC World Test Championship Final 2023',
     'startDt': '1686096000000',
     'endDt': '1686528000000',
     'thumborImageId': 379130},
    {'id': 6255,
     'name': 'West Indies tour of UAE, 2023',
     'startDt': '1685836800000',
     'endDt': '1686268800000',
     'thumborImageId': 379130},
    {'id': 6248,
     'name': 'Afghanistan tour of Sri Lanka, 2023',
     'startDt': '1685664000000',
     'endDt': '1686096000000',
     'thumborImageId': 379130},
    {'id': 6521,
     'name': 'Southern Africa Cup 2023',
     'startDt': '1685145600000',
     'endDt': '1685577600000',
     'thumborImageId': 379130},
    {'id': 4786,
     'name': 'Ireland tour of England Only Test, 2023',
     'startDt': '1685059200000',
     'endDt': '1685836800000',
     'thumborImageId': 379130},
    {'id': 6235,
     'name': 'Nordic T20I Cup 2023',
     'startDt': '1684368000000',
     'endDt': '1684627200000',
     'thumborImageId': 379130},
    {'id': 6022,
     'name': 'Ireland v Bangladesh in England, 2023',
     'startDt': '1683590400000',
     'endDt': '1684022400000',
     'thumborImageId': 379130},
    {'id': 6193,
     'name': 'Gibraltar T20I Tri-Series 2023',
     'startDt': '1683158400000',
     'endDt': '1683417600000',
     'thumborImageId': 379130},
    {'id': 6214,
     'name': 'SEA Games Mens Twenty20 Cricket Competition 2023',
     'startDt': '1682899200000',
     'endDt': '1683763200000',
     'thumborImageId': 379130},
    {'id': 5913,
     'name': 'Ireland tour of Sri Lanka, 2023',
     'startDt': '1681603200000',
     'endDt': '1682640000000',
     'thumborImageId': 379130},
    {'id': 4896,
     'name': 'New Zealand tour of Pakistan, 2023',
     'startDt': '1681430400000',
     'endDt': '1683417600000',
     'thumborImageId': 379130},
    {'id': 6155,
     'name': 'Gibraltar tour of Portugal, 2023',
     'startDt': '1681084800000',
     'endDt': '1681171200000',
     'thumborImageId': 379130},
    {'id': 4861,
     'name': 'Netherlands tour of South Africa, 2023',
     'startDt': '1679961600000',
     'endDt': '1680393600000',
     'thumborImageId': 379130},
    {'id': 6025,
     'name': 'ICC Cricket World Cup Qualifier Play-off 2023',
     'startDt': '1679788800000',
     'endDt': '1680652800000',
     'thumborImageId': 379130},
    {'id': 5987,
     'name': 'Afghanistan v Pakistan in UAE, 2023',
     'startDt': '1679616000000',
     'endDt': '1679875200000',
     'thumborImageId': 379130},
    {'id': 5980,
     'name': 'Netherlands tour of Zimbabwe, 2023',
     'startDt': '1679356800000',
     'endDt': '1679702400000',
     'thumborImageId': 379130},
    {'id': 5490,
     'name': 'Ireland tour of Bangladesh, 2023',
     'startDt': '1678838400000',
     'endDt': '1680912000000',
     'thumborImageId': 379130},
    {'id': 5966,
     'name': 'Hong Kong Quadrangular Series 2023',
     'startDt': '1678233600000',
     'endDt': '1678579200000',
     'thumborImageId': 379130},
    {'id': 4415,
     'name': 'Sri Lanka tour New Zealand, 2023',
     'startDt': '1677888000000',
     'endDt': '1680912000000',
     'thumborImageId': 379130},
    {'id': 5276,
     'name': 'England tour of Bangladesh, 2023',
     'startDt': '1677628800000',
     'endDt': '1678752000000',
     'thumborImageId': 379130},
    {'id': 5959,
     'name': 'ICC Mens T20 World Cup Americas Qualifier 2023',
     'startDt': '1677283200000',
     'endDt': '1677888000000',
     'thumborImageId': 379130},
    {'id': 5847,
     'name': 'Isle of Man tour of Spain, 2023',
     'startDt': '1677196800000',
     'endDt': '1677369600000',
     'thumborImageId': 379130},
    {'id': 5952,
     'name': 'Bermuda tour of Argentina, 2023',
     'startDt': '1676937600000',
     'endDt': '1677024000000',
     'thumborImageId': 379130},
    {'id': 4854,
     'name': 'West Indies tour of South Africa, 2023',
     'startDt': '1676937600000',
     'endDt': '1679961600000',
     'thumborImageId': 379130},
    {'id': 5896,
     'name': 'Afghanistan tour of United Arab Emirates, 2023',
     'startDt': '1676505600000',
     'endDt': '1676764800000',
     'thumborImageId': 379130},
    {'id': 5204,
     'name': 'Australia tour of India, 2023',
     'startDt': '1675900800000',
     'endDt': '1679443200000',
     'thumborImageId': 379130},
    {'id': 4413,
     'name': 'England tour of New Zealand, 2023',
     'startDt': '1675814400000',
     'endDt': '1677542400000',
     'thumborImageId': 379130},
    {'id': 5260,
     'name': 'West Indies tour of Zimbabwe, 2023',
     'startDt': '1674864000000',
     'endDt': '1676505600000',
     'thumborImageId': 379130},
    {'id': 4847,
     'name': 'England tour of South Africa, 2023',
     'startDt': '1674777600000',
     'endDt': '1675209600000',
     'thumborImageId': 379130},
    {'id': 5199,
     'name': 'New Zealand tour of India, 2023',
     'startDt': '1674000000000',
     'endDt': '1675209600000',
     'thumborImageId': 379130},
    {'id': 5213,
     'name': 'Ireland tour of Zimbabwe, 2023',
     'startDt': '1673481600000',
     'endDt': '1674432000000',
     'thumborImageId': 379130},
    {'id': 5197,
     'name': 'Sri Lanka tour of India, 2023',
     'startDt': '1672704000000',
     'endDt': '1673740800000',
     'thumborImageId': 379130}]}],
 'appIndex': {'seoTitle': 'Current Running Cricket Series - Cricbuzz | Cricbuzz.com',
  'webURL': 'www.cricbuzz.com/cricket-series/'}}

In [81]:
import pandas as pd
from datetime import datetime

series_2023 = []

series_data_2023 = international_df3['seriesMapProto'][0]['series']

for s in series_data_2023:

    series_name = s['name']
    series_id = s['id']
    
    # Convert timestamp to date
    start_date = datetime.fromtimestamp(int(s['startDt'])/1000).strftime('%Y-%m-%d')

    # Extract host country (simple logic)
    if "tour of" in series_name:
        host_country = series_name.split("tour of")[-1].split(",")[0].strip()
    elif "in" in series_name:
        host_country = series_name.split("in")[-1].split(",")[0].strip()
    else:
        host_country = "Unknown"

    # Match type detection
    if "T20" in series_name:
        match_type = "T20"
    elif "ODI" in series_name:
        match_type = "ODI"
    elif "Test" in series_name:
        match_type = "Test"
    else:
        match_type = "Internatonal"

    series_2023.append({
        "Series_id" : series_id,
        "Series Name": series_name,
        "Host Country": host_country,
        "Match Type": match_type,
        "Start Date": start_date
    })

df1_2023 = pd.DataFrame(series_2023)

print(df1_2023.head())

   Series_id                                       Series Name                  Host Country    Match Type  Start Date
0       7404  Afghanistan tour of United Arab Emirates 2023-24  United Arab Emirates 2023-24  Internatonal  2023-12-29
1       7415    Philippines tour of Indonesia T20I Series 2023    Indonesia T20I Series 2023           T20  2023-12-22
2       6878              Bangladesh tour of New Zealand, 2023                   New Zealand  Internatonal  2023-12-17
3       7399               Africa Cricket Association Cup 2023                       Unknown  Internatonal  2023-12-11
4       6857               India tour of South Africa, 2023-24                  South Africa  Internatonal  2023-12-10

In [89]:
df1_2023.iloc[30:87]

    Series_id                                        Series Name          Host Country    Match Type  Start Date
30       4791                  New Zealand tour of England, 2023               England  Internatonal  2023-08-25
31       6934          Afghanistan v Pakistan in Sri Lanka, 2023             Sri Lanka  Internatonal  2023-08-22
32       7066                               East Africa Cup 2023               Unknown  Internatonal  2023-08-20
33       6997                               Continental Cup 2023        ental Cup 2023  Internatonal  2023-08-18
34       6836                        India tour of Ireland, 2023               Ireland  Internatonal  2023-08-18
35       5973     New Zealand tour of United Arab Emirates, 2023  United Arab Emirates  Internatonal  2023-08-17
36       6955            Germany v Guernsey in Netherlands, 2023           Netherlands  Internatonal  2023-08-14
37       6948                                  Budapest Cup 2023               Unknown  Internatonal  2023-08-05
38       6687       ICC Mens T20 World Cup Asia Qualifier B 2023               Unknown           T20  2023-07-26
39       6340  ICC Mens T20 World Cup East Asia Pacific Quali...               Unknown           T20  2023-07-22
40       6333       ICC Mens T20 World Cup Europe Qualifier 2023               Unknown           T20  2023-07-20
41       6752                                  Valletta Cup 2023               Unknown  Internatonal  2023-07-12
42       6582                    India tour of West Indies, 2023           West Indies  Internatonal  2023-07-12
43       6652                   Pakistan tour of Sri Lanka, 2023             Sri Lanka  Internatonal  2023-07-11
44       6759                                     Mdina Cup 2023            a Cup 2023  Internatonal  2023-07-10
45       6683                  Austria tour of Isle of Man, 2023           Isle of Man  Internatonal  2023-07-09
46       6676                Inter-Insular Mens T20I Series 2023               Unknown           T20  2023-07-07
47       6669             Austria v Germany in Netherlands, 2023           Netherlands  Internatonal  2023-06-29
48       6666               Switzerland tour of Luxembourg, 2023            Luxembourg  Internatonal  2023-06-24
49       6659                  Bulgaria Quadrangular Series 2023               Unknown  Internatonal  2023-06-23
50       6437              ICC Cricket World Cup Qualifiers 2023               Unknown  Internatonal  2023-06-18
51       4777                                    The Ashes, 2023               Unknown  Internatonal  2023-06-16
52       6351               Afghanistan tour of Bangladesh, 2023            Bangladesh  Internatonal  2023-06-14
53       6606                            Central Europe Cup 2023               Unknown  Internatonal  2023-06-10
54       6599                      Belgium tour of Germany, 2023               Germany  Internatonal  2023-06-09
55       6589                        Africa Continental Cup 2023        ental Cup 2023  Internatonal  2023-06-09
56       5917             ICC World Test Championship Final 2023               al 2023          Test  2023-06-07
57       6255                      West Indies tour of UAE, 2023                   UAE  Internatonal  2023-06-04
58       6248                Afghanistan tour of Sri Lanka, 2023             Sri Lanka  Internatonal  2023-06-02
59       6521                           Southern Africa Cup 2023               Unknown  Internatonal  2023-05-27
60       4786            Ireland tour of England Only Test, 2023     England Only Test          Test  2023-05-26
61       6235                               Nordic T20I Cup 2023               Unknown           T20  2023-05-18
62       6022              Ireland v Bangladesh in England, 2023               England  Internatonal  2023-05-09
63       6193                     Gibraltar T20I Tri-Series 2023               Unknown           T20  2023-05-04
64       6214   SEA Games Mens Twenty20 Cricket Competition 2023               Unknown  Internatonal  2023-05-01
65       5913                    Ireland tour of Sri Lanka, 2023             Sri Lanka  Internatonal  2023-04-16
66       4896                 New Zealand tour of Pakistan, 2023              Pakistan  Internatonal  2023-04-14
67       6155                   Gibraltar tour of Portugal, 2023              Portugal  Internatonal  2023-04-10
68       4861             Netherlands tour of South Africa, 2023          South Africa  Internatonal  2023-03-28
69       6025      ICC Cricket World Cup Qualifier Play-off 2023               Unknown  Internatonal  2023-03-26
70       5987                Afghanistan v Pakistan in UAE, 2023                   UAE  Internatonal  2023-03-24
71       5980                 Netherlands tour of Zimbabwe, 2023              Zimbabwe  Internatonal  2023-03-21
72       5490                   Ireland tour of Bangladesh, 2023            Bangladesh  Internatonal  2023-03-15
73       5966                 Hong Kong Quadrangular Series 2023               Unknown  Internatonal  2023-03-08
74       4415                   Sri Lanka tour New Zealand, 2023               Unknown  Internatonal  2023-03-04
75       5276                   England tour of Bangladesh, 2023            Bangladesh  Internatonal  2023-03-01
76       5959     ICC Mens T20 World Cup Americas Qualifier 2023               Unknown           T20  2023-02-25
77       5847                    Isle of Man tour of Spain, 2023                 Spain  Internatonal  2023-02-24
78       5952                    Bermuda tour of Argentina, 2023             Argentina  Internatonal  2023-02-21
79       4854             West Indies tour of South Africa, 2023          South Africa  Internatonal  2023-02-21
80       5896     Afghanistan tour of United Arab Emirates, 2023  United Arab Emirates  Internatonal  2023-02-16
81       5204                      Australia tour of India, 2023                 India  Internatonal  2023-02-09
82       4413                  England tour of New Zealand, 2023           New Zealand  Internatonal  2023-02-08
83       5260                 West Indies tour of Zimbabwe, 2023              Zimbabwe  Internatonal  2023-01-28
84       4847                 England tour of South Africa, 2023          South Africa  Internatonal  2023-01-27
85       5199                    New Zealand tour of India, 2023                 India  Internatonal  2023-01-18
86       5213                     Ireland tour of Zimbabwe, 2023              Zimbabwe  Internatonal  2023-01-12

In [147]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/series/v1/5204"

headers = {
	"x-rapidapi-key": "e6021fb984msh201af5139a6e2e9p149939jsn32edaa5716a4",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

ser_5204 = response.json()

In [149]:
ser_5204

{'matchDetails': [{'matchDetailsMap': {'key': 'Thu, 09 Feb 2023 - Mon, 13 Feb 2023',
    'match': [{'matchInfo': {'matchId': 60009,
       'seriesId': 5204,
       'seriesName': 'Australia tour of India, 2023',
       'matchDesc': '1st Test',
       'matchFormat': 'TEST',
       'startDate': '1675915200000',
       'endDate': '1676260800000',
       'state': 'complete',
       'status': 'India won by an innings and 132 runs',
       'team1': {'teamId': 2,
        'teamName': 'INDIA',
        'teamSName': 'IND',
        'imageId': 776162},
       'team2': {'teamId': 4,
        'teamName': 'AUSTRALIA',
        'teamSName': 'AUS',
        'imageId': 776202},
       'venueInfo': {'ground': 'Vidarbha Cricket Association Stadium',
        'city': 'Nagpur',
        'timezone': '+05:30'},
       'currBatTeamId': 2,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 400,
         'wickets': 10,
         'overs': 139.3}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 177,
         'wickets': 10,
         'overs': 63.5},
        'inngs2': {'inningsId': 3,
         'runs': 91,
         'wickets': 10,
         'overs': 32.3}}}}],
    'seriesId': 5204}},
  {'adDetail': {'name': 'native_news_index_random_1',
    'layout': 'native_large',
    'position': 1}},
  {'matchDetailsMap': {'key': 'Fri, 17 Feb 2023 - Tue, 21 Feb 2023',
    'match': [{'matchInfo': {'matchId': 60016,
       'seriesId': 5204,
       'seriesName': 'Australia tour of India, 2023',
       'matchDesc': '2nd Test',
       'matchFormat': 'TEST',
       'startDate': '1676606400000',
       'endDate': '1676952000000',
       'state': 'complete',
       'status': 'India won by 6 wkts',
       'team1': {'teamId': 2,
        'teamName': 'INDIA',
        'teamSName': 'IND',
        'imageId': 776162},
       'team2': {'teamId': 4,
        'teamName': 'AUSTRALIA',
        'teamSName': 'AUS',
        'imageId': 776202},
       'venueInfo': {'ground': 'Arun Jaitley Stadium',
        'city': 'Delhi',
        'timezone': '+05:30'},
       'currBatTeamId': 2,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 262,
         'wickets': 10,
         'overs': 83.3},
        'inngs2': {'inningsId': 4, 'runs': 118, 'wickets': 4, 'overs': 26.4}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 263,
         'wickets': 10,
         'overs': 78.4},
        'inngs2': {'inningsId': 3,
         'runs': 113,
         'wickets': 10,
         'overs': 31.1}}}}],
    'seriesId': 5204}},
  {'matchDetailsMap': {'key': 'Wed, 01 Mar 2023 - Sun, 05 Mar 2023',
    'match': [{'matchInfo': {'matchId': 60023,
       'seriesId': 5204,
       'seriesName': 'Australia tour of India, 2023',
       'matchDesc': '3rd Test',
       'matchFormat': 'TEST',
       'startDate': '1677643200000',
       'endDate': '1677988800000',
       'state': 'complete',
       'status': 'Australia won by 9 wkts',
       'team1': {'teamId': 2,
        'teamName': 'INDIA',
        'teamSName': 'IND',
        'imageId': 776162},
       'team2': {'teamId': 4,
        'teamName': 'AUSTRALIA',
        'teamSName': 'AUS',
        'imageId': 776202},
       'venueInfo': {'ground': 'Holkar Stadium',
        'city': 'Indore',
        'timezone': '+05:30'},
       'currBatTeamId': 4,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 109,
         'wickets': 10,
         'overs': 33.2},
        'inngs2': {'inningsId': 3, 'runs': 163, 'wickets': 10, 'overs': 60.3}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 197,
         'wickets': 10,
         'overs': 76.3},
        'inngs2': {'inningsId': 4,
         'runs': 78,
         'wickets': 1,
         'overs': 18.5}}}}],
    'seriesId': 5204}},
  {'matchDetailsMap': {'key': 'Thu, 09 Mar 2023 - Mon, 13 Mar 2023',
    'match': [{'matchInfo': {'matchId': 60028,
       'seriesId': 5204,
       'seriesName': 'Australia tour of India, 2023',
       'matchDesc': '4th Test',
       'matchFormat': 'TEST',
       'startDate': '1678334400000',
       'endDate': '1678680000000',
       'state': 'complete',
       'status': 'Match drawn',
       'team1': {'teamId': 2,
        'teamName': 'INDIA',
        'teamSName': 'IND',
        'imageId': 776162},
       'team2': {'teamId': 4,
        'teamName': 'AUSTRALIA',
        'teamSName': 'AUS',
        'imageId': 776202},
       'venueInfo': {'ground': 'Narendra Modi Stadium',
        'city': 'Ahmedabad',
        'timezone': '+05:30'},
       'currBatTeamId': 4,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 571,
         'wickets': 10,
         'overs': 178.5}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 480,
         'wickets': 10,
         'overs': 167.2},
        'inngs2': {'inningsId': 3,
         'runs': 175,
         'wickets': 2,
         'overs': 78.1,
         'isDeclared': True}}}}],
    'seriesId': 5204}},
  {'matchDetailsMap': {'key': 'Fri, 17 Mar 2023',
    'match': [{'matchInfo': {'matchId': 60035,
       'seriesId': 5204,
       'seriesName': 'Australia tour of India, 2023',
       'matchDesc': '1st ODI',
       'matchFormat': 'ODI',
       'startDate': '1679040000000',
       'endDate': '1679040000000',
       'state': 'complete',
       'status': 'India won by 5 wkts',
       'team1': {'teamId': 2,
        'teamName': 'INDIA',
        'teamSName': 'IND',
        'imageId': 776162},
       'team2': {'teamId': 4,
        'teamName': 'AUSTRALIA',
        'teamSName': 'AUS',
        'imageId': 776202},
       'venueInfo': {'ground': 'Wankhede Stadium',
        'city': 'Mumbai',
        'timezone': '+05:30'},
       'currBatTeamId': 2,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 191,
         'wickets': 5,
         'overs': 39.5}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 188,
         'wickets': 10,
         'overs': 35.4}}}}],
    'seriesId': 5204}},
  {'matchDetailsMap': {'key': 'Sun, 19 Mar 2023',
    'match': [{'matchInfo': {'matchId': 60037,
       'seriesId': 5204,
       'seriesName': 'Australia tour of India, 2023',
       'matchDesc': '2nd ODI',
       'matchFormat': 'ODI',
       'startDate': '1679212800000',
       'endDate': '1679212800000',
       'state': 'complete',
       'status': 'Australia won by 10 wkts',
       'team1': {'teamId': 2,
        'teamName': 'INDIA',
        'teamSName': 'IND',
        'imageId': 776162},
       'team2': {'teamId': 4,
        'teamName': 'AUSTRALIA',
        'teamSName': 'AUS',
        'imageId': 776202},
       'venueInfo': {'ground': 'ACA-VDCA Cricket Stadium',
        'city': 'Visakhapatnam',
        'timezone': '+05:30'},
       'currBatTeamId': 4,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 117,
         'wickets': 10,
         'overs': 26.0}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 121,
         'overs': 11.0}}}}],
    'seriesId': 5204}},
  {'matchDetailsMap': {'key': 'Wed, 22 Mar 2023',
    'match': [{'matchInfo': {'matchId': 60042,
       'seriesId': 5204,
       'seriesName': 'Australia tour of India, 2023',
       'matchDesc': '3rd ODI',
       'matchFormat': 'ODI',
       'startDate': '1679472000000',
       'endDate': '1679472000000',
       'state': 'complete',
       'status': 'Australia won by 21 runs',
       'team1': {'teamId': 2,
        'teamName': 'INDIA',
        'teamSName': 'IND',
        'imageId': 776162},
       'team2': {'teamId': 4,
        'teamName': 'AUSTRALIA',
        'teamSName': 'AUS',
        'imageId': 776202},
       'venueInfo': {'ground': 'MA Chidambaram Stadium',
        'city': 'Chennai',
        'timezone': '+05:30'},
       'currBatTeamId': 4,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 248,
         'wickets': 10,
         'overs': 49.1}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 269,
         'wickets': 10,
         'overs': 49.0}}}}],
    'seriesId': 5204}}],
 'appIndex': {'seoTitle': 'Australia tour of India, 2023 live scores, schedule and results - Cricbuzz | Cricbuzz.com',
  'webURL': 'www.cricbuzz.com/cricket-series/'}}

In [150]:
import pandas as pd
from datetime import datetime

series_aus_23 = []

for item in ser_5204['matchDetails']:
    
    match_map = item.get('matchDetailsMap', {})
    
    for m in match_map.get('match', []):
        
        info = m.get('matchInfo', {})
        
        match_id = info.get('matchId')
        series_name = info.get('seriesName')
        match_desc = info.get('matchDesc')
        match_format = info.get('matchFormat')
        
        team1 = info.get('team1', {}).get('teamName')
        team2 = info.get('team2', {}).get('teamName')
        
        venue = info.get('venueInfo', {}).get('ground')
        city = info.get('venueInfo', {}).get('city')
        
        start_date = datetime.fromtimestamp(
            int(info.get('startDate'))/1000
        ).strftime('%Y-%m-%d')
        
        status = info.get('status')
        
        series_aus_23.append({
            "Match ID": match_id,
            "Series": series_name,
            "Match": match_desc,
            "Format": match_format,
            "Team1": team1,
            "Team2": team2,
            "Venue": venue,
            "City": city,
            "Start Date": start_date,
            "Result": status
        })

df_series_aus23 = pd.DataFrame(series_aus_23)

df_series_aus23.head()

   Match ID                         Series     Match Format  Team1      Team2                                 Venue       City  Start Date                                Result
0     60009  Australia tour of India, 2023  1st Test   TEST  INDIA  AUSTRALIA  Vidarbha Cricket Association Stadium     Nagpur  2023-02-09  India won by an innings and 132 runs
1     60016  Australia tour of India, 2023  2nd Test   TEST  INDIA  AUSTRALIA                  Arun Jaitley Stadium      Delhi  2023-02-17                   India won by 6 wkts
2     60023  Australia tour of India, 2023  3rd Test   TEST  INDIA  AUSTRALIA                        Holkar Stadium     Indore  2023-03-01               Australia won by 9 wkts
3     60028  Australia tour of India, 2023  4th Test   TEST  INDIA  AUSTRALIA                 Narendra Modi Stadium  Ahmedabad  2023-03-09                           Match drawn
4     60035  Australia tour of India, 2023   1st ODI    ODI  INDIA  AUSTRALIA                      Wankhede Stadium     Mumbai  2023-03-17                   India won by 5 wkts

# 2023 match id = 75542

In [109]:
match_idq22 = [100301,75542,100310,100312,100321,100328,78635,78642,100283,100290,78628,100292,60009,60016,60023,60028,60035
]

In [164]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/60035"

headers = {
	"x-rapidapi-key": "e6021fb984msh201af5139a6e2e9p149939jsn32edaa5716a4",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

q22_75542=response.json()

In [109]:
q22_75542

{'matchid': 100301,
 'seriesid': 8402,
 'seriesname': 'England tour of India, 2025',
 'matchdesc': '4th T20I',
 'matchformat': 'T20',
 'startdate': 1738330200000,
 'enddate': 1738342966059,
 'state': 'Complete',
 'status': 'England opt to bowl',
 'team1': {'teamid': 2,
  'teamname': 'India',
  'teamsname': 'IND',
  'isfullmember': False,
  'isassociated': False,
  'isleagueteam': False,
  'iswomenteam': False,
  'isheader': False,
  'isactive': False,
  'teampriority': '',
  'isvideopresent': False,
  'imageid': 0,
  'countryname': '',
  'belongsto': '',
  'teamcolor': ''},
 'team2': {'teamid': 9,
  'teamname': 'England',
  'teamsname': 'ENG',
  'isfullmember': False,
  'isassociated': False,
  'isleagueteam': False,
  'iswomenteam': False,
  'isheader': False,
  'isactive': False,
  'teampriority': '',
  'isvideopresent': False,
  'imageid': 0,
  'countryname': '',
  'belongsto': '',
  'teamcolor': ''},
 'umpire1': {'id': 8905, 'name': 'Jayaraman Madanagopal', 'country': 'IND'},
 'umpire2': {'id': 8862, 'name': 'Nitin Menon', 'country': 'IND'},
 'umpire3': {'id': 8909, 'name': 'Virender Sharma', 'country': 'IND'},
 'referee': {'id': 3894, 'name': 'Javagal Srinath', 'country': 'IND'},
 'venueinfo': {'id': 287,
  'ground': 'Maharashtra Cricket Association Stadium',
  'city': 'Pune',
  'country': 'India',
  'timezone': '+05:30',
  'established': 2011,
  'capacity': '',
  'knownas': '',
  'ends': '',
  'hometeam': '',
  'floodlights': False,
  'curator': '',
  'profile': '',
  'imageurl': '',
  'groundlength': 0.0,
  'groundwidth': 0.0,
  'othersports': '',
  'imageid': 0,
  'latitude': '',
  'longitude': ''},
 'currbatteamid': 0,
 'ismatchnotcovered': False,
 'appindex': {'seotitle': 'Cricket match facts IND vs ENG 4th T20I,England tour of India, 2025 | Cricbuzz.com',
  'weburl': 'http://www.cricbuzz.com/cricket-match-facts/100301/ind-vs-eng-4th-t20i-england-tour-of-india-2025'},
 'istournament': False,
 'tossstatus': 'England opt to bowl',
 'seriesstartdt': 1737417600000,
 'seriesenddt': 1739404800000,
 'istimeannounced': False,
 'statetitle': '',
 'replacematchid': 0,
 'livestreamenabled': False,
 'isfantasyenabled': True,
 'broadcastinfo': [{'country': 'IN',
   'broadcaster': [{'broadcasttype': 'Streaming', 'value': 'JioHotstar'},
    {'broadcasttype': 'TV',
     'value': 'Star Sports Network,Sports 18 Network'}]}],
 'daynight': False,
 'matchtype': 'International',
 'seriestype': '',
 'shortstatus': 'IND won',
 'boundarytrackervalues': {'boundarytrackervalue': []},
 'matchimageid': 607125,
 'islivestreamenabled': False,
 'isfantasyhandbookenabled': False,
 'isforecastenabled': False,
 'ispollenabled': False}

In [104]:
# type_match=data['typeMatches']
# # print(type_match[0])
# series_matches = type_match[0]['seriesMatches']
# # print(series_matches[0])# Access series ad wrapper inside
# series_wrapper = series_matches[0]['seriesAdWrapper']
# # print(series_wrapper.keys())

In [165]:
import pandas as pd

# Extracting the key fields from your response object
match_info = {
    'match_id': q22_75542.get('matchid'),
    'series': q22_75542.get('seriesname'),
    'team1': q22_75542.get('team1', {}).get('teamname'),
    'team2': q22_75542.get('team2', {}).get('teamname'),
    'venue': q22_75542.get('venueinfo', {}).get('ground'),
    'city': q22_75542.get('venueinfo', {}).get('city'),
    'toss': q22_75542.get('tossstatus'),
    'result_short': q22_75542.get('shortstatus')
}

# Create a temporary DataFrame for this match
df_temp = pd.DataFrame([match_info])

# Logic for "Winner" and "Batting First"
# If 'England opt to bowl', then India (team1) batted first.
df_temp['winner'] = df_temp['team1'] if "IND won" in str(df_temp['result_short'].values) else df_temp['team2']
df_temp['bat_first'] = df_temp['team1'] if "opt to bowl" in str(df_temp['toss'].values).lower() and "england" in str(df_temp['toss'].values).lower() else df_temp['team2']

print(df_temp)

   match_id                         series  team1      team2             venue    city               toss result_short winner  bat_first
0     60035  Australia tour of India, 2023  India  Australia  Wankhede Stadium  Mumbai  India opt to bowl      IND won  India  Australia

In [115]:
df_temp

   match_id                      series  team1    team2                                              venue     city                 toss result_short winner bat_first
0     75542  ICC Cricket World Cup 2023  India  England  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...  Lucknow  England opt to bowl      IND won  India     India

In [166]:
import urllib.parse
from sqlalchemy import create_engine

# 1. Encode the special character in password
password = urllib.parse.quote_plus("deepika@88")

# 2. Use the encoded password in your connection string
# Also, ensure 'username' is replaced with your actual DB user (usually 'postgres')
engine = create_engine(f'postgresql+psycopg2://postgres:{password}@localhost:5432/cricbuzz')

# 3. Test the connection and push the data
df_temp.to_sql('q22_test', engine, if_exists='append', index=False)

print("✅ Connection successful and table 'players_india' created!")

✅ Connection successful and table 'players_india' created!

# Q22 match

In [ ]:
100301,75542,100310,100312,100321,100328,78635,78642,100283,100290,78628,100292,60009,60016,60023,60028,60035

Total wins

In [178]:
import requests
import pandas as pd

headers = {
    "x-rapidapi-key": "e6021fb984msh201af5139a6e2e9p149939jsn32edaa5716a4",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

all_matches = []

for match_id in match_idq22:
    url = f"https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/{match_id}/scard"
    
    response = requests.get(url, headers=headers)
    data = response.json()
    
    all_matches.append(data)

print("Total matches fetched:", len(all_matches))

Total matches fetched: 17

In [182]:
import pandas as pd
import re

records = []

for i, match in enumerate(all_matches):

    match_id = match_idq22[i]   # get match id from your list
    
    team1 = match['scorecard'][0]['batteamname']
    team2 = match['scorecard'][1]['batteamname']

    score1 = match['scorecard'][0]['score']
    score2 = match['scorecard'][1]['score']

    status = match['status']

    # winner
    winner = status.split(" won")[0]

    # margin
    margin = re.findall(r'\d+', status)
    margin = int(margin[0]) if margin else None

    bat_first = team1

    records.append({
        "match_id": match_id,
        "team1": team1,
        "team2": team2,
        "bat_first": bat_first,
        "score1": score1,
        "score2": score2,
        "winner": winner,
        "margin": margin
    })

df = pd.DataFrame(records)

print(df)

    match_id      team1      team2  bat_first  score1  score2       winner  margin
0     100301      India    England      India     181     166        India    15.0
1      75542      India    England      India     229     129        India   100.0
2     100310      India    England      India     247      97        India   150.0
3     100312    England      India    England     248     251        India     4.0
4     100321    England      India    England     304     308        India     4.0
5     100328      India    England      India     356     214        India   142.0
6      78635      India    England      India     396     253        India   106.0
7      78642      India    England      India     445     319        India   434.0
8     100283    England      India    England     132     133        India     7.0
9     100290    England      India    England     165     166        India     2.0
10     78628    England      India    England     246     436      England    28.0
11    100292    England      India    England     171     145      England    26.0
12     60009  Australia      India  Australia     177     400        India   132.0
13     60016  Australia      India  Australia     263     262        India     6.0
14     60023      India  Australia      India     109     197    Australia     9.0
15     60028  Australia      India  Australia     480     571  Match drawn     NaN
16     60035  Australia      India  Australia     188     191        India     5.0

In [183]:
import urllib.parse
from sqlalchemy import create_engine

# 1. Encode the special character in password
password = urllib.parse.quote_plus("deepika@88")

# 2. Use the encoded password in your connection string
# Also, ensure 'username' is replaced with your actual DB user (usually 'postgres')
engine = create_engine(f'postgresql+psycopg2://postgres:{password}@localhost:5432/cricbuzz')

# 3. Test the connection and push the data
df.to_sql('q22_final', engine, if_exists='replace', index=False)

print("✅ Connection successful and table 'players_india' created!")

✅ Connection successful and table 'players_india' created!

# Q 23 analysis

In [187]:
import requests
import pandas as pd

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/trending"

headers = {
	"x-rapidapi-key": "e6021fb984msh201af5139a6e2e9p149939jsn32edaa5716a4",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)
fameplayer = response.json()

In [202]:
fameplayer

{'player': [{'id': '41330',
   'name': 'Alan Kirschbaum',
   'teamName': 'Argentina',
   'faceImageId': 182026},
  {'id': '10154',
   'name': 'Asela Gunaratne',
   'teamName': 'Sri Lanka',
   'faceImageId': 155855},
  {'id': '21823',
   'name': 'Sacha De Alwis',
   'teamName': 'Cayman Islands',
   'faceImageId': 182026},
  {'id': '37581',
   'name': 'Nahid Rana',
   'teamName': 'Bangladesh',
   'faceImageId': 616465},
  {'id': '15350',
   'name': 'Boemo Khumalo',
   'teamName': 'Botswana',
   'faceImageId': 182026},
  {'id': '29552',
   'name': 'Imran Khan',
   'teamName': 'Bahrain',
   'faceImageId': 182026},
  {'id': '1452215',
   'name': 'Romario Edwards',
   'teamName': 'Cayman Islands',
   'faceImageId': 182026},
  {'id': '15351',
   'name': 'Dhruvkumar Maisuria',
   'teamName': 'Botswana',
   'faceImageId': 182026},
  {'id': '41312',
   'name': 'Pedro Baron',
   'teamName': 'Argentina',
   'faceImageId': 182026},
  {'id': '24827',
   'name': 'Conroy Wright',
   'teamName': 'Cayman Islands',
   'faceImageId': 182026}],
 'category': 'TRENDING SEARCHES'}

In [197]:
# Corrected code to extract player IDs from the 'fameplayer' JSON response
# Assuming 'fameplayer' is the JSON response from the trending players API

# Based on the API structure, player data is typically under 'values' as a list of dicts
player_ids = [player['id'] for player in fameplayer.get('values', [])]

# If 'player' is a single dict (as in your code), you can access its 'id' directly
# But from the context, 'values' is the list. If 'player' exists and is a dict:
# p_id = fameplayer['player']['id']

# However, to handle it safely and get all IDs if it's a list:
if 'values' in fameplayer:
    player_ids = [player['id'] for player in fameplayer['values']]
elif 'player' in fameplayer and isinstance(fameplayer['player'], list):
    player_ids = [player['id'] for player in fameplayer['player']]
elif 'player' in fameplayer and isinstance(fameplayer['player'], dict):
    player_ids = [fameplayer['player']['id']]
else:
    player_ids = []

print(player_ids)

['41330', '10154', '21823', '37581', '15350', '29552', '1452215', '15351', '41312', '24827']

In [198]:
player_ids

['41330',
 '10154',
 '21823',
 '37581',
 '15350',
 '29552',
 '1452215',
 '15351',
 '41312',
 '24827']

In [200]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/41330/batting"

headers = {
	"x-rapidapi-key": "e6021fb984msh201af5139a6e2e9p149939jsn32edaa5716a4",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com",
	"Content-Type": "application/json"
}

response = requests.get(url, headers=headers)

x41330= response.json()

In [201]:
x41330

{'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'],
 'values': [{'values': ['Matches', '0', '0', '26', '0']},
  {'values': ['Innings', '0', '0', '25', '0']},
  {'values': ['Runs', '0', '0', '298', '0']},
  {'values': ['Balls', '0', '0', '330', '0']},
  {'values': ['Highest', '0', '0', '35', '0']},
  {'values': ['Average', '0', '0', '14.19', '0']},
  {'values': ['SR', '0', '0', '90.31', '0']},
  {'values': ['Not Out', '0', '0', '4', '0']},
  {'values': ['Fours', '0', '0', '21', '0']},
  {'values': ['Sixes', '0', '0', '3', '0']},
  {'values': ['Ducks', '0', '0', '2', '0']},
  {'values': ['50s', '0', '0', '0', '0']},
  {'values': ['100s', '0', '0', '0', '0']},
  {'values': ['200s', '0', '0', '0', '0']},
  {'values': ['300s', '0', '0', '0', '0']},
  {'values': ['400s', '0', '0', '0', '0']}],
 'appIndex': {'seoTitle': 'Alan Kirschbaum Profile - Cricbuzz | Cricbuzz.com',
  'webURL': 'http://www.cricbuzz.com/profiles/41330/alan-kirschbaum'},
 'seriesSpinner': [{'seriesName': 'Career'},
  {'seriesId': 11570,
   'seriesName': "ICC Men's T20 2028 World Cup Americas Sub Regional Qualifier B, 2026"}]}

In [237]:
import requests
import pandas as pd

player_ids = [
    '41330','9647','21823','37581','15350',
    '29552','1452215','15351','41312','24827'
]

headers = {
    "x-rapidapi-key": "095038d962msh9068af945c80bc9p1ad37cjsna03b2a42de54",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

all_bat2_info = []

for pid in player_ids:

    url = f"https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/{pid}/batting"

    response = requests.get(url, headers=headers)
    data = response.json()

    all_bat2.append(data)

print(all_bat2)

[{'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'], 'values': [{'values': ['Matches', '0', '0', '26', '0']}, {'values': ['Innings', '0', '0', '25', '0']}, {'values': ['Runs', '0', '0', '298', '0']}, {'values': ['Balls', '0', '0', '330', '0']}, {'values': ['Highest', '0', '0', '35', '0']}, {'values': ['Average', '0', '0', '14.19', '0']}, {'values': ['SR', '0', '0', '90.31', '0']}, {'values': ['Not Out', '0', '0', '4', '0']}, {'values': ['Fours', '0', '0', '21', '0']}, {'values': ['Sixes', '0', '0', '3', '0']}, {'values': ['Ducks', '0', '0', '2', '0']}, {'values': ['50s', '0', '0', '0', '0']}, {'values': ['100s', '0', '0', '0', '0']}, {'values': ['200s', '0', '0', '0', '0']}, {'values': ['300s', '0', '0', '0', '0']}, {'values': ['400s', '0', '0', '0', '0']}], 'appIndex': {'seoTitle': 'Alan Kirschbaum Profile - Cricbuzz | Cricbuzz.com', 'webURL': 'http://www.cricbuzz.com/profiles/41330/alan-kirschbaum'}, 'seriesSpinner': [{'seriesName': 'Career'}, {'seriesId': 11570, 'seriesName': "ICC Men's T20 2028 World Cup Americas Sub Regional Qualifier B, 2026"}]}, {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'], 'values': [{'values': ['Matches', '6', '31', '12', '0']}, {'values': ['Innings', '10', '25', '12', '0']}, {'values': ['Runs', '455', '575', '225', '0']}, {'values': ['Balls', '861', '724', '178', '0']}, {'values': ['Highest', '116', '114', '84', '0']}, {'values': ['Average', '56.88', '27.38', '25', '0']}, {'values': ['SR', '52.85', '79.42', '126.41', '0']}, {'values': ['Not Out', '2', '4', '3', '0']}, {'values': ['Fours', '50', '50', '19', '0']}, {'values': ['Sixes', '1', '6', '6', '0']}, {'values': ['Ducks', '1', '0', '2', '0']}, {'values': ['50s', '3', '1', '2', '0']}, {'values': ['100s', '1', '1', '0', '0']}, {'values': ['200s', '0', '0', '0', '0']}, {'values': ['300s', '0', '0', '0', '0']}, {'values': ['400s', '0', '0', '0', '0']}], 'appIndex': {'seoTitle': 'Asela Gunaratne Profile - Cricbuzz | Cricbuzz.com', 'webURL': 'http://www.cricbuzz.com/profiles/10154/asela-gunaratne'}, 'seriesSpinner': [{'seriesName': 'Career'}, {'seriesId': 11671, 'seriesName': 'Legends League Cricket 2026'}]}, {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'], 'values': [{'values': ['Matches', '0', '0', '26', '0']}, {'values': ['Innings', '0', '0', '26', '0']}, {'values': ['Runs', '0', '0', '668', '0']}, {'values': ['Balls', '0', '0', '566', '0']}, {'values': ['Highest', '0', '0', '150', '0']}, {'values': ['Average', '0', '0', '33.4', '0']}, {'values': ['SR', '0', '0', '118.03', '0']}, {'values': ['Not Out', '0', '0', '6', '0']}, {'values': ['Fours', '0', '0', '52', '0']}, {'values': ['Sixes', '0', '0', '33', '0']}, {'values': ['Ducks', '0', '0', '1', '0']}, {'values': ['50s', '0', '0', '3', '0']}, {'values': ['100s', '0', '0', '1', '0']}, {'values': ['200s', '0', '0', '0', '0']}, {'values': ['300s', '0', '0', '0', '0']}, {'values': ['400s', '0', '0', '0', '0']}], 'appIndex': {'seoTitle': 'Sacha De Alwis Profile - Cricbuzz | Cricbuzz.com', 'webURL': 'http://www.cricbuzz.com/profiles/21823/sacha-de-alwis'}, 'seriesSpinner': [{'seriesName': 'Career'}, {'seriesId': 11570, 'seriesName': "ICC Men's T20 2028 World Cup Americas Sub Regional Qualifier B, 2026"}]}, {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'], 'values': [{'values': ['Matches', '10', '6', '1', '0']}, {'values': ['Innings', '16', '3', '0', '0']}, {'values': ['Runs', '17', '6', '0', '0']}, {'values': ['Balls', '88', '18', '0', '0']}, {'values': ['Highest', '11', '4', '0', '0']}, {'values': ['Average', '2.43', '0', '0', '0']}, {'values': ['SR', '19.32', '33.34', '0', '0']}, {'values': ['Not Out', '9', '3', '0', '0']}, {'values': ['Fours', '3', '1', '0', '0']}, {'values': ['Sixes', '0', '0', '0', '0']}, {'values': ['Ducks', '6', '0', '0', '0']}, {'values': ['50s', '0', '0', '0', '0']}, {'values': ['100s', '0', '0', '0', '0']}, {'values': ['200s', '0', '0', '0', '0']}, {'values': ['300s', '0', '0', '0', '0']}, {'values': ['400s', '0', '0', '0', '0']}], 'appIndex': {'seoTitle': 'Nahid Rana Profile - Cricbuzz | Cricbuzz.com', 'webURL': 'http://www.cricbuzz.com/profiles/37581/nahid-rana'}, 'seriesSpinner': [{'seriesName': 'Career'}, {'seriesId': 11584, 'seriesName': 'Pakistan tour of Bangladesh, 2026'}]}, {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'], 'values': [{'values': ['Matches', '0', '0', '30', '0']}, {'values': ['Innings', '0', '0', '9', '0']}, {'values': ['Runs', '0', '0', '26', '0']}, {'values': ['Balls', '0', '0', '39', '0']}, {'values': ['Highest', '0', '0', '10', '0']}, {'values': ['Average', '0', '0', '8.67', '0']}, {'values': ['SR', '0', '0', '66.67', '0']}, {'values': ['Not Out', '0', '0', '6', '0']}, {'values': ['Fours', '0', '0', '1', '0']}, {'values': ['Sixes', '0', '0', '0', '0']}, {'values': ['Ducks', '0', '0', '1', '0']}, {'values': ['50s', '0', '0', '0', '0']}, {'values': ['100s', '0', '0', '0', '0']}, {'values': ['200s', '0', '0', '0', '0']}, {'values': ['300s', '0', '0', '0', '0']}, {'values': ['400s', '0', '0', '0', '0']}], 'appIndex': {'seoTitle': 'Boemo Khumalo Profile - Cricbuzz | Cricbuzz.com', 'webURL': 'http://www.cricbuzz.com/profiles/15350/boemo-khumalo'}, 'seriesSpinner': [{'seriesName': 'Career'}, {'seriesId': 11711, 'seriesName': 'Lesotho tour of Botswana, 2026'}]}, {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'], 'values': [{'values': ['Matches', '0', '0', '58', '0']}, {'values': ['Innings', '0', '0', '14', '0']}, {'values': ['Runs', '0', '0', '15', '0']}, {'values': ['Balls', '0', '0', '28', '0']}, {'values': ['Highest', '0', '0', '3', '0']}, {'values': ['Average', '0', '0', '1.67', '0']}, {'values': ['SR', '0', '0', '53.58', '0']}, {'values': ['Not Out', '0', '0', '5', '0']}, {'values': ['Fours', '0', '0', '0', '0']}, {'values': ['Sixes', '0', '0', '0', '0']}, {'values': ['Ducks', '0', '0', '4', '0']}, {'values': ['50s', '0', '0', '0', '0']}, {'values': ['100s', '0', '0', '0', '0']}, {'values': ['200s', '0', '0', '0', '0']}, {'values': ['300s', '0', '0', '0', '0']}, {'values': ['400s', '0', '0', '0', '0']}], 'appIndex': {'seoTitle': 'Imran Khan Profile - Cricbuzz | Cricbuzz.com', 'webURL': 'http://www.cricbuzz.com/profiles/29552/imran-khan'}, 'seriesSpinner': [{'seriesName': 'Career'}]}, {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'], 'values': [{'values': ['Matches', '0', '0', '7', '0']}, {'values': ['Innings', '0', '0', '3', '0']}, {'values': ['Runs', '0', '0', '8', '0']}, {'values': ['Balls', '0', '0', '21', '0']}, {'values': ['Highest', '0', '0', '8', '0']}, {'values': ['Average', '0', '0', '4', '0']}, {'values': ['SR', '0', '0', '38.10', '0']}, {'values': ['Not Out', '0', '0', '1', '0']}, {'values': ['Fours', '0', '0', '0', '0']}, {'values': ['Sixes', '0', '0', '0', '0']}, {'values': ['Ducks', '0', '0', '2', '0']}, {'values': ['50s', '0', '0', '0', '0']}, {'values': ['100s', '0', '0', '0', '0']}, {'values': ['200s', '0', '0', '0', '0']}, {'values': ['300s', '0', '0', '0', '0']}, {'values': ['400s', '0', '0', '0', '0']}], 'appIndex': {'seoTitle': 'Romario Edwards Profile - Cricbuzz | Cricbuzz.com', 'webURL': 'http://www.cricbuzz.com/profiles/1452215/romario-edwards'}, 'seriesSpinner': [{'seriesName': 'Career'}, {'seriesId': 11570, 'seriesName': "ICC Men's T20 2028 World Cup Americas Sub Regional Qualifier B, 2026"}]}, {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'], 'values': [{'values': ['Matches', '0', '0', '43', '0']}, {'values': ['Innings', '0', '0', '18', '0']}, {'values': ['Runs', '0', '0', '90', '0']}, {'values': ['Balls', '0', '0', '129', '0']}, {'values': ['Highest', '0', '0', '32', '0']}, {'values': ['Average', '0', '0', '6', '0']}, {'values': ['SR', '0', '0', '69.77', '0']}, {'values': ['Not Out', '0', '0', '3', '0']}, {'values': ['Fours', '0', '0', '2', '0']}, {'values': ['Sixes', '0', '0', '2', '0']}, {'values': ['Ducks', '0', '0', '7', '0']}, {'values': ['50s', '0', '0', '0', '0']}, {'values': ['100s', '0', '0', '0', '0']}, {'values': ['200s', '0', '0', '0', '0']}, {'values': ['300s', '0', '0', '0', '0']}, {'values': ['400s', '0', '0', '0', '0']}], 'appIndex': {'seoTitle': 'Dhruvkumar Maisuria Profile - Cricbuzz | Cricbuzz.com', 'webURL': 'http://www.cricbuzz.com/profiles/15351/dhruvkumar-maisuria'}, 'seriesSpinner': [{'seriesName': 'Career'}, {'seriesId': 11711, 'seriesName': 'Lesotho tour of Botswana, 2026'}]}, {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'], 'values': [{'values': ['Matches', '0', '0', '26', '0']}, {'values': ['Innings', '0', '0', '31', '0']}, {'values': ['Runs', '0', '0', '693', '0']}, {'values': ['Balls', '0', '0', '653', '0']}, {'values': ['Highest', '0', '0', '73', '0']}, {'values': ['Average', '0', '0', '24.75', '0']}, {'values': ['SR', '0', '0', '106.13', '0']}, {'values': ['Not Out', '0', '0', '3', '0']}, {'values': ['Fours', '0', '0', '78', '0']}, {'values': ['Sixes', '0', '0', '6', '0']}, {'values': ['Ducks', '0', '0', '0', '0']}, {'values': ['50s', '0', '0', '6', '0']}, {'values': ['100s', '0', '0', '0', '0']}, {'values': ['200s', '0', '0', '0', '0']}, {'values': ['300s', '0', '0', '0', '0']}, {'values': ['400s', '0', '0', '0', '0']}], 'appIndex': {'seoTitle': 'Pedro Baron Profile - Cricbuzz | Cricbuzz.com', 'webURL': 'http://www.cricbuzz.com/profiles/41312/pedro-baron'}, 'seriesSpinner': [{'seriesName': 'Career'}, {'seriesId': 11570, 'seriesName': "ICC Men's T20 2028 World Cup Americas Sub Regional Qualifier B, 2026"}]}, {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'], 'values': [{'values': ['Matches', '0', '0', '41', '0']}, {'values': ['Innings', '0', '0', '28', '0']}, {'values': ['Runs', '0', '0', '242', '0']}, {'values': ['Balls', '0', '0', '245', '0']}, {'values': ['Highest', '0', '0', '50', '0']}, {'values': ['Average', '0', '0', '14.24', '0']}, {'values': ['SR', '0', '0', '98.78', '0']}, {'values': ['Not Out', '0', '0', '11', '0']}, {'values': ['Fours', '0', '0', '10', '0']}, {'values': ['Sixes', '0', '0', '9', '0']}, {'values': ['Ducks', '0', '0', '7', '0']}, {'values': ['50s', '0', '0', '1', '0']}, {'values': ['100s', '0', '0', '0', '0']}, {'values': ['200s', '0', '0', '0', '0']}, {'values': ['300s', '0', '0', '0', '0']}, {'values': ['400s', '0', '0', '0', '0']}], 'appIndex': {'seoTitle': 'Conroy Wright Profile - Cricbuzz | Cricbuzz.com', 'webURL': 'http://www.cricbuzz.com/profiles/24827/conroy-wright'}, 'seriesSpinner': [{'seriesName': 'Career'}, {'seriesId': 11570, 'seriesName': "ICC Men's T20 2028 World Cup Americas Sub Regional Qualifier B, 2026"}]}, {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'], 'values': [{'values': ['Matches', '0', '0', '26', '0']}, {'values': ['Innings', '0', '0', '25', '0']}, {'values': ['Runs', '0', '0', '298', '0']}, {'values': ['Balls', '0', '0', '330', '0']}, {'values': ['Highest', '0', '0', '35', '0']}, {'values': ['Average', '0', '0', '14.19', '0']}, {'values': ['SR', '0', '0', '90.31', '0']}, {'values': ['Not Out', '0', '0', '4', '0']}, {'values': ['Fours', '0', '0', '21', '0']}, {'values': ['Sixes', '0', '0', '3', '0']}, {'values': ['Ducks', '0', '0', '2', '0']}, {'values': ['50s', '0', '0', '0', '0']}, {'values': ['100s', '0', '0', '0', '0']}, {'values': ['200s', '0', '0', '0', '0']}, {'values': ['300s', '0', '0', '0', '0']}, {'values': ['400s', '0', '0', '0', '0']}], 'appIndex': {'seoTitle': 'Alan Kirschbaum Profile - Cricbuzz | Cricbuzz.com', 'webURL': 'http://www.cricbuzz.com/profiles/41330/alan-kirschbaum'}, 'seriesSpinner': [{'seriesName': 'Career'}, {'seriesId': 11570, 'seriesName': "ICC Men's T20 2028 World Cup Americas Sub Regional Qualifier B, 2026"}]}, {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'], 'values': [{'values': ['Matches', '11', '94', '138', '152']}, {'values': ['Innings', '18', '68', '109', '140']}, {'values': ['Runs', '532', '1904', '2288', '2749']}, {'values': ['Balls', '720', '1717', '1568', '1871']}, {'values': ['Highest', '108', '92', '71', '91']}, {'values': ['Average', '31.29', '32.83', '28.25', '28.34']}, {'values': ['SR', '73.89', '110.90', '145.92', '146.93']}, {'values': ['Not Out', '1', '10', '28', '43']}, {'values': ['Fours', '68', '141', '168', '207']}, {'values': ['Sixes', '12', '76', '126', '148']}, {'values': ['Ducks', '2', '4', '4', '6']}, {'values': ['50s', '4', '11', '9', '10']}, {'values': ['100s', '1', '0', '0', '0']}, {'values': ['200s', '0', '0', '0', '0']}, {'values': ['300s', '0', '0', '0', '0']}, {'values': ['400s', '0', '0', '0', '0']}], 'appIndex': {'seoTitle': 'Hardik Pandya Profile - Cricbuzz | Cricbuzz.com', 'webURL': 'http://www.cricbuzz.com/profiles/9647/hardik-pandya'}, 'seriesSpinner': [{'seriesName': 'Career'}]}, {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'], 'values': [{'values': ['Matches', '0', '0', '27', '0']}, {'values': ['Innings', '0', '0', '27', '0']}, {'values': ['Runs', '0', '0', '713', '0']}, {'values': ['Balls', '0', '0', '602', '0']}, {'values': ['Highest', '0', '0', '150', '0']}, {'values': ['Average', '0', '0', '33.95', '0']}, {'values': ['SR', '0', '0', '118.44', '0']}, {'values': ['Not Out', '0', '0', '6', '0']}, {'values': ['Fours', '0', '0', '57', '0']}, {'values': ['Sixes', '0', '0', '35', '0']}, {'values': ['Ducks', '0', '0', '1', '0']}, {'values': ['50s', '0', '0', '3', '0']}, {'values': ['100s', '0', '0', '1', '0']}, {'values': ['200s', '0', '0', '0', '0']}, {'values': ['300s', '0', '0', '0', '0']}, {'values': ['400s', '0', '0', '0', '0']}], 'appIndex': {'seoTitle': 'Sacha De Alwis Profile - Cricbuzz | Cricbuzz.com', 'webURL': 'http://www.cricbuzz.com/profiles/21823/sacha-de-alwis'}, 'seriesSpinner': [{'seriesName': 'Career'}, {'seriesId': 11570, 'seriesName': "ICC Men's T20 2028 World Cup Americas Sub Regional Qualifier B, 2026"}]}, {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'], 'values': [{'values': ['Matches', '10', '6', '1', '0']}, {'values': ['Innings', '16', '3', '0', '0']}, {'values': ['Runs', '17', '6', '0', '0']}, {'values': ['Balls', '88', '18', '0', '0']}, {'values': ['Highest', '11', '4', '0', '0']}, {'values': ['Average', '2.43', '0', '0', '0']}, {'values': ['SR', '19.32', '33.34', '0', '0']}, {'values': ['Not Out', '9', '3', '0', '0']}, {'values': ['Fours', '3', '1', '0', '0']}, {'values': ['Sixes', '0', '0', '0', '0']}, {'values': ['Ducks', '6', '0', '0', '0']}, {'values': ['50s', '0', '0', '0', '0']}, {'values': ['100s', '0', '0', '0', '0']}, {'values': ['200s', '0', '0', '0', '0']}, {'values': ['300s', '0', '0', '0', '0']}, {'values': ['400s', '0', '0', '0', '0']}], 'appIndex': {'seoTitle': 'Nahid Rana Profile - Cricbuzz | Cricbuzz.com', 'webURL': 'http://www.cricbuzz.com/profiles/37581/nahid-rana'}, 'seriesSpinner': [{'seriesName': 'Career'}, {'seriesId': 11584, 'seriesName': 'Pakistan tour of Bangladesh, 2026'}]}, {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'], 'values': [{'values': ['Matches', '0', '0', '31', '0']}, {'values': ['Innings', '0', '0', '10', '0']}, {'values': ['Runs', '0', '0', '31', '0']}, {'values': ['Balls', '0', '0', '46', '0']}, {'values': ['Highest', '0', '0', '10', '0']}, {'values': ['Average', '0', '0', '7.75', '0']}, {'values': ['SR', '0', '0', '67.40', '0']}, {'values': ['Not Out', '0', '0', '6', '0']}, {'values': ['Fours', '0', '0', '1', '0']}, {'values': ['Sixes', '0', '0', '0', '0']}, {'values': ['Ducks', '0', '0', '1', '0']}, {'values': ['50s', '0', '0', '0', '0']}, {'values': ['100s', '0', '0', '0', '0']}, {'values': ['200s', '0', '0', '0', '0']}, {'values': ['300s', '0', '0', '0', '0']}, {'values': ['400s', '0', '0', '0', '0']}], 'appIndex': {'seoTitle': 'Boemo Khumalo Profile - Cricbuzz | Cricbuzz.com', 'webURL': 'http://www.cricbuzz.com/profiles/15350/boemo-khumalo'}, 'seriesSpinner': [{'seriesName': 'Career'}, {'seriesId': 11711, 'seriesName': 'Lesotho tour of Botswana, 2026'}]}, {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'], 'values': [{'values': ['Matches', '0', '0', '58', '0']}, {'values': ['Innings', '0', '0', '14', '0']}, {'values': ['Runs', '0', '0', '15', '0']}, {'values': ['Balls', '0', '0', '28', '0']}, {'values': ['Highest', '0', '0', '3', '0']}, {'values': ['Average', '0', '0', '1.67', '0']}, {'values': ['SR', '0', '0', '53.58', '0']}, {'values': ['Not Out', '0', '0', '5', '0']}, {'values': ['Fours', '0', '0', '0', '0']}, {'values': ['Sixes', '0', '0', '0', '0']}, {'values': ['Ducks', '0', '0', '4', '0']}, {'values': ['50s', '0', '0', '0', '0']}, {'values': ['100s', '0', '0', '0', '0']}, {'values': ['200s', '0', '0', '0', '0']}, {'values': ['300s', '0', '0', '0', '0']}, {'values': ['400s', '0', '0', '0', '0']}], 'appIndex': {'seoTitle': 'Imran Khan Profile - Cricbuzz | Cricbuzz.com', 'webURL': 'http://www.cricbuzz.com/profiles/29552/imran-khan'}, 'seriesSpinner': [{'seriesName': 'Career'}]}, {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'], 'values': [{'values': ['Matches', '0', '0', '8', '0']}, {'values': ['Innings', '0', '0', '3', '0']}, {'values': ['Runs', '0', '0', '8', '0']}, {'values': ['Balls', '0', '0', '21', '0']}, {'values': ['Highest', '0', '0', '8', '0']}, {'values': ['Average', '0', '0', '4', '0']}, {'values': ['SR', '0', '0', '38.10', '0']}, {'values': ['Not Out', '0', '0', '1', '0']}, {'values': ['Fours', '0', '0', '0', '0']}, {'values': ['Sixes', '0', '0', '0', '0']}, {'values': ['Ducks', '0', '0', '2', '0']}, {'values': ['50s', '0', '0', '0', '0']}, {'values': ['100s', '0', '0', '0', '0']}, {'values': ['200s', '0', '0', '0', '0']}, {'values': ['300s', '0', '0', '0', '0']}, {'values': ['400s', '0', '0', '0', '0']}], 'appIndex': {'seoTitle': 'Romario Edwards Profile - Cricbuzz | Cricbuzz.com', 'webURL': 'http://www.cricbuzz.com/profiles/1452215/romario-edwards'}, 'seriesSpinner': [{'seriesName': 'Career'}, {'seriesId': 11570, 'seriesName': "ICC Men's T20 2028 World Cup Americas Sub Regional Qualifier B, 2026"}]}, {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'], 'values': [{'values': ['Matches', '0', '0', '44', '0']}, {'values': ['Innings', '0', '0', '19', '0']}, {'values': ['Runs', '0', '0', '95', '0']}, {'values': ['Balls', '0', '0', '139', '0']}, {'values': ['Highest', '0', '0', '32', '0']}, {'values': ['Average', '0', '0', '5.94', '0']}, {'values': ['SR', '0', '0', '68.35', '0']}, {'values': ['Not Out', '0', '0', '3', '0']}, {'values': ['Fours', '0', '0', '2', '0']}, {'values': ['Sixes', '0', '0', '2', '0']}, {'values': ['Ducks', '0', '0', '7', '0']}, {'values': ['50s', '0', '0', '0', '0']}, {'values': ['100s', '0', '0', '0', '0']}, {'values': ['200s', '0', '0', '0', '0']}, {'values': ['300s', '0', '0', '0', '0']}, {'values': ['400s', '0', '0', '0', '0']}], 'appIndex': {'seoTitle': 'Dhruvkumar Maisuria Profile - Cricbuzz | Cricbuzz.com', 'webURL': 'http://www.cricbuzz.com/profiles/15351/dhruvkumar-maisuria'}, 'seriesSpinner': [{'seriesName': 'Career'}, {'seriesId': 11711, 'seriesName': 'Lesotho tour of Botswana, 2026'}]}, {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'], 'values': [{'values': ['Matches', '0', '0', '26', '0']}, {'values': ['Innings', '0', '0', '31', '0']}, {'values': ['Runs', '0', '0', '693', '0']}, {'values': ['Balls', '0', '0', '653', '0']}, {'values': ['Highest', '0', '0', '73', '0']}, {'values': ['Average', '0', '0', '24.75', '0']}, {'values': ['SR', '0', '0', '106.13', '0']}, {'values': ['Not Out', '0', '0', '3', '0']}, {'values': ['Fours', '0', '0', '78', '0']}, {'values': ['Sixes', '0', '0', '6', '0']}, {'values': ['Ducks', '0', '0', '0', '0']}, {'values': ['50s', '0', '0', '6', '0']}, {'values': ['100s', '0', '0', '0', '0']}, {'values': ['200s', '0', '0', '0', '0']}, {'values': ['300s', '0', '0', '0', '0']}, {'values': ['400s', '0', '0', '0', '0']}], 'appIndex': {'seoTitle': 'Pedro Baron Profile - Cricbuzz | Cricbuzz.com', 'webURL': 'http://www.cricbuzz.com/profiles/41312/pedro-baron'}, 'seriesSpinner': [{'seriesName': 'Career'}, {'seriesId': 11570, 'seriesName': "ICC Men's T20 2028 World Cup Americas Sub Regional Qualifier B, 2026"}]}, {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'], 'values': [{'values': ['Matches', '0', '0', '42', '0']}, {'values': ['Innings', '0', '0', '28', '0']}, {'values': ['Runs', '0', '0', '242', '0']}, {'

# Player info

In [235]:
all_bat2_info

[{'id': '41330',
  'bat': 'Right Handed Bat',
  'bowl': 'Right-arm offbreak',
  'name': 'Alan Kirschbaum',
  'fullName': 'Alan Kirschbaum',
  'role': 'Batsman',
  'birthPlace': 'Buenos Aires',
  'intlTeam': 'Argentina',
  'teams': 'Argentina',
  'DoB': 'November 30, 2001 (24 years)',
  'image': 'http://i.cricketcb.com/stats/img/faceImages/41330.jpg',
  'appIndex': {'seoTitle': 'Alan Kirschbaum Profile - Cricbuzz | Cricbuzz.com',
   'webURL': 'http://www.cricbuzz.com/profiles/41330/alan-kirschbaum'},
  'DoBFormat': 'November 30, 2001',
  'faceImageId': 182026,
  'teamNameIds': [{'teamId': '549', 'teamName': 'Argentina'}],
  'playerTeamIds': '549',
  'intlTeamImageId': 172601,
  'recentBatting': {'headers': ['Score', 'OPPN.', 'Format', 'Date'],
   'rows': [{'values': ['147552', '35(28)', 'MEX', 'T20I', '12 Mar 26'],
     'followUpLinkText': "/live-cricket-scores/147552/arg-vs-mex-6th-match-icc-men's-t20-2028-world-cup-americas-sub-regional-qualifier-b-2026"},
    {'values': ['147488', '9(13)', 'SN', 'T20I', '09 Mar 26'],
     'followUpLinkText': "/live-cricket-scores/147488/arg-vs-sn-3rd-match-icc-men's-t20-2028-world-cup-americas-sub-regional-qualifier-b-2026"},
    {'values': ['147192', '7(8)', 'CAYM', 'T20I', '08 Mar 26'],
     'followUpLinkText': "/live-cricket-scores/147192/caym-vs-arg-1st-match-icc-men's-t20-2028-world-cup-americas-sub-regional-qualifier-b-2026"},
    {'values': ['138721', '20(18)', 'BRAZIL', 'T20I', '30 Nov 25'],
     'followUpLinkText': '/live-cricket-scores/138721/arg-vs-brazil-4th-t20i-brazil-tour-of-argentina-2025'},
    {'values': ['138732', '14(13)', 'BRAZIL', 'T20I', '30 Nov 25'],
     'followUpLinkText': '/live-cricket-scores/138732/arg-vs-brazil-5th-t20i-brazil-tour-of-argentina-2025'}]},
  'recentBowling': {'headers': ['Wickets', 'OPPN.', 'Format', 'Date'],
   'rows': [{'values': ['147552', '2-13', 'MEX', 'T20I', '12 Mar 26'],
     'followUpLinkText': "/live-cricket-scores/147552/arg-vs-mex-6th-match-icc-men's-t20-2028-world-cup-americas-sub-regional-qualifier-b-2026"},
    {'values': ['147488', '2-18', 'SN', 'T20I', '09 Mar 26'],
     'followUpLinkText': "/live-cricket-scores/147488/arg-vs-sn-3rd-match-icc-men's-t20-2028-world-cup-americas-sub-regional-qualifier-b-2026"},
    {'values': ['147192', '0-14', 'CAYM', 'T20I', '08 Mar 26'],
     'followUpLinkText': "/live-cricket-scores/147192/caym-vs-arg-1st-match-icc-men's-t20-2028-world-cup-americas-sub-regional-qualifier-b-2026"},
    {'values': ['138721', '1-20', 'BRAZIL', 'T20I', '30 Nov 25'],
     'followUpLinkText': '/live-cricket-scores/138721/arg-vs-brazil-4th-t20i-brazil-tour-of-argentina-2025'},
    {'values': ['138699', '3-8', 'BRAZIL', 'T20I', '29 Nov 25'],
     'followUpLinkText': '/live-cricket-scores/138699/arg-vs-brazil-2nd-t20i-brazil-tour-of-argentina-2025'}]}},
 {'id': '9647',
  'bat': 'Right Handed Bat',
  'bowl': 'Right-arm fast-medium',
  'name': 'Hardik Pandya',
  'fullName': 'Hardik Himanshu Pandya',
  'role': 'Batting Allrounder',
  'birthPlace': 'Choryasi, Gujarat',
  'intlTeam': 'India',
  'teams': 'India, Baroda, Mumbai Indians, India A, India AT20, Indian Board Presidents XI, World XI, Gujarat Titans, Indians',
  'DoB': 'October 11, 1993 (32 years)',
  'image': 'http://i.cricketcb.com/stats/img/faceImages/9647.jpg',
  'bio': "A wiry young lad from a small town in Gujarat, Hardik Pandya, with his tattoos and peroxide highlights, encapsulates the charisma and swagger of the modern-day Indian cricketer. The all-rounder was propelled into the big stage after constant exposure to prime-time television in the form of the Indian Premier League. A deep voice to go with the confidence and energy, and showing no sign of playing it safe, Pandya is the modern icon of audacity in the Indian side. Having gone through the hard grind of domestic cricket, Pandya shot to fame when he was picked up by an IPL franchise - a license to make his talent well-known on the big stage. <br/>  <br/> As several youngsters do in the modern era, Pandya announced himself to the world during the IPL, portraying his swashbuckling ability to strike the ball, outstanding fielding, and some street-smart bowling that transcends the cliché 'just rolls his arm over'. He made the world sit up when he soaked in the pressure and came good in crunch situations, playing a pivotal role in the Mumbai franchise's second title triumph, and winning two Man of the Match awards on his way. The Indian public and critics, who never fail to make comparisons, immediately had the inevitable question at the tip of their tongue: Had India found their first fast-bowling all-rounder since Kapil Dev? <br/>  <br/> Despite being predominantly noted for his explosive batting, Pandya is no slouch with the ball. In fact, it was his all-round skills which caught the attention of the T20 franchises during the Syed Mushtaq Ali tournament culminating a national contract. Pandya's merit was duly rewarded when he was named in India's ODI squad for the home series against New Zealand in 2016. By this time, he had worked on his swing bowling skills, and was hitting the 140s regularly, troubling the batsmen with his nagging length. In fact, having been a part of the 2016 World T20, Pandya defended an equation reading '2 to win off 3' against Bangladesh, bowling back of a length and short on a slow-ish wicket, and keeping India alive in the tournament as a result. <br/>  <br/> Pandya is relatively new to the Indian team and has already played some excellent knocks with the bat in ODIs, sealing off some tight run-chases and scoring quick runs when required. With the ability to surge when required and target a particular bowler, he has pulled off 20-run overs in pressure situations and remains a vital cog in the ODI fold. With an ageing MS Dhoni shifting into a sheet anchor mode rather than his usual swashbuckling mode, Pandya is a crucial factor in the team and can form a vital pairing with Dhoni, by batting around his stability as his apprentice to finish off games. His technique though, however useful in ODIs, isn't the best for non-true wickets, and if he chooses the path of Test cricket, he needs to make himself more compact and solid in terms of batting fundamentals. His bowling has taken giant strides, as he has perfected the art of swing and has figured out the optimal trajectory for his speed as well to impart maximum lateral movement on the ball. <br/>  <br/> Regardless of whether Pandya is India's next Kapil Dev, he certainly beings a much-needed balance to the side. If he remains grounded in the midst of all the glamour, and shapes his game under the able guidance of his seniors and coaches, he is destined for greatness. As of right now, it will be fascinating to watch the exuberance of blending with the maturity that comes with experience as the nation looks up at this charismatic young talent in its quest for those elusive overseas wins. <br/>  <br/> After a grueling 2018, Pandya has come out a more mature cricketer, starting from his happy-go-lucky 93 in Cape Town, to his 5-for and half-century in India's only win in the Test series against England. Pandya's bowling, particularly in Tests, has come a long way, with his extra bounce from a back of a length, and particularly his ability to swing the ball away from the right-hander. Despite not bowling the best deliveries at times, he does seem to have an uncanny knack of dismissing set batsmen, perhaps even established batsmen. His batting, although extremely aggressive, still needs a lot of work as he continues to exhibit a single-dimensional, all-out attack mode to his batting - an approach that has often failed in more bowler-friendly conditions. <br/>  <br/> After a mixed year of glory and heartbreak, Pandya was hampered by a severe back injury during the Asia Cup in 2018 which ruled him out of the tour of Australia. To make things worse, he received a lot of flak when an episode of a talk show aired in India, in which Pandya, along with Rahul, were called out for their misogynistic comments about women, and were suspended by the Board of Control for Cricket in India for poor conduct and tarnishing the image of Indian cricket. The ban has been lifted since the incident. Pandya, however, returned to the side after a lot of internal conflict in the board, for the ODI series against New Zealand and performed admirably, particularly with the ball and in the field. He remains a vital cog in India's 2019 World Cup plans, providing a much-needed balance in the side, as India finally manage to get their hands on a fast-bowling all-rounder for the first time since the Great Kapil Dev.  <br/>  <br/> Pandya was crucial in the 2019 World Cup as an auxiliary bowler, and made some handy contributions with the bat as well against Pakistan and England. However, India crashed out in the semis against New Zealand and post that World Cup exit came a tumultuous time in Pandya’ life.  <br/>  <br/> Workload management became an issue for the lanky all rounder, as he constantly picked up injuries and wasn’t able to bowl his full quota of overs. He played the bulk of the 2021 IPL as a specialist batter and bowled sparingly in the 2021 T20 World Cup as well, as India crashed out in the group stages.  <br/>  <br/> Pandya was dropped from the side and also suffered a back injury in that time period for which he had to go under the knife. The next few months saw the flashy all-rounder work massively on his fitness and diet. On his return, he looked a lot more muscular and war ready - Hardik Pandya 2.0 was upon us!  <br/>  <br/> In 2022, Hardik Pandya was roped in by new franchise Gujarat Titans in the IPL and he was made skipper. He was a revelation as captain as he shared the new ball responsibilities with Shami, batted up the order and was an excellent man manager as well. Gujarat Titans won the IPL in their inaugural season, as Hardik Pandya claimed a three-fer in that final. In the 2023 season, Gujarat Titans reached the final and were only foiled by a Ravindra Jadeja masterclass as he scored 10 runs off the last two balls to snatch the final away for CSK.  <br/>  <br/> Alongside the successes he was achieving as a franchise captain, Hardik Pandya also seemed rejuvenated as an all-rounder. He seemed to easily manage bowling plenty of overs for his side and then aced the role of a finisher with the bat, becoming a vital cog in the Indian setup once again. Pandya played a crucial knock alongside Kohli in the 2022 T20 World Cup against Pakistan, as India resurrected an unlikely looking chase against their arch rivals. Pandya was top scorer in the semi-final against England as well. <br/>  <br/> In the 2023 World Cup, Hardik Pandya injured his ankle in a group game against Bangladesh and was ruled out of the tournament. That injury forced India to rejig their team composition, and many believe that Hardik Pandya was perhaps the missing link in that final where India lost to Australia.   <br/>  <br/> In 2024, Hardik Pandya was transferred back to Mumbai Indians, and he was appointed as captain of the franchise - displacing long standing skipper Rohit Sharma. That decision made him public enemy number 1 as he was booed and ridiculed across stadiums, often by fans of his own franchise. Pandya himself had a dismal IPL as Mumbai finished well outside the playoff positions.  <br/>  <br/> A month or so later though Hardik Pandya had his day of reckoning as he was tasked with bowling the final over for India in the T20 World Cup final against South Africa. He successfully defended 16 runs in that final over as India won an ICC trophy for the first time in 11 years. Hardik Pandya was serenaded back home after that trophy triumph, annulled of all his previous ‘sins.’  <br/>  <br/> Hardik Pandya was a key part of the Indian setup in their 2025 Champions Trophy triumph as well. He partnered well with Shami as the only other seam bowling option and played some crucial cameos against New Zealand and Australia as India won a second ICC title in a span of 9 months.  <br/>  <br/> by <b>Rishi Roy</b> <br/> ",
  'rankings': {'bat': {'t20Rank': '48',
    'testBestRank': '49',
    'odiBestRank': '42',
    't20BestRank': '48',
    't20DiffRank': '+8'},
   'bowl': {'odiRank': '98',
    't20Rank': '46',
    'testBestRank': '51',
    'odiBestRank': '30',
    't20BestRank': '27',
    't20DiffRank': '+23'},
   'all': {'odiRank': '36',
    't20Rank': '2',
    'odiBestRank': '6',
    't20BestRank': '1',
    't20DiffRank': '+1'}},
  'appIndex': {'seoTitle': 'Hardik Pandya Profile - Cricbuzz | Cricbuzz.com',
   'webURL': 'http://www.cricbuzz.com/profiles/9647/hardik-pandya'},
  'DoBFormat': 'October 11, 1993',
  'faceImageId': 846032,
  'teamNameIds': [{'teamId': '2', 'teamName': 'India'},
   {'teamId': '170', 'teamName': 'Baroda'},
   {'teamId': '62', 'teamName': 'Mumbai Indians'},
   {'teamId': '78', 'teamName': 'India A'},
   {'teamId': '315', 'teamName': 'India AT20'},
   {'teamId': '305', 'teamName': 'Indian Board Presidents XI'},
   {'teamId': '425', 'teamName': 'World XI'},
   {'teamId': '971', 'teamName': 'Gujarat Titans'},
   {'teamId': '276', 'teamName': 'Indians'}],
  'playerTeamIds': '2, 170, 62, 78, 315, 305, 425, 971, 276',
  'intlTeamImageId': 776162,
  'recentBatting': {'headers': ['Score', 'OPPN.', 'Format', 'Date'],
   'rows': [{'values': ['139489', '18(13)', 'NZ', 'T20I', '08 Mar 26'],
     'followUpLinkText': "/live-cricket-scores/139489/ind-vs-nz-final-icc-men's-t20-world-cup-2026"},
    {'values': ['139478', '27(12)', 'ENG', 'T20I', '05 Mar 26'],
     'followUpLinkText': "/live-cricket-scores/139478/ind-vs-eng-2nd-semi-final-icc-men's-t20-world-cup-2026"},
    {'values': ['139461', '17(14)', 'WI', 'T20I', '01 Mar 26'],
     'followUpLinkText': "/live-cricket-scores/139461/ind-vs-wi-52nd-match-super-8-group-1-x1-v-x3-icc-men's-t20-world-cup-2026"},
    {'values': ['139426', '50*(23)', 'ZIM', 'T20I', '26 Feb 26'],
     'followUpLinkText': "/live-cricket-scores/139426/ind-vs-zim-48th-match-super-8-group-1-x1-v-x2-icc-men's-t20-world-cup-2026"},
    {'values': ['139381', '18(17)', 'RSA', 'T20I', '22 Feb 26'],
     'followUpLinkText': "/live-cricket-scores/139381/ind-vs-rsa-43rd-match-super-8-group-1-x1-v-x4-icc-men's-t20-world-cup-2026"}]},
  'recentBowling': {'headers': ['Wickets', 'OPPN.', 'Format', 'Date'],
   'rows': [{'values': ['139489', '1-36', 'NZ', 'T20I', '08 Mar 26'],
     'followUpLinkText': "/live-cricket-scores/139489/ind-vs-nz-final-icc-men's-t20-world-cup-2026"},
    {'values': ['139478', '2-38', 'ENG', 'T20I', '05 Mar 26'],
     'followUpLinkText': "/live-cricket-scores/139478/ind-vs-eng-2nd-semi-final-icc-men's-t20-world-cup-2026"},
    {'values': ['139461', '1-40', 'WI', 'T20I', '01 Mar 26'],
     'followUpLinkText': "/live-cricket-scores/139461/ind-vs-wi-52nd-match-super-8-group-1-x1-v-x3-icc-men's-t20-world-cup-2026"},
    {'values': ['139426', '0-21', 'ZIM', 'T20I', '26 Feb 26'],
     'followUpLinkText': "/live-cricket-scores/139426/ind-vs-zim-48th-match-super-8-group-1-x1-v-x2-icc-men's-t20-world-cup-2026"},
    {'values': ['139381', '0-45', 'RSA', 'T20I', '22 Feb 26'],
     'followUpLinkText': "/live-cricket-scores/139381/ind-vs-rsa-43rd-match-super-8-group-1-x1-v-x4-icc-men's-t20-world-cup-2026"}]}},
 {'id': '21823',
  'bat': 'Left Handed Bat',
  'bowl': 'Left-arm orthodox',
  'name': 'Sacha De Alwis',
  'fullName': 'Yeron Sacha DeAlwis Seneveratne',
  'role': 'Bowler',
  'birthPlace': 'Sri Lanka',
  'intlTeam': 'Cayman Islands',
  'teams': 'Dambulla Sixers, Cayman Islands',
  'DoB': 'January 30, 1992 (34 years)',
  'image': 'http://i.cricketcb.com/stats/img/faceImages/21823.jpg',
  'appIndex': {'seoTitle': 'Sacha De Alwis Profile - Cricbuzz | Cricbuzz.com',
   'webURL': 'http://www.cricbuzz.com/profiles/21823/sacha-de-alwis'},
  'DoBFormat': 'January 30, 1992',
  'faceImageId': 182026,
  'teamNameIds': [{'teamId': '946', 'teamName': 'Dambulla Sixers'},
   {'teamId': '1020', 'teamName': 'Cayman Islands'}],
  'playerTeamIds': '946, 1020',
  'intlTeamImageId': 248399,
  'recentBatting': {'headers': ['Score', 'OPPN.', 'Format', 'Date'],
   'rows': [{'values': ['147541', '38*(30)', 'SN', 'T20I', '11 Mar 26'],
     'followUpLinkText': "/live-cricket-scores/147541/sn-vs-caym-5th-match-icc-men's-t20-2028-world-cup-americas-sub-regional-qualifier-b-2026"},
    {'values': ['147535', '32*(33)', 'MEX', 'T20I', '10 Mar 26'],
     'followUpLinkText': "/live-cricket-scores/147535/caym-vs-mex-4th-match-icc-men's-t20-2028-world-cup-americas-sub-regional-qualifier-b-2026"},
    {'values': ['147192', '47*(26)', 'ARG', 'T20I', '08 Mar 26'],
     'followUpLinkText': "/live-cricket-scores/147192/caym-vs-arg-1st-match-icc-men's-t20-2028-world-cup-americas-sub-regional-qualifier-b-2026"},
    {'values': ['117863', '1(3)', 'CAN', 'T20I', '26 Apr 25'],
     'followUpLinkText': '/live-cricket-scores/117863/can-vs-caym-1st-semi-final-the-north-american-t20-cup-2025'},
    {'values': ['117848', '36(39)', 'BHM', 'T20I', '24 Apr 25'],
     'followUpLinkText': '/live-cricket-scores/117848/caym-vs-bhm-9th-match-the-north-american-t20-cup-2025'}]},
  'recentBowling': {'headers': ['Wickets', 'OPPN.', 'Format', 'Date'],
   'rows': [{'values': ['66708', '0-6', 'BER', 'T20I', '25 Feb 23'],
     'followUpLinkText': '/live-cricket-scores/66708/ber-vs-caym-2nd-match-icc-mens-t20-world-cup-americas-qualifier-2023'},
    {'values': ['85650', '0-5', 'USA', 'T20I', '19 Aug 19'],
     'followUpLinkText': '/live-cricket-scores/85650/caym-vs-usa-4th-match-icc-mens-t20-world-cup-americas-region-final-2019'},
    {'values': ['85640', '0-17', 'CAN', 'T20I', '18 Aug 19'],
     'followUpLinkText': '/live-cricket-scores/85640/can-vs-caym-2nd-match-icc-mens-t20-world-cup-americas-region-final-2019'}]}},
 {'id': '37581',
  'bat': 'Right Handed Bat',
  'bowl': 'Right-arm fast',
  'name': 'Nahid Rana',
  'fullName': 'Nahid Rana',
  'role': 'Bowler',
  'birthPlace': 'Chapai Nawabgonj',
  'intlTeam': 'Bangladesh',
  'teams': 'Khulna Tigers, Bangladesh, Rangpur Riders, Peshawar Zalmi, Vista Riders',
  'DoB': 'October 02, 2002 (23 years)',
  'image': 'http://i.cricketcb.com/stats/img/faceImages/37581.jpg',
  'rankings': {'bat': {},
   'bowl': {'testRank': '82', 'testBestRank': '68'},
   'all': {}},
  'appIndex': {'seoTitle': 'Nahid Rana Profile - Cricbuzz | Cricbuzz.com',
   'webURL': 'http://www.cricbuzz.com/profiles/37581/nahid-rana'},
  'DoBFormat': 'October 02, 2002',
  'faceImageId': 616465,
  'teamNameIds': [{'teamId': '627', 'teamName': 'Khulna Tigers'},
   {'teamId': '6', 'teamName': 'Bangladesh'},
   {'teamId': '256', 'teamName': 'Rangpur Riders'},
   {'teamId': '334', 'teamName': 'Peshawar Zalmi'},
   {'teamId': '2894', 'teamName': 'Vista Riders'}],
  'playerTeamIds': '627, 6, 256, 334, 2894',
  'intlTeamImageId': 776210,
  'recentBatting': {'headers': ['Score', 'OPPN.', 'Format', 'Date'],
   'rows': [{'values': ['147863', 'DNB', 'PAK', 'ODI', '11 Mar 26'],
     'followUpLinkText': '/live-cricket-scores/147863/ban-vs-pak-1st-odi-pakistan-tour-of-bangladesh-2026'},
    {'values': ['135041', '4* & DNB', 'IRE', 'Test', '11 Nov 25'],
     'followUpLinkText': '/live-cricket-scores/135041/ban-vs-ire-1st-test-ireland-tour-of-bangladesh-2025'},
    {'values': ['133682', '2*(9)', 'AFG', 'ODI', '14 Oct 25'],
     'followUpLinkText': '/live-cricket-scores/133682/afg-vs-ban-3rd-odi-afghanistan-vs-bangladesh-in-uae-2025'},
    {'values': ['118592', '0* & DNB', 'SL', 'Test', '25 Jun 25'],
     'followUpLinkText': '/live-cricket-scores/118592/sl-vs-ban-2nd-test-bangladesh-tour-of-sri-lanka-2025'},
    {'values': ['118586', '0 & DNB', 'SL', 'Test', '17 Jun 25'],
     'followUpLinkText': '/live-cricket-scores/118586/sl-vs-ban-1st-test-bangladesh-tour-of-sri-lanka-2025'}]},
  'recentBowling': {'headers': ['Wickets', 'OPPN.', 'Format', 'Date'],
   'rows': [{'values': ['147863', '5-24', 'PAK', 'ODI', '11 Mar 26'],

In [234]:
import pandas as pd
import requests
import time

# List of player IDs to scrape
player_ids = ['41330', '9647', '21823', '37581', '15350', '24827']
all_players_data = []

# Headers for RapidAPI
headers = {
    "x-rapidapi-key": "095038d962msh9068af945c80bc9p1ad37cjsna03b2a42de54",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

print("Fetching data for all players...")

# OUTER LOOP: Iterate through each Player ID
for pid in player_ids:
    url = f"https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/{pid}"
    
    try:
        response = requests.get(url, headers=headers, timeout=10)
        if response.status_code != 200:
            print(f"⚠ Skip {pid}: Status {response.status_code}")
            continue
            
        json_data = response.json()
        
        # 1. Extract Profile Info (Static for each player)
        base_info = {
            'ID': json_data.get('id'),
            'Name': json_data.get('name'),
            'Role': json_data.get('role'),
            'Team': json_data.get('intlTeam')
        }
        
        # 2. INNER LOOP: Iterate through 'recentBatting' rows for this specific player
        # This extracts the match-by-match scores needed for Question 23
        recent_matches = json_data.get('recentBatting', {}).get('rows', [])
        
        for match in recent_matches:
            match_vals = match.get('values', [])
            
            # Create a combined dictionary of Profile + Match Data
            # Note: Index 1 is usually the 'Score' in the JSON you provided
            row_data = base_info.copy()
            row_data.update({
                'Score': match_vals[1],
                'Opponent': match_vals[2],
                'Format': match_vals[3],
                'Date': match_vals[4]
            })
            all_players_data.append(row_data)
            
        print(f"✓ Processed: {base_info['Name']}")
        time.sleep(1)  # Respect API limits

    except Exception as e:
        print(f"✗ Error on {pid}: {e}")

# STEP 3: Create the final DataFrame
df_all_players = pd.DataFrame(all_players_data)

# Display the top rows
print("\n--- FINAL DATAFRAME ---")
print(df_all_players.head(10))

Fetching data for all players...
✓ Processed: Alan Kirschbaum
✓ Processed: Hardik Pandya
✓ Processed: Sacha De Alwis
✓ Processed: Nahid Rana
✓ Processed: Boemo Khumalo
✓ Processed: Conroy Wright

--- FINAL DATAFRAME ---
      ID             Name                Role       Team    Score Opponent Format       Date
0  41330  Alan Kirschbaum             Batsman  Argentina   35(28)      MEX   T20I  12 Mar 26
1  41330  Alan Kirschbaum             Batsman  Argentina    9(13)       SN   T20I  09 Mar 26
2  41330  Alan Kirschbaum             Batsman  Argentina     7(8)     CAYM   T20I  08 Mar 26
3  41330  Alan Kirschbaum             Batsman  Argentina   20(18)   BRAZIL   T20I  30 Nov 25
4  41330  Alan Kirschbaum             Batsman  Argentina   14(13)   BRAZIL   T20I  30 Nov 25
5   9647    Hardik Pandya  Batting Allrounder      India   18(13)       NZ   T20I  08 Mar 26
6   9647    Hardik Pandya  Batting Allrounder      India   27(12)      ENG   T20I  05 Mar 26
7   9647    Hardik Pandya  Batting Allrounder      India   17(14)       WI   T20I  01 Mar 26
8   9647    Hardik Pandya  Batting Allrounder      India  50*(23)      ZIM   T20I  26 Feb 26
9   9647    Hardik Pandya  Batting Allrounder      India   18(17)      RSA   T20I  22 Feb 26

In [236]:
df_all_players

       ID             Name                Role            Team     Score Opponent Format       Date
0   41330  Alan Kirschbaum             Batsman       Argentina    35(28)      MEX   T20I  12 Mar 26
1   41330  Alan Kirschbaum             Batsman       Argentina     9(13)       SN   T20I  09 Mar 26
2   41330  Alan Kirschbaum             Batsman       Argentina      7(8)     CAYM   T20I  08 Mar 26
3   41330  Alan Kirschbaum             Batsman       Argentina    20(18)   BRAZIL   T20I  30 Nov 25
4   41330  Alan Kirschbaum             Batsman       Argentina    14(13)   BRAZIL   T20I  30 Nov 25
5    9647    Hardik Pandya  Batting Allrounder           India    18(13)       NZ   T20I  08 Mar 26
6    9647    Hardik Pandya  Batting Allrounder           India    27(12)      ENG   T20I  05 Mar 26
7    9647    Hardik Pandya  Batting Allrounder           India    17(14)       WI   T20I  01 Mar 26
8    9647    Hardik Pandya  Batting Allrounder           India   50*(23)      ZIM   T20I  26 Feb 26
9    9647    Hardik Pandya  Batting Allrounder           India    18(17)      RSA   T20I  22 Feb 26
10  21823   Sacha De Alwis              Bowler  Cayman Islands   38*(30)       SN   T20I  11 Mar 26
11  21823   Sacha De Alwis              Bowler  Cayman Islands   32*(33)      MEX   T20I  10 Mar 26
12  21823   Sacha De Alwis              Bowler  Cayman Islands   47*(26)      ARG   T20I  08 Mar 26
13  21823   Sacha De Alwis              Bowler  Cayman Islands      1(3)      CAN   T20I  26 Apr 25
14  21823   Sacha De Alwis              Bowler  Cayman Islands    36(39)      BHM   T20I  24 Apr 25
15  37581       Nahid Rana              Bowler      Bangladesh       DNB      PAK    ODI  11 Mar 26
16  37581       Nahid Rana              Bowler      Bangladesh  4* & DNB      IRE   Test  11 Nov 25
17  37581       Nahid Rana              Bowler      Bangladesh     2*(9)      AFG    ODI  14 Oct 25
18  37581       Nahid Rana              Bowler      Bangladesh  0* & DNB       SL   Test  25 Jun 25
19  37581       Nahid Rana              Bowler      Bangladesh   0 & DNB       SL   Test  17 Jun 25
20  15350    Boemo Khumalo              Bowler        Botswana      5(7)      LSO   T20I  12 Mar 26
21  15350    Boemo Khumalo              Bowler        Botswana       DNB      LSO   T20I  10 Mar 26
22  15350    Boemo Khumalo              Bowler        Botswana       DNB      LSO   T20I  09 Mar 26
23  15350    Boemo Khumalo              Bowler        Botswana       DNB      TAN   T20I  26 Sep 25
24  15350    Boemo Khumalo              Bowler        Botswana     2*(2)      UGA   T20I  13 Dec 24
25  24827    Conroy Wright  Bowling Allrounder  Cayman Islands       DNB      MEX   T20I  12 Mar 26
26  24827    Conroy Wright  Bowling Allrounder  Cayman Islands       DNB       SN   T20I  11 Mar 26
27  24827    Conroy Wright  Bowling Allrounder  Cayman Islands       DNB      MEX   T20I  10 Mar 26
28  24827    Conroy Wright  Bowling Allrounder  Cayman Islands       DNB      ARG   T20I  08 Mar 26
29  24827    Conroy Wright  Bowling Allrounder  Cayman Islands       DNB      CAN   T20I  19 Jun 25

In [238]:
all_bat2

[{'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'],
  'values': [{'values': ['Matches', '0', '0', '26', '0']},
   {'values': ['Innings', '0', '0', '25', '0']},
   {'values': ['Runs', '0', '0', '298', '0']},
   {'values': ['Balls', '0', '0', '330', '0']},
   {'values': ['Highest', '0', '0', '35', '0']},
   {'values': ['Average', '0', '0', '14.19', '0']},
   {'values': ['SR', '0', '0', '90.31', '0']},
   {'values': ['Not Out', '0', '0', '4', '0']},
   {'values': ['Fours', '0', '0', '21', '0']},
   {'values': ['Sixes', '0', '0', '3', '0']},
   {'values': ['Ducks', '0', '0', '2', '0']},
   {'values': ['50s', '0', '0', '0', '0']},
   {'values': ['100s', '0', '0', '0', '0']},
   {'values': ['200s', '0', '0', '0', '0']},
   {'values': ['300s', '0', '0', '0', '0']},
   {'values': ['400s', '0', '0', '0', '0']}],
  'appIndex': {'seoTitle': 'Alan Kirschbaum Profile - Cricbuzz | Cricbuzz.com',
   'webURL': 'http://www.cricbuzz.com/profiles/41330/alan-kirschbaum'},
  'seriesSpinner': [{'seriesName': 'Career'},
   {'seriesId': 11570,
    'seriesName': "ICC Men's T20 2028 World Cup Americas Sub Regional Qualifier B, 2026"}]},
 {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'],
  'values': [{'values': ['Matches', '6', '31', '12', '0']},
   {'values': ['Innings', '10', '25', '12', '0']},
   {'values': ['Runs', '455', '575', '225', '0']},
   {'values': ['Balls', '861', '724', '178', '0']},
   {'values': ['Highest', '116', '114', '84', '0']},
   {'values': ['Average', '56.88', '27.38', '25', '0']},
   {'values': ['SR', '52.85', '79.42', '126.41', '0']},
   {'values': ['Not Out', '2', '4', '3', '0']},
   {'values': ['Fours', '50', '50', '19', '0']},
   {'values': ['Sixes', '1', '6', '6', '0']},
   {'values': ['Ducks', '1', '0', '2', '0']},
   {'values': ['50s', '3', '1', '2', '0']},
   {'values': ['100s', '1', '1', '0', '0']},
   {'values': ['200s', '0', '0', '0', '0']},
   {'values': ['300s', '0', '0', '0', '0']},
   {'values': ['400s', '0', '0', '0', '0']}],
  'appIndex': {'seoTitle': 'Asela Gunaratne Profile - Cricbuzz | Cricbuzz.com',
   'webURL': 'http://www.cricbuzz.com/profiles/10154/asela-gunaratne'},
  'seriesSpinner': [{'seriesName': 'Career'},
   {'seriesId': 11671, 'seriesName': 'Legends League Cricket 2026'}]},
 {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'],
  'values': [{'values': ['Matches', '0', '0', '26', '0']},
   {'values': ['Innings', '0', '0', '26', '0']},
   {'values': ['Runs', '0', '0', '668', '0']},
   {'values': ['Balls', '0', '0', '566', '0']},
   {'values': ['Highest', '0', '0', '150', '0']},
   {'values': ['Average', '0', '0', '33.4', '0']},
   {'values': ['SR', '0', '0', '118.03', '0']},
   {'values': ['Not Out', '0', '0', '6', '0']},
   {'values': ['Fours', '0', '0', '52', '0']},
   {'values': ['Sixes', '0', '0', '33', '0']},
   {'values': ['Ducks', '0', '0', '1', '0']},
   {'values': ['50s', '0', '0', '3', '0']},
   {'values': ['100s', '0', '0', '1', '0']},
   {'values': ['200s', '0', '0', '0', '0']},
   {'values': ['300s', '0', '0', '0', '0']},
   {'values': ['400s', '0', '0', '0', '0']}],
  'appIndex': {'seoTitle': 'Sacha De Alwis Profile - Cricbuzz | Cricbuzz.com',
   'webURL': 'http://www.cricbuzz.com/profiles/21823/sacha-de-alwis'},
  'seriesSpinner': [{'seriesName': 'Career'},
   {'seriesId': 11570,
    'seriesName': "ICC Men's T20 2028 World Cup Americas Sub Regional Qualifier B, 2026"}]},
 {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'],
  'values': [{'values': ['Matches', '10', '6', '1', '0']},
   {'values': ['Innings', '16', '3', '0', '0']},
   {'values': ['Runs', '17', '6', '0', '0']},
   {'values': ['Balls', '88', '18', '0', '0']},
   {'values': ['Highest', '11', '4', '0', '0']},
   {'values': ['Average', '2.43', '0', '0', '0']},
   {'values': ['SR', '19.32', '33.34', '0', '0']},
   {'values': ['Not Out', '9', '3', '0', '0']},
   {'values': ['Fours', '3', '1', '0', '0']},
   {'values': ['Sixes', '0', '0', '0', '0']},
   {'values': ['Ducks', '6', '0', '0', '0']},
   {'values': ['50s', '0', '0', '0', '0']},
   {'values': ['100s', '0', '0', '0', '0']},
   {'values': ['200s', '0', '0', '0', '0']},
   {'values': ['300s', '0', '0', '0', '0']},
   {'values': ['400s', '0', '0', '0', '0']}],
  'appIndex': {'seoTitle': 'Nahid Rana Profile - Cricbuzz | Cricbuzz.com',
   'webURL': 'http://www.cricbuzz.com/profiles/37581/nahid-rana'},
  'seriesSpinner': [{'seriesName': 'Career'},
   {'seriesId': 11584, 'seriesName': 'Pakistan tour of Bangladesh, 2026'}]},
 {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'],
  'values': [{'values': ['Matches', '0', '0', '30', '0']},
   {'values': ['Innings', '0', '0', '9', '0']},
   {'values': ['Runs', '0', '0', '26', '0']},
   {'values': ['Balls', '0', '0', '39', '0']},
   {'values': ['Highest', '0', '0', '10', '0']},
   {'values': ['Average', '0', '0', '8.67', '0']},
   {'values': ['SR', '0', '0', '66.67', '0']},
   {'values': ['Not Out', '0', '0', '6', '0']},
   {'values': ['Fours', '0', '0', '1', '0']},
   {'values': ['Sixes', '0', '0', '0', '0']},
   {'values': ['Ducks', '0', '0', '1', '0']},
   {'values': ['50s', '0', '0', '0', '0']},
   {'values': ['100s', '0', '0', '0', '0']},
   {'values': ['200s', '0', '0', '0', '0']},
   {'values': ['300s', '0', '0', '0', '0']},
   {'values': ['400s', '0', '0', '0', '0']}],
  'appIndex': {'seoTitle': 'Boemo Khumalo Profile - Cricbuzz | Cricbuzz.com',
   'webURL': 'http://www.cricbuzz.com/profiles/15350/boemo-khumalo'},
  'seriesSpinner': [{'seriesName': 'Career'},
   {'seriesId': 11711, 'seriesName': 'Lesotho tour of Botswana, 2026'}]},
 {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'],
  'values': [{'values': ['Matches', '0', '0', '58', '0']},
   {'values': ['Innings', '0', '0', '14', '0']},
   {'values': ['Runs', '0', '0', '15', '0']},
   {'values': ['Balls', '0', '0', '28', '0']},
   {'values': ['Highest', '0', '0', '3', '0']},
   {'values': ['Average', '0', '0', '1.67', '0']},
   {'values': ['SR', '0', '0', '53.58', '0']},
   {'values': ['Not Out', '0', '0', '5', '0']},
   {'values': ['Fours', '0', '0', '0', '0']},
   {'values': ['Sixes', '0', '0', '0', '0']},
   {'values': ['Ducks', '0', '0', '4', '0']},
   {'values': ['50s', '0', '0', '0', '0']},
   {'values': ['100s', '0', '0', '0', '0']},
   {'values': ['200s', '0', '0', '0', '0']},
   {'values': ['300s', '0', '0', '0', '0']},
   {'values': ['400s', '0', '0', '0', '0']}],
  'appIndex': {'seoTitle': 'Imran Khan Profile - Cricbuzz | Cricbuzz.com',
   'webURL': 'http://www.cricbuzz.com/profiles/29552/imran-khan'},
  'seriesSpinner': [{'seriesName': 'Career'}]},
 {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'],
  'values': [{'values': ['Matches', '0', '0', '7', '0']},
   {'values': ['Innings', '0', '0', '3', '0']},
   {'values': ['Runs', '0', '0', '8', '0']},
   {'values': ['Balls', '0', '0', '21', '0']},
   {'values': ['Highest', '0', '0', '8', '0']},
   {'values': ['Average', '0', '0', '4', '0']},
   {'values': ['SR', '0', '0', '38.10', '0']},
   {'values': ['Not Out', '0', '0', '1', '0']},
   {'values': ['Fours', '0', '0', '0', '0']},
   {'values': ['Sixes', '0', '0', '0', '0']},
   {'values': ['Ducks', '0', '0', '2', '0']},
   {'values': ['50s', '0', '0', '0', '0']},
   {'values': ['100s', '0', '0', '0', '0']},
   {'values': ['200s', '0', '0', '0', '0']},
   {'values': ['300s', '0', '0', '0', '0']},
   {'values': ['400s', '0', '0', '0', '0']}],
  'appIndex': {'seoTitle': 'Romario Edwards Profile - Cricbuzz | Cricbuzz.com',
   'webURL': 'http://www.cricbuzz.com/profiles/1452215/romario-edwards'},
  'seriesSpinner': [{'seriesName': 'Career'},
   {'seriesId': 11570,
    'seriesName': "ICC Men's T20 2028 World Cup Americas Sub Regional Qualifier B, 2026"}]},
 {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'],
  'values': [{'values': ['Matches', '0', '0', '43', '0']},
   {'values': ['Innings', '0', '0', '18', '0']},
   {'values': ['Runs', '0', '0', '90', '0']},
   {'values': ['Balls', '0', '0', '129', '0']},
   {'values': ['Highest', '0', '0', '32', '0']},
   {'values': ['Average', '0', '0', '6', '0']},
   {'values': ['SR', '0', '0', '69.77', '0']},
   {'values': ['Not Out', '0', '0', '3', '0']},
   {'values': ['Fours', '0', '0', '2', '0']},
   {'values': ['Sixes', '0', '0', '2', '0']},
   {'values': ['Ducks', '0', '0', '7', '0']},
   {'values': ['50s', '0', '0', '0', '0']},
   {'values': ['100s', '0', '0', '0', '0']},
   {'values': ['200s', '0', '0', '0', '0']},
   {'values': ['300s', '0', '0', '0', '0']},
   {'values': ['400s', '0', '0', '0', '0']}],
  'appIndex': {'seoTitle': 'Dhruvkumar Maisuria Profile - Cricbuzz | Cricbuzz.com',
   'webURL': 'http://www.cricbuzz.com/profiles/15351/dhruvkumar-maisuria'},
  'seriesSpinner': [{'seriesName': 'Career'},
   {'seriesId': 11711, 'seriesName': 'Lesotho tour of Botswana, 2026'}]},
 {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'],
  'values': [{'values': ['Matches', '0', '0', '26', '0']},
   {'values': ['Innings', '0', '0', '31', '0']},
   {'values': ['Runs', '0', '0', '693', '0']},
   {'values': ['Balls', '0', '0', '653', '0']},
   {'values': ['Highest', '0', '0', '73', '0']},
   {'values': ['Average', '0', '0', '24.75', '0']},
   {'values': ['SR', '0', '0', '106.13', '0']},
   {'values': ['Not Out', '0', '0', '3', '0']},
   {'values': ['Fours', '0', '0', '78', '0']},
   {'values': ['Sixes', '0', '0', '6', '0']},
   {'values': ['Ducks', '0', '0', '0', '0']},
   {'values': ['50s', '0', '0', '6', '0']},
   {'values': ['100s', '0', '0', '0', '0']},
   {'values': ['200s', '0', '0', '0', '0']},
   {'values': ['300s', '0', '0', '0', '0']},
   {'values': ['400s', '0', '0', '0', '0']}],
  'appIndex': {'seoTitle': 'Pedro Baron Profile - Cricbuzz | Cricbuzz.com',
   'webURL': 'http://www.cricbuzz.com/profiles/41312/pedro-baron'},
  'seriesSpinner': [{'seriesName': 'Career'},
   {'seriesId': 11570,
    'seriesName': "ICC Men's T20 2028 World Cup Americas Sub Regional Qualifier B, 2026"}]},
 {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'],
  'values': [{'values': ['Matches', '0', '0', '41', '0']},
   {'values': ['Innings', '0', '0', '28', '0']},
   {'values': ['Runs', '0', '0', '242', '0']},
   {'values': ['Balls', '0', '0', '245', '0']},
   {'values': ['Highest', '0', '0', '50', '0']},
   {'values': ['Average', '0', '0', '14.24', '0']},
   {'values': ['SR', '0', '0', '98.78', '0']},
   {'values': ['Not Out', '0', '0', '11', '0']},
   {'values': ['Fours', '0', '0', '10', '0']},
   {'values': ['Sixes', '0', '0', '9', '0']},
   {'values': ['Ducks', '0', '0', '7', '0']},
   {'values': ['50s', '0', '0', '1', '0']},
   {'values': ['100s', '0', '0', '0', '0']},
   {'values': ['200s', '0', '0', '0', '0']},
   {'values': ['300s', '0', '0', '0', '0']},
   {'values': ['400s', '0', '0', '0', '0']}],
  'appIndex': {'seoTitle': 'Conroy Wright Profile - Cricbuzz | Cricbuzz.com',
   'webURL': 'http://www.cricbuzz.com/profiles/24827/conroy-wright'},
  'seriesSpinner': [{'seriesName': 'Career'},
   {'seriesId': 11570,
    'seriesName': "ICC Men's T20 2028 World Cup Americas Sub Regional Qualifier B, 2026"}]},
 {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'],
  'values': [{'values': ['Matches', '0', '0', '26', '0']},
   {'values': ['Innings', '0', '0', '25', '0']},
   {'values': ['Runs', '0', '0', '298', '0']},
   {'values': ['Balls', '0', '0', '330', '0']},
   {'values': ['Highest', '0', '0', '35', '0']},
   {'values': ['Average', '0', '0', '14.19', '0']},
   {'values': ['SR', '0', '0', '90.31', '0']},
   {'values': ['Not Out', '0', '0', '4', '0']},
   {'values': ['Fours', '0', '0', '21', '0']},
   {'values': ['Sixes', '0', '0', '3', '0']},
   {'values': ['Ducks', '0', '0', '2', '0']},
   {'values': ['50s', '0', '0', '0', '0']},
   {'values': ['100s', '0', '0', '0', '0']},
   {'values': ['200s', '0', '0', '0', '0']},
   {'values': ['300s', '0', '0', '0', '0']},
   {'values': ['400s', '0', '0', '0', '0']}],
  'appIndex': {'seoTitle': 'Alan Kirschbaum Profile - Cricbuzz | Cricbuzz.com',
   'webURL': 'http://www.cricbuzz.com/profiles/41330/alan-kirschbaum'},
  'seriesSpinner': [{'seriesName': 'Career'},
   {'seriesId': 11570,
    'seriesName': "ICC Men's T20 2028 World Cup Americas Sub Regional Qualifier B, 2026"}]},
 {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'],
  'values': [{'values': ['Matches', '11', '94', '138', '152']},
   {'values': ['Innings', '18', '68', '109', '140']},
   {'values': ['Runs', '532', '1904', '2288', '2749']},
   {'values': ['Balls', '720', '1717', '1568', '1871']},
   {'values': ['Highest', '108', '92', '71', '91']},
   {'values': ['Average', '31.29', '32.83', '28.25', '28.34']},
   {'values': ['SR', '73.89', '110.90', '145.92', '146.93']},
   {'values': ['Not Out', '1', '10', '28', '43']},
   {'values': ['Fours', '68', '141', '168', '207']},
   {'values': ['Sixes', '12', '76', '126', '148']},
   {'values': ['Ducks', '2', '4', '4', '6']},
   {'values': ['50s', '4', '11', '9', '10']},
   {'values': ['100s', '1', '0', '0', '0']},
   {'values': ['200s', '0', '0', '0', '0']},
   {'values': ['300s', '0', '0', '0', '0']},
   {'values': ['400s', '0', '0', '0', '0']}],
  'appIndex': {'seoTitle': 'Hardik Pandya Profile - Cricbuzz | Cricbuzz.com',
   'webURL': 'http://www.cricbuzz.com/profiles/9647/hardik-pandya'},
  'seriesSpinner': [{'seriesName': 'Career'}]},
 {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'],
  'values': [{'values': ['Matches', '0', '0', '27', '0']},
   {'values': ['Innings', '0', '0', '27', '0']},
   {'values': ['Runs', '0', '0', '713', '0']},
   {'values': ['Balls', '0', '0', '602', '0']},
   {'values': ['Highest', '0', '0', '150', '0']},
   {'values': ['Average', '0', '0', '33.95', '0']},
   {'values': ['SR', '0', '0', '118.44', '0']},
   {'values': ['Not Out', '0', '0', '6', '0']},
   {'values': ['Fours', '0', '0', '57', '0']},
   {'values': ['Sixes', '0', '0', '35', '0']},
   {'values': ['Ducks', '0', '0', '1', '0']},
   {'values': ['50s', '0', '0', '3', '0']},
   {'values': ['100s', '0', '0', '1', '0']},
   {'values': ['200s', '0', '0', '0', '0']},
   {'values': ['300s', '0', '0', '0', '0']},
   {'values': ['400s', '0', '0', '0', '0']}],
  'appIndex': {'seoTitle': 'Sacha De Alwis Profile - Cricbuzz | Cricbuzz.com',
   'webURL': 'http://www.cricbuzz.com/profiles/21823/sacha-de-alwis'},
  'seriesSpinner': [{'seriesName': 'Career'},
   {'seriesId': 11570,
    'seriesName': "ICC Men's T20 2028 World Cup Americas Sub Regional Qualifier B, 2026"}]},
 {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'],
  'values': [{'values': ['Matches', '10', '6', '1', '0']},
   {'values': ['Innings', '16', '3', '0', '0']},
   {'values': ['Runs', '17', '6', '0', '0']},
   {'values': ['Balls', '88', '18', '0', '0']},
   {'values': ['Highest', '11', '4', '0', '0']},
   {'values': ['Average', '2.43', '0', '0', '0']},
   {'values': ['SR', '19.32', '33.34', '0', '0']},
   {'values': ['Not Out', '9', '3', '0', '0']},
   {'values': ['Fours', '3', '1', '0', '0']},
   {'values': ['Sixes', '0', '0', '0', '0']},
   {'values': ['Ducks', '6', '0', '0', '0']},
   {'values': ['50s', '0', '0', '0', '0']},
   {'values': ['100s', '0', '0', '0', '0']},
   {'values': ['200s', '0', '0', '0', '0']},
   {'values': ['300s', '0', '0', '0', '0']},
   {'values': ['400s', '0', '0', '0', '0']}],
  'appIndex': {'seoTitle': 'Nahid Rana Profile - Cricbuzz | Cricbuzz.com',
   'webURL': 'http://www.cricbuzz.com/profiles/37581/nahid-rana'},
  'seriesSpinner': [{'seriesName': 'Career'},
   {'seriesId': 11584, 'seriesName': 'Pakistan tour of Bangladesh, 2026'}]},
 {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'],
  'values': [{'values': ['Matches', '0', '0', '31', '0']},
   {'values': ['Innings', '0', '0', '10', '0']},
   {'values': ['Runs', '0', '0', '31', '0']},
   {'values': ['Balls', '0', '0', '46', '0']},
   {'values': ['Highest', '0', '0', '10', '0']},
   {'values': ['Average', '0', '0', '7.75', '0']},
   {'values': ['SR', '0', '0', '67.40', '0']},
   {'values': ['Not Out', '0', '0', '6', '0']},
   {'values': ['Fours', '0', '0', '1', '0']},
   {'values': ['Sixes', '0', '0', '0', '0']},
   {'values': ['Ducks', '0', '0', '1', '0']},
   {'values': ['50s', '0', '0', '0', '0']},
   {'values': ['100s', '0', '0', '0', '0']},
   {'values': ['200s', '0', '0', '0', '0']},
   {'values': ['300s', '0', '0', '0', '0']},
   {'values': ['400s', '0', '0', '0', '0']}],
  'appIndex': {'seoTitle': 'Boemo Khumalo Profile - Cricbuzz | Cricbuzz.com',
   'webURL': 'http://www.cricbuzz.com/profiles/15350/boemo-khumalo'},
  'seriesSpinner': [{'seriesName': 'Career'},
   {'seriesId': 11711, 'seriesName': 'Lesotho tour of Botswana, 2026'}]},
 {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'],
  'values': [{'values': ['Matches', '0', '0', '58', '0']},
   {'values': ['Innings', '0', '0', '14', '0']},
   {'values': ['Runs', '0', '0', '15', '0']},
   {'values': ['Balls', '0', '0', '28', '0']},
   {'values': ['Highest', '0', '0', '3', '0']},
   {'values': ['Average', '0', '0', '1.67', '0']},
   {'values': ['SR', '0', '0', '53.58', '0']},
   {'values': ['Not Out', '0', '0', '5', '0']},
   {'values': ['Fours', '0', '0', '0', '0']},
   {'values': ['Sixes', '0', '0', '0', '0']},
   {'values': ['Ducks', '0', '0', '4', '0']},
   {'values': ['50s', '0', '0', '0', '0']},
   {'values': ['100s', '0', '0', '0', '0']},
   {'values': ['200s', '0', '0', '0', '0']},
   {'values': ['300s', '0', '0', '0', '0']},
   {'values': ['400s', '0', '0', '0', '0']}],
  'appIndex': {'seoTitle': 'Imran Khan Profile - Cricbuzz | Cricbuzz.com',
   'webURL': 'http://www.cricbuzz.com/profiles/29552/imran-khan'},
  'seriesSpinner': [{'seriesName': 'Career'}]},
 {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'],
  'values': [{'values': ['Matches', '0', '0', '8', '0']},
   {'values': ['Innings', '0', '0', '3', '0']},
   {'values': ['Runs', '0', '0', '8', '0']},
   {'values': ['Balls', '0', '0', '21', '0']},
   {'values': ['Highest', '0', '0', '8', '0']},
   {'values': ['Average', '0', '0', '4', '0']},
   {'values': ['SR', '0', '0', '38.10', '0']},
   {'values': ['Not Out', '0', '0', '1', '0']},
   {'values': ['Fours', '0', '0', '0', '0']},
   {'values': ['Sixes', '0', '0', '0', '0']},
   {'values': ['Ducks', '0', '0', '2', '0']},
   {'values': ['50s', '0', '0', '0', '0']},
   {'values': ['100s', '0', '0', '0', '0']},
   {'values': ['200s', '0', '0', '0', '0']},
   {'values': ['300s', '0', '0', '0', '0']},
   {'values': ['400s', '0', '0', '0', '0']}],
  'appIndex': {'seoTitle': 'Romario Edwards Profile - Cricbuzz | Cricbuzz.com',
   'webURL': 'http://www.cricbuzz.com/profiles/1452215/romario-edwards'},
  'seriesSpinner': [{'seriesName': 'Career'},
   {'seriesId': 11570,
    'seriesName': "ICC Men's T20 2028 World Cup Americas Sub Regional Qualifier B, 2026"}]},
 {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'],
  'values': [{'values': ['Matches', '0', '0', '44', '0']},
   {'values': ['Innings', '0', '0', '19', '0']},
   {'values': ['Runs', '0', '0', '95', '0']},
   {'values': ['Balls', '0', '0', '139', '0']},
   {'values': ['Highest', '0', '0', '32', '0']},
   {'values': ['Average', '0', '0', '5.94', '0']},
   {'values': ['SR', '0', '0', '68.35', '0']},
   {'values': ['Not Out', '0', '0', '3', '0']},
   {'values': ['Fours', '0', '0', '2', '0']},
   {'values': ['Sixes', '0', '0', '2', '0']},
   {'values': ['Ducks', '0', '0', '7', '0']},
   {'values': ['50s', '0', '0', '0', '0']},
   {'values': ['100s', '0', '0', '0', '0']},
   {'values': ['200s', '0', '0', '0', '0']},
   {'values': ['300s', '0', '0', '0', '0']},
   {'values': ['400s', '0', '0', '0', '0']}],
  'appIndex': {'seoTitle': 'Dhruvkumar Maisuria Profile - Cricbuzz | Cricbuzz.com',
   'webURL': 'http://www.cricbuzz.com/profiles/15351/dhruvkumar-maisuria'},
  'seriesSpinner': [{'seriesName': 'Career'},
   {'seriesId': 11711, 'seriesName': 'Lesotho tour of Botswana, 2026'}]},
 {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'],
  'values': [{'values': ['Matches', '0', '0', '26', '0']},
   {'values': ['Innings', '0', '0', '31', '0']},

In [242]:
import pandas as pd

records = []

for player in all_bat2:   # data = your full API response list
    
    headers = player['headers']
    values = player['values']
    
    # Extract player name
    name = player['appIndex']['seoTitle'].split(" Profile")[0]

    for row in values:
        stat = row['values'][0]
        test = row['values'][1]
        odi = row['values'][2]
        t20 = row['values'][3]
        ipl = row['values'][4]

        records.append([name, stat, test, odi, t20, ipl])

df23 = pd.DataFrame(records, columns=[
    "player", "stat", "Test", "ODI", "T20", "IPL"
])

print(df23)

              player     stat Test ODI  T20 IPL
0    Alan Kirschbaum  Matches    0   0   26   0
1    Alan Kirschbaum  Innings    0   0   25   0
2    Alan Kirschbaum     Runs    0   0  298   0
3    Alan Kirschbaum    Balls    0   0  330   0
4    Alan Kirschbaum  Highest    0   0   35   0
..               ...      ...  ...  ..  ...  ..
315    Conroy Wright      50s    0   0    1   0
316    Conroy Wright     100s    0   0    0   0
317    Conroy Wright     200s    0   0    0   0
318    Conroy Wright     300s    0   0    0   0
319    Conroy Wright     400s    0   0    0   0

[320 rows x 6 columns]

In [246]:
df23.iloc[100:150]

                  player     stat Test ODI     T20 IPL
100      Romario Edwards  Highest    0   0       8   0
101      Romario Edwards  Average    0   0       4   0
102      Romario Edwards       SR    0   0   38.10   0
103      Romario Edwards  Not Out    0   0       1   0
104      Romario Edwards    Fours    0   0       0   0
105      Romario Edwards    Sixes    0   0       0   0
106      Romario Edwards    Ducks    0   0       2   0
107      Romario Edwards      50s    0   0       0   0
108      Romario Edwards     100s    0   0       0   0
109      Romario Edwards     200s    0   0       0   0
110      Romario Edwards     300s    0   0       0   0
111      Romario Edwards     400s    0   0       0   0
112  Dhruvkumar Maisuria  Matches    0   0      43   0
113  Dhruvkumar Maisuria  Innings    0   0      18   0
114  Dhruvkumar Maisuria     Runs    0   0      90   0
115  Dhruvkumar Maisuria    Balls    0   0     129   0
116  Dhruvkumar Maisuria  Highest    0   0      32   0
117  Dhruvkumar Maisuria  Average    0   0       6   0
118  Dhruvkumar Maisuria       SR    0   0   69.77   0
119  Dhruvkumar Maisuria  Not Out    0   0       3   0
120  Dhruvkumar Maisuria    Fours    0   0       2   0
121  Dhruvkumar Maisuria    Sixes    0   0       2   0
122  Dhruvkumar Maisuria    Ducks    0   0       7   0
123  Dhruvkumar Maisuria      50s    0   0       0   0
124  Dhruvkumar Maisuria     100s    0   0       0   0
125  Dhruvkumar Maisuria     200s    0   0       0   0
126  Dhruvkumar Maisuria     300s    0   0       0   0
127  Dhruvkumar Maisuria     400s    0   0       0   0
128          Pedro Baron  Matches    0   0      26   0
129          Pedro Baron  Innings    0   0      31   0
130          Pedro Baron     Runs    0   0     693   0
131          Pedro Baron    Balls    0   0     653   0
132          Pedro Baron  Highest    0   0      73   0
133          Pedro Baron  Average    0   0   24.75   0
134          Pedro Baron       SR    0   0  106.13   0
135          Pedro Baron  Not Out    0   0       3   0
136          Pedro Baron    Fours    0   0      78   0
137          Pedro Baron    Sixes    0   0       6   0
138          Pedro Baron    Ducks    0   0       0   0
139          Pedro Baron      50s    0   0       6   0
140          Pedro Baron     100s    0   0       0   0
141          Pedro Baron     200s    0   0       0   0
142          Pedro Baron     300s    0   0       0   0
143          Pedro Baron     400s    0   0       0   0
144        Conroy Wright  Matches    0   0      41   0
145        Conroy Wright  Innings    0   0      28   0
146        Conroy Wright     Runs    0   0     242   0
147        Conroy Wright    Balls    0   0     245   0
148        Conroy Wright  Highest    0   0      50   0
149        Conroy Wright  Average    0   0   14.24   0

In [248]:
import urllib.parse
from sqlalchemy import create_engine

# 1. Encode the special character in password
password = urllib.parse.quote_plus("deepika@88")

# 2. Use the encoded password in your connection string
# Also, ensure 'username' is replaced with your actual DB user (usually 'postgres')
engine = create_engine(f'postgresql+psycopg2://postgres:{password}@localhost:5432/cricbuzz')

# 3. Test the connection and push the data
df23.to_sql('df23_test', engine, if_exists='replace', index=False)

print("✅ Connection successful and table '23table' created!")

✅ Connection successful and table '23table' created!

# Q24 analysis

In [105]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/78642/scard"

headers = {
	"x-rapidapi-key": "35af2ec44amsh9bf8173e77da1c2p13358ejsn3a9ce0e712f9",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

msc = response.json()

In [84]:
msc

{'scorecard': [{'inningsid': 1,
   'batsman': [{'id': 8271,
     'balls': 3,
     'runs': 1,
     'fours': 0,
     'sixes': 0,
     'strkrate': '33.33',
     'name': 'Samson',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': True,
     'outdec': 'c Brydon Carse b Saqib Mahmood',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 12086,
     'balls': 19,
     'runs': 29,
     'fours': 4,
     'sixes': 1,
     'strkrate': '152.63',
     'name': 'Abhishek Sharma',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c Jacob Bethell b Adil Rashid',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 14504,
     'balls': 1,
     'runs': 0,
     'fours': 0,
     'sixes': 0,
     'strkrate': '0',
     'name': 'Tilak Varma',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c Jofra Archer b Saqib Mahmood',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 7915,
     'balls': 4,
     'runs': 0,
     'fours': 0,
     'sixes': 0,
     'strkrate': '0',
     'name': 'Suryakumar Yadav',
     'nickname': '',
     'iscaptain': True,
     'iskeeper': False,
     'outdec': 'c Brydon Carse b Saqib Mahmood',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 10896,
     'balls': 26,
     'runs': 30,
     'fours': 4,
     'sixes': 1,
     'strkrate': '115.38',
     'name': 'Rinku Singh',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c Adil Rashid b Brydon Carse',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': 'IN'},
    {'id': 11195,
     'balls': 34,
     'runs': 53,
     'fours': 7,
     'sixes': 2,
     'strkrate': '155.88',
     'name': 'Shivam Dube',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'run out (Jos Buttler)',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': 'MOUT',
     'isoverseas': False,
     'playingxichange': 'IN'},
    {'id': 9647,
     'balls': 30,
     'runs': 53,
     'fours': 4,
     'sixes': 4,
     'strkrate': '176.67',
     'name': 'Hardik Pandya',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c Jos Buttler b Jamie Overton',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 8808,
     'balls': 4,
     'runs': 5,
     'fours': 0,
     'sixes': 0,
     'strkrate': '125',
     'name': 'Axar',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c Jacob Bethell b Jamie Overton',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 13217,
     'balls': 1,
     'runs': 0,
     'fours': 0,
     'sixes': 0,
     'strkrate': '0',
     'name': 'Arshdeep Singh',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'run out (Salt/Jamie Overton)',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': 'IN'},
    {'id': 14659,
     'balls': 0,
     'runs': 0,
     'fours': 0,
     'sixes': 0,
     'strkrate': '0',
     'name': 'Ravi Bishnoi',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'not out',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 12926,
     'balls': 0,
     'runs': 0,
     'fours': 0,
     'sixes': 0,
     'strkrate': '0',
     'name': 'Varun Chakravarthy',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': '',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 24729,
     'balls': 0,
     'runs': 0,
     'fours': 0,
     'sixes': 0,
     'strkrate': '0',
     'name': 'Harshit Rana',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': '',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': 'MIN',
     'isoverseas': False,
     'playingxichange': 'IN'}],
   'bowler': [{'id': 11540,
     'overs': '4',
     'maidens': 0,
     'wickets': 0,
     'runs': 37,
     'economy': '9.2',
     'name': 'Jofra Archer',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'dots': 0,
     'balls': 24,
     'rpb': 0.0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 10394,
     'overs': '4',
     'maidens': 1,
     'wickets': 3,
     'runs': 35,
     'economy': '8.8',
     'name': 'Saqib Mahmood',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'dots': 0,
     'balls': 24,
     'rpb': 0.0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': 'IN'},
    {'id': 11436,
     'overs': '4',
     'maidens': 0,
     'wickets': 1,
     'runs': 39,
     'economy': '9.8',
     'name': 'Brydon Carse',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'dots': 0,
     'balls': 24,
     'rpb': 0.0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 8512,
     'overs': '4',
     'maidens': 0,
     'wickets': 2,
     'runs': 32,
     'economy': '8',
     'name': 'Jamie Overton',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'dots': 0,
     'balls': 24,
     'rpb': 0.0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 1742,
     'overs': '4',
     'maidens': 0,
     'wickets': 1,
     'runs': 35,
     'economy': '8.8',
     'name': 'Adil Rashid',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'dots': 0,
     'balls': 24,
     'rpb': 0.0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''}],
   'fow': {'fow': [{'batsmanid': 8271,
      'batsmanname': 'Samson',
      'overnbr': 1.1,
      'runs': 12,
      'ballnbr': 7},
     {'batsmanid': 14504,
      'batsmanname': 'Tilak Varma',
      'overnbr': 1.2,
      'runs': 12,
      'ballnbr': 8},
     {'batsmanid': 7915,
      'batsmanname': 'Suryakumar Yadav',
      'overnbr': 1.6,
      'runs': 12,
      'ballnbr': 12},
     {'batsmanid': 12086,
      'batsmanname': 'Abhishek Sharma',
      'overnbr': 7.2,
      'runs': 57,
      'ballnbr': 44},
     {'batsmanid': 10896,
      'batsmanname': 'Rinku Singh',
      'overnbr': 10.4,
      'runs': 79,
      'ballnbr': 64},
     {'batsmanid': 9647,
      'batsmanname': 'Hardik Pandya',
      'overnbr': 17.6,
      'runs': 166,
      'ballnbr': 108},
     {'batsmanid': 8808,
      'batsmanname': 'Axar',
      'overnbr': 19.2,
      'runs': 180,
      'ballnbr': 116},
     {'batsmanid': 13217,
      'batsmanname': 'Arshdeep Singh',
      'overnbr': 19.3,
      'runs': 180,
      'ballnbr': 117},
     {'batsmanid': 11195,
      'batsmanname': 'Shivam Dube',
      'overnbr': 20.0,
      'runs': 181,
      'ballnbr': 120}]},
   'extras': {'legbyes': 3,
    'byes': 0,
    'wides': 5,
    'noballs': 2,
    'penalty': 0,
    'total': 10},
   'pp': {'powerplay': [{'id': 1,
      'ovrfrom': 0.1,
      'ovrto': 6.0,
      'pptype': 'Mandatory',
      'run': 47,
      'wickets': 0}]},
   'score': 181,
   'wickets': 9,
   'overs': 20.0,
   'runrate': 9.05,
   'batteamname': 'India',
   'batteamsname': 'IND',
   'isdeclared': False,
   'isfollowon': False,
   'ballnbr': 120,
   'rpb': 1.51,
   'partnership': {'partnership': [{'id': 0,
      'bat1id': 8271,
      'bat1name': 'Samson',
      'bat1runs': 1,
      'bat1fours': 0,
      'bat1sixes': 0,
      'bat2id': 12086,
      'bat2name': 'Abhishek Sharma',
      'bat2runs': 10,
      'bat2fours': 1,
      'bat2sixes': 1,
      'totalruns': 12,
      'totalballs': 7,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 14504,
      'bat1name': 'Tilak Varma',
      'bat1runs': 0,
      'bat1fours': 0,
      'bat1sixes': 0,
      'bat2id': 12086,
      'bat2name': 'Abhishek Sharma',
      'bat2runs': 0,
      'bat2fours': 0,
      'bat2sixes': 0,
      'totalruns': 0,
      'totalballs': 1,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 7915,
      'bat1name': 'Suryakumar Yadav',
      'bat1runs': 0,
      'bat1fours': 0,
      'bat1sixes': 0,
      'bat2id': 12086,
      'bat2name': 'Abhishek Sharma',
      'bat2runs': 0,
      'bat2fours': 0,
      'bat2sixes': 0,
      'totalruns': 0,
      'totalballs': 4,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 10896,
      'bat1name': 'Rinku Singh',
      'bat1runs': 25,
      'bat1fours': 4,
      'bat1sixes': 1,
      'bat2id': 12086,
      'bat2name': 'Abhishek Sharma',
      'bat2runs': 19,
      'bat2fours': 3,
      'bat2sixes': 0,
      'totalruns': 45,
      'totalballs': 32,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 10896,
      'bat1name': 'Rinku Singh',
      'bat1runs': 5,
      'bat1fours': 0,
      'bat1sixes': 0,
      'bat2id': 11195,
      'bat2name': 'Shivam Dube',
      'bat2runs': 13,
      'bat2fours': 1,
      'bat2sixes': 1,
      'totalruns': 22,
      'totalballs': 21,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 9647,
      'bat1name': 'Hardik Pandya',
      'bat1runs': 53,
      'bat1fours': 4,
      'bat1sixes': 4,
      'bat2id': 11195,
      'bat2name': 'Shivam Dube',
      'bat2runs': 30,
      'bat2fours': 4,
      'bat2sixes': 1,
      'totalruns': 87,
      'totalballs': 45,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 8808,
      'bat1name': 'Axar',
      'bat1runs': 5,
      'bat1fours': 0,
      'bat1sixes': 0,
      'bat2id': 11195,
      'bat2name': 'Shivam Dube',
      'bat2runs': 9,
      'bat2fours': 2,
      'bat2sixes': 0,
      'totalruns': 14,
      'totalballs': 8,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 13217,
      'bat1name': 'Arshdeep Singh',
      'bat1runs': 0,
      'bat1fours': 0,
      'bat1sixes': 0,
      'bat2id': 11195,
      'bat2name': 'Shivam Dube',
      'bat2runs': 0,
      'bat2fours': 0,
      'bat2sixes': 0,
      'totalruns': 0,
      'totalballs': 1,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 14659,
      'bat1name': 'Ravi Bishnoi',
      'bat1runs': 0,
      'bat1fours': 0,
      'bat1sixes': 0,
      'bat2id': 11195,
      'bat2name': 'Shivam Dube',
      'bat2runs': 0,
      'bat2fours': 0,
      'bat2sixes': 0,
      'totalruns': 0,
      'totalballs': 3,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0}]}},
  {'inningsid': 2,
   'batsman': [{'id': 10479,
     'balls': 21,
     'runs': 23,
     'fours': 4,
     'sixes': 0,
     'strkrate': '109.52',
     'name': 'Philip Salt',
     'nickname': 'Salt',
     'iscaptain': False,
     'iskeeper': True,
     'outdec': 'b Axar',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 8502,
     'balls': 19,
     'runs': 39,
     'fours': 7,
     'sixes': 1,
     'strkrate': '205.26',
     'name': 'Ben Duckett',
     'nickname': 'Duckett',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c Suryakumar Yadav b Ravi Bishnoi',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 2258,
     'balls': 3,
     'runs': 2,
     'fours': 0,
     'sixes': 0,
     'strkrate': '66.67',
     'name': 'Jos Buttler',
     'nickname': 'Jos Buttler',
     'iscaptain': True,
     'iskeeper': False,
     'outdec': 'c Harshit Rana b Ravi Bishnoi',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 12201,
     'balls': 26,
     'runs': 51,
     'fours': 5,
     'sixes': 2,
     'strkrate': '196.15',
     'name': 'Harry Brook',
     'nickname': 'Harry Brook',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c Arshdeep Singh b Varun Chakravarthy',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 10045,
     'balls': 13,
     'runs': 9,
     'fours': 0,
     'sixes': 0,
     'strkrate': '69.23',
     'name': 'Liam Livingstone',
     'nickname': 'Livingstone',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c Samson b Harshit Rana',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 19636,
     'balls': 9,
     'runs': 6,
     'fours': 0,
     'sixes': 0,
     'strkrate': '66.67',
     'name': 'Jacob Bethell',
     'nickname': 'Jacob Bethell',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c Suryakumar Yadav b Harshit Rana',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': 'IN'},
    {'id': 11436,
     'balls': 2,
     'runs': 0,
     'fours': 0,
     'sixes': 0,
     'strkrate': '0',
     'name': 'Brydon Carse',
     'nickname': 'Brydon Carse',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c Rinku Singh b Varun Chakravarthy',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',

In [106]:
# 1. Get the list of innings
scard = msc.get('scorecard', [])

# 2. Check if the list actually has data before accessing index 0
if scard:
    # Get partnership from the first innings (index 0)
    scard_partner = scard[0].get('partnership', [])
    
    # Get batsman from the first innings (index 0)
    scard_batting = scard[0].get('batsman', [])
else:
    # Provide empty lists if the scorecard is missing
    scard_partner = []
    scard_batting = []

In [29]:
match_idq22

[100301,
 75542,
 100310,
 100312,
 100321,
 100328,
 78635,
 78642,
 100283,
 100290,
 78628,
 100292,
 60009,
 60016,
 60023,
 60028,
 60035]

# Q24 answer

In [107]:
partnership_list = []

scorecard = msc.get("scorecard", [])

for inning in scorecard:

    partnerships = inning.get("partnership", {})

    for p in partnerships.values():

        if isinstance(p, list):

            for part in p:

                partnership_list.append({

                    "match_id": match_idq22[7],

                    "innings_id": inning.get("inningsid"),

                    "bat1_name": part.get("bat1name"),

                    "bat1_runs": part.get("bat1runs"),

                    "bat2_name": part.get("bat2name"),

                    "bat2_runs": part.get("bat2runs"),

                    "total_partnership_runs": part.get("totalruns"),

                    "total_balls": part.get("totalballs")

                })

        else:

            partnership_list.append({

                "match_id": match_idq22[3],

                "innings_id": inning.get("inningsid"),

                "bat1_name": p.get("bat1name"),
                "bat1_runs": p.get("bat1runs"),

                "bat2_name": p.get("bat2name"),
                "bat2_runs": p.get("bat2runs"),

                "total_partnership_runs": p.get("totalruns"),

                "total_balls": p.get("totalballs")

            })

df_partnership = pd.DataFrame(partnership_list)

print(df_partnership)

    match_id  innings_id      bat1_name  bat1_runs      bat2_name  bat2_runs  \
0      78642           1        Jaiswal         10          Rohit         11
1      78642           1   Shubman Gill          0          Rohit          2
2      78642           1  Rajat Patidar          5          Rohit          4
3      78642           1         Jadeja         84          Rohit        114
4      78642           1         Jadeja         15  Sarfaraz Khan         62
5      78642           1         Jadeja         13  Kuldeep Yadav          4
6      78642           1         Jadeja          0    Dhruv Jurel          0
7      78642           1         Ashwin         37    Dhruv Jurel         39
8      78642           1         Bumrah          0    Dhruv Jurel          7
9      78642           1         Bumrah         26          Siraj          3
10     78642           2        Crawley         15        Duckett         68
11     78642           2     Ollie Pope         39        Duckett         51
12     78642           2           Root         18        Duckett         22
13     78642           2       Bairstow          0        Duckett          1
14     78642           2         Stokes         20        Duckett         11
15     78642           2         Stokes         21         Foakes         13
16     78642           2    Rehan Ahmed          0         Foakes          0
17     78642           2    Rehan Ahmed          6    Tom Hartley          9
18     78642           2      Mark Wood          0    Tom Hartley          0
19     78642           2      Mark Wood          4       Anderson          1
20     78642           3        Jaiswal         10          Rohit         19
21     78642           3        Jaiswal         94   Shubman Gill         57
22     78642           3  Rajat Patidar          0   Shubman Gill          6
23     78642           3  Kuldeep Yadav         26   Shubman Gill         28
24     78642           3  Kuldeep Yadav          1        Jaiswal         11
25     78642           3  Sarfaraz Khan         68        Jaiswal         99
26     78642           4        Crawley         11        Duckett          4
27     78642           4        Crawley          0     Ollie Pope          2
28     78642           4           Root          1     Ollie Pope          1
29     78642           4           Root          4       Bairstow          4
30     78642           4           Root          2         Stokes         15
31     78642           4         Foakes          0         Stokes          0
32     78642           4         Foakes          0    Rehan Ahmed          0
33     78642           4         Foakes         16    Tom Hartley         16
34     78642           4      Mark Wood          8    Tom Hartley          0
35     78642           4      Mark Wood         25       Anderson          1

    total_partnership_runs  total_balls
0                       22           24
1                        2           11
2                        9           19
3                      204          329
4                       77          110
5                       17           47
6                        0            7
7                       77          175
8                        7           23
9                       30           42
10                      84           80
11                      93          102
12                      42           61
13                       1            5
14                      35           57
15                      39           89
16                       0            1
17                      15           28
18                       0            3
19                       5            5
20                      30           69
21                     155          195
22                       6           22
23                      55           98
24                      12           46
25                     172          158
26                      15           37
27                       3           13
28                       2            8
29                       8            9
30                      22           65
31                       0            6
32                       0           11
33                      32           67
34                       9            3
35                      31           22

In [87]:
df_partnership

,match_id,innings_id,bat1_name,bat1_runs,bat2_name,bat2_runs,total_partnership_runs,total_balls
0,100301,1,Samson,1,Abhishek Sharma,10,12,7
1,100301,1,Tilak Varma,0,Abhishek Sharma,0,0,1
2,100301,1,Suryakumar Yadav,0,Abhishek Sharma,0,0,4
3,100301,1,Rinku Singh,25,Abhishek Sharma,19,45,32
4,100301,1,Rinku Singh,5,Shivam Dube,13,22,21
5,100301,1,Hardik Pandya,53,Shivam Dube,30,87,45
6,100301,1,Axar,5,Shivam Dube,9,14,8
7,100301,1,Arshdeep Singh,0,Shivam Dube,0,0,1
8,100301,1,Ravi Bishnoi,0,Shivam Dube,0,0,3
9,100301,2,Philip Salt,22,Duckett,39,62,36
10,100301,2,Philip Salt,1,Buttler,1,3,5
11,100301,2,Brook,1,Buttler,1,2,4
12,100301,2,Brook,19,Livingstone,9,28,23
13,100301,2,Brook,31,Jacob Bethell,3,34,19
14,100301,2,Brydon Carse,0,Jacob Bethell,0,4,2
15,100301,2,Jamie Overton,1,Jacob Bethell,3,4,6
16,100301,2,Jamie Overton,9,Jofra Archer,0,9,6
17,100301,2,Jamie Overton,9,Adil Rashid,8,17,13
18,100301,2,Saqib Mahmood,1,Adil Rashid,2,3,4

In [108]:
import urllib.parse
from sqlalchemy import create_engine

# 1. Encode the special character in password
password = urllib.parse.quote_plus("deepika@88")

# 2. Use the encoded password in your connection string
# Also, ensure 'username' is replaced with your actual DB user (usually 'postgres')
engine = create_engine(f'postgresql+psycopg2://postgres:{password}@localhost:5432/cricbuzz')

# 3. Test the connection and push the data
df_partnership.to_sql('scard_partner_clone', engine, if_exists='append', index=False)

print("✅ Connection successful and table 'scard_partner_clone' created!")

✅ Connection successful and table 'scard_partner_clone' created!

# streamlit top player works

In [23]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/topstats/0"

querystring = {"statsType":"mostRuns","year":"2025","matchType":"1"}

headers = {
	"x-rapidapi-key": "095038d962msh9068af945c80bc9p1ad37cjsna03b2a42de54",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com",
	"Content-Type": "application/json"
}

response = requests.get(url, headers=headers, params=querystring)

topst2025 = response.json()

In [24]:
topst2025

{'filter': {'matchtype': [{'matchTypeId': '1', 'matchTypeDesc': 'test'},
   {'matchTypeId': '2', 'matchTypeDesc': 'odi'},
   {'matchTypeId': '3', 'matchTypeDesc': 't20i'}],
  'team': [{'id': '2', 'teamShortName': 'IND'},
   {'id': '27', 'teamShortName': 'IRE'},
   {'id': '3', 'teamShortName': 'PAK'},
   {'id': '4', 'teamShortName': 'AUS'},
   {'id': '5', 'teamShortName': 'SL'},
   {'id': '6', 'teamShortName': 'BAN'},
   {'id': '9', 'teamShortName': 'ENG'},
   {'id': '10', 'teamShortName': 'WI'},
   {'id': '11', 'teamShortName': 'RSA'},
   {'id': '12', 'teamShortName': 'ZIM'},
   {'id': '13', 'teamShortName': 'NZ'},
   {'id': '96', 'teamShortName': 'AFG'}],
  'selectedMatchType': 'test',
  'selectedYear': '2025'},
 'headers': ['Batter', 'M', 'I', 'R', 'Avg'],
 'values': [{'values': ['11808', 'Shubman Gill', '9', '16', '983', '65.53']},
  {'values': ['8497', 'Travis Head', '11', '21', '817', '40.85']},
  {'values': ['8733', 'Rahul', '10', '19', '813', '45.17']},
  {'values': ['8019', 'Root', '10', '18', '805', '50.31']},
  {'values': ['12201', 'Harry Brook', '10', '18', '771', '45.35']},
  {'values': ['9200', 'Alex Carey', '11', '17', '767', '47.94']},
  {'values': ['587', 'Ravindra Jadeja', '10', '17', '764', '63.67']},
  {'values': ['13940', 'Yashasvi Jaiswal', '10', '19', '745', '39.21']},
  {'values': ['8502', 'Ben Duckett', '10', '18', '735', '40.83']},
  {'values': ['9838', 'Devon Conway', '5', '9', '697', '87.12']},
  {'values': ['12770', 'Zak Crawley', '10', '18', '670', '37.22']},
  {'values': ['11200', 'Mulder', '7', '12', '669', '66.90']},
  {'values': ['2250', 'Steven Smith', '9', '16', '651', '50.08']},
  {'values': ['441', 'Sean Williams', '8', '16', '648', '43.20']},
  {'values': ['10744', 'Rishabh Pant', '7', '13', '629', '48.38']},
  {'values': ['6635', 'Khawaja', '10', '18', '614', '36.12']},
  {'values': ['11691', 'Ollie Pope', '9', '16', '602', '37.62']},
  {'values': ['13810', 'Jamie Smith', '10', '18', '577', '41.21']},
  {'values': ['13070', 'Ryan Rickelton', '6', '11', '540', '54.00']},
  {'values': ['10384', 'Shai Hope', '8', '16', '534', '33.38']}],
 'appIndex': {'seoTitle': 'Live cricket scores, schedule, news, archive, series | Cricbuzz.com',
  'webURL': 'www.cricbuzz.com'}}

In [26]:
print(topst2025.keys())

dict_keys(['filter', 'headers', 'values', 'appIndex'])

In [ ]:
# Assuming 'response_data' is the variable containing your JSON
top2025 = []
columns = ['playerID', 'Player', 'Matches', 'Innings', 'Runs', 'Avg']
#access the list of players from the teams/players
for player in topst2025.get('player',[]):
    details = {
        "player_id" : player.get("id"),
        "full_name" : player.get("name"),
        "batting_style" : player.get("battingStyle"),
        "bowling_style" : player.get("bowlingStyle")
    }
    indianplayers.append(details)

NameError: name 'response_data' is not defined

# Q25 analysis

In [110]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/1413/batting"

headers = {
	"x-rapidapi-key": "35af2ec44amsh9bf8173e77da1c2p13358ejsn3a9ce0e712f9",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com",
	"Content-Type": "application/json"
}

response = requests.get(url, headers=headers)

virat = response.json()

In [111]:
virat

{'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'],
 'values': [{'values': ['Matches', '123', '311', '125', '267']},
  {'values': ['Innings', '210', '299', '117', '259']},
  {'values': ['Runs', '9230', '14797', '4188', '8661']},
  {'values': ['Balls', '16608', '15771', '3056', '6519']},
  {'values': ['Highest', '254', '183', '122', '113']},
  {'values': ['Average', '46.85', '58.72', '48.7', '39.55']},
  {'values': ['SR', '55.58', '93.83', '137.05', '132.86']},
  {'values': ['Not Out', '13', '47', '31', '40']},
  {'values': ['Fours', '1027', '1376', '369', '771']},
  {'values': ['Sixes', '30', '169', '124', '291']},
  {'values': ['Ducks', '15', '18', '7', '10']},
  {'values': ['50s', '31', '77', '38', '63']},
  {'values': ['100s', '30', '54', '1', '8']},
  {'values': ['200s', '7', '0', '0', '0']},
  {'values': ['300s', '0', '0', '0', '0']},
  {'values': ['400s', '0', '0', '0', '0']}],
 'appIndex': {'seoTitle': 'Virat Kohli Profile - Cricbuzz | Cricbuzz.com',
  'webURL': 'http://www.cricbuzz.com/profiles/1413/virat-kohli'},
 'seriesSpinner': [{'seriesName': 'Career'}]}

In [148]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/87878/scard"

headers = {
	"x-rapidapi-key": "35af2ec44amsh9bf8173e77da1c2p13358ejsn3a9ce0e712f9",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com",
	"Content-Type": "application/json"
}

response = requests.get(url, headers=headers)

vk1 = response.json()

In [115]:
vk1

{'scorecard': [{'inningsid': 1,
   'batsman': [{'id': 9838,
     'balls': 4,
     'runs': 5,
     'fours': 1,
     'sixes': 0,
     'strkrate': '125',
     'name': 'Devon Conway',
     'nickname': 'Conway',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c Rohit b Harshit Rana',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 10694,
     'balls': 1,
     'runs': 0,
     'fours': 0,
     'sixes': 0,
     'strkrate': '0',
     'name': 'Henry Nicholls',
     'nickname': 'Henry Nicholls',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'b Arshdeep Singh',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 8549,
     'balls': 41,
     'runs': 30,
     'fours': 5,
     'sixes': 1,
     'strkrate': '73.17',
     'name': 'Will Young',
     'nickname': 'Will Young',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c Ravindra Jadeja b Harshit Rana',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 10713,
     'balls': 131,
     'runs': 137,
     'fours': 15,
     'sixes': 3,
     'strkrate': '104.58',
     'name': 'Daryl Mitchell',
     'nickname': 'Daryl Mitchell',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c Kuldeep Yadav b Siraj',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 10693,
     'balls': 88,
     'runs': 106,
     'fours': 9,
     'sixes': 3,
     'strkrate': '120.45',
     'name': 'Glenn Phillips',
     'nickname': 'Glenn Phillips',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c Rahul b Arshdeep Singh',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 9551,
     'balls': 18,
     'runs': 28,
     'fours': 1,
     'sixes': 3,
     'strkrate': '155.56',
     'name': 'Michael Bracewell',
     'nickname': 'Michael Bracewell',
     'iscaptain': True,
     'iskeeper': False,
     'outdec': 'not out',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 18612,
     'balls': 6,
     'runs': 2,
     'fours': 0,
     'sixes': 0,
     'strkrate': '33.33',
     'name': 'Mitchell Hay',
     'nickname': 'Mitchell Hay',
     'iscaptain': False,
     'iskeeper': True,
     'outdec': 'lbw b Kuldeep Yadav',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 24391,
     'balls': 8,
     'runs': 10,
     'fours': 1,
     'sixes': 0,
     'strkrate': '125',
     'name': 'Zakary Foulkes',
     'nickname': 'Zakary Foulkes',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c Kuldeep Yadav b Arshdeep Singh',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 15197,
     'balls': 5,
     'runs': 11,
     'fours': 1,
     'sixes': 1,
     'strkrate': '220',
     'name': 'Kristian Clarke',
     'nickname': 'Kristian Clarke',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'b Harshit Rana',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 9441,
     'balls': 0,
     'runs': 0,
     'fours': 0,
     'sixes': 0,
     'strkrate': '0',
     'name': 'Kyle Jamieson',
     'nickname': 'Jamieson',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'not out',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 15769,
     'balls': 0,
     'runs': 0,
     'fours': 0,
     'sixes': 0,
     'strkrate': '0',
     'name': 'Jayden Lennox',
     'nickname': 'Jayden Lennox',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': '',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''}],
   'bowler': [{'id': 13217,
     'overs': '10',
     'maidens': 1,
     'wickets': 3,
     'runs': 63,
     'economy': '6.3',
     'name': 'Arshdeep Singh',
     'nickname': 'Arshdeep Singh',
     'iscaptain': False,
     'iskeeper': False,
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'dots': 0,
     'balls': 60,
     'rpb': 0.0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': 'IN'},
    {'id': 24729,
     'overs': '10',
     'maidens': 0,
     'wickets': 3,
     'runs': 84,
     'economy': '8.4',
     'name': 'Harshit Rana',
     'nickname': 'Harshit Rana',
     'iscaptain': False,
     'iskeeper': False,
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'dots': 0,
     'balls': 60,
     'rpb': 0.0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 10808,
     'overs': '10',
     'maidens': 0,
     'wickets': 1,
     'runs': 43,
     'economy': '4.3',
     'name': 'Mohammed Siraj',
     'nickname': 'Siraj',
     'iscaptain': False,
     'iskeeper': False,
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'dots': 0,
     'balls': 60,
     'rpb': 0.0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 14701,
     'overs': '8',
     'maidens': 0,
     'wickets': 0,
     'runs': 53,
     'economy': '6.6',
     'name': 'Nitish Kumar Reddy',
     'nickname': 'Nitish Reddy',
     'iscaptain': False,
     'iskeeper': False,
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'dots': 0,
     'balls': 48,
     'rpb': 0.0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 8292,
     'overs': '6',
     'maidens': 0,
     'wickets': 1,
     'runs': 48,
     'economy': '8',
     'name': 'Kuldeep Yadav',
     'nickname': 'Kuldeep Yadav',
     'iscaptain': False,
     'iskeeper': False,
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'dots': 0,
     'balls': 36,
     'rpb': 0.0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 587,
     'overs': '6',
     'maidens': 0,
     'wickets': 0,
     'runs': 41,
     'economy': '6.8',
     'name': 'Ravindra Jadeja',
     'nickname': 'Ravindra Jadeja',
     'iscaptain': False,
     'iskeeper': False,
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'dots': 0,
     'balls': 36,
     'rpb': 0.0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''}],
   'fow': {'fow': [{'batsmanid': 10694,
      'batsmanname': 'Henry Nicholls',
      'overnbr': 0.4,
      'runs': 5,
      'ballnbr': 4},
     {'batsmanid': 9838,
      'batsmanname': 'Devon Conway',
      'overnbr': 1.1,
      'runs': 5,
      'ballnbr': 7},
     {'batsmanid': 8549,
      'batsmanname': 'Will Young',
      'overnbr': 12.1,
      'runs': 58,
      'ballnbr': 73},
     {'batsmanid': 10693,
      'batsmanname': 'Glenn Phillips',
      'overnbr': 43.1,
      'runs': 277,
      'ballnbr': 259},
     {'batsmanid': 10713,
      'batsmanname': 'Daryl Mitchell',
      'overnbr': 44.1,
      'runs': 283,
      'ballnbr': 265},
     {'batsmanid': 18612,
      'batsmanname': 'Mitchell Hay',
      'overnbr': 45.2,
      'runs': 286,
      'ballnbr': 272},
     {'batsmanid': 24391,
      'batsmanname': 'Zakary Foulkes',
      'overnbr': 47.1,
      'runs': 304,
      'ballnbr': 283},
     {'batsmanid': 15197,
      'batsmanname': 'Kristian Clarke',
      'overnbr': 48.6,
      'runs': 327,
      'ballnbr': 294}]},
   'extras': {'legbyes': 0,
    'byes': 5,
    'wides': 1,
    'noballs': 2,
    'penalty': 0,
    'total': 8},
   'pp': {'powerplay': [{'id': 25,
      'ovrfrom': 0.1,
      'ovrto': 10.0,
      'pptype': 'Mandatory',
      'run': 47,
      'wickets': 0}]},
   'score': 337,
   'wickets': 8,
   'overs': 50.0,
   'runrate': 6.74,
   'batteamname': 'New Zealand',
   'batteamsname': 'NZ',
   'isdeclared': False,
   'isfollowon': False,
   'ballnbr': 300,
   'rpb': 1.12,
   'partnership': {'partnership': [{'id': 0,
      'bat1id': 9838,
      'bat1name': 'Conway',
      'bat1runs': 5,
      'bat1fours': 1,
      'bat1sixes': 0,
      'bat2id': 10694,
      'bat2name': 'Nicholls',
      'bat2runs': 0,
      'bat2fours': 0,
      'bat2sixes': 0,
      'totalruns': 5,
      'totalballs': 4,
      'bat1balls': 3,
      'bat2balls': 1,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 1,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 1,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 9838,
      'bat1name': 'Conway',
      'bat1runs': 0,
      'bat1fours': 0,
      'bat1sixes': 0,
      'bat2id': 8549,
      'bat2name': 'Will Young',
      'bat2runs': 0,
      'bat2fours': 0,
      'bat2sixes': 0,
      'totalruns': 0,
      'totalballs': 3,
      'bat1balls': 1,
      'bat2balls': 2,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 10713,
      'bat1name': 'Mitchell',
      'bat1runs': 22,
      'bat1fours': 4,
      'bat1sixes': 0,
      'bat2id': 8549,
      'bat2name': 'Will Young',
      'bat2runs': 30,
      'bat2fours': 5,
      'bat2sixes': 1,
      'totalruns': 53,
      'totalballs': 66,
      'bat1balls': 27,
      'bat2balls': 39,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 6,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 4,
      'bat1sixers': 0,
      'bat2ones': 4,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 5,
      'bat2sixers': 1},
     {'id': 0,
      'bat1id': 10713,
      'bat1name': 'Mitchell',
      'bat1runs': 110,
      'bat1fours': 10,
      'bat1sixes': 3,
      'bat2id': 10693,
      'bat2name': 'Phillips',
      'bat2runs': 106,
      'bat2fours': 9,
      'bat2sixes': 3,
      'totalruns': 219,
      'totalballs': 186,
      'bat1balls': 100,
      'bat2balls': 88,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 50,
      'bat1twos': 1,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 10,
      'bat1sixers': 3,
      'bat2ones': 52,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 9,
      'bat2sixers': 3},
     {'id': 0,
      'bat1id': 10713,
      'bat1name': 'Mitchell',
      'bat1runs': 5,
      'bat1fours': 1,
      'bat1sixes': 0,
      'bat2id': 9551,
      'bat2name': 'Michael Bracewell',
      'bat2runs': 1,
      'bat2fours': 0,
      'bat2sixes': 0,
      'totalruns': 6,
      'totalballs': 6,
      'bat1balls': 4,
      'bat2balls': 2,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 1,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 1,
      'bat1sixers': 0,
      'bat2ones': 1,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 18612,
      'bat1name': 'Mitchell Hay',
      'bat1runs': 2,
      'bat1fours': 0,
      'bat1sixes': 0,
      'bat2id': 9551,
      'bat2name': 'Michael Bracewell',
      'bat2runs': 1,
      'bat2fours': 0,
      'bat2sixes': 0,
      'totalruns': 3,
      'totalballs': 7,
      'bat1balls': 6,
      'bat2balls': 1,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 1,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 1,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 24391,
      'bat1name': 'Foulkes',
      'bat1runs': 10,
      'bat1fours': 1,
      'bat1sixes': 0,
      'bat2id': 9551,
      'bat2name': 'Michael Bracewell',
      'bat2runs': 8,
      'bat2fours': 0,
      'bat2sixes': 1,
      'totalruns': 18,
      'totalballs': 11,
      'bat1balls': 8,
      'bat2balls': 3,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 4,
      'bat1twos': 1,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 1,
      'bat1sixers': 0,
      'bat2ones': 2,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 1},
     {'id': 0,
      'bat1id': 15197,
      'bat1name': 'Kristian Clarke',
      'bat1runs': 11,
      'bat1fours': 1,
      'bat1sixes': 1,
      'bat2id': 9551,
      'bat2name': 'Michael Bracewell',
      'bat2runs': 12,
      'bat2fours': 1,
      'bat2sixes': 1,
      'totalruns': 23,
      'totalballs': 11,
      'bat1balls': 5,
      'bat2balls': 6,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 1,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 1,
      'bat1sixers': 1,
      'bat2ones': 2,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 1,
      'bat2sixers': 1},
     {'id': 0,
      'bat1id': 9441,
      'bat1name': 'Jamieson',
      'bat1runs': 0,
      'bat1fours': 0,
      'bat1sixes': 0,
      'bat2id': 9551,
      'bat2name': 'Michael Bracewell',
      'bat2runs': 6,
      'bat2fours': 0,
      'bat2sixes': 1,
      'totalruns': 10,
      'totalballs': 6,
      'bat1balls': 0,
      'bat2balls': 6,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 1}]}},
  {'inningsid': 2,
   'batsman': [{'id': 576,
     'balls': 13,
     'runs': 11,
     'fours': 2,
     'sixes': 0,
     'strkrate': '84.62',
     'name': 'Rohit Sharma',
     'nickname': 'Rohit',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c Kristian Clarke b Zakary Foulkes',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 11808,
     'balls': 18,
     'runs': 23,
     'fours': 4,
     'sixes': 0,
     'strkrate': '127.78',
     'name': 'Shubman Gill',
     'nickname': 'Shubman Gill',
     'iscaptain': True,
     'iskeeper': False,
     'outdec': 'b Jamieson',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 1413,
     'balls': 108,
     'runs': 124,
     'fours': 10,
     'sixes': 3,
     'strkrate': '114.81',
     'name': 'Virat Kohli',
     'nickname': 'Kohli',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c Daryl Mitchell b Kristian Clarke',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 9428,
     'balls': 10,
     'runs': 3,
     'fours': 0,
     'sixes': 0,
     'strkrate': '30',
     'name': 'Shreyas Iyer',
     'nickname': 'Shreyas Iyer',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c Zakary Foulkes b Kristian Clarke',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 8733,
     'balls': 6,
     'runs': 1,
     'fours': 0,
     'sixes': 0,
     'strkrate': '16.67',
     'name': 'KL Rahul',
     'nickname': 'Rahul',
     'iscaptain': False,
     'iskeeper': True,
     'outdec': 'c Glenn Phillips b Jayden Lennox',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 14701,
     'balls': 57,
     'runs': 53,
     'fours': 2,
     'sixes': 2,
     'strkrate': '92.98',
     'name': 'Nitish Kumar Reddy',
     'nickname': 'Nitish Reddy',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c Will Young b Kristian Clarke',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 587,
     'balls': 16,
     'runs': 12,
     'fours': 0,
     'sixes': 0,
     'strkrate': '75',
     'name': 'Ravindra Jadeja',
     'nickname': 'Ravindra Jadeja',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c Will Young b Jayden Lennox',
     'videotype': '',
     'videourl': '',

In [149]:
from datetime import datetime
import pandas as pd

timestamp = data.get("responselastupdated")
match_date = datetime.fromtimestamp(timestamp).date()

bat_list = []

scorecard = vk1.get("scorecard", [])

for inning in scorecard:

    batsmanvk = inning.get("batsman", [])

    for p in batsmanvk:

        bat_list.append({
            "match_id": 87878,
            "innings_id": inning.get("inningsid"),
            "bat_name": p.get("name"),
            "runs": p.get("runs"),
            "strike_rate": p.get("strkrate"),
            "balls": p.get("balls"),
            "match_date": match_date
        })

df_bat = pd.DataFrame(bat_list)

print(df_bat)

    match_id  innings_id          bat_name  runs strike_rate  balls  \
0      87878           1             Rohit     9         180      5
1      87878           1             Kohli    76      128.81     59
2      87878           1              Pant     0           0      2
3      87878           1  Suryakumar Yadav     3          75      4
4      87878           1              Axar    47      151.61     31
5      87878           1       Shivam Dube    27      168.75     16
6      87878           1     Hardik Pandya     5         250      2
7      87878           1   Ravindra Jadeja     2         100      2
8      87878           1    Arshdeep Singh     0           0      0
9      87878           1     Kuldeep Yadav     0           0      0
10     87878           1            Bumrah     0           0      0
11     87878           2   Reeza Hendricks     4          80      5
12     87878           2   Quinton de Kock    39      125.81     31
13     87878           2     Aiden Markram     4          80      5
14     87878           2    Tristan Stubbs    31      147.62     21
15     87878           2  Heinrich Klaasen    52      192.59     27
16     87878           2      David Miller    21      123.53     17
17     87878           2      Marco Jansen     2          50      4
18     87878           2    Keshav Maharaj     2       28.57      7
19     87878           2     Kagiso Rabada     4      133.33      3
20     87878           2     Anrich Nortje     1         100      1
21     87878           2    Tabraiz Shamsi     0           0      0

    match_date
0   2026-03-13
1   2026-03-13
2   2026-03-13
3   2026-03-13
4   2026-03-13
5   2026-03-13
6   2026-03-13
7   2026-03-13
8   2026-03-13
9   2026-03-13
10  2026-03-13
11  2026-03-13
12  2026-03-13
13  2026-03-13
14  2026-03-13
15  2026-03-13
16  2026-03-13
17  2026-03-13
18  2026-03-13
19  2026-03-13
20  2026-03-13
21  2026-03-13

In [150]:
import urllib.parse
from sqlalchemy import create_engine

# 1. Encode the special character in password
password = urllib.parse.quote_plus("deepika@88")

# 2. Use the encoded password in your connection string
# Also, ensure 'username' is replaced with your actual DB user (usually 'postgres')
engine = create_engine(f'postgresql+psycopg2://postgres:{password}@localhost:5432/cricbuzz')

# 3. Test the connection and push the data
df_bat.to_sql('scard_bat_2', engine, if_exists='append', index=False)

print("✅ Connection successful and table 'scard_bat_2' created!")

✅ Connection successful and table 'scard_bat_2' created!